from __future__ import annotations

import csv
from copy import deepcopy
from dataclasses import dataclass
from dataclasses import replace
from datetime import UTC
from datetime import datetime
from datetime import timedelta
import hashlib
import io
import json
import math
from numbers import Number
import re
from threading import Lock
from typing import Any
from typing import Callable
from typing import Iterable
from typing import Mapping
from uuid import uuid4

from akra_trader.application_flows.run_execution import RunExecutionFlow
from akra_trader.application_flows.guarded_live import GuardedLiveAlertCompatibilityMixin
from akra_trader.application_flows.provider_provenance import ProviderProvenanceCompatibilityMixin
from akra_trader.application_flows.provider_provenance.serialization import *  # noqa: F403
from akra_trader.application_flows.strategy_catalog import StrategyCatalogFlow
from akra_trader.application_flows.strategy_catalog import _apply_registration_snapshot_metadata
from akra_trader.application_flows.strategy_catalog import _build_run_experiment_metadata
from akra_trader.application_flows.strategy_catalog import _merge_preset_parameters
from akra_trader.application_flows.strategy_catalog import _normalize_experiment_filter_value
from akra_trader.application_flows.strategy_catalog import _normalize_experiment_identifier
from akra_trader.application_flows.strategy_catalog import _normalize_experiment_tags
from akra_trader.application_flows.strategy_catalog import serialize_preset
from akra_trader.application_flows.strategy_catalog import serialize_preset_revision
from akra_trader.application_flows.strategy_catalog import serialize_strategy
from akra_trader.lineage import apply_operator_lineage_evidence_retention_deletion_counts
from akra_trader.lineage import build_operator_lineage_drill_evidence_pack
from akra_trader.lineage import build_operator_lineage_evidence_retention_policy
from akra_trader.lineage import build_operator_lineage_evidence_retention_result
from akra_trader.adapters.provider_provenance_search import (
  EmbeddedProviderProvenanceSchedulerSearchServiceClient,
)
from akra_trader.adapters.provider_provenance_search import (
  InMemoryProviderProvenanceSchedulerSearchStore,
)
from akra_trader.adapters.provider_provenance_search import (
  ProviderProvenanceSchedulerSearchService,
)
from akra_trader.domain.models import RunComparison
from akra_trader.domain.models import RunComparisonNarrative
from akra_trader.domain.models import RunComparisonMetricRow
from akra_trader.domain.models import RunComparisonRun
from akra_trader.domain.models import ComparisonEligibilityContract
from akra_trader.domain.models import default_comparison_eligibility_contract
from akra_trader.domain.models import ReplayIntentAliasAuditRecord
from akra_trader.domain.models import ReplayIntentAliasAuditExportArtifactRecord
from akra_trader.domain.models import ReplayIntentAliasAuditExportJobAuditRecord
from akra_trader.domain.models import ReplayIntentAliasAuditExportJobRecord
from akra_trader.domain.models import ReplayIntentAliasRecord
from akra_trader.domain.models import ProviderProvenanceAnalyticsPresetRecord
from akra_trader.domain.models import ProviderProvenanceDashboardViewRecord
from akra_trader.domain.models import ProviderProvenanceExportArtifactRecord
from akra_trader.domain.models import ProviderProvenanceExportJobAuditRecord
from akra_trader.domain.models import ProviderProvenanceExportJobRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerStitchedReportViewAuditRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerStitchedReportViewRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerStitchedReportViewRevisionRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerHealth
from akra_trader.domain.models import ProviderProvenanceSchedulerHealthRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchDocumentRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchFeedbackRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchModerationCatalogGovernancePlanPreviewItem
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchModerationCatalogGovernancePlanRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlanPreviewItem
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlanRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisionRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchModerationPlanPreviewItem
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchModerationPlanRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchModerationPolicyCatalogRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisionRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerSearchQueryAnalyticsRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeBulkGovernanceItemResult
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeBulkGovernanceResult
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernancePlanBatchItemResult
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernancePlanBatchResult
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyStep
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernancePlanListResult
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernancePlanRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogStageResult
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeGovernancePreviewItem
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeRegistryRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeRegistryRevisionRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeTemplateRecord
from akra_trader.domain.models import ProviderProvenanceSchedulerNarrativeTemplateRevisionRecord
from akra_trader.domain.models import ProviderProvenanceScheduledReportAuditRecord
from akra_trader.domain.models import ProviderProvenanceScheduledReportRecord
from akra_trader.domain.models import RunSurfaceCapabilities
from akra_trader.domain.models import GuardedLiveKillSwitch
from akra_trader.domain.models import ClosedTrade
from akra_trader.domain.models import GuardedLiveInternalExposure
from akra_trader.domain.models import GuardedLiveInternalStateSnapshot
from akra_trader.domain.models import GuardedLiveReconciliation
from akra_trader.domain.models import GuardedLiveReconciliationFinding
from akra_trader.domain.models import GuardedLiveRecoveredExposure
from akra_trader.domain.models import GuardedLiveVenueOrderRequest
from akra_trader.domain.models import GuardedLiveVenueOrderResult
from akra_trader.domain.models import GuardedLiveState
from akra_trader.domain.models import GuardedLiveStatus
from akra_trader.domain.models import GuardedLiveVenueBalance
from akra_trader.domain.models import GuardedLiveVenueOpenOrder
from akra_trader.domain.models import GuardedLiveVenueSessionHandoff
from akra_trader.domain.models import GuardedLiveVenueStateSnapshot
from akra_trader.domain.models import GuardedLiveRuntimeRecovery
from akra_trader.domain.models import GuardedLiveOrderBookSync
from akra_trader.domain.models import GuardedLiveSessionOwnership
from akra_trader.domain.models import GuardedLiveVenueSessionRestore
from akra_trader.domain.models import GuardedLiveVenueSessionSync
from akra_trader.domain.models import Fill
from akra_trader.domain.models import ExperimentPreset
from akra_trader.domain.models import Instrument
from akra_trader.domain.models import InstrumentStatus
from akra_trader.domain.models import MarketDataStatus
from akra_trader.domain.models import MarketDataRemediationResult
from akra_trader.domain.models import Order
from akra_trader.domain.models import OrderSide
from akra_trader.domain.models import OrderStatus
from akra_trader.domain.models import OrderType
from akra_trader.domain.models import OperatorAlert
from akra_trader.domain.models import OperatorAlertMarketContextFieldProvenance
from akra_trader.domain.models import OperatorAlertMarketContextProvenance
from akra_trader.domain.models import OperatorAlertPrimaryFocus
from akra_trader.domain.models import OperatorAuditEvent
from akra_trader.domain.models import OperatorIncidentDelivery
from akra_trader.domain.models import OperatorIncidentEvent
from akra_trader.domain.models import OperatorIncidentFireHydrantRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentFireHydrantRecoveryState
from akra_trader.domain.models import OperatorIncidentIncidentIoRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentIncidentIoRecoveryState
from akra_trader.domain.models import OperatorIncidentOpsgenieRecoveryState
from akra_trader.domain.models import OperatorIncidentOpsgenieRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentPagerDutyRecoveryState
from akra_trader.domain.models import OperatorIncidentPagerDutyRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentRootlyRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentRootlyRecoveryState
from akra_trader.domain.models import OperatorIncidentBlamelessRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentBlamelessRecoveryState
from akra_trader.domain.models import OperatorIncidentXmattersRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentXmattersRecoveryState
from akra_trader.domain.models import OperatorIncidentServicenowRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentServicenowRecoveryState
from akra_trader.domain.models import OperatorIncidentSquadcastRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentSquadcastRecoveryState
from akra_trader.domain.models import OperatorIncidentBigPandaRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentBigPandaRecoveryState
from akra_trader.domain.models import OperatorIncidentGrafanaOnCallRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentGrafanaOnCallRecoveryState
from akra_trader.domain.models import OperatorIncidentZendutyRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentZendutyRecoveryState
from akra_trader.domain.models import OperatorIncidentSplunkOnCallRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentSplunkOnCallRecoveryState
from akra_trader.domain.models import OperatorIncidentJiraServiceManagementRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentJiraServiceManagementRecoveryState
from akra_trader.domain.models import OperatorIncidentPagerTreeRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentPagerTreeRecoveryState
from akra_trader.domain.models import OperatorIncidentAlertOpsRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentAlertOpsRecoveryState
from akra_trader.domain.models import OperatorIncidentSignl4RecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentSignl4RecoveryState
from akra_trader.domain.models import OperatorIncidentIlertRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentIlertRecoveryState
from akra_trader.domain.models import OperatorIncidentBetterstackRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentBetterstackRecoveryState
from akra_trader.domain.models import OperatorIncidentOnpageRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentOnpageRecoveryState
from akra_trader.domain.models import OperatorIncidentAllquietRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentAllquietRecoveryState
from akra_trader.domain.models import OperatorIncidentMoogsoftRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentMoogsoftRecoveryState
from akra_trader.domain.models import OperatorIncidentSpikeshRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentSpikeshRecoveryState
from akra_trader.domain.models import OperatorIncidentDutyCallsRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentDutyCallsRecoveryState
from akra_trader.domain.models import OperatorIncidentIncidentHubRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentIncidentHubRecoveryState
from akra_trader.domain.models import OperatorIncidentResolverRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentResolverRecoveryState
from akra_trader.domain.models import OperatorIncidentOpenDutyRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentOpenDutyRecoveryState
from akra_trader.domain.models import OperatorIncidentCabotRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentCabotRecoveryState
from akra_trader.domain.models import OperatorIncidentHaloItsmRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentHaloItsmRecoveryState
from akra_trader.domain.models import OperatorIncidentIncidentManagerIoRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentIncidentManagerIoRecoveryState
from akra_trader.domain.models import OperatorIncidentOneUptimeRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentOneUptimeRecoveryState
from akra_trader.domain.models import OperatorIncidentSquzyRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentSquzyRecoveryState
from akra_trader.domain.models import OperatorIncidentCrisesControlRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentCrisesControlRecoveryState
from akra_trader.domain.models import OperatorIncidentFreshserviceRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentFreshserviceRecoveryState
from akra_trader.domain.models import OperatorIncidentFreshdeskRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentFreshdeskRecoveryState
from akra_trader.domain.models import OperatorIncidentHappyfoxRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentHappyfoxRecoveryState
from akra_trader.domain.models import OperatorIncidentZendeskRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentZendeskRecoveryState
from akra_trader.domain.models import OperatorIncidentZohoDeskRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentZohoDeskRecoveryState
from akra_trader.domain.models import OperatorIncidentHelpScoutRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentHelpScoutRecoveryState
from akra_trader.domain.models import OperatorIncidentFrontRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentFrontRecoveryState
from akra_trader.domain.models import OperatorIncidentIntercomRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentIntercomRecoveryState
from akra_trader.domain.models import OperatorIncidentKayakoRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentKayakoRecoveryState
from akra_trader.domain.models import OperatorIncidentServiceDeskPlusRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentServiceDeskPlusRecoveryState
from akra_trader.domain.models import OperatorIncidentSysAidRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentSysAidRecoveryState
from akra_trader.domain.models import OperatorIncidentBmcHelixRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentBmcHelixRecoveryState
from akra_trader.domain.models import OperatorIncidentSolarWindsServiceDeskRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentSolarWindsServiceDeskRecoveryState
from akra_trader.domain.models import OperatorIncidentInvGateServiceDeskRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentInvGateServiceDeskRecoveryState
from akra_trader.domain.models import OperatorIncidentTopdeskRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentTopdeskRecoveryState
from akra_trader.domain.models import OperatorIncidentOpsRampRecoveryPhaseGraph
from akra_trader.domain.models import OperatorIncidentOpsRampRecoveryState
from akra_trader.domain.models import OperatorIncidentProviderPullSync
from akra_trader.domain.models import OperatorIncidentProviderRecoveryState
from akra_trader.domain.models import OperatorIncidentProviderRecoveryStatusMachine
from akra_trader.domain.models import OperatorIncidentProviderRecoveryTelemetry
from akra_trader.domain.models import OperatorIncidentProviderRecoveryVerification
from akra_trader.domain.models import OperatorIncidentRemediation
from akra_trader.domain.models import OperatorVisibility
from akra_trader.domain.models import Position
from akra_trader.domain.models import ReferenceSource
from akra_trader.domain.models import RunConfig
from akra_trader.domain.models import RunExperimentMetadata
from akra_trader.domain.models import RunMode
from akra_trader.domain.models import RunProvenance
from akra_trader.domain.models import RunRecord
from akra_trader.domain.models import RunSurfaceSharedContract
from akra_trader.domain.models import RunStatus
from akra_trader.domain.models import StrategyLifecycle
from akra_trader.domain.models import StrategyCatalogSemantics
from akra_trader.domain.models import StrategyMetadata
from akra_trader.domain.models import StrategyParameterSnapshot
from akra_trader.domain.models import StrategyRegistration
from akra_trader.domain.models import StrategySnapshot
from akra_trader.adapters.freqtrade import FreqtradeReferenceAdapter
from akra_trader.application_support import COMPARISON_INTENT_COPY
from akra_trader.application_support import COMPARISON_INTENT_DEFAULT
from akra_trader.application_support import COMPARISON_INTENT_WEIGHTS
from akra_trader.application_support import COMPARISON_METRICS
from akra_trader.application_support import COMPARISON_METRIC_COPY
from akra_trader.application_support.comparison_serialization import _build_comparison_metric_row
from akra_trader.application_support.comparison_serialization import _build_comparison_narrative
from akra_trader.application_support.comparison_serialization import _normalize_comparison_intent
from akra_trader.application_support.comparison_serialization import _normalize_run_ids
from akra_trader.application_support.comparison_serialization import _rank_comparison_narratives
from akra_trader.application_support.comparison_serialization import _serialize_comparison_run
from akra_trader.application_support.comparison_serialization import serialize_comparison_eligibility_contract
from akra_trader.application_support.comparison_serialization import serialize_run_comparison
from akra_trader.application_support.comparison_serialization import serialize_run_surface_capabilities
from akra_trader.application_support.run_subresources import serialize_run_metrics_response
from akra_trader.application_support.run_subresources import serialize_run_orders_response
from akra_trader.application_support.run_subresources import serialize_run_positions_response
from akra_trader.application_support.run_subresources import serialize_run_subresource_response
from akra_trader.application_support.run_surfaces import _build_run_action_availability
from akra_trader.application_support.run_surfaces import _build_run_surface_enforcement
from akra_trader.application_support.run_surfaces import _ensure_order_action_allowed
from akra_trader.application_support.run_surfaces import _ensure_run_action_allowed
from akra_trader.application_support.run_surfaces import _get_run_surface_capability_family
from akra_trader.application_support.run_surfaces import _get_run_surface_capability_surface_rule
from akra_trader.application_support import NoopOperatorAlertDeliveryAdapter
from akra_trader.application_support import UnavailableVenueExecutionAdapter
from akra_trader.application_support import UnavailableVenueStateAdapter
from akra_trader.application_support import _EphemeralExperimentPresetCatalog
from akra_trader.application_support import _EphemeralGuardedLiveStateStore
from akra_trader.application_support import _IncidentPagingPolicy
from akra_trader.application_support import _IncidentRemediationPlan
from akra_trader.application_support.guarded_live_orchestration import (
  maintain_guarded_live_worker_sessions as maintain_guarded_live_worker_sessions_support,
)
from akra_trader.application_support.guarded_live_runtime import (
  advance_guarded_live_worker_run as advance_guarded_live_worker_run_support,
)
from akra_trader.application_support.guarded_live_runtime import (
  apply_guarded_live_decision as apply_guarded_live_decision_support,
)
from akra_trader.application_support.guarded_live_runtime import (
  apply_guarded_live_restored_session as apply_guarded_live_restored_session_support,
)
from akra_trader.application_support.guarded_live_runtime import (
  apply_guarded_live_synced_order_state as apply_guarded_live_synced_order_state_support,
)
from akra_trader.application_support.guarded_live_runtime import (
  guarded_live_venue_restore_has_state as guarded_live_venue_restore_has_state_support,
)
from akra_trader.application_support.guarded_live_runtime import (
  infer_last_processed_candle_at as infer_last_processed_candle_at_support,
)
from akra_trader.application_support.guarded_live_runtime import (
  infer_sandbox_primed_candle_count as infer_sandbox_primed_candle_count_support,
)
from akra_trader.application_support.guarded_live_runtime import (
  map_guarded_live_order_status as map_guarded_live_order_status_support,
)
from akra_trader.application_support.guarded_live_runtime import (
  materialize_guarded_live_fill_delta as materialize_guarded_live_fill_delta_support,
)
from akra_trader.application_support.guarded_live_runtime import (
  materialize_guarded_live_restored_order as materialize_guarded_live_restored_order_support,
)
from akra_trader.application_support.guarded_live_runtime import (
  submit_guarded_live_limit_order as submit_guarded_live_limit_order_support,
)
from akra_trader.application_support.guarded_live_runtime import (
  submit_guarded_live_market_order as submit_guarded_live_market_order_support,
)
from akra_trader.application_support.guarded_live_runtime import (
  sync_guarded_live_orders as sync_guarded_live_orders_support,
)
from akra_trader.application_support.guarded_live_runtime import (
  sync_guarded_live_session as sync_guarded_live_session_support,
)
from akra_trader.application_support import guarded_live_alert_state_refresh as guarded_live_alert_state_refresh_support
from akra_trader.application_support import guarded_live_alert_workflows as guarded_live_alert_workflows_support
from akra_trader.application_support import guarded_live_delivery_orchestration as guarded_live_delivery_orchestration_support
from akra_trader.application_support import guarded_live_external_sync_orchestration as guarded_live_external_sync_orchestration_support
from akra_trader.application_support import guarded_live_incident_event_construction as guarded_live_incident_event_construction_support
from akra_trader.application_support import guarded_live_incident_workflow_orchestration as guarded_live_incident_workflow_orchestration_support
from akra_trader.application_support import guarded_live_pull_sync_orchestration as guarded_live_pull_sync_orchestration_support
from akra_trader.application_support import guarded_live_remediation_orchestration as guarded_live_remediation_orchestration_support
from akra_trader.application_support import guarded_live_run_alert_builder as guarded_live_run_alert_builder_support
from akra_trader.application_support import guarded_live_payload_helpers as guarded_live_payload_helpers_support
from akra_trader.application_support import guarded_live_remediation_support as guarded_live_remediation_support
from akra_trader.application_support import guarded_live_incident_support as guarded_live_incident_support
from akra_trader.application_support import guarded_live_market_context_support as guarded_live_market_context_support
from akra_trader.application_support import guarded_live_market_context_workflows as guarded_live_market_context_workflows
from akra_trader.application_support import guarded_live_provider_recovery as guarded_live_provider_recovery_support
from akra_trader.application_support.provider_governance_catalog_plan_workflows import (
  apply_provider_provenance_scheduler_search_moderation_catalog_governance_plan as apply_provider_provenance_scheduler_search_moderation_catalog_governance_plan_support,
)
from akra_trader.application_support.provider_governance_catalog_plan_workflows import (
  approve_provider_provenance_scheduler_search_moderation_catalog_governance_plan as approve_provider_provenance_scheduler_search_moderation_catalog_governance_plan_support,
)
from akra_trader.application_support.provider_governance_meta_workflows import (
  apply_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan as apply_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan_support,
)
from akra_trader.application_support.provider_governance_meta_workflows import (
  approve_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan as approve_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan_support,
)
from akra_trader.application_support.provider_governance_bulk_policy_orchestration import (
  bulk_govern_provider_provenance_scheduler_search_moderation_catalog_governance_policies as bulk_govern_provider_provenance_scheduler_search_moderation_catalog_governance_policies_support,
)
from akra_trader.application_support.provider_governance_catalog_plan_workflows import (
  list_provider_provenance_scheduler_search_moderation_catalog_governance_plans as list_provider_provenance_scheduler_search_moderation_catalog_governance_plans_support,
)
from akra_trader.application_support.provider_governance_catalog_plan_workflows import (
  stage_provider_provenance_scheduler_search_moderation_catalog_governance_plan as stage_provider_provenance_scheduler_search_moderation_catalog_governance_plan_support,
)
from akra_trader.application_support.provider_governance_meta_workflows import (
  create_provider_provenance_scheduler_search_moderation_catalog_governance_meta_policy as create_provider_provenance_scheduler_search_moderation_catalog_governance_meta_policy_support,
)
from akra_trader.application_support.provider_governance_meta_workflows import (
  list_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plans as list_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plans_support,
)
from akra_trader.application_support.provider_governance_meta_workflows import (
  list_provider_provenance_scheduler_search_moderation_catalog_governance_meta_policies as list_provider_provenance_scheduler_search_moderation_catalog_governance_meta_policies_support,
)
from akra_trader.application_support.provider_governance_meta_workflows import (
  stage_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan as stage_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan_support,
)
from akra_trader.application_support.provider_governance_persistence import (
  list_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan_records as list_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan_records_support,
)
from akra_trader.application_support.provider_governance_persistence import (
  list_provider_provenance_scheduler_search_moderation_catalog_governance_meta_policy_records as list_provider_provenance_scheduler_search_moderation_catalog_governance_meta_policy_records_support,
)
from akra_trader.application_support.provider_governance_persistence import (
  list_provider_provenance_scheduler_search_moderation_catalog_governance_plan_records as list_provider_provenance_scheduler_search_moderation_catalog_governance_plan_records_support,
)
from akra_trader.application_support.provider_governance_persistence import (
  list_provider_provenance_scheduler_search_moderation_catalog_governance_policy_audit_records as list_provider_provenance_scheduler_search_moderation_catalog_governance_policy_audit_records_support,
)
from akra_trader.application_support.provider_governance_persistence import (
  list_provider_provenance_scheduler_search_moderation_catalog_governance_policy_records as list_provider_provenance_scheduler_search_moderation_catalog_governance_policy_records_support,
)
from akra_trader.application_support.provider_governance_persistence import (
  list_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revision_records as list_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revision_records_support,
)
from akra_trader.application_support.provider_governance_persistence import (
  save_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan_record as save_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan_record_support,
)
from akra_trader.application_support.provider_governance_persistence import (
  save_provider_provenance_scheduler_search_moderation_catalog_governance_meta_policy_record as save_provider_provenance_scheduler_search_moderation_catalog_governance_meta_policy_record_support,
)
from akra_trader.application_support.provider_governance_persistence import (
  save_provider_provenance_scheduler_search_moderation_catalog_governance_plan_record as save_provider_provenance_scheduler_search_moderation_catalog_governance_plan_record_support,
)
from akra_trader.application_support.provider_governance_persistence import (
  save_provider_provenance_scheduler_search_moderation_catalog_governance_policy_audit_record as save_provider_provenance_scheduler_search_moderation_catalog_governance_policy_audit_record_support,
)
from akra_trader.application_support.provider_governance_persistence import (
  save_provider_provenance_scheduler_search_moderation_catalog_governance_policy_record as save_provider_provenance_scheduler_search_moderation_catalog_governance_policy_record_support,
)
from akra_trader.application_support.provider_governance_persistence import (
  save_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revision_record as save_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revision_record_support,
)
from akra_trader.application_support.provider_governance_policy_history import (
  build_provider_provenance_scheduler_search_moderation_catalog_governance_policy_audit_detail as build_provider_provenance_scheduler_search_moderation_catalog_governance_policy_audit_detail_support,
)
from akra_trader.application_support.provider_governance_policy_history import (
  build_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revision as build_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revision_support,
)
from akra_trader.application_support.provider_governance_policy_history import (
  normalize_provider_provenance_scheduler_search_moderation_catalog_governance_policy_status as normalize_provider_provenance_scheduler_search_moderation_catalog_governance_policy_status_support,
)
from akra_trader.application_support.provider_governance_policy_history import (
  record_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revision as record_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revision_support,
)
from akra_trader.application_support.provider_governance_policy_mutations import (
  create_provider_provenance_scheduler_search_moderation_catalog_governance_policy as create_provider_provenance_scheduler_search_moderation_catalog_governance_policy_support,
)
from akra_trader.application_support.provider_governance_policy_mutations import (
  delete_provider_provenance_scheduler_search_moderation_catalog_governance_policy as delete_provider_provenance_scheduler_search_moderation_catalog_governance_policy_support,
)
from akra_trader.application_support.provider_governance_policy_mutations import (
  restore_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revision as restore_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revision_support,
)
from akra_trader.application_support.provider_governance_policy_mutations import (
  update_provider_provenance_scheduler_search_moderation_catalog_governance_policy as update_provider_provenance_scheduler_search_moderation_catalog_governance_policy_support,
)
from akra_trader.application_support.provider_governance_policy_reads import (
  list_provider_provenance_scheduler_search_moderation_catalog_governance_policies as list_provider_provenance_scheduler_search_moderation_catalog_governance_policies_support,
)
from akra_trader.application_support.provider_governance_policy_reads import (
  list_provider_provenance_scheduler_search_moderation_catalog_governance_policy_audits as list_provider_provenance_scheduler_search_moderation_catalog_governance_policy_audits_support,
)
from akra_trader.application_support.provider_governance_policy_reads import (
  list_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revisions as list_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revisions_support,
)
from akra_trader.application_support.provider_governance_records import (
  get_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan_record as get_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan_record_support,
)
from akra_trader.application_support.provider_governance_records import (
  get_provider_provenance_scheduler_search_moderation_catalog_governance_meta_policy_record as get_provider_provenance_scheduler_search_moderation_catalog_governance_meta_policy_record_support,
)
from akra_trader.application_support.provider_governance_records import (
  get_provider_provenance_scheduler_search_moderation_catalog_governance_plan_record as get_provider_provenance_scheduler_search_moderation_catalog_governance_plan_record_support,
)
from akra_trader.application_support.provider_governance_records import (
  get_provider_provenance_scheduler_search_moderation_catalog_governance_policy_record as get_provider_provenance_scheduler_search_moderation_catalog_governance_policy_record_support,
)
from akra_trader.application_support.provider_governance_records import (
  load_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revision_record as load_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revision_record_support,
)
from akra_trader.application_support.provider_governance_records import (
  serialize_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan_preview_item as serialize_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan_preview_item_support,
)
from akra_trader.application_support.provider_governance_records import (
  serialize_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan_record as serialize_provider_provenance_scheduler_search_moderation_catalog_governance_meta_plan_record_support,
)
from akra_trader.application_support.provider_governance_records import (
  serialize_provider_provenance_scheduler_search_moderation_catalog_governance_meta_policy_record as serialize_provider_provenance_scheduler_search_moderation_catalog_governance_meta_policy_record_support,
)
from akra_trader.application_support.provider_governance_records import (
  serialize_provider_provenance_scheduler_search_moderation_catalog_governance_plan_preview_item as serialize_provider_provenance_scheduler_search_moderation_catalog_governance_plan_preview_item_support,
)
from akra_trader.application_support.provider_governance_records import (
  serialize_provider_provenance_scheduler_search_moderation_catalog_governance_plan_record as serialize_provider_provenance_scheduler_search_moderation_catalog_governance_plan_record_support,
)
from akra_trader.application_support.provider_governance_records import (
  serialize_provider_provenance_scheduler_search_moderation_catalog_governance_policy_audit_record as serialize_provider_provenance_scheduler_search_moderation_catalog_governance_policy_audit_record_support,
)
from akra_trader.application_support.provider_governance_records import (
  serialize_provider_provenance_scheduler_search_moderation_catalog_governance_policy_record as serialize_provider_provenance_scheduler_search_moderation_catalog_governance_policy_record_support,
)
from akra_trader.application_support.provider_governance_records import (
  serialize_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revision_record as serialize_provider_provenance_scheduler_search_moderation_catalog_governance_policy_revision_record_support,
)
from akra_trader.application_support.runtime_queries import StandaloneSurfaceCollectionPathSpec
from akra_trader.application_support.runtime_queries import StandaloneSurfaceFilterCondition
from akra_trader.application_support.runtime_queries import StandaloneSurfaceFilterExpressionNode
from akra_trader.application_support.runtime_queries import StandaloneSurfaceFilterParamSpec
from akra_trader.application_support.runtime_queries import StandaloneSurfaceRuntimeBinding
from akra_trader.application_support.runtime_queries import StandaloneSurfaceSortTerm
from akra_trader.application_support.run_surfaces import serialize_run
from akra_trader.application_support.standalone_route_guards import (
  require_operator_alert_external_sync_token as require_operator_alert_external_sync_token_support,
)
from akra_trader.application_support.standalone_route_guards import (
  require_replay_alias_audit_admin_token as require_replay_alias_audit_admin_token_support,
)
from akra_trader.application_support.standalone_surfaces import execute_standalone_surface_binding
from akra_trader.application_support.standalone_surfaces import get_run_subresource_contract
from akra_trader.application_support.standalone_surfaces import get_run_subresource_runtime_binding
from akra_trader.application_support.standalone_surfaces import get_standalone_surface_runtime_binding
from akra_trader.application_support.standalone_surfaces import list_collection_query_shared_contracts
from akra_trader.application_support.standalone_surfaces import list_run_subresource_contracts
from akra_trader.application_support.standalone_surfaces import list_run_subresource_runtime_bindings
from akra_trader.application_support.standalone_surfaces import list_run_surface_shared_contracts
from akra_trader.application_support.standalone_surfaces import list_standalone_surface_runtime_bindings
from akra_trader.application_support.standalone_surfaces import serialize_collection_path_parameter_domain
from akra_trader.application_support.standalone_surfaces import serialize_collection_path_parameter_spec
from akra_trader.application_support.standalone_surfaces import serialize_collection_path_spec
from akra_trader.application_support.standalone_surfaces import serialize_collection_query_expression_authoring
from akra_trader.application_support.standalone_surfaces import serialize_run_surface_shared_contracts
from akra_trader.application_support.standalone_surfaces import serialize_standalone_filter_param_spec
from akra_trader.application_support.standalone_surfaces import serialize_standalone_surface_response
from akra_trader.domain.services import apply_signal
from akra_trader.domain.services import build_equity_point
from akra_trader.domain.services import summarize_performance
from akra_trader.lineage import build_dataset_boundary_contract
from akra_trader.lineage import build_rerun_boundary_identity
from akra_trader.ports import GuardedLiveStatePort
from akra_trader.ports import ExperimentPresetCatalogPort
from akra_trader.ports import MarketDataPort
from akra_trader.ports import OperatorAlertDeliveryPort
from akra_trader.ports import ProviderProvenanceSchedulerSearchBackendPort
from akra_trader.ports import ReferenceCatalogPort
from akra_trader.ports import RunRepositoryPort
from akra_trader.ports import StrategyCatalogPort
from akra_trader.ports import StrategyRuntime
from akra_trader.ports import VenueExecutionPort
from akra_trader.ports import VenueStatePort
from akra_trader.runtime import DataEngine
from akra_trader.runtime import ExecutionEngine
from akra_trader.runtime import ExecutionModeService
from akra_trader.runtime import RunSupervisor
from akra_trader.runtime import StateCache
from akra_trader.runtime import candles_to_frame

PROVIDER_PROVENANCE_SCHEDULER_ALERT_AUTOMATION_TAB_ID = (
  "system:provider-provenance-scheduler-alerts"
)
PROVIDER_PROVENANCE_SCHEDULER_ALERT_AUTOMATION_TAB_LABEL = (
  "Scheduler alert automation"
)
