from __future__ import annotations

from akra_trader.application_context import *  # noqa: F403
from akra_trader.application_context import RunExecutionFlow
from akra_trader.application_context import GuardedLiveAlertCompatibilityMixin
from akra_trader.application_context import ProviderProvenanceCompatibilityMixin
from akra_trader.application_context import StrategyCatalogFlow
from akra_trader.application_core_mixin import TradingApplicationCoreMixin
from akra_trader.application_lineage_mixin import TradingApplicationLineageMixin
from akra_trader.application_guarded_live_session_mixin import TradingApplicationGuardedLiveSessionMixin
from akra_trader.application_guarded_live_runtime_mixin import TradingApplicationGuardedLiveRuntimeMixin
from akra_trader.application_guarded_live_worker_mixin import TradingApplicationGuardedLiveWorkerMixin
from akra_trader.application_guarded_live_consistency_mixin import TradingApplicationGuardedLiveConsistencyMixin
from akra_trader.application_incident_remediation_mixin import TradingApplicationIncidentRemediationMixin
from akra_trader.application_operator_alert_mixin import TradingApplicationOperatorAlertMixin
from akra_trader.application_simulation_rerun_mixin import TradingApplicationSimulationRerunMixin


class TradingApplication(
  TradingApplicationCoreMixin,
  TradingApplicationLineageMixin,
  TradingApplicationGuardedLiveSessionMixin,
  TradingApplicationGuardedLiveRuntimeMixin,
  TradingApplicationGuardedLiveWorkerMixin,
  TradingApplicationGuardedLiveConsistencyMixin,
  TradingApplicationIncidentRemediationMixin,
  TradingApplicationOperatorAlertMixin,
  TradingApplicationSimulationRerunMixin,
  RunExecutionFlow,
  GuardedLiveAlertCompatibilityMixin,
  ProviderProvenanceCompatibilityMixin,
  StrategyCatalogFlow,
):
  pass
