from __future__ import annotations

from dataclasses import dataclass
import os


def _parse_csv_env(value: str) -> tuple[str, ...]:
  return tuple(item.strip() for item in value.split(",") if item.strip())


def _parse_bool_env(value: str) -> bool:
  return value.strip().lower() in {"1", "true", "yes", "on"}


@dataclass(frozen=True)
class Settings:
  app_name: str = "Akra Trader API"
  api_prefix: str = "/api"
  cors_origin: str = "http://localhost:5173"
  market_data_provider: str = "binance"
  guarded_live_venue: str | None = None
  default_quote_currency: str = "USDT"
  runs_database_url: str | None = None
  market_data_database_url: str | None = None
  provider_provenance_scheduler_search_database_url: str | None = None
  provider_provenance_scheduler_search_service_url: str | None = None
  provider_provenance_scheduler_search_service_auth_token: str | None = None
  market_data_symbols: tuple[str, ...] = ("BTC/USDT", "ETH/USDT", "SOL/USDT")
  market_data_sync_timeframes: tuple[str, ...] = ("5m",)
  market_data_sync_interval_seconds: int = 60
  market_data_default_candle_limit: int = 500
  market_data_historical_candle_limit: int = 2_000
  provider_provenance_report_scheduler_enabled: bool = True
  provider_provenance_report_scheduler_interval_seconds: int = 60
  provider_provenance_report_scheduler_batch_limit: int = 25
  sandbox_worker_heartbeat_interval_seconds: int = 15
  sandbox_worker_heartbeat_timeout_seconds: int = 45
  guarded_live_execution_enabled: bool = False
  guarded_live_worker_heartbeat_interval_seconds: int = 15
  guarded_live_worker_heartbeat_timeout_seconds: int = 45
  operator_alert_delivery_targets: tuple[str, ...] = ("console",)
  operator_alert_escalation_targets: tuple[str, ...] = ()
  operator_alert_webhook_url: str | None = None
  operator_alert_slack_webhook_url: str | None = None
  operator_alert_pagerduty_integration_key: str | None = None
  operator_alert_pagerduty_api_token: str | None = None
  operator_alert_pagerduty_from_email: str | None = None
  operator_alert_pagerduty_recovery_engine_url_template: str | None = None
  operator_alert_pagerduty_recovery_engine_token: str | None = None
  operator_alert_incidentio_api_token: str | None = None
  operator_alert_incidentio_api_url: str = "https://api.incident.io"
  operator_alert_incidentio_recovery_engine_url_template: str | None = None
  operator_alert_incidentio_recovery_engine_token: str | None = None
  operator_alert_firehydrant_api_token: str | None = None
  operator_alert_firehydrant_api_url: str = "https://api.firehydrant.io"
  operator_alert_firehydrant_recovery_engine_url_template: str | None = None
  operator_alert_firehydrant_recovery_engine_token: str | None = None
  operator_alert_rootly_api_token: str | None = None
  operator_alert_rootly_api_url: str = "https://api.rootly.com"
  operator_alert_rootly_recovery_engine_url_template: str | None = None
  operator_alert_rootly_recovery_engine_token: str | None = None
  operator_alert_blameless_api_token: str | None = None
  operator_alert_blameless_api_url: str = "https://api.blameless.com"
  operator_alert_blameless_recovery_engine_url_template: str | None = None
  operator_alert_blameless_recovery_engine_token: str | None = None
  operator_alert_xmatters_api_token: str | None = None
  operator_alert_xmatters_api_url: str = "https://api.xmatters.com"
  operator_alert_xmatters_recovery_engine_url_template: str | None = None
  operator_alert_xmatters_recovery_engine_token: str | None = None
  operator_alert_servicenow_api_token: str | None = None
  operator_alert_servicenow_api_url: str = "https://api.servicenow.com"
  operator_alert_servicenow_recovery_engine_url_template: str | None = None
  operator_alert_servicenow_recovery_engine_token: str | None = None
  operator_alert_squadcast_api_token: str | None = None
  operator_alert_squadcast_api_url: str = "https://api.squadcast.com"
  operator_alert_squadcast_recovery_engine_url_template: str | None = None
  operator_alert_squadcast_recovery_engine_token: str | None = None
  operator_alert_bigpanda_api_token: str | None = None
  operator_alert_bigpanda_api_url: str = "https://api.bigpanda.io"
  operator_alert_bigpanda_recovery_engine_url_template: str | None = None
  operator_alert_bigpanda_recovery_engine_token: str | None = None
  operator_alert_grafana_oncall_api_token: str | None = None
  operator_alert_grafana_oncall_api_url: str = "https://oncall-api.grafana.com"
  operator_alert_grafana_oncall_recovery_engine_url_template: str | None = None
  operator_alert_grafana_oncall_recovery_engine_token: str | None = None
  operator_alert_zenduty_api_token: str | None = None
  operator_alert_zenduty_api_url: str = "https://api.zenduty.com"
  operator_alert_zenduty_recovery_engine_url_template: str | None = None
  operator_alert_zenduty_recovery_engine_token: str | None = None
  operator_alert_splunk_oncall_api_token: str | None = None
  operator_alert_splunk_oncall_api_url: str = "https://api.splunkoncall.com"
  operator_alert_splunk_oncall_recovery_engine_url_template: str | None = None
  operator_alert_splunk_oncall_recovery_engine_token: str | None = None
  operator_alert_jira_service_management_api_token: str | None = None
  operator_alert_jira_service_management_api_url: str = "https://api.atlassian.com/jsm"
  operator_alert_jira_service_management_recovery_engine_url_template: str | None = None
  operator_alert_jira_service_management_recovery_engine_token: str | None = None
  operator_alert_pagertree_api_token: str | None = None
  operator_alert_pagertree_api_url: str = "https://api.pagertree.com"
  operator_alert_pagertree_recovery_engine_url_template: str | None = None
  operator_alert_pagertree_recovery_engine_token: str | None = None
  operator_alert_alertops_api_token: str | None = None
  operator_alert_alertops_api_url: str = "https://api.alertops.com"
  operator_alert_alertops_recovery_engine_url_template: str | None = None
  operator_alert_alertops_recovery_engine_token: str | None = None
  operator_alert_signl4_api_token: str | None = None
  operator_alert_signl4_api_url: str = "https://connect.signl4.com"
  operator_alert_signl4_recovery_engine_url_template: str | None = None
  operator_alert_signl4_recovery_engine_token: str | None = None
  operator_alert_ilert_api_token: str | None = None
  operator_alert_ilert_api_url: str = "https://api.ilert.com"
  operator_alert_ilert_recovery_engine_url_template: str | None = None
  operator_alert_ilert_recovery_engine_token: str | None = None
  operator_alert_betterstack_api_token: str | None = None
  operator_alert_betterstack_api_url: str = "https://uptime.betterstack.com/api/v2"
  operator_alert_betterstack_recovery_engine_url_template: str | None = None
  operator_alert_betterstack_recovery_engine_token: str | None = None
  operator_alert_onpage_api_token: str | None = None
  operator_alert_onpage_api_url: str = "https://api.onpage.com/v1"
  operator_alert_onpage_recovery_engine_url_template: str | None = None
  operator_alert_onpage_recovery_engine_token: str | None = None
  operator_alert_allquiet_api_token: str | None = None
  operator_alert_allquiet_api_url: str = "https://api.allquiet.app/v1"
  operator_alert_allquiet_recovery_engine_url_template: str | None = None
  operator_alert_allquiet_recovery_engine_token: str | None = None
  operator_alert_moogsoft_api_token: str | None = None
  operator_alert_moogsoft_api_url: str = "https://api.moogsoft.com/v1"
  operator_alert_moogsoft_recovery_engine_url_template: str | None = None
  operator_alert_moogsoft_recovery_engine_token: str | None = None
  operator_alert_spikesh_api_token: str | None = None
  operator_alert_spikesh_api_url: str = "https://api.spike.sh/v1"
  operator_alert_spikesh_recovery_engine_url_template: str | None = None
  operator_alert_spikesh_recovery_engine_token: str | None = None
  operator_alert_dutycalls_api_token: str | None = None
  operator_alert_dutycalls_api_url: str = "https://api.dutycalls.com/v1"
  operator_alert_dutycalls_recovery_engine_url_template: str | None = None
  operator_alert_dutycalls_recovery_engine_token: str | None = None
  operator_alert_incidenthub_api_token: str | None = None
  operator_alert_incidenthub_api_url: str = "https://api.incidenthub.cloud/v1"
  operator_alert_incidenthub_recovery_engine_url_template: str | None = None
  operator_alert_incidenthub_recovery_engine_token: str | None = None
  operator_alert_resolver_api_token: str | None = None
  operator_alert_resolver_api_url: str = "https://api.resolver.com/v1"
  operator_alert_resolver_recovery_engine_url_template: str | None = None
  operator_alert_resolver_recovery_engine_token: str | None = None
  operator_alert_openduty_api_token: str | None = None
  operator_alert_openduty_api_url: str = "https://api.openduty.com/v1"
  operator_alert_openduty_recovery_engine_url_template: str | None = None
  operator_alert_openduty_recovery_engine_token: str | None = None
  operator_alert_cabot_api_token: str | None = None
  operator_alert_cabot_api_url: str = "https://api.cabot.io/v1"
  operator_alert_cabot_recovery_engine_url_template: str | None = None
  operator_alert_cabot_recovery_engine_token: str | None = None
  operator_alert_haloitsm_api_token: str | None = None
  operator_alert_haloitsm_api_url: str = "https://api.haloitsm.com/v1"
  operator_alert_haloitsm_recovery_engine_url_template: str | None = None
  operator_alert_haloitsm_recovery_engine_token: str | None = None
  operator_alert_incidentmanagerio_api_token: str | None = None
  operator_alert_incidentmanagerio_api_url: str = "https://api.incidentmanager.io/v1"
  operator_alert_incidentmanagerio_recovery_engine_url_template: str | None = None
  operator_alert_incidentmanagerio_recovery_engine_token: str | None = None
  operator_alert_oneuptime_api_token: str | None = None
  operator_alert_oneuptime_api_url: str = "https://api.oneuptime.com/v1"
  operator_alert_oneuptime_recovery_engine_url_template: str | None = None
  operator_alert_oneuptime_recovery_engine_token: str | None = None
  operator_alert_squzy_api_token: str | None = None
  operator_alert_squzy_api_url: str = "https://api.squzy.app/v1"
  operator_alert_squzy_recovery_engine_url_template: str | None = None
  operator_alert_squzy_recovery_engine_token: str | None = None
  operator_alert_crisescontrol_api_token: str | None = None
  operator_alert_crisescontrol_api_url: str = "https://api.crises-control.com/v1"
  operator_alert_crisescontrol_recovery_engine_url_template: str | None = None
  operator_alert_crisescontrol_recovery_engine_token: str | None = None
  operator_alert_freshservice_api_token: str | None = None
  operator_alert_freshservice_api_url: str = "https://api.freshservice.com/v2"
  operator_alert_freshservice_recovery_engine_url_template: str | None = None
  operator_alert_freshservice_recovery_engine_token: str | None = None
  operator_alert_freshdesk_api_token: str | None = None
  operator_alert_freshdesk_api_url: str = "https://api.freshdesk.com/v2"
  operator_alert_freshdesk_recovery_engine_url_template: str | None = None
  operator_alert_freshdesk_recovery_engine_token: str | None = None
  operator_alert_happyfox_api_token: str | None = None
  operator_alert_happyfox_api_url: str = "https://api.happyfox.com/v1"
  operator_alert_happyfox_recovery_engine_url_template: str | None = None
  operator_alert_happyfox_recovery_engine_token: str | None = None
  operator_alert_zendesk_api_token: str | None = None
  operator_alert_zendesk_api_url: str = "https://api.zendesk.com/api/v2"
  operator_alert_zendesk_recovery_engine_url_template: str | None = None
  operator_alert_zendesk_recovery_engine_token: str | None = None
  operator_alert_zohodesk_api_token: str | None = None
  operator_alert_zohodesk_api_url: str = "https://desk.zoho.com/api/v1"
  operator_alert_zohodesk_recovery_engine_url_template: str | None = None
  operator_alert_zohodesk_recovery_engine_token: str | None = None
  operator_alert_helpscout_api_token: str | None = None
  operator_alert_helpscout_api_url: str = "https://api.helpscout.net/v2"
  operator_alert_helpscout_recovery_engine_url_template: str | None = None
  operator_alert_helpscout_recovery_engine_token: str | None = None
  operator_alert_kayako_api_token: str | None = None
  operator_alert_kayako_api_url: str = "https://api.kayako.com/v1"
  operator_alert_kayako_recovery_engine_url_template: str | None = None
  operator_alert_kayako_recovery_engine_token: str | None = None
  operator_alert_intercom_api_token: str | None = None
  operator_alert_intercom_api_url: str = "https://api.intercom.io"
  operator_alert_intercom_recovery_engine_url_template: str | None = None
  operator_alert_intercom_recovery_engine_token: str | None = None
  operator_alert_front_api_token: str | None = None
  operator_alert_front_api_url: str = "https://api2.frontapp.com"
  operator_alert_front_recovery_engine_url_template: str | None = None
  operator_alert_front_recovery_engine_token: str | None = None
  operator_alert_servicedeskplus_api_token: str | None = None
  operator_alert_servicedeskplus_api_url: str = "https://api.manageengine.com/servicedeskplus/v3"
  operator_alert_servicedeskplus_recovery_engine_url_template: str | None = None
  operator_alert_servicedeskplus_recovery_engine_token: str | None = None
  operator_alert_sysaid_api_token: str | None = None
  operator_alert_sysaid_api_url: str = "https://api.sysaid.com/v1"
  operator_alert_sysaid_recovery_engine_url_template: str | None = None
  operator_alert_sysaid_recovery_engine_token: str | None = None
  operator_alert_bmchelix_api_token: str | None = None
  operator_alert_bmchelix_api_url: str = "https://api.bmchelix.com/v1"
  operator_alert_bmchelix_recovery_engine_url_template: str | None = None
  operator_alert_bmchelix_recovery_engine_token: str | None = None
  operator_alert_solarwindsservicedesk_api_token: str | None = None
  operator_alert_solarwindsservicedesk_api_url: str = "https://api.solarwinds.com/servicedesk/v1"
  operator_alert_solarwindsservicedesk_recovery_engine_url_template: str | None = None
  operator_alert_solarwindsservicedesk_recovery_engine_token: str | None = None
  operator_alert_topdesk_api_token: str | None = None
  operator_alert_topdesk_api_url: str = "https://api.topdesk.com/tas/api"
  operator_alert_topdesk_recovery_engine_url_template: str | None = None
  operator_alert_topdesk_recovery_engine_token: str | None = None
  operator_alert_invgateservicedesk_api_token: str | None = None
  operator_alert_invgateservicedesk_api_url: str = "https://api.invgate.com/service-desk/v1"
  operator_alert_invgateservicedesk_recovery_engine_url_template: str | None = None
  operator_alert_invgateservicedesk_recovery_engine_token: str | None = None
  operator_alert_opsramp_api_token: str | None = None
  operator_alert_opsramp_api_url: str = "https://api.opsramp.com/v1"
  operator_alert_opsramp_recovery_engine_url_template: str | None = None
  operator_alert_opsramp_recovery_engine_token: str | None = None
  operator_alert_opsgenie_api_key: str | None = None
  operator_alert_opsgenie_api_url: str = "https://api.opsgenie.com"
  operator_alert_opsgenie_recovery_engine_url_template: str | None = None
  operator_alert_opsgenie_recovery_engine_api_key: str | None = None
  operator_alert_webhook_timeout_seconds: int = 5
  operator_alert_delivery_max_attempts: int = 4
  operator_alert_delivery_initial_backoff_seconds: int = 15
  operator_alert_delivery_max_backoff_seconds: int = 300
  operator_alert_delivery_backoff_multiplier: float = 2.0
  operator_alert_paging_policy_default_provider: str | None = None
  operator_alert_paging_policy_warning_targets: tuple[str, ...] = ()
  operator_alert_paging_policy_critical_targets: tuple[str, ...] = ()
  operator_alert_paging_policy_warning_escalation_targets: tuple[str, ...] = ()
  operator_alert_paging_policy_critical_escalation_targets: tuple[str, ...] = ()
  operator_alert_external_sync_token: str | None = None
  replay_alias_audit_admin_read_token: str | None = None
  replay_alias_audit_admin_write_token: str | None = None
  operator_alert_incident_ack_timeout_seconds: int = 300
  operator_alert_incident_max_escalations: int = 2
  operator_alert_incident_escalation_backoff_multiplier: float = 2.0
  guarded_live_api_key: str | None = None
  guarded_live_api_secret: str | None = None
  binance_api_key: str | None = None
  binance_api_secret: str | None = None


from akra_trader.config_loader import load_settings
