from __future__ import annotations

from dataclasses import replace
from datetime import datetime
from typing import Any

from akra_trader.domain.models import (
  OperatorIncidentAlertOpsRecoveryPhaseGraph,
  OperatorIncidentAlertOpsRecoveryState,
  OperatorIncidentAllquietRecoveryPhaseGraph,
  OperatorIncidentAllquietRecoveryState,
  OperatorIncidentBetterstackRecoveryPhaseGraph,
  OperatorIncidentBetterstackRecoveryState,
  OperatorIncidentBigPandaRecoveryPhaseGraph,
  OperatorIncidentBigPandaRecoveryState,
  OperatorIncidentBlamelessRecoveryPhaseGraph,
  OperatorIncidentBlamelessRecoveryState,
  OperatorIncidentBmcHelixRecoveryPhaseGraph,
  OperatorIncidentBmcHelixRecoveryState,
  OperatorIncidentCabotRecoveryPhaseGraph,
  OperatorIncidentCabotRecoveryState,
  OperatorIncidentCrisesControlRecoveryPhaseGraph,
  OperatorIncidentCrisesControlRecoveryState,
  OperatorIncidentDutyCallsRecoveryPhaseGraph,
  OperatorIncidentDutyCallsRecoveryState,
  OperatorIncidentFireHydrantRecoveryPhaseGraph,
  OperatorIncidentFireHydrantRecoveryState,
  OperatorIncidentFreshdeskRecoveryPhaseGraph,
  OperatorIncidentFreshdeskRecoveryState,
  OperatorIncidentFreshserviceRecoveryPhaseGraph,
  OperatorIncidentFreshserviceRecoveryState,
  OperatorIncidentFrontRecoveryPhaseGraph,
  OperatorIncidentFrontRecoveryState,
  OperatorIncidentGrafanaOnCallRecoveryPhaseGraph,
  OperatorIncidentGrafanaOnCallRecoveryState,
  OperatorIncidentHaloItsmRecoveryPhaseGraph,
  OperatorIncidentHaloItsmRecoveryState,
  OperatorIncidentHappyfoxRecoveryPhaseGraph,
  OperatorIncidentHappyfoxRecoveryState,
  OperatorIncidentHelpScoutRecoveryPhaseGraph,
  OperatorIncidentHelpScoutRecoveryState,
  OperatorIncidentIlertRecoveryPhaseGraph,
  OperatorIncidentIlertRecoveryState,
  OperatorIncidentIncidentHubRecoveryPhaseGraph,
  OperatorIncidentIncidentHubRecoveryState,
  OperatorIncidentIncidentIoRecoveryPhaseGraph,
  OperatorIncidentIncidentIoRecoveryState,
  OperatorIncidentIncidentManagerIoRecoveryPhaseGraph,
  OperatorIncidentIncidentManagerIoRecoveryState,
  OperatorIncidentIntercomRecoveryPhaseGraph,
  OperatorIncidentIntercomRecoveryState,
  OperatorIncidentInvGateServiceDeskRecoveryPhaseGraph,
  OperatorIncidentInvGateServiceDeskRecoveryState,
  OperatorIncidentJiraServiceManagementRecoveryPhaseGraph,
  OperatorIncidentJiraServiceManagementRecoveryState,
  OperatorIncidentKayakoRecoveryPhaseGraph,
  OperatorIncidentKayakoRecoveryState,
  OperatorIncidentMoogsoftRecoveryPhaseGraph,
  OperatorIncidentMoogsoftRecoveryState,
  OperatorIncidentOneUptimeRecoveryPhaseGraph,
  OperatorIncidentOneUptimeRecoveryState,
  OperatorIncidentOnpageRecoveryPhaseGraph,
  OperatorIncidentOnpageRecoveryState,
  OperatorIncidentOpenDutyRecoveryPhaseGraph,
  OperatorIncidentOpenDutyRecoveryState,
  OperatorIncidentOpsRampRecoveryPhaseGraph,
  OperatorIncidentOpsRampRecoveryState,
  OperatorIncidentOpsgenieRecoveryPhaseGraph,
  OperatorIncidentOpsgenieRecoveryState,
  OperatorIncidentPagerDutyRecoveryPhaseGraph,
  OperatorIncidentPagerDutyRecoveryState,
  OperatorIncidentPagerTreeRecoveryPhaseGraph,
  OperatorIncidentPagerTreeRecoveryState,
  OperatorIncidentProviderRecoveryState,
  OperatorIncidentProviderRecoveryStatusMachine,
  OperatorIncidentProviderRecoveryTelemetry,
  OperatorIncidentProviderRecoveryVerification,
  OperatorIncidentRemediation,
  OperatorIncidentResolverRecoveryPhaseGraph,
  OperatorIncidentResolverRecoveryState,
  OperatorIncidentRootlyRecoveryPhaseGraph,
  OperatorIncidentRootlyRecoveryState,
  OperatorIncidentServiceDeskPlusRecoveryPhaseGraph,
  OperatorIncidentServiceDeskPlusRecoveryState,
  OperatorIncidentServicenowRecoveryPhaseGraph,
  OperatorIncidentServicenowRecoveryState,
  OperatorIncidentSignl4RecoveryPhaseGraph,
  OperatorIncidentSignl4RecoveryState,
  OperatorIncidentSolarWindsServiceDeskRecoveryPhaseGraph,
  OperatorIncidentSolarWindsServiceDeskRecoveryState,
  OperatorIncidentSpikeshRecoveryPhaseGraph,
  OperatorIncidentSpikeshRecoveryState,
  OperatorIncidentSplunkOnCallRecoveryPhaseGraph,
  OperatorIncidentSplunkOnCallRecoveryState,
  OperatorIncidentSquadcastRecoveryPhaseGraph,
  OperatorIncidentSquadcastRecoveryState,
  OperatorIncidentSquzyRecoveryPhaseGraph,
  OperatorIncidentSquzyRecoveryState,
  OperatorIncidentSysAidRecoveryPhaseGraph,
  OperatorIncidentSysAidRecoveryState,
  OperatorIncidentTopdeskRecoveryPhaseGraph,
  OperatorIncidentTopdeskRecoveryState,
  OperatorIncidentXmattersRecoveryPhaseGraph,
  OperatorIncidentXmattersRecoveryState,
  OperatorIncidentZendeskRecoveryPhaseGraph,
  OperatorIncidentZendeskRecoveryState,
  OperatorIncidentZendutyRecoveryPhaseGraph,
  OperatorIncidentZendutyRecoveryState,
  OperatorIncidentZohoDeskRecoveryPhaseGraph,
  OperatorIncidentZohoDeskRecoveryState,
)

from akra_trader.application_support import provider_recovery_family_primary as _provider_recovery_family_primary
from akra_trader.application_support import provider_recovery_family_secondary as _provider_recovery_family_secondary
from akra_trader.application_support.provider_recovery_core_provider_schema_primary import _build_provider_recovery_provider_schema_group_primary
from akra_trader.application_support.provider_recovery_core_provider_schema_mid import _build_provider_recovery_provider_schema_group_mid
from akra_trader.application_support.provider_recovery_core_provider_schema_late import _build_provider_recovery_provider_schema_group_late

globals().update(
  {
    name: getattr(_provider_recovery_family_primary, name)
    for name in dir(_provider_recovery_family_primary)
    if name.startswith("_") and not name.startswith("__")
  }
)
globals().update(
  {
    name: getattr(_provider_recovery_family_secondary, name)
    for name in dir(_provider_recovery_family_secondary)
    if name.startswith("_") and not name.startswith("__")
  }
)

def _build_provider_recovery_provider_schema(
  self,
  *,
  provider: str,
  payload: dict[str, Any],
  lifecycle_state: str,
  status_machine: OperatorIncidentProviderRecoveryStatusMachine,
  synced_at: datetime,
  workflow_state: str | None,
  workflow_reference: str | None,
  reference: str | None,
  existing: OperatorIncidentProviderRecoveryState,
) -> tuple[
  str | None,
  OperatorIncidentPagerDutyRecoveryState,
  OperatorIncidentOpsgenieRecoveryState,
  OperatorIncidentIncidentIoRecoveryState,
  OperatorIncidentFireHydrantRecoveryState,
  OperatorIncidentRootlyRecoveryState,
  OperatorIncidentBlamelessRecoveryState,
  OperatorIncidentXmattersRecoveryState,
  OperatorIncidentServicenowRecoveryState,
  OperatorIncidentSquadcastRecoveryState,
  OperatorIncidentBigPandaRecoveryState,
  OperatorIncidentGrafanaOnCallRecoveryState,
  OperatorIncidentZendutyRecoveryState,
  OperatorIncidentSplunkOnCallRecoveryState,
  OperatorIncidentJiraServiceManagementRecoveryState,
  OperatorIncidentPagerTreeRecoveryState,
  OperatorIncidentAlertOpsRecoveryState,
  OperatorIncidentSignl4RecoveryState,
  OperatorIncidentIlertRecoveryState,
]:
  normalized_provider = self._normalize_paging_provider(provider)
  schema_payload = self._extract_payload_mapping(payload.get("provider_schema"))

  (
    pagerduty,
    opsgenie,
    incidentio,
    firehydrant,
  ) = _build_provider_recovery_provider_schema_group_primary(
    self,
    schema_payload=schema_payload,
    payload=payload,
    lifecycle_state=lifecycle_state,
    status_machine=status_machine,
    synced_at=synced_at,
    workflow_state=workflow_state,
    workflow_reference=workflow_reference,
    reference=reference,
    existing=existing,
  )
  (
    rootly,
    blameless,
    xmatters,
    servicenow,
    squadcast,
  ) = _build_provider_recovery_provider_schema_group_mid(
    self,
    schema_payload=schema_payload,
    payload=payload,
    lifecycle_state=lifecycle_state,
    status_machine=status_machine,
    synced_at=synced_at,
    workflow_state=workflow_state,
    workflow_reference=workflow_reference,
    reference=reference,
    existing=existing,
  )
  (
    bigpanda,
    grafana_oncall,
    zenduty,
    splunk_oncall,
    jira_service_management,
    pagertree,
    alertops,
    signl4,
    ilert,
  ) = _build_provider_recovery_provider_schema_group_late(
    self,
    schema_payload=schema_payload,
    payload=payload,
    lifecycle_state=lifecycle_state,
    status_machine=status_machine,
    synced_at=synced_at,
    workflow_state=workflow_state,
    workflow_reference=workflow_reference,
    reference=reference,
    existing=existing,
  )
  if normalized_provider == "pagerduty":
    return (
      "pagerduty",
      pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "opsgenie":
    return (
      "opsgenie",
      existing.pagerduty,
      opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "incidentio":
    return (
      "incidentio",
      existing.pagerduty,
      existing.opsgenie,
      incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "firehydrant":
    return (
      "firehydrant",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "rootly":
    return (
      "rootly",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "blameless":
    return (
      "blameless",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "xmatters":
    return (
      "xmatters",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "servicenow":
    return (
      "servicenow",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "squadcast":
    return (
      "squadcast",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "bigpanda":
    return (
      "bigpanda",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "grafana_oncall":
    return (
      "grafana_oncall",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "zenduty":
    return (
      "zenduty",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "splunk_oncall":
    return (
      "splunk_oncall",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "jira_service_management":
    return (
      "jira_service_management",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "pagertree":
    return (
      "pagertree",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      pagertree,
      existing.alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "alertops":
    return (
      "alertops",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      alertops,
      existing.signl4,
      existing.ilert,
    )
  if normalized_provider == "signl4":
    return (
      "signl4",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      signl4,
      existing.ilert,
    )
  if normalized_provider == "ilert":
    return (
      "ilert",
      existing.pagerduty,
      existing.opsgenie,
      existing.incidentio,
      existing.firehydrant,
      existing.rootly,
      existing.blameless,
      existing.xmatters,
      existing.servicenow,
      existing.squadcast,
      existing.bigpanda,
      existing.grafana_oncall,
      existing.zenduty,
      existing.splunk_oncall,
      existing.jira_service_management,
      existing.pagertree,
      existing.alertops,
      existing.signl4,
      ilert,
    )
  return (
    existing.provider_schema_kind,
    existing.pagerduty,
    existing.opsgenie,
    existing.incidentio,
    existing.firehydrant,
    existing.rootly,
    existing.blameless,
    existing.xmatters,
    existing.servicenow,
    existing.squadcast,
    existing.bigpanda,
    existing.grafana_oncall,
    existing.zenduty,
    existing.splunk_oncall,
    existing.jira_service_management,
    existing.pagertree,
    existing.alertops,
    existing.signl4,
    existing.ilert,
  )
