// @ts-nocheck

import { CSSProperties, FormEvent, KeyboardEvent, MouseEvent, PointerEvent, ReactNode, forwardRef, useCallback, useEffect, useId, useLayoutEffect, useMemo, useRef, useState, AKRA_TOUCH_FEEDBACK_BRIDGE_VERSION, AKRA_TOUCH_FEEDBACK_EVENT_NAME, AkraTouchFeedbackDetail, AkraTouchFeedbackEnvelope, triggerAkraTouchFeedbackBridge, WorkspaceShell, buildControlWorkspaceDescriptors, ControlWorkspaceDescriptor, ControlStripMetric, useWorkspaceRoute, WorkspaceRouteContent, buildRunHistoryWorkspacePanels, LiveOrderReplacementDraft, RunHistoryWorkspaceSectionProps, RunOrderControls, getRunListBoundaryContractSnapshot, getRunListBoundarySurfaceLabel, getRunSurfaceCapabilityFamily, getRunSurfaceCapabilityFamilyOrder, getRunSurfaceCapabilityGroupOrder, getRunSurfaceCapabilitySchemaContract, getRunSurfaceCollectionQueryContracts, getRunSurfaceSharedContracts, getRunSurfaceSubresourceContracts, RunListComparisonBoundaryNote, shouldEnableReferenceProvenanceSemantics, shouldEnableRunListMetricDrillBack, shouldEnableRunSnapshotSemantics, shouldEnableStrategyCatalogSchemaHints, shouldHydratePresetParameterDefaults, shouldRenderOrderActionBoundaryNote, shouldRenderWorkflowControlBoundaryNote, RunSurfaceCollectionQueryBuilder, formatComparisonTooltipTuningDelta, formatComparisonTooltipTuningValue, formatRelativeTimestampLabel, RunSection, RunSurfaceCollectionQueryBuilderApplyPayload, RunSurfaceCollectionQueryRuntimeCandidateContextSelection, RunSurfaceCollectionQueryRuntimeCandidateSample, applyProviderProvenanceSchedulerStitchedReportGovernancePlan, applyProviderProvenanceSchedulerNarrativeGovernancePlan, approveProviderProvenanceSchedulerStitchedReportGovernancePlan, approveProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceAnalyticsPreset, createProviderProvenanceDashboardView, createProviderProvenanceExportJob, createProviderProvenanceSchedulerStitchedReportGovernanceRegistry, createProviderProvenanceSchedulerStitchedReportGovernancePlan, createProviderProvenanceSchedulerStitchedReportView, createProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, captureProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchy, createProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, createProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceSchedulerNarrativeRegistryEntry, createProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceScheduledReport, approveProviderProvenanceExportJob, applyProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, deleteProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, deleteProviderProvenanceSchedulerNarrativeRegistryEntry, deleteProviderProvenanceSchedulerStitchedReportView, deleteProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, createRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, createRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, downloadProviderProvenanceExportJob, downloadRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, escalateProviderProvenanceExportJob, exportProviderProvenanceSchedulerHealth, exportProviderProvenanceSchedulerStitchedNarrativeReport, reconstructProviderProvenanceSchedulerHealthExport, exportRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, fetchJson, getProviderProvenanceExportAnalytics, getProviderProvenanceExportJobHistory, getProviderProvenanceSchedulerHealthAnalytics, getProviderProvenanceScheduledReportHistory, getRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobHistory, listProviderProvenanceAnalyticsPresets, listProviderProvenanceDashboardViews, listProviderProvenanceSchedulerStitchedReportViews, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogs, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplates, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePlans, listProviderProvenanceSchedulerNarrativeRegistryEntries, listProviderProvenanceSchedulerNarrativeRegistryRevisions, listProviderProvenanceSchedulerNarrativeTemplates, listProviderProvenanceSchedulerNarrativeTemplateRevisions, listProviderProvenanceSchedulerStitchedReportGovernancePolicyCatalogs, listProviderProvenanceSchedulerStitchedReportGovernancePolicyTemplates, listProviderProvenanceSchedulerStitchedReportGovernancePlans, rollbackProviderProvenanceSchedulerStitchedReportGovernancePlan, rollbackProviderProvenanceSchedulerNarrativeGovernancePlan, listMarketDataIngestionJobs, listMarketDataLineageHistory, listProviderProvenanceExportJobs, listProviderProvenanceSchedulerAlertHistory, listProviderProvenanceSchedulerHealthHistory, listProviderProvenanceSchedulerStitchedReportGovernanceRegistries, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryAudits, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisions, listProviderProvenanceSchedulerStitchedReportViewAudits, listProviderProvenanceSchedulerStitchedReportViewRevisions, getProviderProvenanceSchedulerSearchDashboard, bulkGovernProviderProvenanceSchedulerSearchModerationPolicyCatalogs, bulkGovernProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, createProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicy, createProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, listProviderProvenanceSchedulerSearchModerationPolicyCatalogs, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlans, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAudits, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisions, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePlans, listProviderProvenanceSchedulerSearchModerationPolicyCatalogAudits, listProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisions, listProviderProvenanceSchedulerSearchModerationPlans, listProviderProvenanceScheduledReports, listRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, listRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, approveProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, approveProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, approveProviderProvenanceSchedulerSearchModerationPlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, applyProviderProvenanceSchedulerSearchModerationPlan, createProviderProvenanceSchedulerSearchModerationPolicyCatalog, deleteProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, deleteProviderProvenanceSchedulerSearchModerationPolicyCatalog, moderateProviderProvenanceSchedulerSearchFeedbackBatch, moderateProviderProvenanceSchedulerSearchFeedback, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, recordProviderProvenanceSchedulerSearchFeedback, resolveRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevision, restoreProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevision, restoreProviderProvenanceSchedulerSearchModerationPolicyCatalogRevision, restoreProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevision, restoreProviderProvenanceSchedulerNarrativeRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportViewRevision, restoreProviderProvenanceSchedulerNarrativeTemplateRevision, revokeRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, runProviderProvenanceSchedulerNarrativeGovernancePlanBatchAction, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkGovernance, stageProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, stageProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, stageProviderProvenanceSchedulerSearchModerationPlan, updateProviderProvenanceSchedulerSearchModerationPolicyCatalog, updateProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, stageProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, runDueProviderProvenanceScheduledReports, runProviderProvenanceScheduledReport, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStep, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, updateProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, updateProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, updateProviderProvenanceSchedulerNarrativeRegistryEntry, updateProviderProvenanceSchedulerStitchedReportGovernanceRegistry, updateProviderProvenanceSchedulerStitchedReportView, updateProviderProvenanceSchedulerNarrativeTemplate, updateProviderProvenanceExportJobPolicy, deleteProviderProvenanceSchedulerStitchedReportGovernanceRegistry, ALL_FILTER_VALUE, apiBase, COMPARISON_FOCUS_ARTIFACT_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_MICRO_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_NOTE_PAGE_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_SCRUB_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_COMPONENT_SEARCH_PARAM, COMPARISON_FOCUS_DETAIL_SEARCH_PARAM, COMPARISON_FOCUS_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ORIGIN_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_SECTION_SEARCH_PARAM, COMPARISON_FOCUS_SOURCE_SEARCH_PARAM, COMPARISON_FOCUS_TOOLTIP_SEARCH_PARAM, COMPARISON_HISTORY_BROWSER_STATE_KEY, COMPARISON_HISTORY_BROWSER_STATE_VERSION, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_KEY, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_VERSION, COMPARISON_HISTORY_SYNC_CONFLICT_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_PREFERENCE_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_WORKSPACE_FIELD_DEFINITIONS, COMPARISON_HISTORY_TAB_ID_SESSION_KEY, COMPARISON_INTENT_SEARCH_PARAM, COMPARISON_RUN_ID_SEARCH_PARAM, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_KEY, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_VERSION, COMPARISON_TOOLTIP_TUNING_GROUPS, COMPARISON_TOOLTIP_TUNING_LABELS, COMPARISON_TOOLTIP_TUNING_SHARE_PARAM, COMPARISON_TOOLTIP_TUNING_STORAGE_KEY, COMPARISON_TOOLTIP_TUNING_STORAGE_VERSION, COMPARISON_TOOLTIP_UNCHANGED_GROUP_COLLAPSE_THRESHOLD, CONTROL_ROOM_UI_STATE_STORAGE_KEY, CONTROL_ROOM_UI_STATE_VERSION, DEFAULT_COMPARISON_TOOLTIP_PRESET_IMPORT_CONFLICT_POLICY, DEFAULT_COMPARISON_TOOLTIP_TUNING, DEFAULT_CONTROL_ROOM_DOCUMENT_TITLE, LEGACY_GAP_WINDOW_EXPANSION_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_VERSION, MAX_COMPARISON_HISTORY_PANEL_ENTRIES, MAX_COMPARISON_HISTORY_SYNC_AUDIT_ENTRIES, MAX_COMPARISON_RUNS, MAX_MARKET_DATA_PROVENANCE_EXPORT_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_REVIEWED_CONFLICT_KEYS, MAX_VISIBLE_COMPARISON_TOOLTIP_CONFLICT_SESSION_SUMMARIES, MAX_VISIBLE_GAP_WINDOWS, PRESET_PROFILE_AGGRESSIVENESS_RANKS, PRESET_PROFILE_CONFIDENCE_RANKS, PRESET_PROFILE_SPEED_RANKS, PRESET_TIMEFRAME_UNIT_TO_MINUTES, REPLAY_INTENT_ACTION_FILTER_SEARCH_PARAM, REPLAY_INTENT_ALIAS_SEARCH_PARAM, REPLAY_INTENT_EDGE_FILTER_SEARCH_PARAM, REPLAY_INTENT_GROUP_FILTER_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_DIFF_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_GROUP_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_TRACE_SEARCH_PARAM, REPLAY_INTENT_SCOPE_SEARCH_PARAM, REPLAY_INTENT_SEARCH_PARAM, REPLAY_INTENT_STEP_SEARCH_PARAM, REPLAY_INTENT_TEMPLATE_SEARCH_PARAM, RUN_HISTORY_SAVED_FILTER_STORAGE_KEY_PREFIX, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_TAB_ID_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_BROWSER_STATE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_PAYLOAD_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_SIGNING_SECRET_STORAGE_KEY, SHOW_COMPARISON_TOOLTIP_TUNING_PANEL, TOUCH_GAP_WINDOW_SWEEP_HOLD_MS, TOUCH_GAP_WINDOW_SWEEP_MOVE_TOLERANCE_PX, BenchmarkArtifact, ParameterSchema, ComparisonCueKind, ComparisonHistoryBrowserState, ComparisonHistoryPanelEntry, ComparisonHistoryPanelState, ComparisonHistoryPanelSyncState, ComparisonHistoryStepDescriptor, ComparisonHistorySyncAuditEntry, ComparisonHistorySyncAuditFilter, ComparisonHistorySyncAuditKind, ComparisonHistorySyncAuditTrailState, ComparisonHistorySyncConflictFieldKey, ComparisonHistorySyncConflictFieldSource, ComparisonHistorySyncConflictReview, ComparisonHistorySyncConflictReviewGroup, ComparisonHistorySyncPreferenceFieldKey, ComparisonHistorySyncPreferenceReview, ComparisonHistorySyncPreferenceReviewRow, ComparisonHistorySyncPreferenceState, ComparisonHistorySyncWorkspaceRecommendationOverview, ComparisonHistorySyncWorkspaceReview, ComparisonHistorySyncWorkspaceReviewRow, ComparisonHistorySyncWorkspaceReviewSelectionKey, ComparisonHistorySyncWorkspaceSemanticSignal, ComparisonHistorySyncWorkspaceSignalDetailNestedKey, ComparisonHistorySyncWorkspaceSignalDetailSubviewKey, ComparisonHistorySyncWorkspaceSignalMicroInteractionKey, ComparisonHistorySyncWorkspaceSignalMicroViewKey, ComparisonHistorySyncWorkspaceState, ComparisonHistoryTabIdentity, ComparisonHistoryWriteMode, ComparisonIntent, ComparisonScoreDrillBackOptions, ComparisonScoreLinkedRunRole, ComparisonScoreLinkSource, ComparisonScoreLinkTarget, ComparisonScoreSection, ComparisonTooltipConflictSessionSummary, ComparisonTooltipConflictSessionSummarySession, ComparisonTooltipConflictSessionUiState, ComparisonTooltipConflictUiStateV1, ComparisonTooltipInteractionOptions, ComparisonTooltipLayout, ComparisonTooltipPendingPresetImportConflict, ComparisonTooltipPresetConflictPreviewGroup, ComparisonTooltipPresetConflictPreviewRow, ComparisonTooltipPresetImportConflictPolicy, ComparisonTooltipPresetImportResolution, ComparisonTooltipTargetProps, ComparisonTooltipTuning, ComparisonTooltipTuningPresetStateV1, ComparisonTooltipTuningShareImport, ComparisonTooltipTuningSinglePresetShareV1, ControlRoomComparisonHistoryPanelUiState, ControlRoomComparisonSelectionState, ControlRoomUiStateV1, ControlRoomUiStateV2, ControlRoomUiStateV3, ControlRoomUiStateV4, ExpandedGapWindowSelections, ExperimentPreset, ExperimentPresetRevision, GapWindowDragSelectionState, GuardedLiveStatus, MarketDataIngestionJobRecord, MarketDataProvenanceExportFilterState, MarketDataProvenanceExportHistoryEntry, MarketDataProvenanceExportSort, MarketDataProvenanceExportStateV1, MarketDataLineageHistoryRecord, MarketDataStatus, OperatorAlertMarketContextProvenance, OperatorAlertPrimaryFocus, OperatorVisibility, PendingTouchGapWindowSweepState, PresetDraftConflict, PresetRevisionDiff, PresetRevisionFilterState, PresetStructuredDiffDeltaValue, PresetStructuredDiffGroup, PresetStructuredDiffRow, ProviderProvenanceAnalyticsPresetEntry, ProviderProvenanceDashboardLayout, ProviderProvenanceDashboardViewEntry, ProviderProvenanceExportAnalyticsPayload, ProviderProvenanceExportJobEntry, ProviderProvenanceExportJobEscalationResult, ProviderProvenanceExportJobHistoryPayload, ProviderProvenanceExportJobPolicyResult, ProviderProvenanceSchedulerAlertHistoryPayload, ProviderProvenanceSchedulerHealthExportPayload, ProviderProvenanceSchedulerHealthAnalyticsPayload, ProviderProvenanceSchedulerHealthHistoryPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditRecord, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditRecord, ProviderProvenanceSchedulerSearchModerationPlanListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogListPayload, ProviderProvenanceSchedulerSearchFeedbackBatchModerationResult, ProviderProvenanceSchedulerSearchDashboardPayload, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditRecord, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionListPayload, ProviderProvenanceSchedulerStitchedReportViewAuditRecord, ProviderProvenanceSchedulerStitchedReportViewEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionListPayload, ProviderProvenanceSchedulerNarrativeBulkGovernanceResult, ProviderProvenanceSchedulerNarrativeGovernancePlan, ProviderProvenanceSchedulerNarrativeGovernancePlanBatchResult, ProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyStep, ProviderProvenanceSchedulerNarrativeGovernanceQueueView, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeRegistryEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionListPayload, ProviderProvenanceSchedulerNarrativeTemplateEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionListPayload, ProviderProvenanceScheduledReportEntry, ProviderProvenanceScheduledReportHistoryPayload, ProvenanceArtifactLineDetailView, ProvenanceArtifactLineMicroView, ReferenceSource, Run, RunComparison, RunHistoryFilter, RunHistorySurfaceKey, RunListBoundaryContract, RunListBoundaryEligibility, RunListBoundaryGroupKey, RunListBoundarySurfaceId, RunSurfaceCapabilities, RunSurfaceCapabilityFamily, RunSurfaceCapabilityFamilyContract, RunSurfaceCapabilityFamilyKey, RunSurfaceCapabilitySchemaContract, RunSurfaceCapabilitySurfaceKey, RunSurfaceCollectionQueryBuilderReplayIntentSnapshot, RunSurfaceCollectionQueryBuilderReplayLinkAliasRecordPayload, RunSurfaceCollectionQueryBuilderReplayLinkRedactionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkRetentionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobDownloadPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobPrunePayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditPrunePayload, RunSurfaceCollectionQueryContract, RunSurfaceCollectionQueryElementField, RunSurfaceCollectionQueryExpressionAuthoring, RunSurfaceCollectionQueryParameterDomainDescriptor, RunSurfaceCollectionQuerySchema, RunSurfaceSharedContract, RunSurfaceSubresourceContract, SavedRunHistoryFilterPreset, SavedRunHistoryFilterPresetStateV1, Strategy, TouchGapWindowActivationFeedbackState, TouchGapWindowHoldProgressState, defaultRunForm, defaultPresetForm, defaultPresetRevisionFilter, defaultMarketDataProvenanceExportFilterState, defaultProviderProvenanceAnalyticsQueryState, defaultProviderProvenanceSchedulerSearchDashboardFilterState, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilter, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, defaultProviderProvenanceSchedulerSearchModerationQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationStageDraft, normalizeProviderProvenanceSchedulerRoutingPolicyDraftValue, normalizeProviderProvenanceSchedulerApprovalPolicyDraftValue, buildProviderProvenanceSchedulerExportPolicyDraft, getProviderProvenanceSchedulerNarrativeGovernanceQueuePriorityRank, getProviderProvenanceSchedulerNarrativeGovernanceQueueState, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchySummary, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepSummary, formatProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyPosition, isProviderProvenanceSchedulerAlertCategory, getOperatorAlertOccurrenceKey, formatProviderProvenanceSchedulerTimelineSummary, formatProviderProvenanceSchedulerSearchMatchSummary, formatProviderProvenanceSchedulerRetrievalClusterSummary, buildProviderProvenanceSchedulerAlertWorkflowReason, defaultProviderProvenanceDashboardLayout, DEFAULT_PROVIDER_PROVENANCE_SCHEDULER_NARRATIVE_GOVERNANCE_QUEUE_SORT, defaultProviderProvenanceWorkspaceDraft, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraft, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraft, KEEP_CURRENT_BULK_GOVERNANCE_VALUE, CLEAR_TEMPLATE_LINK_BULK_GOVERNANCE_VALUE, defaultProviderProvenanceSchedulerNarrativeTemplateBulkDraft, defaultProviderProvenanceSchedulerStitchedReportViewBulkDraft, defaultProviderProvenanceSchedulerNarrativeRegistryDraft, defaultProviderProvenanceSchedulerNarrativeRegistryBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceQueueFilter, defaultProviderProvenanceSchedulerStitchedReportGovernanceQueueFilter, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilter, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilter, defaultProviderProvenanceSchedulerStitchedReportViewAuditFilter, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilter, defaultProviderProvenanceReportDraft, buildPresetFormFromPreset, buildCurrentPresetRevisionSnapshot, buildEmptyPresetRevisionSnapshot, formatPresetStructuredDiffDisplayValue, isPresetStructuredDiffObject, isPresetStructuredDiffScalar, arePresetStructuredDiffValuesEquivalent, matchesPresetParameterSchemaType, joinPresetStructuredDiffHints, tokenizePresetParameterPath, parsePresetTimeframeToMinutes, buildPresetRankedStringDelta, buildPresetParameterStrategyContext, buildPresetParameterDomainContext, formatPresetParameterSchemaHint, getPresetParameterSchemaEntry, buildPresetStructuredDiffDelta, summarizePresetStructuredDiffGroup, groupPresetStructuredDiffRows, buildPresetStructuredDiffRows, describePresetRevisionDiff, describePresetDraftConflict, matchesPresetRevisionFilter, defaultRunHistoryFilter, sanitizeRunHistoryFilter, cloneRunHistoryFilter, hasRunHistoryFilterCriteria, areRunHistoryFiltersEquivalent, buildRunHistorySavedFilterStorageKey, normalizeSavedRunHistoryFilterPreset, loadSavedRunHistoryFilterPresets, persistSavedRunHistoryFilterPresets, describeRunHistoryFilter, DEFAULT_COMPARISON_INTENT, comparisonIntentOptions, parseExperimentTags, parseJsonObjectInput, formatPresetLifecycleStage, buildRunSubmissionPayload, normalizeRunFormPreset, resolveMarketDataSymbol, buildMarketDataInstrumentFocusKey, isMarketDataInstrumentAtRisk, resolvePreferredMarketDataInstrument, formatWorkflowToken, formatMarketContextFieldProvenance, summarizeProviderRecoveryMarketContextProvenance, serializeLinkedMarketInstrumentContext, getOperatorSeverityRank, normalizeMarketDataProvenanceExportSort, normalizeMarketDataProvenanceExportFilterState, normalizeMarketDataProvenanceExportHistoryEntry, loadPersistedMarketDataProvenanceExportState, persistMarketDataProvenanceExportState, formatMarketDataProvenanceExportFilterSummary, formatProviderProvenanceAnalyticsQuerySummary, normalizeProviderProvenanceDashboardLayoutState, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueSort, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkQueueViewPatch, formatProviderProvenanceSchedulerNarrativeGovernanceQueueSortLabel, providerProvenanceSchedulerNarrativeGovernancePolicySupportsItemType, formatProviderProvenanceSchedulerNarrativeGovernanceQueueViewSummary, buildProviderProvenanceAnalyticsWorkspaceQuery, buildProviderProvenanceAnalyticsQueryStateFromWorkspaceQuery, formatProviderProvenanceSchedulerNarrativeFacet, resolveProviderProvenanceSeriesBarWidth, formatProviderDriftIntensity, formatSchedulerLagSeconds, downloadTextExport, escapeRegExp, normalizeMarketSymbol, buildMarketSymbolSearchVariants, matchesMarketSymbolInText, dedupeMarketDataInstruments, formatMarketDataInstrumentLabel, getMarketDataInstrumentSyncSeverityRank, getMarketDataInstrumentRiskScore, buildLiveMarketDataPreference, getMarketDataInstrumentLiveRelevance, selectPrimaryMarketDataInstrument, extractMatchingMarketTimeframe, extractMatchingMarketSymbols, buildLinkedMarketInstrumentContext, buildLinkedMarketInstrumentContextFromPayload, formatLinkedMarketPrimaryFocusNote, resolveInstrumentsBySymbolsAndTimeframe, resolveMarketDataInstrumentLink, getAlertLinkPriority, compareAlertLinkPriority, resolveAutoLinkedMarketInstrument, formatTimestamp, formatProviderRecoverySchema, formatProviderRecoveryTelemetry, shortenIdentifier, truncateLabel, formatRange, benchmarkArtifactSummaryOrder, benchmarkArtifactSummaryLabels, benchmarkArtifactSectionOrder, benchmarkArtifactSectionLabels, formatBenchmarkArtifactSummaryEntries, benchmarkArtifactSummarySortIndex, formatBenchmarkArtifactSummaryLabel, formatBenchmarkArtifactSummaryValue, formatBenchmarkArtifactSectionEntries, benchmarkArtifactSectionSortIndex, formatBenchmarkArtifactSectionLabel, formatBenchmarkArtifactSectionLines, formatBenchmarkArtifactSectionValue, formatBenchmarkArtifactInlineValue, ProviderProvenanceAnalyticsScope, ProviderProvenanceSchedulerOccurrenceNarrativeFacet, ProviderProvenanceAnalyticsQueryState, ProviderProvenanceSchedulerSearchDashboardFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, ProviderProvenanceSchedulerSearchModerationQueueFilterState, ProviderProvenanceSchedulerSearchModerationStageDraft, ProviderProvenanceSchedulerExportPolicyDraft, OperatorVisibilityAlertEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraftState, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraftState, ProviderProvenanceSchedulerNarrativeBulkToggleValue, ProviderProvenanceSchedulerNarrativeTemplateBulkDraftState, ProviderProvenanceSchedulerStitchedReportViewBulkDraftState, ProviderProvenanceSchedulerNarrativeRegistryDraftState, ProviderProvenanceSchedulerNarrativeRegistryBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraftState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepVersionEntry, ProviderProvenanceSchedulerNarrativeGovernanceQueueFilterState, ProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterState, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilterState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilterState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilterState, ProviderProvenanceSchedulerStitchedReportViewAuditFilterState, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilterState, ProviderProvenanceReportDraftState, LinkedMarketInstrumentContext, MarketDataLinkableAlertRecord, MarketDataIncidentHistoryEntry, ProviderRecoveryMarketContextSummary, MarketDataProviderProvenanceEventRecord, MarketDataPrimaryFocusSelection } from "./ControlRoomViewHelpersContext";
import { PanelDisclosure, BackfillCountStatus, BackfillQualityStatus, SyncCheckpointStatus, SyncFailureStatus, formatCompletion, summarizeGapWindows, formatGapWindows, buildLegacyGapWindowKey, buildGapWindowKey, parseGapWindowKey, formatGapWindowKeyLabel, normalizeExpandedGapWindowSelectionList, resolveGapWindowSelectionList, buildGapWindowSelectionUpdate, isSameGapWindowSelectionList, filterExpandedGapWindowSelections, buildGapWindowSelectionLookup, instrumentGapRowKey, toggleExpandedGapRow, pruneExpandedGapRows, pruneExpandedGapWindowSelections } from "./ControlRoomViewStatusPanels";
import { loadExpandedGapRows, loadExpandedGapWindowSelections, defaultControlRoomComparisonSelectionState, loadPersistedComparisonSelection, defaultComparisonHistoryPanelState, defaultComparisonHistoryPanelUiState, loadPersistedComparisonHistoryPanelUiState, loadControlRoomUiState, readControlRoomUiStateValue, persistControlRoomUiState, loadComparisonHistorySyncAuditTrail, persistComparisonHistorySyncAuditTrail, loadComparisonSelectionFromUrl, buildComparisonSelectionHistoryUrl, readComparisonHistoryBrowserState, buildComparisonHistoryBrowserState, isSameComparisonHistoryBrowserState, persistComparisonSelectionToUrl, buildComparisonHistoryEntryId, buildComparisonHistoryTabId, formatComparisonHistoryTabLabel, loadComparisonHistoryTabIdentity, buildComparisonHistoryPanelSyncState, buildComparisonHistorySyncSignature, buildComparisonHistorySyncAuditId, buildComparisonHistoryPanelEntry, findComparisonHistoryPanelEntryForSelection, mergeComparisonHistoryPanelState, mergeComparisonHistoryPanelEntries, reconcileComparisonHistoryPanelState, sortComparisonHistoryPanelEntries, limitComparisonHistoryPanelEntries } from "./ControlRoomViewComparisonStorage";
import { listComparisonHistoryExpandedGapRowKeys, listComparisonHistoryExpandedGapRowDiffKeys, buildComparisonHistoryExpandedGapRowSelectionKey, parseComparisonHistoryExpandedGapRowSelectionKey, buildComparisonHistoryExpandedGapWindowSelectionKey, parseComparisonHistoryExpandedGapWindowSelectionKey, listComparisonHistoryExpandedGapWindowDiffKeys, isSameComparisonHistoryExpandedGapRows, isSameExpandedGapWindowSelections, formatComparisonHistoryExpandedGapRowKey, formatComparisonHistoryExpandedGapRowsValue, formatComparisonHistoryExpandedGapRowsDiffValue, formatComparisonHistorySyncWorkspaceSelectionKeyLabel, rankComparisonHistorySyncWorkspaceSelectionKey, ComparisonHistorySyncWorkspaceSemanticRanking, listComparisonHistorySyncWorkspaceDiffSelectionKeys, resolveComparisonHistorySyncWorkspaceFieldSource, listComparisonHistorySyncWorkspaceConflictSelectionKeys, scoreComparisonHistorySyncWorkspaceCandidateSource, sortComparisonHistorySyncWorkspaceSemanticSignals, rankComparisonHistorySyncWorkspaceFieldSemantics, buildComparisonHistorySyncWorkspaceRecommendedSources, summarizeComparisonHistorySyncWorkspaceChanges, buildComparisonHistorySyncWorkspaceState, formatComparisonHistorySyncWorkspaceFieldValue, hasComparisonHistorySyncWorkspaceFieldDifference, buildDefaultComparisonHistorySyncWorkspaceSelectedSources, buildComparisonHistorySyncWorkspaceReview, buildComparisonHistorySyncWorkspaceReviewRows, buildComparisonHistorySyncWorkspaceRecommendationOverview, formatComparisonHistorySyncWorkspaceResolutionSummary, resolveComparisonHistorySyncWorkspaceReview, buildComparisonHistorySyncAuditEntries } from "./ControlRoomViewComparisonWorkspace";
import { loadLegacyExpandedGapRows, filterExpandedGapRows, normalizeControlRoomComparisonSelection, isSameComparisonSelection, formatComparisonHistoryPanelEntryMeta, matchesComparisonHistoryPanelEntry, formatComparisonHistorySyncAuditKindLabel, buildComparisonHistoryStepDescriptor, resolveComparisonHistoryRunLabel, normalizeComparisonRunIdList, normalizeComparisonIntent, normalizeComparisonScoreSection, normalizeComparisonScoreLinkSource, normalizeComparisonScoreLinkSubFocusKey, normalizeComparisonScoreLinkExpandedState, normalizeComparisonScoreLinkTooltipKey, normalizeComparisonScoreLinkArtifactLineDetailView, normalizeComparisonScoreLinkArtifactLineMicroView, normalizeComparisonScoreLinkArtifactLineNotePage, normalizeComparisonScoreLinkArtifactLineDetailHoverKey, normalizeComparisonScoreLinkArtifactLineScrubStep, normalizeComparisonScoreLinkArtifactHoverKey, normalizeComparisonScoreLinkTarget, isControlRoomUiStateV1, isControlRoomUiStateV2, isControlRoomUiStateV3, isControlRoomUiStateV4, buildRunsPath, buildRunComparisonPath, normalizeRunHistoryFilter, normalizeRunHistoryPresetFilter, getStrategyVersionOptions, pickLatestBenchmarkRun } from "./ControlRoomViewRunFilters";
import { StrategyColumn, ReferenceCatalog, PresetStructuredDiffPreview, PresetCatalogPanel, RunForm, ExperimentMetadataPills } from "./ControlRoomViewCatalogPanels";
import { RunListBoundarySurfaceContract, RunListBoundaryGroupContract, RunSurfaceCapabilityDiscoveryPanel, Metric, formatMetric, formatLineagePosture, formatLineageIndicator, formatComparisonScoreValue } from "./ControlRoomViewCapabilities";
import { buildComparisonScoreHighlights, buildComparisonScoreDetailRows, formatComparisonScoreHighlight, formatComparisonScoreComponentLabel, formatComparisonScoreLinkSourceLabel, encodeComparisonScoreLinkToken, decodeComparisonScoreLinkToken, buildComparisonProvenanceLineSubFocusKey, buildComparisonRunCardLineSubFocusKey, buildComparisonRunListLineSubFocusKey, buildComparisonRunListOrderPreviewSubFocusKey, buildComparisonRunListDataSymbolSubFocusKey, buildComparisonProvenanceArtifactSubFocusKey, buildComparisonProvenanceArtifactSectionSubFocusKey, buildComparisonProvenanceArtifactSummaryHoverKey, buildComparisonProvenanceArtifactSectionLineHoverKey, buildComparisonProvenanceArtifactLineDetailHoverKey, buildComparisonMetricTooltipKey, formatComparisonScoreLinkSubFocusLabel, formatComparisonScoreLinkTooltipLabel, formatComparisonScoreLinkArtifactHoverLabel, formatComparisonScoreLinkArtifactLineDetailViewLabel, formatComparisonScoreLinkArtifactLineMicroViewLabel, formatComparisonScoreLinkArtifactLineDetailHoverLabel, formatComparisonScoreComponentDetail, buildComparisonScoreComponentDetails, formatComparisonScoreComponentRawValue, formatComparisonScoreSignedValue, getComparisonScoreLinkedRunRole, isSameComparisonScoreLinkTarget, isSameComparisonScoreLinkSurface, resolveComparisonScoreDrillBackTarget, isComparisonScoreLinkMatch, formatEditableNumber } from "./ControlRoomViewComparisonLinks";
import { formatFixedNumber, buildLiveOrderDraftKey, formatComparisonMetric, formatComparisonDelta, formatComparisonNarrativeLabel, formatComparisonIntentLabel, formatComparisonIntentLegend, formatComparisonIntentTooltip, formatComparisonCueTooltip, buildComparisonCellTooltip, getComparisonIntentClassName, formatLaneLabel, formatVersionLineage, extractDefaultParameters, formatParameterMap, formatParameterValue, summarizeRunNotes } from "./ControlRoomViewFormatting";

export function normalizeComparisonHistoryPanelUiState(
  value: Partial<ControlRoomComparisonHistoryPanelUiState> | null | undefined,
): ControlRoomComparisonHistoryPanelUiState {
  return {
    open: value?.open === true,
    panel: normalizeComparisonHistoryPanelState(value?.panel),
    searchQuery: typeof value?.searchQuery === "string" ? value.searchQuery : "",
    showPinnedOnly: value?.showPinnedOnly === true,
    auditFilter: normalizeComparisonHistorySyncAuditFilter(value?.auditFilter),
    showResolvedAuditEntries: value?.showResolvedAuditEntries !== false,
    expandedConflictReviewIds:
      value?.expandedConflictReviewIds && typeof value.expandedConflictReviewIds === "object"
        ? Object.entries(value.expandedConflictReviewIds).reduce<Record<string, boolean>>(
            (accumulator, [key, candidate]) => {
              if (candidate === true) {
                accumulator[key] = true;
              }
              return accumulator;
            },
            {},
          )
        : {},
    expandedWorkspaceScoreDetailIds:
      value?.expandedWorkspaceScoreDetailIds && typeof value.expandedWorkspaceScoreDetailIds === "object"
        ? Object.entries(value.expandedWorkspaceScoreDetailIds).reduce<Record<string, boolean>>(
            (accumulator, [key, candidate]) => {
              if (candidate === true) {
                accumulator[key] = true;
              }
              return accumulator;
            },
            {},
          )
        : {},
    focusedWorkspaceScoreDetailSources:
      value?.focusedWorkspaceScoreDetailSources
      && typeof value.focusedWorkspaceScoreDetailSources === "object"
        ? Object.entries(value.focusedWorkspaceScoreDetailSources).reduce<
            Record<string, ComparisonHistorySyncConflictFieldSource>
          >((accumulator, [key, candidate]) => {
            if (candidate === "local" || candidate === "remote") {
              accumulator[key] = candidate;
            }
            return accumulator;
          }, {})
        : {},
    focusedWorkspaceScoreDetailSignalKeys:
      value?.focusedWorkspaceScoreDetailSignalKeys
      && typeof value.focusedWorkspaceScoreDetailSignalKeys === "object"
        ? Object.entries(value.focusedWorkspaceScoreDetailSignalKeys).reduce<Record<string, string>>(
            (accumulator, [key, candidate]) => {
              if (typeof candidate === "string" && candidate.trim()) {
                accumulator[key] = candidate;
              }
              return accumulator;
            },
            {},
          )
        : {},
    expandedWorkspaceScoreSignalDetailIds:
      value?.expandedWorkspaceScoreSignalDetailIds
      && typeof value.expandedWorkspaceScoreSignalDetailIds === "object"
        ? Object.entries(value.expandedWorkspaceScoreSignalDetailIds).reduce<Record<string, boolean>>(
            (accumulator, [key, candidate]) => {
              if (candidate === true) {
                accumulator[key] = true;
              }
              return accumulator;
            },
            {},
          )
        : {},
    collapsedWorkspaceScoreSignalSubviewIds:
      value?.collapsedWorkspaceScoreSignalSubviewIds
      && typeof value.collapsedWorkspaceScoreSignalSubviewIds === "object"
        ? Object.entries(value.collapsedWorkspaceScoreSignalSubviewIds).reduce<Record<string, boolean>>(
            (accumulator, [key, candidate]) => {
              if (candidate === true) {
                accumulator[key] = true;
              }
              return accumulator;
            },
            {},
          )
        : {},
    collapsedWorkspaceScoreSignalNestedSubviewIds:
      value?.collapsedWorkspaceScoreSignalNestedSubviewIds
      && typeof value.collapsedWorkspaceScoreSignalNestedSubviewIds === "object"
        ? Object.entries(value.collapsedWorkspaceScoreSignalNestedSubviewIds).reduce<Record<string, boolean>>(
            (accumulator, [key, candidate]) => {
              if (candidate === true) {
                accumulator[key] = true;
              }
              return accumulator;
            },
            {},
          )
        : {},
    focusedWorkspaceScoreSignalMicroViews:
      value?.focusedWorkspaceScoreSignalMicroViews
      && typeof value.focusedWorkspaceScoreSignalMicroViews === "object"
        ? Object.entries(value.focusedWorkspaceScoreSignalMicroViews).reduce<
            Record<string, ComparisonHistorySyncWorkspaceSignalMicroViewKey>
          >((accumulator, [key, candidate]) => {
            if (
              candidate === "summary"
              || candidate === "trace"
              || candidate === "recommendation"
              || candidate === "alternative"
              || candidate === "position"
              || candidate === "score"
              || candidate === "share"
              || candidate === "impact"
              || candidate === "selection"
              || candidate === "lane"
              || candidate === "gap"
              || candidate === "reason"
            ) {
              accumulator[key] = candidate;
            }
            return accumulator;
          }, {})
        : {},
    focusedWorkspaceScoreSignalMicroInteractions:
      value?.focusedWorkspaceScoreSignalMicroInteractions
      && typeof value.focusedWorkspaceScoreSignalMicroInteractions === "object"
        ? Object.entries(value.focusedWorkspaceScoreSignalMicroInteractions).reduce<
            Record<string, ComparisonHistorySyncWorkspaceSignalMicroInteractionKey>
          >((accumulator, [key, candidate]) => {
            if (
              candidate === "lane"
              || candidate === "polarity"
              || candidate === "signal"
              || candidate === "source"
              || candidate === "support"
              || candidate === "tradeoff"
              || candidate === "rank"
              || candidate === "score"
              || candidate === "share"
              || candidate === "impact"
              || candidate === "selected"
              || candidate === "focusedLane"
              || candidate === "gap"
              || candidate === "reason"
            ) {
              accumulator[key] = candidate;
            }
            return accumulator;
          }, {})
        : {},
    hoveredWorkspaceScoreSignalMicroTargets:
      value?.hoveredWorkspaceScoreSignalMicroTargets
      && typeof value.hoveredWorkspaceScoreSignalMicroTargets === "object"
        ? Object.entries(value.hoveredWorkspaceScoreSignalMicroTargets).reduce<Record<string, string>>(
            (accumulator, [key, candidate]) => {
              if (typeof candidate === "string" && candidate.trim()) {
                accumulator[key] = candidate;
              }
              return accumulator;
            },
            {},
          )
        : {},
    scrubbedWorkspaceScoreSignalMicroSteps:
      value?.scrubbedWorkspaceScoreSignalMicroSteps
      && typeof value.scrubbedWorkspaceScoreSignalMicroSteps === "object"
        ? Object.entries(value.scrubbedWorkspaceScoreSignalMicroSteps).reduce<Record<string, number>>(
            (accumulator, [key, candidate]) => {
              if (typeof candidate === "number" && Number.isInteger(candidate) && candidate >= 0) {
                accumulator[key] = candidate;
              }
              return accumulator;
            },
            {},
          )
        : {},
    selectedWorkspaceScoreSignalMicroNotePages:
      value?.selectedWorkspaceScoreSignalMicroNotePages
      && typeof value.selectedWorkspaceScoreSignalMicroNotePages === "object"
        ? Object.entries(value.selectedWorkspaceScoreSignalMicroNotePages).reduce<Record<string, number>>(
            (accumulator, [key, candidate]) => {
              if (typeof candidate === "number" && Number.isInteger(candidate) && candidate >= 0) {
                accumulator[key] = candidate;
              }
              return accumulator;
            },
            {},
          )
        : {},
    activeWorkspaceOverviewRowId:
      typeof value?.activeWorkspaceOverviewRowId === "string"
        ? value.activeWorkspaceOverviewRowId.trim() || null
        : null,
    sync: normalizeComparisonHistoryPanelSyncState(value?.sync),
  };
}

export function normalizeComparisonHistorySyncAuditFilter(value: unknown): ComparisonHistorySyncAuditFilter {
  return value === "conflicts" || value === "preferences" || value === "workspace" || value === "merges"
    ? value
    : "all";
}

export function normalizeComparisonHistoryPanelSyncState(
  value: Partial<ComparisonHistoryPanelSyncState> | null | undefined,
): ComparisonHistoryPanelSyncState | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const tabId = typeof value.tabId === "string" ? value.tabId.trim() : "";
  const tabLabel = typeof value.tabLabel === "string" ? value.tabLabel.trim() : "";
  const updatedAt = typeof value.updatedAt === "string" ? value.updatedAt : "";
  if (!tabId || !tabLabel || !updatedAt) {
    return null;
  }
  return {
    tabId,
    tabLabel,
    updatedAt,
  };
}

export function normalizeComparisonHistoryPanelState(
  value: Partial<ComparisonHistoryPanelState> | null | undefined,
): ComparisonHistoryPanelState {
  const entries = limitComparisonHistoryPanelEntries(
    sortComparisonHistoryPanelEntries(
      Array.isArray(value?.entries)
        ? value.entries
            .map((entry) => normalizeComparisonHistoryPanelEntry(entry))
            .filter((entry): entry is ComparisonHistoryPanelEntry => entry !== null)
        : [],
    ),
  );
  const activeEntryId =
    typeof value?.activeEntryId === "string" && entries.some((entry) => entry.entryId === value.activeEntryId)
      ? value.activeEntryId
      : entries[entries.length - 1]?.entryId ?? null;
  return {
    entries,
    activeEntryId,
  };
}

export function normalizeComparisonHistoryPanelEntry(value: unknown): ComparisonHistoryPanelEntry | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const candidate = value as Partial<ComparisonHistoryPanelEntry>;
  const entryId = typeof candidate.entryId === "string" ? candidate.entryId.trim() : "";
  const label = typeof candidate.label === "string" ? candidate.label : "";
  const summary = typeof candidate.summary === "string" ? candidate.summary : "";
  const title = typeof candidate.title === "string" ? candidate.title : "";
  const url = typeof candidate.url === "string" ? candidate.url : "";
  const recordedAt = typeof candidate.recordedAt === "string" ? candidate.recordedAt : "";
  if (
    !entryId
    || !label
    || !summary
    || !title
    || !url
    || !recordedAt
    || typeof candidate.stepIndex !== "number"
    || !Number.isFinite(candidate.stepIndex)
  ) {
    return null;
  }
  return {
    entryId,
    stepIndex: candidate.stepIndex,
    label,
    summary,
    title,
    url,
    hidden: candidate.hidden === true,
    pinned: candidate.pinned === true,
    recordedAt,
    selection: normalizeControlRoomComparisonSelection(candidate.selection),
  };
}

export function normalizeComparisonHistorySyncAuditEntry(
  value: unknown,
): ComparisonHistorySyncAuditEntry | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const candidate = value as Partial<ComparisonHistorySyncAuditEntry>;
  const auditId = typeof candidate.auditId === "string" ? candidate.auditId.trim() : "";
  const kind = candidate.kind;
  const summary = typeof candidate.summary === "string" ? candidate.summary : "";
  const detail = typeof candidate.detail === "string" ? candidate.detail : "";
  const recordedAt = typeof candidate.recordedAt === "string" ? candidate.recordedAt : "";
  const sourceTabId = typeof candidate.sourceTabId === "string" ? candidate.sourceTabId.trim() : "";
  const sourceTabLabel =
    typeof candidate.sourceTabLabel === "string" ? candidate.sourceTabLabel.trim() : "";
  if (
    !auditId
    || (kind !== "merge" && kind !== "conflict" && kind !== "preferences" && kind !== "workspace")
    || !summary
    || !detail
    || !recordedAt
    || !sourceTabId
    || !sourceTabLabel
  ) {
    return null;
  }
  return {
    auditId,
    kind,
    summary,
    detail,
    recordedAt,
    sourceTabId,
    sourceTabLabel,
    conflictReview: normalizeComparisonHistorySyncConflictReview(candidate.conflictReview),
    preferenceReview: normalizeComparisonHistorySyncPreferenceReview(candidate.preferenceReview),
    workspaceReview: normalizeComparisonHistorySyncWorkspaceReview(candidate.workspaceReview),
  };
}

export function normalizeComparisonHistorySyncConflictReview(
  value: unknown,
): ComparisonHistorySyncConflictReview | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const candidate = value as Partial<ComparisonHistorySyncConflictReview>;
  const entryId = typeof candidate.entryId === "string" ? candidate.entryId.trim() : "";
  const entryLabel = typeof candidate.entryLabel === "string" ? candidate.entryLabel : "";
  const localEntry = normalizeComparisonHistoryPanelEntry(candidate.localEntry);
  const remoteEntry = normalizeComparisonHistoryPanelEntry(candidate.remoteEntry);
  if (!entryId || !entryLabel || !localEntry || !remoteEntry) {
    return null;
  }
  const selectedSources = normalizeComparisonHistorySyncConflictSelectedSources(candidate.selectedSources);
  return {
    entryId,
    entryLabel,
    localEntry,
    remoteEntry,
    selectedSources,
    resolvedAt: typeof candidate.resolvedAt === "string" ? candidate.resolvedAt : null,
    resolutionSummary:
      typeof candidate.resolutionSummary === "string" ? candidate.resolutionSummary : null,
  };
}

export function normalizeComparisonHistorySyncConflictSelectedSources(
  value: unknown,
): Partial<Record<ComparisonHistorySyncConflictFieldKey, ComparisonHistorySyncConflictFieldSource>> {
  if (!value || typeof value !== "object") {
    return {};
  }
  return COMPARISON_HISTORY_SYNC_CONFLICT_FIELD_DEFINITIONS.reduce<
    Partial<Record<ComparisonHistorySyncConflictFieldKey, ComparisonHistorySyncConflictFieldSource>>
  >((accumulator, definition) => {
    const candidate = (value as Record<string, unknown>)[definition.fieldKey];
    if (candidate === "local" || candidate === "remote") {
      accumulator[definition.fieldKey] = candidate;
    }
    return accumulator;
  }, {});
}

export function normalizeComparisonHistorySyncPreferenceReview(
  value: unknown,
): ComparisonHistorySyncPreferenceReview | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const candidate = value as Partial<ComparisonHistorySyncPreferenceReview>;
  const localState = normalizeComparisonHistorySyncPreferenceState(candidate.localState);
  const remoteState = normalizeComparisonHistorySyncPreferenceState(candidate.remoteState);
  if (!localState || !remoteState) {
    return null;
  }
  return {
    localState,
    remoteState,
    selectedSources: normalizeComparisonHistorySyncPreferenceSelectedSources(candidate.selectedSources),
    resolvedAt: typeof candidate.resolvedAt === "string" ? candidate.resolvedAt : null,
    resolutionSummary:
      typeof candidate.resolutionSummary === "string" ? candidate.resolutionSummary : null,
  };
}

export function normalizeComparisonHistorySyncWorkspaceReview(
  value: unknown,
): ComparisonHistorySyncWorkspaceReview | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const candidate = value as Partial<ComparisonHistorySyncWorkspaceReview>;
  const localState = normalizeComparisonHistorySyncWorkspaceState(candidate.localState);
  const remoteState = normalizeComparisonHistorySyncWorkspaceState(candidate.remoteState);
  if (!localState || !remoteState) {
    return null;
  }
  return {
    localState,
    remoteState,
    selectedSources: normalizeComparisonHistorySyncWorkspaceSelectedSources(candidate.selectedSources),
    resolvedAt: typeof candidate.resolvedAt === "string" ? candidate.resolvedAt : null,
    resolutionSummary:
      typeof candidate.resolutionSummary === "string" ? candidate.resolutionSummary : null,
  };
}

export function normalizeComparisonHistorySyncPreferenceState(
  value: unknown,
): ComparisonHistorySyncPreferenceState | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const candidate = value as Partial<ComparisonHistorySyncPreferenceState>;
  return {
    open: candidate.open === true,
    searchQuery: typeof candidate.searchQuery === "string" ? candidate.searchQuery : "",
    showPinnedOnly: candidate.showPinnedOnly === true,
    auditFilter: normalizeComparisonHistorySyncAuditFilter(candidate.auditFilter),
    showResolvedAuditEntries: candidate.showResolvedAuditEntries !== false,
  };
}

export function normalizeComparisonHistorySyncWorkspaceState(
  value: unknown,
): ComparisonHistorySyncWorkspaceState | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const candidate = value as Partial<ComparisonHistorySyncWorkspaceState>;
  return {
    comparisonSelection: normalizeControlRoomComparisonSelection(candidate.comparisonSelection),
    expandedGapRows: filterExpandedGapRows(candidate.expandedGapRows),
    expandedGapWindowSelections: filterExpandedGapWindowSelections(candidate.expandedGapWindowSelections),
  };
}

export function normalizeComparisonHistorySyncPreferenceSelectedSources(
  value: unknown,
): Partial<Record<ComparisonHistorySyncPreferenceFieldKey, ComparisonHistorySyncConflictFieldSource>> {
  if (!value || typeof value !== "object") {
    return {};
  }
  return COMPARISON_HISTORY_SYNC_PREFERENCE_FIELD_DEFINITIONS.reduce<
    Partial<Record<ComparisonHistorySyncPreferenceFieldKey, ComparisonHistorySyncConflictFieldSource>>
  >((accumulator, definition) => {
    const candidate = (value as Record<string, unknown>)[definition.fieldKey];
    if (candidate === "local" || candidate === "remote") {
      accumulator[definition.fieldKey] = candidate;
    }
    return accumulator;
  }, {});
}

export function normalizeComparisonHistorySyncWorkspaceSelectedSources(
  value: unknown,
): Partial<Record<ComparisonHistorySyncWorkspaceReviewSelectionKey, ComparisonHistorySyncConflictFieldSource>> {
  if (!value || typeof value !== "object") {
    return {};
  }
  const selectedSources = COMPARISON_HISTORY_SYNC_WORKSPACE_FIELD_DEFINITIONS.reduce<
    Partial<Record<ComparisonHistorySyncWorkspaceReviewSelectionKey, ComparisonHistorySyncConflictFieldSource>>
  >((accumulator, definition) => {
    const candidate = (value as Record<string, unknown>)[definition.fieldKey];
    if (candidate === "local" || candidate === "remote") {
      accumulator[definition.fieldKey] = candidate;
    }
    return accumulator;
  }, {});
  Object.entries(value as Record<string, unknown>).forEach(([key, candidate]) => {
    if (!key.startsWith("expandedGapRows:") && !key.startsWith("expandedGapWindows|")) {
      return;
    }
    if (candidate === "local" || candidate === "remote") {
      selectedSources[key as ComparisonHistorySyncWorkspaceReviewSelectionKey] = candidate;
    }
  });
  return selectedSources;
}

export function limitComparisonHistorySyncAuditEntries(entries: ComparisonHistorySyncAuditEntry[]) {
  return entries.slice(-MAX_COMPARISON_HISTORY_SYNC_AUDIT_ENTRIES);
}

export function appendComparisonHistorySyncAuditEntries(
  currentEntries: ComparisonHistorySyncAuditEntry[],
  nextEntries: ComparisonHistorySyncAuditEntry[],
) {
  if (!nextEntries.length) {
    return currentEntries;
  }
  return limitComparisonHistorySyncAuditEntries([
    ...currentEntries,
    ...nextEntries,
  ]);
}

export function isSameComparisonHistoryPanelState(
  left: ComparisonHistoryPanelState,
  right: ComparisonHistoryPanelState,
) {
  return (
    left.activeEntryId === right.activeEntryId
    && left.entries.length === right.entries.length
    && left.entries.every((entry, index) =>
      isSameComparisonHistoryPanelEntry(entry, right.entries[index]),
    )
  );
}

export function isSameComparisonHistoryPanelSyncState(
  left: ComparisonHistoryPanelSyncState | null,
  right: ComparisonHistoryPanelSyncState | null,
) {
  if (!left || !right) {
    return left === right;
  }
  return (
    left.tabId === right.tabId
    && left.tabLabel === right.tabLabel
    && left.updatedAt === right.updatedAt
  );
}

export function isSameComparisonHistoryPanelEntry(
  left: ComparisonHistoryPanelEntry,
  right: ComparisonHistoryPanelEntry | undefined,
) {
  if (!right) {
    return false;
  }
  return (
    left.entryId === right.entryId
    && left.stepIndex === right.stepIndex
    && left.label === right.label
    && left.summary === right.summary
    && left.title === right.title
    && left.url === right.url
    && left.hidden === right.hidden
    && left.pinned === right.pinned
    && left.recordedAt === right.recordedAt
    && isSameComparisonSelection(left.selection, right.selection)
  );
}

export function getComparisonHistoryPanelEntryChangedFields(
  localEntry: ComparisonHistoryPanelEntry,
  remoteEntry: ComparisonHistoryPanelEntry,
) {
  const fields: string[] = [];
  if (localEntry.stepIndex !== remoteEntry.stepIndex) {
    fields.push("step");
  }
  if (localEntry.label !== remoteEntry.label) {
    fields.push("label");
  }
  if (localEntry.summary !== remoteEntry.summary) {
    fields.push("summary");
  }
  if (localEntry.title !== remoteEntry.title) {
    fields.push("title");
  }
  if (localEntry.url !== remoteEntry.url) {
    fields.push("link");
  }
  if (localEntry.hidden !== remoteEntry.hidden) {
    fields.push(remoteEntry.hidden ? "cleared" : "restored");
  }
  if (localEntry.pinned !== remoteEntry.pinned) {
    fields.push(remoteEntry.pinned ? "pinned" : "unpinned");
  }
  if (!isSameComparisonSelection(localEntry.selection, remoteEntry.selection)) {
    fields.push("selection");
  }
  return fields;
}

export function formatComparisonHistorySyncConflictScoreLinkValue(
  scoreLink: ControlRoomComparisonSelectionState["scoreLink"],
) {
  if (!scoreLink) {
    return "No focus";
  }
  return `${truncateLabel(scoreLink.narrativeRunId, 18)} · ${formatComparisonScoreComponentLabel(
    scoreLink.section,
    scoreLink.componentKey,
  )}`;
}

export function formatComparisonHistorySyncConflictRunSelectionValue(selectedRunIds: string[]) {
  if (!selectedRunIds.length) {
    return "No runs selected";
  }
  const sample = selectedRunIds.slice(0, 2).map((runId) => truncateLabel(runId, 18)).join(", ");
  return selectedRunIds.length > 2
    ? `${selectedRunIds.length} runs · ${sample} +${selectedRunIds.length - 2}`
    : `${selectedRunIds.length} run${selectedRunIds.length === 1 ? "" : "s"} · ${sample}`;
}

export function formatComparisonHistorySyncConflictFieldValue(
  fieldKey: ComparisonHistorySyncConflictFieldKey,
  entry: ComparisonHistoryPanelEntry,
) {
  switch (fieldKey) {
    case "stepIndex":
      return `Step ${entry.stepIndex + 1}`;
    case "label":
      return entry.label;
    case "summary":
      return entry.summary;
    case "title":
      return entry.title;
    case "url":
      return entry.url;
    case "hidden":
      return entry.hidden ? "Cleared" : "Visible";
    case "pinned":
      return entry.pinned ? "Pinned" : "Not pinned";
    case "selection.intent":
      return formatComparisonIntentLabel(entry.selection.intent);
    case "selection.selectedRunIds":
      return formatComparisonHistorySyncConflictRunSelectionValue(entry.selection.selectedRunIds);
    case "selection.scoreLink":
      return formatComparisonHistorySyncConflictScoreLinkValue(entry.selection.scoreLink);
    default:
      return "n/a";
  }
}

export function hasComparisonHistorySyncConflictFieldDifference(
  fieldKey: ComparisonHistorySyncConflictFieldKey,
  localEntry: ComparisonHistoryPanelEntry,
  remoteEntry: ComparisonHistoryPanelEntry,
) {
  switch (fieldKey) {
    case "stepIndex":
      return localEntry.stepIndex !== remoteEntry.stepIndex;
    case "label":
      return localEntry.label !== remoteEntry.label;
    case "summary":
      return localEntry.summary !== remoteEntry.summary;
    case "title":
      return localEntry.title !== remoteEntry.title;
    case "url":
      return localEntry.url !== remoteEntry.url;
    case "hidden":
      return localEntry.hidden !== remoteEntry.hidden;
    case "pinned":
      return localEntry.pinned !== remoteEntry.pinned;
    case "selection.intent":
      return localEntry.selection.intent !== remoteEntry.selection.intent;
    case "selection.selectedRunIds":
      return !(
        localEntry.selection.selectedRunIds.length === remoteEntry.selection.selectedRunIds.length
        && localEntry.selection.selectedRunIds.every(
          (runId, index) => runId === remoteEntry.selection.selectedRunIds[index],
        )
      );
    case "selection.scoreLink":
      return !(
        localEntry.selection.scoreLink?.narrativeRunId === remoteEntry.selection.scoreLink?.narrativeRunId
        && localEntry.selection.scoreLink?.section === remoteEntry.selection.scoreLink?.section
        && localEntry.selection.scoreLink?.componentKey === remoteEntry.selection.scoreLink?.componentKey
      );
    default:
      return false;
  }
}
