// @ts-nocheck

import { CSSProperties, FormEvent, KeyboardEvent, MouseEvent, PointerEvent, ReactNode, forwardRef, useCallback, useEffect, useId, useLayoutEffect, useMemo, useRef, useState, AKRA_TOUCH_FEEDBACK_BRIDGE_VERSION, AKRA_TOUCH_FEEDBACK_EVENT_NAME, AkraTouchFeedbackDetail, AkraTouchFeedbackEnvelope, triggerAkraTouchFeedbackBridge, WorkspaceShell, buildControlWorkspaceDescriptors, ControlWorkspaceDescriptor, ControlStripMetric, useWorkspaceRoute, WorkspaceRouteContent, buildRunHistoryWorkspacePanels, LiveOrderReplacementDraft, RunHistoryWorkspaceSectionProps, RunOrderControls, getRunListBoundaryContractSnapshot, getRunListBoundarySurfaceLabel, getRunSurfaceCapabilityFamily, getRunSurfaceCapabilityFamilyOrder, getRunSurfaceCapabilityGroupOrder, getRunSurfaceCapabilitySchemaContract, getRunSurfaceCollectionQueryContracts, getRunSurfaceSharedContracts, getRunSurfaceSubresourceContracts, RunListComparisonBoundaryNote, shouldEnableReferenceProvenanceSemantics, shouldEnableRunListMetricDrillBack, shouldEnableRunSnapshotSemantics, shouldEnableStrategyCatalogSchemaHints, shouldHydratePresetParameterDefaults, shouldRenderOrderActionBoundaryNote, shouldRenderWorkflowControlBoundaryNote, RunSurfaceCollectionQueryBuilder, formatComparisonTooltipTuningDelta, formatComparisonTooltipTuningValue, formatRelativeTimestampLabel, RunSection, RunSurfaceCollectionQueryBuilderApplyPayload, RunSurfaceCollectionQueryRuntimeCandidateContextSelection, RunSurfaceCollectionQueryRuntimeCandidateSample, applyProviderProvenanceSchedulerStitchedReportGovernancePlan, applyProviderProvenanceSchedulerNarrativeGovernancePlan, approveProviderProvenanceSchedulerStitchedReportGovernancePlan, approveProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceAnalyticsPreset, createProviderProvenanceDashboardView, createProviderProvenanceExportJob, createProviderProvenanceSchedulerStitchedReportGovernanceRegistry, createProviderProvenanceSchedulerStitchedReportGovernancePlan, createProviderProvenanceSchedulerStitchedReportView, createProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, captureProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchy, createProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, createProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceSchedulerNarrativeRegistryEntry, createProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceScheduledReport, approveProviderProvenanceExportJob, applyProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, deleteProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, deleteProviderProvenanceSchedulerNarrativeRegistryEntry, deleteProviderProvenanceSchedulerStitchedReportView, deleteProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, createRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, createRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, downloadProviderProvenanceExportJob, downloadRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, escalateProviderProvenanceExportJob, exportProviderProvenanceSchedulerHealth, exportProviderProvenanceSchedulerStitchedNarrativeReport, reconstructProviderProvenanceSchedulerHealthExport, exportRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, fetchJson, getProviderProvenanceExportAnalytics, getProviderProvenanceExportJobHistory, getProviderProvenanceSchedulerHealthAnalytics, getProviderProvenanceScheduledReportHistory, getRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobHistory, listProviderProvenanceAnalyticsPresets, listProviderProvenanceDashboardViews, listProviderProvenanceSchedulerStitchedReportViews, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogs, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplates, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePlans, listProviderProvenanceSchedulerNarrativeRegistryEntries, listProviderProvenanceSchedulerNarrativeRegistryRevisions, listProviderProvenanceSchedulerNarrativeTemplates, listProviderProvenanceSchedulerNarrativeTemplateRevisions, listProviderProvenanceSchedulerStitchedReportGovernancePolicyCatalogs, listProviderProvenanceSchedulerStitchedReportGovernancePolicyTemplates, listProviderProvenanceSchedulerStitchedReportGovernancePlans, rollbackProviderProvenanceSchedulerStitchedReportGovernancePlan, rollbackProviderProvenanceSchedulerNarrativeGovernancePlan, listMarketDataIngestionJobs, listMarketDataLineageHistory, listProviderProvenanceExportJobs, listProviderProvenanceSchedulerAlertHistory, listProviderProvenanceSchedulerHealthHistory, listProviderProvenanceSchedulerStitchedReportGovernanceRegistries, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryAudits, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisions, listProviderProvenanceSchedulerStitchedReportViewAudits, listProviderProvenanceSchedulerStitchedReportViewRevisions, getProviderProvenanceSchedulerSearchDashboard, bulkGovernProviderProvenanceSchedulerSearchModerationPolicyCatalogs, bulkGovernProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, createProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicy, createProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, listProviderProvenanceSchedulerSearchModerationPolicyCatalogs, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlans, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAudits, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisions, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePlans, listProviderProvenanceSchedulerSearchModerationPolicyCatalogAudits, listProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisions, listProviderProvenanceSchedulerSearchModerationPlans, listProviderProvenanceScheduledReports, listRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, listRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, approveProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, approveProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, approveProviderProvenanceSchedulerSearchModerationPlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, applyProviderProvenanceSchedulerSearchModerationPlan, createProviderProvenanceSchedulerSearchModerationPolicyCatalog, deleteProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, deleteProviderProvenanceSchedulerSearchModerationPolicyCatalog, moderateProviderProvenanceSchedulerSearchFeedbackBatch, moderateProviderProvenanceSchedulerSearchFeedback, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, recordProviderProvenanceSchedulerSearchFeedback, resolveRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevision, restoreProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevision, restoreProviderProvenanceSchedulerSearchModerationPolicyCatalogRevision, restoreProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevision, restoreProviderProvenanceSchedulerNarrativeRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportViewRevision, restoreProviderProvenanceSchedulerNarrativeTemplateRevision, revokeRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, runProviderProvenanceSchedulerNarrativeGovernancePlanBatchAction, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkGovernance, stageProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, stageProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, stageProviderProvenanceSchedulerSearchModerationPlan, updateProviderProvenanceSchedulerSearchModerationPolicyCatalog, updateProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, stageProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, runDueProviderProvenanceScheduledReports, runProviderProvenanceScheduledReport, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStep, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, updateProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, updateProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, updateProviderProvenanceSchedulerNarrativeRegistryEntry, updateProviderProvenanceSchedulerStitchedReportGovernanceRegistry, updateProviderProvenanceSchedulerStitchedReportView, updateProviderProvenanceSchedulerNarrativeTemplate, updateProviderProvenanceExportJobPolicy, deleteProviderProvenanceSchedulerStitchedReportGovernanceRegistry, ALL_FILTER_VALUE, apiBase, COMPARISON_FOCUS_ARTIFACT_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_MICRO_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_NOTE_PAGE_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_SCRUB_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_COMPONENT_SEARCH_PARAM, COMPARISON_FOCUS_DETAIL_SEARCH_PARAM, COMPARISON_FOCUS_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ORIGIN_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_SECTION_SEARCH_PARAM, COMPARISON_FOCUS_SOURCE_SEARCH_PARAM, COMPARISON_FOCUS_TOOLTIP_SEARCH_PARAM, COMPARISON_HISTORY_BROWSER_STATE_KEY, COMPARISON_HISTORY_BROWSER_STATE_VERSION, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_KEY, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_VERSION, COMPARISON_HISTORY_SYNC_CONFLICT_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_PREFERENCE_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_WORKSPACE_FIELD_DEFINITIONS, COMPARISON_HISTORY_TAB_ID_SESSION_KEY, COMPARISON_INTENT_SEARCH_PARAM, COMPARISON_RUN_ID_SEARCH_PARAM, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_KEY, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_VERSION, COMPARISON_TOOLTIP_TUNING_GROUPS, COMPARISON_TOOLTIP_TUNING_LABELS, COMPARISON_TOOLTIP_TUNING_SHARE_PARAM, COMPARISON_TOOLTIP_TUNING_STORAGE_KEY, COMPARISON_TOOLTIP_TUNING_STORAGE_VERSION, COMPARISON_TOOLTIP_UNCHANGED_GROUP_COLLAPSE_THRESHOLD, CONTROL_ROOM_UI_STATE_STORAGE_KEY, CONTROL_ROOM_UI_STATE_VERSION, DEFAULT_COMPARISON_TOOLTIP_PRESET_IMPORT_CONFLICT_POLICY, DEFAULT_COMPARISON_TOOLTIP_TUNING, DEFAULT_CONTROL_ROOM_DOCUMENT_TITLE, LEGACY_GAP_WINDOW_EXPANSION_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_VERSION, MAX_COMPARISON_HISTORY_PANEL_ENTRIES, MAX_COMPARISON_HISTORY_SYNC_AUDIT_ENTRIES, MAX_COMPARISON_RUNS, MAX_MARKET_DATA_PROVENANCE_EXPORT_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_REVIEWED_CONFLICT_KEYS, MAX_VISIBLE_COMPARISON_TOOLTIP_CONFLICT_SESSION_SUMMARIES, MAX_VISIBLE_GAP_WINDOWS, PRESET_PROFILE_AGGRESSIVENESS_RANKS, PRESET_PROFILE_CONFIDENCE_RANKS, PRESET_PROFILE_SPEED_RANKS, PRESET_TIMEFRAME_UNIT_TO_MINUTES, REPLAY_INTENT_ACTION_FILTER_SEARCH_PARAM, REPLAY_INTENT_ALIAS_SEARCH_PARAM, REPLAY_INTENT_EDGE_FILTER_SEARCH_PARAM, REPLAY_INTENT_GROUP_FILTER_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_DIFF_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_GROUP_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_TRACE_SEARCH_PARAM, REPLAY_INTENT_SCOPE_SEARCH_PARAM, REPLAY_INTENT_SEARCH_PARAM, REPLAY_INTENT_STEP_SEARCH_PARAM, REPLAY_INTENT_TEMPLATE_SEARCH_PARAM, RUN_HISTORY_SAVED_FILTER_STORAGE_KEY_PREFIX, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_TAB_ID_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_BROWSER_STATE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_PAYLOAD_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_SIGNING_SECRET_STORAGE_KEY, SHOW_COMPARISON_TOOLTIP_TUNING_PANEL, TOUCH_GAP_WINDOW_SWEEP_HOLD_MS, TOUCH_GAP_WINDOW_SWEEP_MOVE_TOLERANCE_PX, BenchmarkArtifact, ParameterSchema, ComparisonCueKind, ComparisonHistoryBrowserState, ComparisonHistoryPanelEntry, ComparisonHistoryPanelState, ComparisonHistoryPanelSyncState, ComparisonHistoryStepDescriptor, ComparisonHistorySyncAuditEntry, ComparisonHistorySyncAuditFilter, ComparisonHistorySyncAuditKind, ComparisonHistorySyncAuditTrailState, ComparisonHistorySyncConflictFieldKey, ComparisonHistorySyncConflictFieldSource, ComparisonHistorySyncConflictReview, ComparisonHistorySyncConflictReviewGroup, ComparisonHistorySyncPreferenceFieldKey, ComparisonHistorySyncPreferenceReview, ComparisonHistorySyncPreferenceReviewRow, ComparisonHistorySyncPreferenceState, ComparisonHistorySyncWorkspaceRecommendationOverview, ComparisonHistorySyncWorkspaceReview, ComparisonHistorySyncWorkspaceReviewRow, ComparisonHistorySyncWorkspaceReviewSelectionKey, ComparisonHistorySyncWorkspaceSemanticSignal, ComparisonHistorySyncWorkspaceSignalDetailNestedKey, ComparisonHistorySyncWorkspaceSignalDetailSubviewKey, ComparisonHistorySyncWorkspaceSignalMicroInteractionKey, ComparisonHistorySyncWorkspaceSignalMicroViewKey, ComparisonHistorySyncWorkspaceState, ComparisonHistoryTabIdentity, ComparisonHistoryWriteMode, ComparisonIntent, ComparisonScoreDrillBackOptions, ComparisonScoreLinkedRunRole, ComparisonScoreLinkSource, ComparisonScoreLinkTarget, ComparisonScoreSection, ComparisonTooltipConflictSessionSummary, ComparisonTooltipConflictSessionSummarySession, ComparisonTooltipConflictSessionUiState, ComparisonTooltipConflictUiStateV1, ComparisonTooltipInteractionOptions, ComparisonTooltipLayout, ComparisonTooltipPendingPresetImportConflict, ComparisonTooltipPresetConflictPreviewGroup, ComparisonTooltipPresetConflictPreviewRow, ComparisonTooltipPresetImportConflictPolicy, ComparisonTooltipPresetImportResolution, ComparisonTooltipTargetProps, ComparisonTooltipTuning, ComparisonTooltipTuningPresetStateV1, ComparisonTooltipTuningShareImport, ComparisonTooltipTuningSinglePresetShareV1, ControlRoomComparisonHistoryPanelUiState, ControlRoomComparisonSelectionState, ControlRoomUiStateV1, ControlRoomUiStateV2, ControlRoomUiStateV3, ControlRoomUiStateV4, ExpandedGapWindowSelections, ExperimentPreset, ExperimentPresetRevision, GapWindowDragSelectionState, GuardedLiveStatus, MarketDataIngestionJobRecord, MarketDataProvenanceExportFilterState, MarketDataProvenanceExportHistoryEntry, MarketDataProvenanceExportSort, MarketDataProvenanceExportStateV1, MarketDataLineageHistoryRecord, MarketDataStatus, OperatorAlertMarketContextProvenance, OperatorAlertPrimaryFocus, OperatorVisibility, PendingTouchGapWindowSweepState, PresetDraftConflict, PresetRevisionDiff, PresetRevisionFilterState, PresetStructuredDiffDeltaValue, PresetStructuredDiffGroup, PresetStructuredDiffRow, ProviderProvenanceAnalyticsPresetEntry, ProviderProvenanceDashboardLayout, ProviderProvenanceDashboardViewEntry, ProviderProvenanceExportAnalyticsPayload, ProviderProvenanceExportJobEntry, ProviderProvenanceExportJobEscalationResult, ProviderProvenanceExportJobHistoryPayload, ProviderProvenanceExportJobPolicyResult, ProviderProvenanceSchedulerAlertHistoryPayload, ProviderProvenanceSchedulerHealthExportPayload, ProviderProvenanceSchedulerHealthAnalyticsPayload, ProviderProvenanceSchedulerHealthHistoryPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditRecord, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditRecord, ProviderProvenanceSchedulerSearchModerationPlanListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogListPayload, ProviderProvenanceSchedulerSearchFeedbackBatchModerationResult, ProviderProvenanceSchedulerSearchDashboardPayload, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditRecord, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionListPayload, ProviderProvenanceSchedulerStitchedReportViewAuditRecord, ProviderProvenanceSchedulerStitchedReportViewEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionListPayload, ProviderProvenanceSchedulerNarrativeBulkGovernanceResult, ProviderProvenanceSchedulerNarrativeGovernancePlan, ProviderProvenanceSchedulerNarrativeGovernancePlanBatchResult, ProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyStep, ProviderProvenanceSchedulerNarrativeGovernanceQueueView, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeRegistryEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionListPayload, ProviderProvenanceSchedulerNarrativeTemplateEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionListPayload, ProviderProvenanceScheduledReportEntry, ProviderProvenanceScheduledReportHistoryPayload, ProvenanceArtifactLineDetailView, ProvenanceArtifactLineMicroView, ReferenceSource, Run, RunComparison, RunHistoryFilter, RunHistorySurfaceKey, RunListBoundaryContract, RunListBoundaryEligibility, RunListBoundaryGroupKey, RunListBoundarySurfaceId, RunSurfaceCapabilities, RunSurfaceCapabilityFamily, RunSurfaceCapabilityFamilyContract, RunSurfaceCapabilityFamilyKey, RunSurfaceCapabilitySchemaContract, RunSurfaceCapabilitySurfaceKey, RunSurfaceCollectionQueryBuilderReplayIntentSnapshot, RunSurfaceCollectionQueryBuilderReplayLinkAliasRecordPayload, RunSurfaceCollectionQueryBuilderReplayLinkRedactionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkRetentionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobDownloadPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobPrunePayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditPrunePayload, RunSurfaceCollectionQueryContract, RunSurfaceCollectionQueryElementField, RunSurfaceCollectionQueryExpressionAuthoring, RunSurfaceCollectionQueryParameterDomainDescriptor, RunSurfaceCollectionQuerySchema, RunSurfaceSharedContract, RunSurfaceSubresourceContract, SavedRunHistoryFilterPreset, SavedRunHistoryFilterPresetStateV1, Strategy, TouchGapWindowActivationFeedbackState, TouchGapWindowHoldProgressState } from "./ControlRoomCoreHelpersContext";
import { defaultRunForm, defaultPresetForm, defaultPresetRevisionFilter, defaultMarketDataProvenanceExportFilterState, ProviderProvenanceAnalyticsScope, ProviderProvenanceSchedulerOccurrenceNarrativeFacet, ProviderProvenanceAnalyticsQueryState, ProviderProvenanceSchedulerSearchDashboardFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, ProviderProvenanceSchedulerSearchModerationQueueFilterState, ProviderProvenanceSchedulerSearchModerationStageDraft, ProviderProvenanceSchedulerExportPolicyDraft, OperatorVisibilityAlertEntry, defaultProviderProvenanceAnalyticsQueryState, defaultProviderProvenanceSchedulerSearchDashboardFilterState, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilter, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, defaultProviderProvenanceSchedulerSearchModerationQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationStageDraft, normalizeProviderProvenanceSchedulerRoutingPolicyDraftValue, normalizeProviderProvenanceSchedulerApprovalPolicyDraftValue, buildProviderProvenanceSchedulerExportPolicyDraft, getProviderProvenanceSchedulerNarrativeGovernanceQueuePriorityRank, getProviderProvenanceSchedulerNarrativeGovernanceQueueState, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchySummary, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepSummary, formatProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyPosition, isProviderProvenanceSchedulerAlertCategory, getOperatorAlertOccurrenceKey, formatProviderProvenanceSchedulerTimelineSummary, formatProviderProvenanceSchedulerSearchMatchSummary, formatProviderProvenanceSchedulerRetrievalClusterSummary, buildProviderProvenanceSchedulerAlertWorkflowReason } from "./ControlRoomCoreDefaults";
import { defaultProviderProvenanceDashboardLayout, DEFAULT_PROVIDER_PROVENANCE_SCHEDULER_NARRATIVE_GOVERNANCE_QUEUE_SORT, defaultProviderProvenanceWorkspaceDraft, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraftState, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraft, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraftState, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraft, KEEP_CURRENT_BULK_GOVERNANCE_VALUE, CLEAR_TEMPLATE_LINK_BULK_GOVERNANCE_VALUE, ProviderProvenanceSchedulerNarrativeBulkToggleValue, ProviderProvenanceSchedulerNarrativeTemplateBulkDraftState, defaultProviderProvenanceSchedulerNarrativeTemplateBulkDraft, ProviderProvenanceSchedulerStitchedReportViewBulkDraftState, defaultProviderProvenanceSchedulerStitchedReportViewBulkDraft, ProviderProvenanceSchedulerNarrativeRegistryDraftState, defaultProviderProvenanceSchedulerNarrativeRegistryDraft, ProviderProvenanceSchedulerNarrativeRegistryBulkDraftState, defaultProviderProvenanceSchedulerNarrativeRegistryBulkDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraft, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraftState, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraft, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraftState, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepVersionEntry, ProviderProvenanceSchedulerNarrativeGovernanceQueueFilterState, defaultProviderProvenanceSchedulerNarrativeGovernanceQueueFilter, ProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterState, defaultProviderProvenanceSchedulerStitchedReportGovernanceQueueFilter, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilterState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilter, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilterState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilter, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilterState, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilter, ProviderProvenanceSchedulerStitchedReportViewAuditFilterState, defaultProviderProvenanceSchedulerStitchedReportViewAuditFilter, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilterState, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilter, ProviderProvenanceReportDraftState, defaultProviderProvenanceReportDraft } from "./ControlRoomCoreProviderDrafts";
import { buildPresetFormFromPreset, buildCurrentPresetRevisionSnapshot, buildEmptyPresetRevisionSnapshot, formatPresetStructuredDiffDisplayValue, isPresetStructuredDiffObject, isPresetStructuredDiffScalar, arePresetStructuredDiffValuesEquivalent, matchesPresetParameterSchemaType, joinPresetStructuredDiffHints, tokenizePresetParameterPath, parsePresetTimeframeToMinutes, buildPresetRankedStringDelta, buildPresetParameterStrategyContext, buildPresetParameterDomainContext, formatPresetParameterSchemaHint, getPresetParameterSchemaEntry, buildPresetStructuredDiffDelta, summarizePresetStructuredDiffGroup, groupPresetStructuredDiffRows, buildPresetStructuredDiffRows, describePresetRevisionDiff, describePresetDraftConflict, matchesPresetRevisionFilter } from "./ControlRoomCorePresetDiff";
import { defaultRunHistoryFilter, sanitizeRunHistoryFilter, cloneRunHistoryFilter, hasRunHistoryFilterCriteria, areRunHistoryFiltersEquivalent, buildRunHistorySavedFilterStorageKey, normalizeSavedRunHistoryFilterPreset, loadSavedRunHistoryFilterPresets, persistSavedRunHistoryFilterPresets, describeRunHistoryFilter, DEFAULT_COMPARISON_INTENT, comparisonIntentOptions, parseExperimentTags, parseJsonObjectInput, formatPresetLifecycleStage, buildRunSubmissionPayload, normalizeRunFormPreset } from "./ControlRoomCoreRunHistory";

export function resolveMarketDataSymbol(instrumentId: string) {
  const separatorIndex = instrumentId.indexOf(":");
  return separatorIndex >= 0 ? instrumentId.slice(separatorIndex + 1) : instrumentId;
}

export function buildMarketDataInstrumentFocusKey(
  instrument: MarketDataStatus["instruments"][number],
) {
  return `${instrument.instrument_id}|${instrument.timeframe}`;
}

export function isMarketDataInstrumentAtRisk(
  instrument: MarketDataStatus["instruments"][number],
) {
  return (
    instrument.sync_status !== "synced"
    || instrument.failure_count_24h > 0
    || (instrument.lag_seconds ?? 0) > 0
    || instrument.backfill_gap_windows.length > 0
    || instrument.issues.length > 0
  );
}

export function resolvePreferredMarketDataInstrument(
  marketStatus: MarketDataStatus,
  preferredKey: string | null,
) {
  if (preferredKey) {
    const preferredInstrument = marketStatus.instruments.find(
      (instrument) => buildMarketDataInstrumentFocusKey(instrument) === preferredKey,
    );
    if (preferredInstrument) {
      return preferredInstrument;
    }
  }
  return (
    marketStatus.instruments.find((instrument) => isMarketDataInstrumentAtRisk(instrument))
    ?? marketStatus.instruments[0]
    ?? null
  );
}

export function formatWorkflowToken(value?: string | null) {
  if (!value) {
    return "n/a";
  }
  return value.replaceAll("_", " ");
}

export type LinkedMarketInstrumentContext = {
  instrument: MarketDataStatus["instruments"][number];
  focusKey: string;
  symbol: string;
  timeframe: string;
  matchReason: string;
  candidateCount: number;
  candidateLabels: string[];
  primaryFocusPolicy: string;
  primaryFocusReason: string;
};

export type MarketDataLinkableAlertRecord = {
  alert_id?: string | null;
  category?: string | null;
  summary: string;
  detail: string;
  run_id?: string | null;
  session_id?: string | null;
  symbol?: string | null;
  symbols?: string[];
  timeframe?: string | null;
  primary_focus?: OperatorAlertPrimaryFocus | null;
  source?: string | null;
  provider_recovery_symbols?: string[];
  provider_recovery_timeframe?: string | null;
};

export type MarketDataIncidentHistoryEntry = {
  entryId: string;
  occurredAt: string;
  sourceLabel: string;
  statusLabel: string;
  summary: string;
  detail: string;
  tone: "critical" | "warning" | "neutral";
};

export type ProviderRecoveryMarketContextSummary = {
  summary: string;
  fieldSummaries: string[];
};

export type MarketDataProviderProvenanceEventRecord = {
  event: OperatorVisibility["incident_events"][number];
  link: LinkedMarketInstrumentContext | null;
  provider: string;
  vendorField: string;
  provenanceSummary: string;
  fieldSummaries: string[];
  severityRank: number;
  occurredAtMs: number;
  searchText: string;
};

export type MarketDataPrimaryFocusSelection = {
  instrument: MarketDataStatus["instruments"][number];
  candidateCount: number;
  candidateLabels: string[];
  primaryFocusPolicy: string;
  primaryFocusReason: string;
};

export function formatMarketContextFieldProvenance(
  label: string,
  provenance?: OperatorAlertMarketContextProvenance["symbol"] | null,
) {
  if (!provenance) {
    return null;
  }
  const scope = provenance.scope?.trim() || null;
  const path = provenance.path?.trim() || null;
  if (!scope && !path) {
    return null;
  }
  return `${label} ${scope && path ? `${scope} -> ${path}` : scope ?? path}`;
}

export function summarizeProviderRecoveryMarketContextProvenance(providerRecovery: {
  provider?: string | null;
  market_context_provenance?: OperatorAlertMarketContextProvenance | null;
}): ProviderRecoveryMarketContextSummary | null {
  const provenance = providerRecovery.market_context_provenance;
  if (!provenance) {
    return null;
  }
  const fieldSummaries = [
    formatMarketContextFieldProvenance("symbol", provenance.symbol),
    formatMarketContextFieldProvenance("symbols", provenance.symbols),
    formatMarketContextFieldProvenance("timeframe", provenance.timeframe),
    formatMarketContextFieldProvenance("primary focus", provenance.primary_focus),
  ].filter((value): value is string => Boolean(value));
  const summaryLead = [
    provenance.provider?.trim() || providerRecovery.provider?.trim() || null,
    provenance.vendor_field?.trim() ? `via ${provenance.vendor_field.trim()}` : null,
  ].filter(Boolean);
  const parts = [
    summaryLead.length ? summaryLead.join(" ") : null,
    ...fieldSummaries,
  ].filter((value): value is string => Boolean(value));
  if (!parts.length) {
    return null;
  }
  return {
    summary: `Market-context provenance: ${parts.join(" / ")}`,
    fieldSummaries,
  };
}

export function serializeLinkedMarketInstrumentContext(link: LinkedMarketInstrumentContext | null) {
  if (!link) {
    return null;
  }
  return {
    symbol: link.symbol,
    timeframe: link.timeframe,
    match_reason: link.matchReason,
    candidate_count: link.candidateCount,
    candidate_labels: link.candidateLabels,
    primary_focus_policy: link.primaryFocusPolicy,
    primary_focus_reason: link.primaryFocusReason,
  };
}

export function getOperatorSeverityRank(severity: string) {
  switch (severity) {
    case "critical":
      return 3;
    case "warning":
      return 2;
    case "info":
      return 1;
    default:
      return 0;
  }
}

export function normalizeMarketDataProvenanceExportSort(
  value: unknown,
): MarketDataProvenanceExportSort {
  return value === "oldest" || value === "provider" || value === "severity" || value === "newest"
    ? value
    : defaultMarketDataProvenanceExportFilterState.sort;
}

export function normalizeMarketDataProvenanceExportFilterState(
  value: unknown,
): MarketDataProvenanceExportFilterState {
  if (!value || typeof value !== "object") {
    return { ...defaultMarketDataProvenanceExportFilterState };
  }
  const candidate = value as Partial<MarketDataProvenanceExportFilterState>;
  return {
    provider:
      typeof candidate.provider === "string" && candidate.provider.trim().length
        ? candidate.provider
        : defaultMarketDataProvenanceExportFilterState.provider,
    vendor_field:
      typeof candidate.vendor_field === "string" && candidate.vendor_field.trim().length
        ? candidate.vendor_field
        : defaultMarketDataProvenanceExportFilterState.vendor_field,
    search_query:
      typeof candidate.search_query === "string"
        ? candidate.search_query
        : defaultMarketDataProvenanceExportFilterState.search_query,
    sort: normalizeMarketDataProvenanceExportSort(candidate.sort),
  };
}

export function normalizeMarketDataProvenanceExportHistoryEntry(
  value: unknown,
): MarketDataProvenanceExportHistoryEntry | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const candidate = value as Partial<MarketDataProvenanceExportHistoryEntry>;
  if (
    typeof candidate.export_id !== "string"
    || typeof candidate.exported_at !== "string"
    || typeof candidate.focus_key !== "string"
    || typeof candidate.focus_label !== "string"
    || typeof candidate.symbol !== "string"
    || typeof candidate.timeframe !== "string"
    || typeof candidate.provider !== "string"
    || typeof candidate.venue !== "string"
    || typeof candidate.result_count !== "number"
    || typeof candidate.provider_provenance_count !== "number"
    || !Array.isArray(candidate.provider_labels)
    || typeof candidate.content !== "string"
  ) {
    return null;
  }
  return {
    export_id: candidate.export_id,
    exported_at: candidate.exported_at,
    focus_key: candidate.focus_key,
    focus_label: candidate.focus_label,
    symbol: candidate.symbol,
    timeframe: candidate.timeframe,
    provider: candidate.provider,
    venue: candidate.venue,
    result_count: candidate.result_count,
    provider_provenance_count: candidate.provider_provenance_count,
    provider_labels: candidate.provider_labels.filter((label): label is string => typeof label === "string"),
    filter: normalizeMarketDataProvenanceExportFilterState(candidate.filter),
    content: candidate.content,
  };
}

export function loadPersistedMarketDataProvenanceExportState(): {
  activeFilter: MarketDataProvenanceExportFilterState;
  history: MarketDataProvenanceExportHistoryEntry[];
} {
  if (typeof window === "undefined") {
    return {
      activeFilter: { ...defaultMarketDataProvenanceExportFilterState },
      history: [],
    };
  }
  try {
    const raw = window.localStorage.getItem(MARKET_DATA_PROVENANCE_EXPORT_STORAGE_KEY);
    if (!raw) {
      return {
        activeFilter: { ...defaultMarketDataProvenanceExportFilterState },
        history: [],
      };
    }
    const parsed = JSON.parse(raw) as Partial<MarketDataProvenanceExportStateV1> | null;
    if (parsed?.version !== MARKET_DATA_PROVENANCE_EXPORT_STORAGE_VERSION) {
      return {
        activeFilter: { ...defaultMarketDataProvenanceExportFilterState },
        history: [],
      };
    }
    return {
      activeFilter: normalizeMarketDataProvenanceExportFilterState(parsed.active_filter),
      history: Array.isArray(parsed.history)
        ? parsed.history
            .map((entry) => normalizeMarketDataProvenanceExportHistoryEntry(entry))
            .filter((entry): entry is MarketDataProvenanceExportHistoryEntry => entry !== null)
            .slice(0, MAX_MARKET_DATA_PROVENANCE_EXPORT_HISTORY_ENTRIES)
        : [],
    };
  } catch {
    return {
      activeFilter: { ...defaultMarketDataProvenanceExportFilterState },
      history: [],
    };
  }
}

export function persistMarketDataProvenanceExportState(state: {
  activeFilter: MarketDataProvenanceExportFilterState;
  history: MarketDataProvenanceExportHistoryEntry[];
}) {
  if (typeof window === "undefined") {
    return;
  }
  try {
    const nextState: MarketDataProvenanceExportStateV1 = {
      version: MARKET_DATA_PROVENANCE_EXPORT_STORAGE_VERSION,
      active_filter: normalizeMarketDataProvenanceExportFilterState(state.activeFilter),
      history: state.history.slice(0, MAX_MARKET_DATA_PROVENANCE_EXPORT_HISTORY_ENTRIES),
    };
    window.localStorage.setItem(
      MARKET_DATA_PROVENANCE_EXPORT_STORAGE_KEY,
      JSON.stringify(nextState),
    );
  } catch {
    // Ignore localStorage failures for provider provenance export state.
  }
}

export function formatMarketDataProvenanceExportFilterSummary(
  filter: MarketDataProvenanceExportFilterState,
) {
  const parts = [
    filter.provider !== ALL_FILTER_VALUE ? `provider ${filter.provider}` : null,
    filter.vendor_field !== ALL_FILTER_VALUE ? `vendor field ${filter.vendor_field}` : null,
    filter.search_query.trim() ? `search ${filter.search_query.trim()}` : null,
    filter.sort !== "newest" ? `sort ${filter.sort}` : null,
  ].filter((value): value is string => Boolean(value));
  return parts.length ? parts.join(" / ") : "All providers · newest first";
}

export function formatProviderProvenanceAnalyticsQuerySummary(
  query: ProviderProvenanceAnalyticsQueryState,
) {
  const parts = [
    query.scope === "all_focuses" ? "all focuses" : "current focus",
    `${query.window_days}d window`,
    query.provider_label !== ALL_FILTER_VALUE ? `provider ${query.provider_label}` : null,
    query.vendor_field !== ALL_FILTER_VALUE ? `vendor field ${query.vendor_field}` : null,
    query.market_data_provider !== ALL_FILTER_VALUE ? `market data ${query.market_data_provider}` : null,
    query.requested_by_tab_id !== ALL_FILTER_VALUE ? `requester ${query.requested_by_tab_id}` : null,
    query.scheduler_alert_category !== ALL_FILTER_VALUE
      ? `scheduler category ${query.scheduler_alert_category}`
      : null,
    query.scheduler_alert_status !== ALL_FILTER_VALUE
      ? `scheduler status ${query.scheduler_alert_status}`
      : null,
    query.scheduler_alert_narrative_facet !== "all_occurrences"
      ? `scheduler ${formatProviderProvenanceSchedulerNarrativeFacet(query.scheduler_alert_narrative_facet)}`
      : null,
    query.search_query.trim() ? `search ${query.search_query.trim()}` : null,
  ].filter((value): value is string => Boolean(value));
  return parts.join(" / ");
}

export function normalizeProviderProvenanceDashboardLayoutState(
  layout: Partial<ProviderProvenanceDashboardLayout> | null | undefined,
): ProviderProvenanceDashboardLayout {
  const normalizedGovernanceQueueView = normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueView(
    layout?.governance_queue_view,
  );
  return {
    highlight_panel:
      layout?.highlight_panel === "drift"
      || layout?.highlight_panel === "burn_up"
      || layout?.highlight_panel === "rollups"
      || layout?.highlight_panel === "scheduler_alerts"
      || layout?.highlight_panel === "recent_exports"
        ? layout.highlight_panel
        : "overview",
    show_rollups: layout?.show_rollups !== false,
    show_time_series: layout?.show_time_series !== false,
    show_recent_exports: layout?.show_recent_exports !== false,
    ...(normalizedGovernanceQueueView
      ? {
          governance_queue_view: normalizedGovernanceQueueView,
        }
      : {}),
  };
}

// Runtime placeholders for generated barrel compatibility.
export const LinkedMarketInstrumentContext = undefined;
export const MarketDataLinkableAlertRecord = undefined;
export const MarketDataIncidentHistoryEntry = undefined;
export const ProviderRecoveryMarketContextSummary = undefined;
export const MarketDataProviderProvenanceEventRecord = undefined;
export const MarketDataPrimaryFocusSelection = undefined;
