// @ts-nocheck

import { CSSProperties, FormEvent, KeyboardEvent, MouseEvent, PointerEvent, ReactNode, forwardRef, useCallback, useEffect, useId, useLayoutEffect, useMemo, useRef, useState, AKRA_TOUCH_FEEDBACK_BRIDGE_VERSION, AKRA_TOUCH_FEEDBACK_EVENT_NAME, AkraTouchFeedbackDetail, AkraTouchFeedbackEnvelope, triggerAkraTouchFeedbackBridge, WorkspaceShell, buildControlWorkspaceDescriptors, ControlWorkspaceDescriptor, ControlStripMetric, useWorkspaceRoute, WorkspaceRouteContent, buildRunHistoryWorkspacePanels, LiveOrderReplacementDraft, RunHistoryWorkspaceSectionProps, RunOrderControls, getRunListBoundaryContractSnapshot, getRunListBoundarySurfaceLabel, getRunSurfaceCapabilityFamily, getRunSurfaceCapabilityFamilyOrder, getRunSurfaceCapabilityGroupOrder, getRunSurfaceCapabilitySchemaContract, getRunSurfaceCollectionQueryContracts, getRunSurfaceSharedContracts, getRunSurfaceSubresourceContracts, RunListComparisonBoundaryNote, shouldEnableStrategyProvenanceSemantics, shouldEnableRunListMetricDrillBack, shouldEnableRunSnapshotSemantics, shouldEnableStrategyCatalogSchemaHints, shouldHydratePresetParameterDefaults, shouldRenderOrderActionBoundaryNote, shouldRenderWorkflowControlBoundaryNote, RunSurfaceCollectionQueryBuilder, formatComparisonTooltipTuningDelta, formatComparisonTooltipTuningValue, formatRelativeTimestampLabel, RunSection, RunSurfaceCollectionQueryBuilderApplyPayload, RunSurfaceCollectionQueryRuntimeCandidateContextSelection, RunSurfaceCollectionQueryRuntimeCandidateSample, applyProviderProvenanceSchedulerStitchedReportGovernancePlan, applyProviderProvenanceSchedulerNarrativeGovernancePlan, approveProviderProvenanceSchedulerStitchedReportGovernancePlan, approveProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceAnalyticsPreset, createProviderProvenanceDashboardView, createProviderProvenanceExportJob, createProviderProvenanceSchedulerStitchedReportGovernanceRegistry, createProviderProvenanceSchedulerStitchedReportGovernancePlan, createProviderProvenanceSchedulerStitchedReportView, createProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, captureProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchy, createProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, createProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceSchedulerNarrativeRegistryEntry, createProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceScheduledReport, approveProviderProvenanceExportJob, applyProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, deleteProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, deleteProviderProvenanceSchedulerNarrativeRegistryEntry, deleteProviderProvenanceSchedulerStitchedReportView, deleteProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, createRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, createRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, downloadProviderProvenanceExportJob, downloadRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, escalateProviderProvenanceExportJob, exportProviderProvenanceSchedulerHealth, exportProviderProvenanceSchedulerStitchedNarrativeReport, reconstructProviderProvenanceSchedulerHealthExport, exportRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, fetchJson, getProviderProvenanceExportAnalytics, getProviderProvenanceExportJobHistory, getProviderProvenanceSchedulerHealthAnalytics, getProviderProvenanceScheduledReportHistory, getRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobHistory, listProviderProvenanceAnalyticsPresets, listProviderProvenanceDashboardViews, listProviderProvenanceSchedulerStitchedReportViews, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogs, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplates, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePlans, listProviderProvenanceSchedulerNarrativeRegistryEntries, listProviderProvenanceSchedulerNarrativeRegistryRevisions, listProviderProvenanceSchedulerNarrativeTemplates, listProviderProvenanceSchedulerNarrativeTemplateRevisions, listProviderProvenanceSchedulerStitchedReportGovernancePolicyCatalogs, listProviderProvenanceSchedulerStitchedReportGovernancePolicyTemplates, listProviderProvenanceSchedulerStitchedReportGovernancePlans, rollbackProviderProvenanceSchedulerStitchedReportGovernancePlan, rollbackProviderProvenanceSchedulerNarrativeGovernancePlan, listMarketDataIngestionJobs, listMarketDataLineageHistory, listProviderProvenanceExportJobs, listProviderProvenanceSchedulerAlertHistory, listProviderProvenanceSchedulerHealthHistory, listProviderProvenanceSchedulerStitchedReportGovernanceRegistries, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryAudits, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisions, listProviderProvenanceSchedulerStitchedReportViewAudits, listProviderProvenanceSchedulerStitchedReportViewRevisions, getProviderProvenanceSchedulerSearchDashboard, bulkGovernProviderProvenanceSchedulerSearchModerationPolicyCatalogs, bulkGovernProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, createProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicy, createProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, listProviderProvenanceSchedulerSearchModerationPolicyCatalogs, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlans, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAudits, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisions, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePlans, listProviderProvenanceSchedulerSearchModerationPolicyCatalogAudits, listProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisions, listProviderProvenanceSchedulerSearchModerationPlans, listProviderProvenanceScheduledReports, listRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, listRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, approveProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, approveProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, approveProviderProvenanceSchedulerSearchModerationPlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, applyProviderProvenanceSchedulerSearchModerationPlan, createProviderProvenanceSchedulerSearchModerationPolicyCatalog, deleteProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, deleteProviderProvenanceSchedulerSearchModerationPolicyCatalog, moderateProviderProvenanceSchedulerSearchFeedbackBatch, moderateProviderProvenanceSchedulerSearchFeedback, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, recordProviderProvenanceSchedulerSearchFeedback, resolveRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevision, restoreProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevision, restoreProviderProvenanceSchedulerSearchModerationPolicyCatalogRevision, restoreProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevision, restoreProviderProvenanceSchedulerNarrativeRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportViewRevision, restoreProviderProvenanceSchedulerNarrativeTemplateRevision, revokeRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, runProviderProvenanceSchedulerNarrativeGovernancePlanBatchAction, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkGovernance, stageProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, stageProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, stageProviderProvenanceSchedulerSearchModerationPlan, updateProviderProvenanceSchedulerSearchModerationPolicyCatalog, updateProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, stageProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, runDueProviderProvenanceScheduledReports, runProviderProvenanceScheduledReport, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStep, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, updateProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, updateProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, updateProviderProvenanceSchedulerNarrativeRegistryEntry, updateProviderProvenanceSchedulerStitchedReportGovernanceRegistry, updateProviderProvenanceSchedulerStitchedReportView, updateProviderProvenanceSchedulerNarrativeTemplate, updateProviderProvenanceExportJobPolicy, deleteProviderProvenanceSchedulerStitchedReportGovernanceRegistry, ALL_FILTER_VALUE, apiBase, COMPARISON_FOCUS_ARTIFACT_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_MICRO_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_NOTE_PAGE_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_SCRUB_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_COMPONENT_SEARCH_PARAM, COMPARISON_FOCUS_DETAIL_SEARCH_PARAM, COMPARISON_FOCUS_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ORIGIN_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_SECTION_SEARCH_PARAM, COMPARISON_FOCUS_SOURCE_SEARCH_PARAM, COMPARISON_FOCUS_TOOLTIP_SEARCH_PARAM, COMPARISON_HISTORY_BROWSER_STATE_KEY, COMPARISON_HISTORY_BROWSER_STATE_VERSION, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_KEY, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_VERSION, COMPARISON_HISTORY_SYNC_CONFLICT_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_PREFERENCE_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_WORKSPACE_FIELD_DEFINITIONS, COMPARISON_HISTORY_TAB_ID_SESSION_KEY, COMPARISON_INTENT_SEARCH_PARAM, COMPARISON_RUN_ID_SEARCH_PARAM, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_KEY, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_VERSION, COMPARISON_TOOLTIP_TUNING_GROUPS, COMPARISON_TOOLTIP_TUNING_LABELS, COMPARISON_TOOLTIP_TUNING_SHARE_PARAM, COMPARISON_TOOLTIP_TUNING_STORAGE_KEY, COMPARISON_TOOLTIP_TUNING_STORAGE_VERSION, COMPARISON_TOOLTIP_UNCHANGED_GROUP_COLLAPSE_THRESHOLD, CONTROL_ROOM_UI_STATE_STORAGE_KEY, CONTROL_ROOM_UI_STATE_VERSION, DEFAULT_COMPARISON_TOOLTIP_PRESET_IMPORT_CONFLICT_POLICY, DEFAULT_COMPARISON_TOOLTIP_TUNING, DEFAULT_CONTROL_ROOM_DOCUMENT_TITLE, LEGACY_GAP_WINDOW_EXPANSION_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_VERSION, MAX_COMPARISON_HISTORY_PANEL_ENTRIES, MAX_COMPARISON_HISTORY_SYNC_AUDIT_ENTRIES, MAX_COMPARISON_RUNS, MAX_MARKET_DATA_PROVENANCE_EXPORT_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_REVIEWED_CONFLICT_KEYS, MAX_VISIBLE_COMPARISON_TOOLTIP_CONFLICT_SESSION_SUMMARIES, MAX_VISIBLE_GAP_WINDOWS, PRESET_PROFILE_AGGRESSIVENESS_RANKS, PRESET_PROFILE_CONFIDENCE_RANKS, PRESET_PROFILE_SPEED_RANKS, PRESET_TIMEFRAME_UNIT_TO_MINUTES, REPLAY_INTENT_ACTION_FILTER_SEARCH_PARAM, REPLAY_INTENT_ALIAS_SEARCH_PARAM, REPLAY_INTENT_EDGE_FILTER_SEARCH_PARAM, REPLAY_INTENT_GROUP_FILTER_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_DIFF_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_GROUP_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_TRACE_SEARCH_PARAM, REPLAY_INTENT_SCOPE_SEARCH_PARAM, REPLAY_INTENT_SEARCH_PARAM, REPLAY_INTENT_STEP_SEARCH_PARAM, REPLAY_INTENT_TEMPLATE_SEARCH_PARAM, RUN_HISTORY_SAVED_FILTER_STORAGE_KEY_PREFIX, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_TAB_ID_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_BROWSER_STATE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_PAYLOAD_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_SIGNING_SECRET_STORAGE_KEY, SHOW_COMPARISON_TOOLTIP_TUNING_PANEL, TOUCH_GAP_WINDOW_SWEEP_HOLD_MS, TOUCH_GAP_WINDOW_SWEEP_MOVE_TOLERANCE_PX, BenchmarkArtifact, ParameterSchema, ComparisonCueKind, ComparisonHistoryBrowserState, ComparisonHistoryPanelEntry, ComparisonHistoryPanelState, ComparisonHistoryPanelSyncState, ComparisonHistoryStepDescriptor, ComparisonHistorySyncAuditEntry, ComparisonHistorySyncAuditFilter, ComparisonHistorySyncAuditKind, ComparisonHistorySyncAuditTrailState, ComparisonHistorySyncConflictFieldKey, ComparisonHistorySyncConflictFieldSource, ComparisonHistorySyncConflictReview, ComparisonHistorySyncConflictReviewGroup, ComparisonHistorySyncPreferenceFieldKey, ComparisonHistorySyncPreferenceReview, ComparisonHistorySyncPreferenceReviewRow, ComparisonHistorySyncPreferenceState, ComparisonHistorySyncWorkspaceRecommendationOverview, ComparisonHistorySyncWorkspaceReview, ComparisonHistorySyncWorkspaceReviewRow, ComparisonHistorySyncWorkspaceReviewSelectionKey, ComparisonHistorySyncWorkspaceSemanticSignal, ComparisonHistorySyncWorkspaceSignalDetailNestedKey, ComparisonHistorySyncWorkspaceSignalDetailSubviewKey, ComparisonHistorySyncWorkspaceSignalMicroInteractionKey, ComparisonHistorySyncWorkspaceSignalMicroViewKey, ComparisonHistorySyncWorkspaceState, ComparisonHistoryTabIdentity, ComparisonHistoryWriteMode, ComparisonIntent, ComparisonScoreDrillBackOptions, ComparisonScoreLinkedRunRole, ComparisonScoreLinkSource, ComparisonScoreLinkTarget, ComparisonScoreSection, ComparisonTooltipConflictSessionSummary, ComparisonTooltipConflictSessionSummarySession, ComparisonTooltipConflictSessionUiState, ComparisonTooltipConflictUiStateV1, ComparisonTooltipInteractionOptions, ComparisonTooltipLayout, ComparisonTooltipPendingPresetImportConflict, ComparisonTooltipPresetConflictPreviewGroup, ComparisonTooltipPresetConflictPreviewRow, ComparisonTooltipPresetImportConflictPolicy, ComparisonTooltipPresetImportResolution, ComparisonTooltipTargetProps, ComparisonTooltipTuning, ComparisonTooltipTuningPresetStateV1, ComparisonTooltipTuningShareImport, ComparisonTooltipTuningSinglePresetShareV1, ControlRoomComparisonHistoryPanelUiState, ControlRoomComparisonSelectionState, ControlRoomUiStateV1, ControlRoomUiStateV2, ControlRoomUiStateV3, ControlRoomUiStateV4, ExpandedGapWindowSelections, ExperimentPreset, ExperimentPresetRevision, GapWindowDragSelectionState, GuardedLiveStatus, MarketDataIngestionJobRecord, MarketDataProvenanceExportFilterState, MarketDataProvenanceExportHistoryEntry, MarketDataProvenanceExportSort, MarketDataProvenanceExportStateV1, MarketDataLineageHistoryRecord, MarketDataStatus, OperatorAlertMarketContextProvenance, OperatorAlertPrimaryFocus, OperatorVisibility, PendingTouchGapWindowSweepState, PresetDraftConflict, PresetRevisionDiff, PresetRevisionFilterState, PresetStructuredDiffDeltaValue, PresetStructuredDiffGroup, PresetStructuredDiffRow, ProviderProvenanceAnalyticsPresetEntry, ProviderProvenanceDashboardLayout, ProviderProvenanceDashboardViewEntry, ProviderProvenanceExportAnalyticsPayload, ProviderProvenanceExportJobEntry, ProviderProvenanceExportJobEscalationResult, ProviderProvenanceExportJobHistoryPayload, ProviderProvenanceExportJobPolicyResult, ProviderProvenanceSchedulerAlertHistoryPayload, ProviderProvenanceSchedulerHealthExportPayload, ProviderProvenanceSchedulerHealthAnalyticsPayload, ProviderProvenanceSchedulerHealthHistoryPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditRecord, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditRecord, ProviderProvenanceSchedulerSearchModerationPlanListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogListPayload, ProviderProvenanceSchedulerSearchFeedbackBatchModerationResult, ProviderProvenanceSchedulerSearchDashboardPayload, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditRecord, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionListPayload, ProviderProvenanceSchedulerStitchedReportViewAuditRecord, ProviderProvenanceSchedulerStitchedReportViewEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionListPayload, ProviderProvenanceSchedulerNarrativeBulkGovernanceResult, ProviderProvenanceSchedulerNarrativeGovernancePlan, ProviderProvenanceSchedulerNarrativeGovernancePlanBatchResult, ProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyStep, ProviderProvenanceSchedulerNarrativeGovernanceQueueView, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeRegistryEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionListPayload, ProviderProvenanceSchedulerNarrativeTemplateEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionListPayload, ProviderProvenanceScheduledReportEntry, ProviderProvenanceScheduledReportHistoryPayload, ProvenanceArtifactLineDetailView, ProvenanceArtifactLineMicroView, Run, RunComparison, RunHistoryFilter, RunHistorySurfaceKey, RunListBoundaryContract, RunListBoundaryEligibility, RunListBoundaryGroupKey, RunListBoundarySurfaceId, RunSurfaceCapabilities, RunSurfaceCapabilityFamily, RunSurfaceCapabilityFamilyContract, RunSurfaceCapabilityFamilyKey, RunSurfaceCapabilitySchemaContract, RunSurfaceCapabilitySurfaceKey, RunSurfaceCollectionQueryBuilderReplayIntentSnapshot, RunSurfaceCollectionQueryBuilderReplayLinkAliasRecordPayload, RunSurfaceCollectionQueryBuilderReplayLinkRedactionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkRetentionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobDownloadPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobPrunePayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditPrunePayload, RunSurfaceCollectionQueryContract, RunSurfaceCollectionQueryElementField, RunSurfaceCollectionQueryExpressionAuthoring, RunSurfaceCollectionQueryParameterDomainDescriptor, RunSurfaceCollectionQuerySchema, RunSurfaceSharedContract, RunSurfaceSubresourceContract, SavedRunHistoryFilterPreset, SavedRunHistoryFilterPresetStateV1, Strategy, TouchGapWindowActivationFeedbackState, TouchGapWindowHoldProgressState, defaultRunForm, defaultPresetForm, defaultPresetRevisionFilter, defaultMarketDataProvenanceExportFilterState, defaultProviderProvenanceAnalyticsQueryState, defaultProviderProvenanceSchedulerSearchDashboardFilterState, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilter, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, defaultProviderProvenanceSchedulerSearchModerationQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationStageDraft, normalizeProviderProvenanceSchedulerRoutingPolicyDraftValue, normalizeProviderProvenanceSchedulerApprovalPolicyDraftValue, buildProviderProvenanceSchedulerExportPolicyDraft, getProviderProvenanceSchedulerNarrativeGovernanceQueuePriorityRank, getProviderProvenanceSchedulerNarrativeGovernanceQueueState, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchySummary, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepSummary, formatProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyPosition, isProviderProvenanceSchedulerAlertCategory, getOperatorAlertOccurrenceKey, formatProviderProvenanceSchedulerTimelineSummary, formatProviderProvenanceSchedulerSearchMatchSummary, formatProviderProvenanceSchedulerRetrievalClusterSummary, buildProviderProvenanceSchedulerAlertWorkflowReason, defaultProviderProvenanceDashboardLayout, DEFAULT_PROVIDER_PROVENANCE_SCHEDULER_NARRATIVE_GOVERNANCE_QUEUE_SORT, defaultProviderProvenanceWorkspaceDraft, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraft, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraft, KEEP_CURRENT_BULK_GOVERNANCE_VALUE, CLEAR_TEMPLATE_LINK_BULK_GOVERNANCE_VALUE, defaultProviderProvenanceSchedulerNarrativeTemplateBulkDraft, defaultProviderProvenanceSchedulerStitchedReportViewBulkDraft, defaultProviderProvenanceSchedulerNarrativeRegistryDraft, defaultProviderProvenanceSchedulerNarrativeRegistryBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceQueueFilter, defaultProviderProvenanceSchedulerStitchedReportGovernanceQueueFilter, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilter, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilter, defaultProviderProvenanceSchedulerStitchedReportViewAuditFilter, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilter, defaultProviderProvenanceReportDraft, buildPresetFormFromPreset, buildCurrentPresetRevisionSnapshot, buildEmptyPresetRevisionSnapshot, formatPresetStructuredDiffDisplayValue, isPresetStructuredDiffObject, isPresetStructuredDiffScalar, arePresetStructuredDiffValuesEquivalent, matchesPresetParameterSchemaType, joinPresetStructuredDiffHints, tokenizePresetParameterPath, parsePresetTimeframeToMinutes, buildPresetRankedStringDelta, buildPresetParameterStrategyContext, buildPresetParameterDomainContext, formatPresetParameterSchemaHint, getPresetParameterSchemaEntry, buildPresetStructuredDiffDelta, summarizePresetStructuredDiffGroup, groupPresetStructuredDiffRows, buildPresetStructuredDiffRows, describePresetRevisionDiff, describePresetDraftConflict, matchesPresetRevisionFilter, defaultRunHistoryFilter, sanitizeRunHistoryFilter, cloneRunHistoryFilter, hasRunHistoryFilterCriteria, areRunHistoryFiltersEquivalent, buildRunHistorySavedFilterStorageKey, normalizeSavedRunHistoryFilterPreset, loadSavedRunHistoryFilterPresets, persistSavedRunHistoryFilterPresets, describeRunHistoryFilter, DEFAULT_COMPARISON_INTENT, comparisonIntentOptions, parseExperimentTags, parseJsonObjectInput, formatPresetLifecycleStage, buildRunSubmissionPayload, normalizeRunFormPreset, resolveMarketDataSymbol, buildMarketDataInstrumentFocusKey, isMarketDataInstrumentAtRisk, resolvePreferredMarketDataInstrument, formatWorkflowToken, formatMarketContextFieldProvenance, summarizeProviderRecoveryMarketContextProvenance, serializeLinkedMarketInstrumentContext, getOperatorSeverityRank, normalizeMarketDataProvenanceExportSort, normalizeMarketDataProvenanceExportFilterState, normalizeMarketDataProvenanceExportHistoryEntry, loadPersistedMarketDataProvenanceExportState, persistMarketDataProvenanceExportState, formatMarketDataProvenanceExportFilterSummary, formatProviderProvenanceAnalyticsQuerySummary, normalizeProviderProvenanceDashboardLayoutState, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueSort, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkQueueViewPatch, formatProviderProvenanceSchedulerNarrativeGovernanceQueueSortLabel, providerProvenanceSchedulerNarrativeGovernancePolicySupportsItemType, formatProviderProvenanceSchedulerNarrativeGovernanceQueueViewSummary, buildProviderProvenanceAnalyticsWorkspaceQuery, buildProviderProvenanceAnalyticsQueryStateFromWorkspaceQuery, formatProviderProvenanceSchedulerNarrativeFacet, resolveProviderProvenanceSeriesBarWidth, formatProviderDriftIntensity, formatSchedulerLagSeconds, downloadTextExport, escapeRegExp, normalizeMarketSymbol, buildMarketSymbolSearchVariants, matchesMarketSymbolInText, dedupeMarketDataInstruments, formatMarketDataInstrumentLabel, getMarketDataInstrumentSyncSeverityRank, getMarketDataInstrumentRiskScore, buildLiveMarketDataPreference, getMarketDataInstrumentLiveRelevance, selectPrimaryMarketDataInstrument, extractMatchingMarketTimeframe, extractMatchingMarketSymbols, buildLinkedMarketInstrumentContext, buildLinkedMarketInstrumentContextFromPayload, formatLinkedMarketPrimaryFocusNote, resolveInstrumentsBySymbolsAndTimeframe, resolveMarketDataInstrumentLink, getAlertLinkPriority, compareAlertLinkPriority, resolveAutoLinkedMarketInstrument, formatTimestamp, formatProviderRecoverySchema, formatProviderRecoveryTelemetry, shortenIdentifier, truncateLabel, formatRange, benchmarkArtifactSummaryOrder, benchmarkArtifactSummaryLabels, benchmarkArtifactSectionOrder, benchmarkArtifactSectionLabels, formatBenchmarkArtifactSummaryEntries, benchmarkArtifactSummarySortIndex, formatBenchmarkArtifactSummaryLabel, formatBenchmarkArtifactSummaryValue, formatBenchmarkArtifactSectionEntries, benchmarkArtifactSectionSortIndex, formatBenchmarkArtifactSectionLabel, formatBenchmarkArtifactSectionLines, formatBenchmarkArtifactSectionValue, formatBenchmarkArtifactInlineValue, ProviderProvenanceAnalyticsScope, ProviderProvenanceSchedulerOccurrenceNarrativeFacet, ProviderProvenanceAnalyticsQueryState, ProviderProvenanceSchedulerSearchDashboardFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, ProviderProvenanceSchedulerSearchModerationQueueFilterState, ProviderProvenanceSchedulerSearchModerationStageDraft, ProviderProvenanceSchedulerExportPolicyDraft, OperatorVisibilityAlertEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraftState, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraftState, ProviderProvenanceSchedulerNarrativeBulkToggleValue, ProviderProvenanceSchedulerNarrativeTemplateBulkDraftState, ProviderProvenanceSchedulerStitchedReportViewBulkDraftState, ProviderProvenanceSchedulerNarrativeRegistryDraftState, ProviderProvenanceSchedulerNarrativeRegistryBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraftState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepVersionEntry, ProviderProvenanceSchedulerNarrativeGovernanceQueueFilterState, ProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterState, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilterState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilterState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilterState, ProviderProvenanceSchedulerStitchedReportViewAuditFilterState, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilterState, ProviderProvenanceReportDraftState, LinkedMarketInstrumentContext, MarketDataLinkableAlertRecord, MarketDataIncidentHistoryEntry, ProviderRecoveryMarketContextSummary, MarketDataProviderProvenanceEventRecord, MarketDataPrimaryFocusSelection } from "./ControlRoomViewHelpersContext";
import { PanelDisclosure, BackfillCountStatus, BackfillQualityStatus, SyncCheckpointStatus, SyncFailureStatus, formatCompletion, summarizeGapWindows, formatGapWindows, buildLegacyGapWindowKey, buildGapWindowKey, parseGapWindowKey, formatGapWindowKeyLabel, normalizeExpandedGapWindowSelectionList, resolveGapWindowSelectionList, buildGapWindowSelectionUpdate, isSameGapWindowSelectionList, filterExpandedGapWindowSelections, buildGapWindowSelectionLookup, instrumentGapRowKey, toggleExpandedGapRow, pruneExpandedGapRows, pruneExpandedGapWindowSelections } from "./ControlRoomViewStatusPanels";
import { loadExpandedGapRows, loadExpandedGapWindowSelections, defaultControlRoomComparisonSelectionState, loadPersistedComparisonSelection, defaultComparisonHistoryPanelState, defaultComparisonHistoryPanelUiState, loadPersistedComparisonHistoryPanelUiState, loadControlRoomUiState, readControlRoomUiStateValue, persistControlRoomUiState, loadComparisonHistorySyncAuditTrail, persistComparisonHistorySyncAuditTrail, loadComparisonSelectionFromUrl, buildComparisonSelectionHistoryUrl, readComparisonHistoryBrowserState, buildComparisonHistoryBrowserState, isSameComparisonHistoryBrowserState, persistComparisonSelectionToUrl, buildComparisonHistoryEntryId, buildComparisonHistoryTabId, formatComparisonHistoryTabLabel, loadComparisonHistoryTabIdentity, buildComparisonHistoryPanelSyncState, buildComparisonHistorySyncSignature, buildComparisonHistorySyncAuditId, buildComparisonHistoryPanelEntry, findComparisonHistoryPanelEntryForSelection, mergeComparisonHistoryPanelState, mergeComparisonHistoryPanelEntries, reconcileComparisonHistoryPanelState, sortComparisonHistoryPanelEntries, limitComparisonHistoryPanelEntries } from "./ControlRoomViewComparisonStorage";
import { normalizeComparisonHistoryPanelUiState, normalizeComparisonHistorySyncAuditFilter, normalizeComparisonHistoryPanelSyncState, normalizeComparisonHistoryPanelState, normalizeComparisonHistoryPanelEntry, normalizeComparisonHistorySyncAuditEntry, normalizeComparisonHistorySyncConflictReview, normalizeComparisonHistorySyncConflictSelectedSources, normalizeComparisonHistorySyncPreferenceReview, normalizeComparisonHistorySyncWorkspaceReview, normalizeComparisonHistorySyncPreferenceState, normalizeComparisonHistorySyncWorkspaceState, normalizeComparisonHistorySyncPreferenceSelectedSources, normalizeComparisonHistorySyncWorkspaceSelectedSources, limitComparisonHistorySyncAuditEntries, appendComparisonHistorySyncAuditEntries, isSameComparisonHistoryPanelState, isSameComparisonHistoryPanelSyncState, isSameComparisonHistoryPanelEntry, getComparisonHistoryPanelEntryChangedFields, formatComparisonHistorySyncConflictScoreLinkValue, formatComparisonHistorySyncConflictRunSelectionValue, formatComparisonHistorySyncConflictFieldValue, hasComparisonHistorySyncConflictFieldDifference, buildDefaultComparisonHistorySyncConflictSelectedSources, buildComparisonHistorySyncConflictReview, buildComparisonHistorySyncConflictReviewGroups, summarizeComparisonHistoryPanelEntryConflict, formatComparisonHistorySyncConflictResolutionSummary, resolveComparisonHistorySyncConflictReviewEntry, applyResolvedComparisonHistoryPanelEntry, summarizeComparisonHistorySyncPreferenceChanges, buildComparisonHistorySyncPreferenceState, formatComparisonHistorySyncPreferenceFieldValue, hasComparisonHistorySyncPreferenceFieldDifference, buildDefaultComparisonHistorySyncPreferenceSelectedSources, buildComparisonHistorySyncPreferenceReview, buildComparisonHistorySyncPreferenceReviewRows, formatComparisonHistorySyncPreferenceResolutionSummary, resolveComparisonHistorySyncPreferenceReview } from "./ControlRoomViewComparisonNormalize";
import { listComparisonHistoryExpandedGapRowKeys, listComparisonHistoryExpandedGapRowDiffKeys, buildComparisonHistoryExpandedGapRowSelectionKey, parseComparisonHistoryExpandedGapRowSelectionKey, buildComparisonHistoryExpandedGapWindowSelectionKey, parseComparisonHistoryExpandedGapWindowSelectionKey, listComparisonHistoryExpandedGapWindowDiffKeys, isSameComparisonHistoryExpandedGapRows, isSameExpandedGapWindowSelections, formatComparisonHistoryExpandedGapRowKey, formatComparisonHistoryExpandedGapRowsValue, formatComparisonHistoryExpandedGapRowsDiffValue, formatComparisonHistorySyncWorkspaceSelectionKeyLabel, rankComparisonHistorySyncWorkspaceSelectionKey, ComparisonHistorySyncWorkspaceSemanticRanking, listComparisonHistorySyncWorkspaceDiffSelectionKeys, resolveComparisonHistorySyncWorkspaceFieldSource, listComparisonHistorySyncWorkspaceConflictSelectionKeys, scoreComparisonHistorySyncWorkspaceCandidateSource, sortComparisonHistorySyncWorkspaceSemanticSignals, rankComparisonHistorySyncWorkspaceFieldSemantics, buildComparisonHistorySyncWorkspaceRecommendedSources, summarizeComparisonHistorySyncWorkspaceChanges, buildComparisonHistorySyncWorkspaceState, formatComparisonHistorySyncWorkspaceFieldValue, hasComparisonHistorySyncWorkspaceFieldDifference, buildDefaultComparisonHistorySyncWorkspaceSelectedSources, buildComparisonHistorySyncWorkspaceReview, buildComparisonHistorySyncWorkspaceReviewRows, buildComparisonHistorySyncWorkspaceRecommendationOverview, formatComparisonHistorySyncWorkspaceResolutionSummary, resolveComparisonHistorySyncWorkspaceReview, buildComparisonHistorySyncAuditEntries } from "./ControlRoomViewComparisonWorkspace";
import { StrategyColumn, PresetStructuredDiffPreview, PresetCatalogPanel, RunForm, ExperimentMetadataPills } from "./ControlRoomViewCatalogPanels";
import { RunListBoundarySurfaceContract, RunListBoundaryGroupContract, RunSurfaceCapabilityDiscoveryPanel, Metric, formatMetric, formatLineagePosture, formatLineageIndicator, formatComparisonScoreValue } from "./ControlRoomViewCapabilities";
import { buildComparisonScoreHighlights, buildComparisonScoreDetailRows, formatComparisonScoreHighlight, formatComparisonScoreComponentLabel, formatComparisonScoreLinkSourceLabel, encodeComparisonScoreLinkToken, decodeComparisonScoreLinkToken, buildComparisonProvenanceLineSubFocusKey, buildComparisonRunCardLineSubFocusKey, buildComparisonRunListLineSubFocusKey, buildComparisonRunListOrderPreviewSubFocusKey, buildComparisonRunListDataSymbolSubFocusKey, buildComparisonProvenanceArtifactSubFocusKey, buildComparisonProvenanceArtifactSectionSubFocusKey, buildComparisonProvenanceArtifactSummaryHoverKey, buildComparisonProvenanceArtifactSectionLineHoverKey, buildComparisonProvenanceArtifactLineDetailHoverKey, buildComparisonMetricTooltipKey, formatComparisonScoreLinkSubFocusLabel, formatComparisonScoreLinkTooltipLabel, formatComparisonScoreLinkArtifactHoverLabel, formatComparisonScoreLinkArtifactLineDetailViewLabel, formatComparisonScoreLinkArtifactLineMicroViewLabel, formatComparisonScoreLinkArtifactLineDetailHoverLabel, formatComparisonScoreComponentDetail, buildComparisonScoreComponentDetails, formatComparisonScoreComponentRawValue, formatComparisonScoreSignedValue, getComparisonScoreLinkedRunRole, isSameComparisonScoreLinkTarget, isSameComparisonScoreLinkSurface, resolveComparisonScoreDrillBackTarget, isComparisonScoreLinkMatch, formatEditableNumber } from "./ControlRoomViewComparisonLinks";
import { formatFixedNumber, buildLiveOrderDraftKey, formatComparisonMetric, formatComparisonDelta, formatComparisonNarrativeLabel, formatComparisonIntentLabel, formatComparisonIntentLegend, formatComparisonIntentTooltip, formatComparisonCueTooltip, buildComparisonCellTooltip, getComparisonIntentClassName, formatLaneLabel, formatVersionLineage, extractDefaultParameters, formatParameterMap, formatParameterValue, summarizeRunNotes } from "./ControlRoomViewFormatting";

export function loadLegacyExpandedGapRows() {
  if (typeof window === "undefined") {
    return {};
  }
  try {
    const raw = window.localStorage.getItem(LEGACY_GAP_WINDOW_EXPANSION_STORAGE_KEY);
    if (!raw) {
      return {};
    }
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== "object") {
      return {};
    }
    return filterExpandedGapRows(parsed);
  } catch {
    return {};
  }
}

export function filterExpandedGapRows(value: unknown) {
  if (!value || typeof value !== "object") {
    return {};
  }
  return Object.fromEntries(
    Object.entries(value).filter((entry): entry is [string, boolean] => entry[1] === true),
  );
}

export function normalizeControlRoomComparisonSelection(
  value: Partial<ControlRoomComparisonSelectionState> | null | undefined,
): ControlRoomComparisonSelectionState {
  const selectedRunIds = normalizeComparisonRunIdList(value?.selectedRunIds);
  const scoreLink = normalizeComparisonScoreLinkTarget(value?.scoreLink);
  return {
    intent: normalizeComparisonIntent(value?.intent),
    selectedRunIds,
    scoreLink:
      scoreLink && selectedRunIds.includes(scoreLink.narrativeRunId)
        ? {
            ...scoreLink,
            detailExpanded: scoreLink.detailExpanded,
            artifactDetailExpanded: scoreLink.artifactDetailExpanded,
            artifactLineDetailExpanded: scoreLink.artifactLineDetailExpanded,
            artifactLineDetailView: scoreLink.artifactLineDetailView,
            artifactLineMicroView: scoreLink.artifactLineMicroView,
            artifactLineNotePage: scoreLink.artifactLineNotePage,
            artifactLineDetailHoverKey: scoreLink.artifactLineDetailHoverKey,
            artifactLineDetailScrubStep: scoreLink.artifactLineDetailScrubStep,
            originRunId:
              scoreLink.originRunId && selectedRunIds.includes(scoreLink.originRunId)
                ? scoreLink.originRunId
                : null,
            subFocusKey: scoreLink.subFocusKey,
            tooltipKey: scoreLink.tooltipKey,
            artifactHoverKey: scoreLink.artifactHoverKey,
          }
        : null,
  };
}

export function isSameComparisonSelection(
  left: Partial<ControlRoomComparisonSelectionState> | null | undefined,
  right: Partial<ControlRoomComparisonSelectionState> | null | undefined,
) {
  const normalizedLeft = normalizeControlRoomComparisonSelection(left);
  const normalizedRight = normalizeControlRoomComparisonSelection(right);
  return (
    normalizedLeft.intent === normalizedRight.intent
    && normalizedLeft.selectedRunIds.length === normalizedRight.selectedRunIds.length
    && normalizedLeft.selectedRunIds.every((runId, index) => runId === normalizedRight.selectedRunIds[index])
    && (
      (normalizedLeft.scoreLink === null && normalizedRight.scoreLink === null)
      || (
        normalizedLeft.scoreLink !== null
        && normalizedRight.scoreLink !== null
        && normalizedLeft.scoreLink.narrativeRunId === normalizedRight.scoreLink.narrativeRunId
        && normalizedLeft.scoreLink.section === normalizedRight.scoreLink.section
        && normalizedLeft.scoreLink.componentKey === normalizedRight.scoreLink.componentKey
        && normalizedLeft.scoreLink.source === normalizedRight.scoreLink.source
        && normalizedLeft.scoreLink.originRunId === normalizedRight.scoreLink.originRunId
        && normalizedLeft.scoreLink.subFocusKey === normalizedRight.scoreLink.subFocusKey
        && normalizedLeft.scoreLink.detailExpanded === normalizedRight.scoreLink.detailExpanded
        && normalizedLeft.scoreLink.artifactDetailExpanded === normalizedRight.scoreLink.artifactDetailExpanded
        && normalizedLeft.scoreLink.artifactLineDetailExpanded === normalizedRight.scoreLink.artifactLineDetailExpanded
        && normalizedLeft.scoreLink.artifactLineDetailView === normalizedRight.scoreLink.artifactLineDetailView
        && normalizedLeft.scoreLink.artifactLineMicroView === normalizedRight.scoreLink.artifactLineMicroView
        && normalizedLeft.scoreLink.artifactLineNotePage === normalizedRight.scoreLink.artifactLineNotePage
        && normalizedLeft.scoreLink.artifactLineDetailHoverKey === normalizedRight.scoreLink.artifactLineDetailHoverKey
        && normalizedLeft.scoreLink.artifactLineDetailScrubStep === normalizedRight.scoreLink.artifactLineDetailScrubStep
        && normalizedLeft.scoreLink.tooltipKey === normalizedRight.scoreLink.tooltipKey
        && normalizedLeft.scoreLink.artifactHoverKey === normalizedRight.scoreLink.artifactHoverKey
      )
    )
  );
}

export function formatComparisonHistoryPanelEntryMeta(entry: ComparisonHistoryPanelEntry) {
  const parts = [
    formatComparisonIntentLabel(entry.selection.intent),
    `${entry.selection.selectedRunIds.length} run${entry.selection.selectedRunIds.length === 1 ? "" : "s"}`,
    `Saved ${formatTimestamp(entry.recordedAt)}`,
  ];
  if (entry.selection.scoreLink) {
    parts.push(
      formatComparisonScoreComponentLabel(
        entry.selection.scoreLink.section,
        entry.selection.scoreLink.componentKey,
      ),
    );
    parts.push(formatComparisonScoreLinkSourceLabel(entry.selection.scoreLink.source));
    const subFocusLabel = formatComparisonScoreLinkSubFocusLabel(entry.selection.scoreLink.subFocusKey);
    if (subFocusLabel) {
      parts.push(subFocusLabel);
    }
    const tooltipLabel = formatComparisonScoreLinkTooltipLabel(entry.selection.scoreLink.tooltipKey);
    if (tooltipLabel) {
      parts.push(tooltipLabel);
    }
    const artifactHoverLabel = formatComparisonScoreLinkArtifactHoverLabel(
      entry.selection.scoreLink.artifactHoverKey,
    );
    const artifactLineViewLabel = formatComparisonScoreLinkArtifactLineDetailViewLabel(
      entry.selection.scoreLink.artifactLineDetailView,
    );
    const artifactLineMicroViewLabel = formatComparisonScoreLinkArtifactLineMicroViewLabel(
      entry.selection.scoreLink.artifactLineMicroView,
    );
    const artifactLineDetailHoverLabel = formatComparisonScoreLinkArtifactLineDetailHoverLabel(
      entry.selection.scoreLink.artifactLineDetailHoverKey,
    );
    if (artifactHoverLabel) {
      parts.push(artifactHoverLabel);
    }
    if (entry.selection.scoreLink.detailExpanded === true) {
      parts.push("details open");
    } else if (entry.selection.scoreLink.detailExpanded === false) {
      parts.push("details hidden");
    }
    if (entry.selection.scoreLink.artifactDetailExpanded === true) {
      parts.push("artifact details open");
    } else if (entry.selection.scoreLink.artifactDetailExpanded === false) {
      parts.push("artifact details hidden");
    }
    if (entry.selection.scoreLink.artifactLineDetailExpanded === true) {
      parts.push("line detail open");
    } else if (entry.selection.scoreLink.artifactLineDetailExpanded === false) {
      parts.push("line detail hidden");
    }
    if (entry.selection.scoreLink.artifactLineDetailExpanded === true && artifactLineViewLabel) {
      parts.push(artifactLineViewLabel);
    }
    if (entry.selection.scoreLink.artifactLineDetailExpanded === true && artifactLineMicroViewLabel) {
      parts.push(artifactLineMicroViewLabel);
    }
    if (
      entry.selection.scoreLink.artifactLineDetailExpanded === true
      && entry.selection.scoreLink.artifactLineMicroView === "note"
      && entry.selection.scoreLink.artifactLineNotePage !== null
    ) {
      parts.push(`note ${entry.selection.scoreLink.artifactLineNotePage + 1}`);
    }
    if (entry.selection.scoreLink.artifactLineDetailExpanded === true && artifactLineDetailHoverLabel) {
      parts.push(artifactLineDetailHoverLabel);
    }
    if (
      entry.selection.scoreLink.artifactLineDetailExpanded === true
      && entry.selection.scoreLink.artifactLineDetailScrubStep !== null
    ) {
      parts.push(`scrub ${entry.selection.scoreLink.artifactLineDetailScrubStep + 1}`);
    }
  }
  if (entry.pinned) {
    parts.push("Pinned");
  }
  return parts.join(" / ");
}

export function matchesComparisonHistoryPanelEntry(entry: ComparisonHistoryPanelEntry, query: string) {
  const haystack = [
    entry.label,
    entry.summary,
    entry.title,
    entry.url,
    formatComparisonHistoryPanelEntryMeta(entry),
  ].join(" ").toLowerCase();
  return haystack.includes(query);
}

export function formatComparisonHistorySyncAuditKindLabel(kind: ComparisonHistorySyncAuditKind) {
  switch (kind) {
    case "merge":
      return "Merge";
    case "conflict":
      return "Conflict";
    case "preferences":
      return "Browser";
    case "workspace":
      return "Workspace";
    default:
      return kind;
  }
}

export function buildComparisonHistoryStepDescriptor(
  selection: ControlRoomComparisonSelectionState,
  runs: Run[],
  comparison: RunComparison | null,
): ComparisonHistoryStepDescriptor {
  const normalizedSelection = normalizeControlRoomComparisonSelection(selection);
  const intentLabel = formatComparisonIntentLabel(normalizedSelection.intent);
  const selectedRuns = normalizedSelection.selectedRunIds.map((runId) => ({
    runId,
    label: resolveComparisonHistoryRunLabel(runId, runs, comparison),
  }));
  const baselineRunId =
    comparison?.baseline_run_id && normalizedSelection.selectedRunIds.includes(comparison.baseline_run_id)
      ? comparison.baseline_run_id
      : selectedRuns[0]?.runId ?? null;
  const baselineLabel = baselineRunId
    ? resolveComparisonHistoryRunLabel(baselineRunId, runs, comparison)
    : null;
  const comparisonTargets = selectedRuns.filter((candidate) => candidate.runId !== baselineRunId);
  const primaryNarrative = comparison?.narratives.find((candidate) => candidate.is_primary) ?? comparison?.narratives[0] ?? null;

  if (normalizedSelection.scoreLink) {
    const componentLabel = formatComparisonScoreComponentLabel(
      normalizedSelection.scoreLink.section,
      normalizedSelection.scoreLink.componentKey,
    );
    const sourceLabel = formatComparisonScoreLinkSourceLabel(normalizedSelection.scoreLink.source);
    const subFocusLabel = formatComparisonScoreLinkSubFocusLabel(normalizedSelection.scoreLink.subFocusKey);
    const tooltipLabel = formatComparisonScoreLinkTooltipLabel(normalizedSelection.scoreLink.tooltipKey);
    const artifactHoverLabel = formatComparisonScoreLinkArtifactHoverLabel(
      normalizedSelection.scoreLink.artifactHoverKey,
    );
    const artifactLineViewLabel = formatComparisonScoreLinkArtifactLineDetailViewLabel(
      normalizedSelection.scoreLink.artifactLineDetailView,
    );
    const artifactLineMicroViewLabel = formatComparisonScoreLinkArtifactLineMicroViewLabel(
      normalizedSelection.scoreLink.artifactLineMicroView,
    );
    const artifactLineDetailHoverLabel = formatComparisonScoreLinkArtifactLineDetailHoverLabel(
      normalizedSelection.scoreLink.artifactLineDetailHoverKey,
    );
    const focusRunLabel = resolveComparisonHistoryRunLabel(
      normalizedSelection.scoreLink.narrativeRunId,
      runs,
      comparison,
    );
    const originRunLabel =
      normalizedSelection.scoreLink.originRunId
        ? resolveComparisonHistoryRunLabel(
            normalizedSelection.scoreLink.originRunId,
            runs,
            comparison,
          )
        : null;
    const focusNarrative = comparison?.narratives.find(
      (candidate) => candidate.run_id === normalizedSelection.scoreLink?.narrativeRunId,
    ) ?? null;
    const label = `${truncateLabel(componentLabel, 20)} ${truncateLabel(sourceLabel, 12)} focus`;
    const summary = [
      `${componentLabel} is pinned to ${focusRunLabel} via ${sourceLabel}.`,
      normalizedSelection.selectedRunIds.length > 1
        ? `${intentLabel} across ${normalizedSelection.selectedRunIds.length} runs.`
        : `${intentLabel} with one staged run.`,
      subFocusLabel ? `Detail ${subFocusLabel}.` : null,
      tooltipLabel ? `Tooltip ${tooltipLabel}.` : null,
      artifactHoverLabel ? `Inspecting ${artifactHoverLabel}.` : null,
      normalizedSelection.scoreLink.detailExpanded === true ? "Score details open." : null,
      normalizedSelection.scoreLink.detailExpanded === false ? "Score details hidden." : null,
      normalizedSelection.scoreLink.artifactDetailExpanded === true ? "Artifact details open." : null,
      normalizedSelection.scoreLink.artifactDetailExpanded === false ? "Artifact details hidden." : null,
      normalizedSelection.scoreLink.artifactLineDetailExpanded === true ? "Line detail open." : null,
      normalizedSelection.scoreLink.artifactLineDetailExpanded === false ? "Line detail hidden." : null,
      normalizedSelection.scoreLink.artifactLineDetailExpanded === true && artifactLineViewLabel
        ? `${artifactLineViewLabel}.`
        : null,
      normalizedSelection.scoreLink.artifactLineDetailExpanded === true && artifactLineMicroViewLabel
        ? `${artifactLineMicroViewLabel}.`
        : null,
      normalizedSelection.scoreLink.artifactLineDetailExpanded === true
      && normalizedSelection.scoreLink.artifactLineMicroView === "note"
      && normalizedSelection.scoreLink.artifactLineNotePage !== null
        ? `Note ${normalizedSelection.scoreLink.artifactLineNotePage + 1}.`
        : null,
      normalizedSelection.scoreLink.artifactLineDetailExpanded === true && artifactLineDetailHoverLabel
        ? `Inspecting ${artifactLineDetailHoverLabel}.`
        : null,
      normalizedSelection.scoreLink.artifactLineDetailExpanded === true
      && normalizedSelection.scoreLink.artifactLineDetailScrubStep !== null
        ? `Scrub ${normalizedSelection.scoreLink.artifactLineDetailScrubStep + 1}.`
        : null,
      originRunLabel && originRunLabel !== focusRunLabel
        ? `Origin run ${originRunLabel}.`
        : null,
      baselineLabel && baselineRunId !== normalizedSelection.scoreLink.narrativeRunId
        ? `Baseline ${baselineLabel}.`
        : null,
      focusNarrative?.title ? `Story: ${truncateLabel(focusNarrative.title, 104)}.` : null,
    ]
      .filter(Boolean)
      .join(" ");
    return {
      label,
      summary,
      title: `Compare: ${label} | ${DEFAULT_CONTROL_ROOM_DOCUMENT_TITLE}`,
    };
  }

  if (!selectedRuns.length) {
    return {
      label: "Comparison cleared",
      summary: `No runs selected. ${intentLabel} is ready for the next comparison step.`,
      title: `Compare: cleared | ${DEFAULT_CONTROL_ROOM_DOCUMENT_TITLE}`,
    };
  }

  if (selectedRuns.length === 1) {
    const onlyRun = selectedRuns[0];
    const label = `${truncateLabel(onlyRun.label, 28)} staged`;
    return {
      label,
      summary: `${onlyRun.label} is staged for ${intentLabel.toLowerCase()}. Select one more run to open comparison insights.`,
      title: `Compare: ${label} | ${DEFAULT_CONTROL_ROOM_DOCUMENT_TITLE}`,
    };
  }

  const comparisonLabel =
    baselineLabel && comparisonTargets[0]
      ? `${truncateLabel(baselineLabel, 18)} vs ${truncateLabel(comparisonTargets[0].label, 18)}${
          comparisonTargets.length > 1 ? ` +${comparisonTargets.length - 1}` : ""
        }`
      : `${truncateLabel(selectedRuns[0].label, 18)} +${selectedRuns.length - 1}`;
  const summary = [
    baselineLabel
      ? `Baseline ${baselineLabel}${comparisonTargets[0] ? ` against ${comparisonTargets[0].label}` : ""}${
          comparisonTargets.length > 1 ? ` and ${comparisonTargets.length - 1} more runs` : ""
        }.`
      : `Tracking ${selectedRuns.length} runs.`,
    `${intentLabel} is active.`,
    primaryNarrative?.title ? `Top insight: ${truncateLabel(primaryNarrative.title, 104)}.` : null,
  ]
    .filter(Boolean)
    .join(" ");
  return {
    label: comparisonLabel,
    summary,
    title: `Compare: ${comparisonLabel} | ${DEFAULT_CONTROL_ROOM_DOCUMENT_TITLE}`,
  };
}

export function resolveComparisonHistoryRunLabel(
  runId: string,
  runs: Run[],
  comparison: RunComparison | null,
) {
  const comparisonRun = comparison?.runs.find((candidate) => candidate.run_id === runId);
  if (comparisonRun) {
    return (
      comparisonRun.reference?.title
      ?? comparisonRun.strategy_name
      ?? comparisonRun.strategy_id
      ?? shortenIdentifier(runId)
    );
  }
  const run = runs.find((candidate) => candidate.config.run_id === runId);
  if (!run) {
    return shortenIdentifier(runId);
  }
  return (
    run.provenance.strategy?.name
    ?? run.config.strategy_id
    ?? shortenIdentifier(runId)
  );
}

export function normalizeComparisonRunIdList(value: unknown) {
  if (!Array.isArray(value)) {
    return [];
  }
  return Array.from(
    new Set(
      value
        .map((item) => String(item).trim())
        .filter(Boolean),
    ),
  ).slice(0, MAX_COMPARISON_RUNS);
}

export function normalizeComparisonIntent(value: unknown): ComparisonIntent {
  return comparisonIntentOptions.includes(value as ComparisonIntent)
    ? (value as ComparisonIntent)
    : DEFAULT_COMPARISON_INTENT;
}

export function normalizeComparisonScoreSection(value: unknown): ComparisonScoreSection | null {
  return value === "metrics" || value === "semantics" || value === "context"
    ? value
    : null;
}

export function normalizeComparisonScoreLinkSource(value: unknown): ComparisonScoreLinkSource | null {
  if (
    value === "metric"
    || value === "drillback"
    || value === "overview"
    || value === "provenance"
    || value === "run_card"
    || value === "run_list"
  ) {
    return value;
  }
  if (value === "narrative") {
    return "drillback";
  }
  return null;
}

export function normalizeComparisonScoreLinkSubFocusKey(value: unknown) {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

export function normalizeComparisonScoreLinkExpandedState(value: unknown) {
  if (value === true || value === false) {
    return value;
  }
  if (value === "1" || value === "true") {
    return true;
  }
  if (value === "0" || value === "false") {
    return false;
  }
  return null;
}

export function normalizeComparisonScoreLinkTooltipKey(value: unknown) {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

export function normalizeComparisonScoreLinkArtifactLineDetailView(
  value: unknown,
): ProvenanceArtifactLineDetailView | null {
  return value === "stats" || value === "context" ? value : null;
}

export function normalizeComparisonScoreLinkArtifactLineMicroView(
  value: unknown,
): ProvenanceArtifactLineMicroView | null {
  return value === "structure" || value === "signal" || value === "note" ? value : null;
}

export function normalizeComparisonScoreLinkArtifactLineNotePage(value: unknown) {
  if (typeof value === "number" && Number.isInteger(value) && value >= 0) {
    return value;
  }
  if (typeof value === "string" && value.trim()) {
    const parsed = Number.parseInt(value, 10);
    return Number.isInteger(parsed) && parsed >= 0 ? parsed : null;
  }
  return null;
}

export function normalizeComparisonScoreLinkArtifactLineDetailHoverKey(value: unknown) {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

export function normalizeComparisonScoreLinkArtifactLineScrubStep(value: unknown) {
  if (typeof value === "number" && Number.isInteger(value) && value >= 0) {
    return value;
  }
  if (typeof value === "string" && value.trim()) {
    const parsed = Number.parseInt(value, 10);
    return Number.isInteger(parsed) && parsed >= 0 ? parsed : null;
  }
  return null;
}

export function normalizeComparisonScoreLinkArtifactHoverKey(value: unknown) {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

export function normalizeComparisonScoreLinkTarget(value: unknown): ComparisonScoreLinkTarget | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const candidate = value as Partial<ComparisonScoreLinkTarget>;
  const narrativeRunId =
    typeof candidate.narrativeRunId === "string" ? candidate.narrativeRunId.trim() : "";
  const componentKey = typeof candidate.componentKey === "string" ? candidate.componentKey.trim() : "";
  const section = normalizeComparisonScoreSection(candidate.section);
  const source = normalizeComparisonScoreLinkSource(candidate.source) ?? "drillback";
  const originRunId =
    typeof candidate.originRunId === "string" && candidate.originRunId.trim()
      ? candidate.originRunId.trim()
      : null;
  const subFocusKey = normalizeComparisonScoreLinkSubFocusKey(candidate.subFocusKey);
  const detailExpanded = normalizeComparisonScoreLinkExpandedState(candidate.detailExpanded);
  const artifactDetailExpanded = normalizeComparisonScoreLinkExpandedState(
    candidate.artifactDetailExpanded,
  );
  const artifactLineDetailExpanded = normalizeComparisonScoreLinkExpandedState(
    candidate.artifactLineDetailExpanded,
  );
  const artifactLineDetailView = normalizeComparisonScoreLinkArtifactLineDetailView(
    candidate.artifactLineDetailView,
  );
  const artifactLineMicroView = normalizeComparisonScoreLinkArtifactLineMicroView(
    candidate.artifactLineMicroView,
  );
  const artifactLineNotePage = normalizeComparisonScoreLinkArtifactLineNotePage(
    candidate.artifactLineNotePage,
  );
  const artifactLineDetailHoverKey = normalizeComparisonScoreLinkArtifactLineDetailHoverKey(
    candidate.artifactLineDetailHoverKey,
  );
  const artifactLineDetailScrubStep = normalizeComparisonScoreLinkArtifactLineScrubStep(
    candidate.artifactLineDetailScrubStep,
  );
  const tooltipKey = normalizeComparisonScoreLinkTooltipKey(candidate.tooltipKey);
  const artifactHoverKey = normalizeComparisonScoreLinkArtifactHoverKey(candidate.artifactHoverKey);
  if (!narrativeRunId || !componentKey || !section) {
    return null;
  }
  return {
    componentKey,
    detailExpanded,
    artifactDetailExpanded,
    artifactLineDetailExpanded,
    artifactLineDetailView,
    artifactLineMicroView,
    artifactLineNotePage,
    artifactLineDetailHoverKey,
    artifactLineDetailScrubStep,
    narrativeRunId,
    originRunId,
    section,
    source,
    subFocusKey,
    tooltipKey,
    artifactHoverKey,
  };
}

export function isControlRoomUiStateV1(value: unknown): value is ControlRoomUiStateV1 {
  if (!value || typeof value !== "object") {
    return false;
  }
  const candidate = value as Partial<ControlRoomUiStateV1>;
  return (
    candidate.version === 1 &&
    candidate.expandedGapRows !== undefined
  );
}

export function isControlRoomUiStateV2(value: unknown): value is ControlRoomUiStateV2 {
  if (!value || typeof value !== "object") {
    return false;
  }
  const candidate = value as Partial<ControlRoomUiStateV2>;
  return (
    candidate.version === 2 &&
    candidate.expandedGapRows !== undefined &&
    candidate.comparisonSelection !== undefined
  );
}

export function isControlRoomUiStateV3(value: unknown): value is ControlRoomUiStateV3 {
  if (!value || typeof value !== "object") {
    return false;
  }
  const candidate = value as Partial<ControlRoomUiStateV3>;
  return (
    candidate.version === 3 &&
    candidate.expandedGapRows !== undefined &&
    candidate.comparisonSelection !== undefined &&
    candidate.comparisonHistoryPanel !== undefined
  );
}

export function isControlRoomUiStateV4(value: unknown): value is ControlRoomUiStateV4 {
  if (!value || typeof value !== "object") {
    return false;
  }
  const candidate = value as Partial<ControlRoomUiStateV4>;
  return (
    candidate.version === CONTROL_ROOM_UI_STATE_VERSION &&
    candidate.expandedGapRows !== undefined &&
    candidate.expandedGapWindowSelections !== undefined &&
    candidate.comparisonSelection !== undefined &&
    candidate.comparisonHistoryPanel !== undefined
  );
}

export function buildRunsPath(mode: string, filter: RunHistoryFilter) {
  const params = new URLSearchParams({ mode });
  const sanitizedFilter = sanitizeRunHistoryFilter(filter);
  if (sanitizedFilter.strategy_id !== ALL_FILTER_VALUE) {
    params.set("strategy_id", sanitizedFilter.strategy_id);
  }
  if (sanitizedFilter.strategy_version !== ALL_FILTER_VALUE) {
    params.set("strategy_version", sanitizedFilter.strategy_version);
  }
  if (sanitizedFilter.preset_id) {
    params.set("preset_id", sanitizedFilter.preset_id);
  }
  if (sanitizedFilter.benchmark_family) {
    params.set("benchmark_family", sanitizedFilter.benchmark_family);
  }
  if (sanitizedFilter.tag) {
    parseExperimentTags(sanitizedFilter.tag).forEach((tag) => params.append("tag", tag));
  }
  if (sanitizedFilter.dataset_identity) {
    params.set("dataset_identity", sanitizedFilter.dataset_identity);
  }
  if (sanitizedFilter.filter_expr) {
    params.set("filter_expr", sanitizedFilter.filter_expr);
  }
  return `/runs?${params.toString()}`;
}

export function buildRunComparisonPath(runIds: string[], intent: ComparisonIntent) {
  const params = new URLSearchParams();
  runIds.forEach((runId) => params.append("run_id", runId));
  params.set("intent", intent);
  return `/runs/compare?${params.toString()}`;
}

export function normalizeRunHistoryFilter(current: RunHistoryFilter, strategies: Strategy[]) {
  const sanitizedCurrent = sanitizeRunHistoryFilter(current);
  const availableStrategyIds = new Set(strategies.map((strategy) => strategy.strategy_id));
  if (
    sanitizedCurrent.strategy_id !== ALL_FILTER_VALUE &&
    !availableStrategyIds.has(sanitizedCurrent.strategy_id)
  ) {
    return {
      ...defaultRunHistoryFilter,
      preset_id: sanitizedCurrent.preset_id,
      benchmark_family: sanitizedCurrent.benchmark_family,
      tag: sanitizedCurrent.tag,
      dataset_identity: sanitizedCurrent.dataset_identity,
      filter_expr: sanitizedCurrent.filter_expr,
      collection_query_label: sanitizedCurrent.collection_query_label,
    };
  }
  const availableVersions = getStrategyVersionOptions(strategies, sanitizedCurrent.strategy_id);
  if (
    sanitizedCurrent.strategy_version !== ALL_FILTER_VALUE &&
    !availableVersions.includes(sanitizedCurrent.strategy_version)
  ) {
    return { ...sanitizedCurrent, strategy_version: ALL_FILTER_VALUE };
  }
  return sanitizedCurrent;
}

export function normalizeRunHistoryPresetFilter(
  current: RunHistoryFilter,
  presets: ExperimentPreset[],
) {
  const sanitizedCurrent = sanitizeRunHistoryFilter(current);
  if (!sanitizedCurrent.preset_id) {
    return sanitizedCurrent;
  }
  const matchingPreset = presets.find((preset) => preset.preset_id === sanitizedCurrent.preset_id);
  if (
    matchingPreset &&
    (
      sanitizedCurrent.strategy_id === ALL_FILTER_VALUE ||
      !matchingPreset.strategy_id ||
      matchingPreset.strategy_id === sanitizedCurrent.strategy_id
    )
  ) {
    return sanitizedCurrent;
  }
  return {
    ...sanitizedCurrent,
    preset_id: "",
  };
}

export function getStrategyVersionOptions(strategies: Strategy[], strategyId: string) {
  const scopedStrategies =
    strategyId === ALL_FILTER_VALUE
      ? strategies
      : strategies.filter((strategy) => strategy.strategy_id === strategyId);
  return Array.from(
    new Set(
      scopedStrategies.flatMap((strategy) =>
        strategy.version_lineage.length ? strategy.version_lineage : [strategy.version],
      ),
    ),
  ).sort();
}

export function pickLatestBenchmarkRun(runs: Run[], lane: string) {
  return (
    runs.find((run) => run.provenance.lane === lane && run.status === "completed") ??
    runs.find((run) => run.provenance.lane === lane) ??
    null
  );
}
