// @ts-nocheck

import { CSSProperties, FormEvent, KeyboardEvent, MouseEvent, PointerEvent, ReactNode, forwardRef, useCallback, useEffect, useId, useLayoutEffect, useMemo, useRef, useState, AKRA_TOUCH_FEEDBACK_BRIDGE_VERSION, AKRA_TOUCH_FEEDBACK_EVENT_NAME, AkraTouchFeedbackDetail, AkraTouchFeedbackEnvelope, triggerAkraTouchFeedbackBridge, WorkspaceShell, buildControlWorkspaceDescriptors, ControlWorkspaceDescriptor, ControlStripMetric, useWorkspaceRoute, WorkspaceRouteContent, buildRunHistoryWorkspacePanels, LiveOrderReplacementDraft, RunHistoryWorkspaceSectionProps, RunOrderControls, getRunListBoundaryContractSnapshot, getRunListBoundarySurfaceLabel, getRunSurfaceCapabilityFamily, getRunSurfaceCapabilityFamilyOrder, getRunSurfaceCapabilityGroupOrder, getRunSurfaceCapabilitySchemaContract, getRunSurfaceCollectionQueryContracts, getRunSurfaceSharedContracts, getRunSurfaceSubresourceContracts, RunListComparisonBoundaryNote, shouldEnableStrategyProvenanceSemantics, shouldEnableRunListMetricDrillBack, shouldEnableRunSnapshotSemantics, shouldEnableStrategyCatalogSchemaHints, shouldHydratePresetParameterDefaults, shouldRenderOrderActionBoundaryNote, shouldRenderWorkflowControlBoundaryNote, RunSurfaceCollectionQueryBuilder, formatComparisonTooltipTuningDelta, formatComparisonTooltipTuningValue, formatRelativeTimestampLabel, RunSection, RunSurfaceCollectionQueryBuilderApplyPayload, RunSurfaceCollectionQueryRuntimeCandidateContextSelection, RunSurfaceCollectionQueryRuntimeCandidateSample, applyProviderProvenanceSchedulerStitchedReportGovernancePlan, applyProviderProvenanceSchedulerNarrativeGovernancePlan, approveProviderProvenanceSchedulerStitchedReportGovernancePlan, approveProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceAnalyticsPreset, createProviderProvenanceDashboardView, createProviderProvenanceExportJob, createProviderProvenanceSchedulerStitchedReportGovernanceRegistry, createProviderProvenanceSchedulerStitchedReportGovernancePlan, createProviderProvenanceSchedulerStitchedReportView, createProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, captureProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchy, createProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, createProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceSchedulerNarrativeRegistryEntry, createProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceScheduledReport, approveProviderProvenanceExportJob, applyProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, deleteProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, deleteProviderProvenanceSchedulerNarrativeRegistryEntry, deleteProviderProvenanceSchedulerStitchedReportView, deleteProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, createRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, createRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, downloadProviderProvenanceExportJob, downloadRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, escalateProviderProvenanceExportJob, exportProviderProvenanceSchedulerHealth, exportProviderProvenanceSchedulerStitchedNarrativeReport, reconstructProviderProvenanceSchedulerHealthExport, exportRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, fetchJson, getProviderProvenanceExportAnalytics, getProviderProvenanceExportJobHistory, getProviderProvenanceSchedulerHealthAnalytics, getProviderProvenanceScheduledReportHistory, getRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobHistory, listProviderProvenanceAnalyticsPresets, listProviderProvenanceDashboardViews, listProviderProvenanceSchedulerStitchedReportViews, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogs, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplates, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePlans, listProviderProvenanceSchedulerNarrativeRegistryEntries, listProviderProvenanceSchedulerNarrativeRegistryRevisions, listProviderProvenanceSchedulerNarrativeTemplates, listProviderProvenanceSchedulerNarrativeTemplateRevisions, listProviderProvenanceSchedulerStitchedReportGovernancePolicyCatalogs, listProviderProvenanceSchedulerStitchedReportGovernancePolicyTemplates, listProviderProvenanceSchedulerStitchedReportGovernancePlans, rollbackProviderProvenanceSchedulerStitchedReportGovernancePlan, rollbackProviderProvenanceSchedulerNarrativeGovernancePlan, listMarketDataIngestionJobs, listMarketDataLineageHistory, listProviderProvenanceExportJobs, listProviderProvenanceSchedulerAlertHistory, listProviderProvenanceSchedulerHealthHistory, listProviderProvenanceSchedulerStitchedReportGovernanceRegistries, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryAudits, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisions, listProviderProvenanceSchedulerStitchedReportViewAudits, listProviderProvenanceSchedulerStitchedReportViewRevisions, getProviderProvenanceSchedulerSearchDashboard, bulkGovernProviderProvenanceSchedulerSearchModerationPolicyCatalogs, bulkGovernProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, createProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicy, createProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, listProviderProvenanceSchedulerSearchModerationPolicyCatalogs, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlans, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAudits, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisions, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePlans, listProviderProvenanceSchedulerSearchModerationPolicyCatalogAudits, listProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisions, listProviderProvenanceSchedulerSearchModerationPlans, listProviderProvenanceScheduledReports, listRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, listRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, approveProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, approveProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, approveProviderProvenanceSchedulerSearchModerationPlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, applyProviderProvenanceSchedulerSearchModerationPlan, createProviderProvenanceSchedulerSearchModerationPolicyCatalog, deleteProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, deleteProviderProvenanceSchedulerSearchModerationPolicyCatalog, moderateProviderProvenanceSchedulerSearchFeedbackBatch, moderateProviderProvenanceSchedulerSearchFeedback, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, recordProviderProvenanceSchedulerSearchFeedback, resolveRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevision, restoreProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevision, restoreProviderProvenanceSchedulerSearchModerationPolicyCatalogRevision, restoreProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevision, restoreProviderProvenanceSchedulerNarrativeRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportViewRevision, restoreProviderProvenanceSchedulerNarrativeTemplateRevision, revokeRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, runProviderProvenanceSchedulerNarrativeGovernancePlanBatchAction, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkGovernance, stageProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, stageProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, stageProviderProvenanceSchedulerSearchModerationPlan, updateProviderProvenanceSchedulerSearchModerationPolicyCatalog, updateProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, stageProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, runDueProviderProvenanceScheduledReports, runProviderProvenanceScheduledReport, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStep, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, updateProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, updateProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, updateProviderProvenanceSchedulerNarrativeRegistryEntry, updateProviderProvenanceSchedulerStitchedReportGovernanceRegistry, updateProviderProvenanceSchedulerStitchedReportView, updateProviderProvenanceSchedulerNarrativeTemplate, updateProviderProvenanceExportJobPolicy, deleteProviderProvenanceSchedulerStitchedReportGovernanceRegistry, ALL_FILTER_VALUE, apiBase, COMPARISON_FOCUS_ARTIFACT_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_MICRO_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_NOTE_PAGE_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_SCRUB_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_COMPONENT_SEARCH_PARAM, COMPARISON_FOCUS_DETAIL_SEARCH_PARAM, COMPARISON_FOCUS_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ORIGIN_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_SECTION_SEARCH_PARAM, COMPARISON_FOCUS_SOURCE_SEARCH_PARAM, COMPARISON_FOCUS_TOOLTIP_SEARCH_PARAM, COMPARISON_HISTORY_BROWSER_STATE_KEY, COMPARISON_HISTORY_BROWSER_STATE_VERSION, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_KEY, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_VERSION, COMPARISON_HISTORY_SYNC_CONFLICT_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_PREFERENCE_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_WORKSPACE_FIELD_DEFINITIONS, COMPARISON_HISTORY_TAB_ID_SESSION_KEY, COMPARISON_INTENT_SEARCH_PARAM, COMPARISON_RUN_ID_SEARCH_PARAM, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_KEY, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_VERSION, COMPARISON_TOOLTIP_TUNING_GROUPS, COMPARISON_TOOLTIP_TUNING_LABELS, COMPARISON_TOOLTIP_TUNING_SHARE_PARAM, COMPARISON_TOOLTIP_TUNING_STORAGE_KEY, COMPARISON_TOOLTIP_TUNING_STORAGE_VERSION, COMPARISON_TOOLTIP_UNCHANGED_GROUP_COLLAPSE_THRESHOLD, CONTROL_ROOM_UI_STATE_STORAGE_KEY, CONTROL_ROOM_UI_STATE_VERSION, DEFAULT_COMPARISON_TOOLTIP_PRESET_IMPORT_CONFLICT_POLICY, DEFAULT_COMPARISON_TOOLTIP_TUNING, DEFAULT_CONTROL_ROOM_DOCUMENT_TITLE, LEGACY_GAP_WINDOW_EXPANSION_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_VERSION, MAX_COMPARISON_HISTORY_PANEL_ENTRIES, MAX_COMPARISON_HISTORY_SYNC_AUDIT_ENTRIES, MAX_COMPARISON_RUNS, MAX_MARKET_DATA_PROVENANCE_EXPORT_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_REVIEWED_CONFLICT_KEYS, MAX_VISIBLE_COMPARISON_TOOLTIP_CONFLICT_SESSION_SUMMARIES, MAX_VISIBLE_GAP_WINDOWS, PRESET_PROFILE_AGGRESSIVENESS_RANKS, PRESET_PROFILE_CONFIDENCE_RANKS, PRESET_PROFILE_SPEED_RANKS, PRESET_TIMEFRAME_UNIT_TO_MINUTES, REPLAY_INTENT_ACTION_FILTER_SEARCH_PARAM, REPLAY_INTENT_ALIAS_SEARCH_PARAM, REPLAY_INTENT_EDGE_FILTER_SEARCH_PARAM, REPLAY_INTENT_GROUP_FILTER_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_DIFF_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_GROUP_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_TRACE_SEARCH_PARAM, REPLAY_INTENT_SCOPE_SEARCH_PARAM, REPLAY_INTENT_SEARCH_PARAM, REPLAY_INTENT_STEP_SEARCH_PARAM, REPLAY_INTENT_TEMPLATE_SEARCH_PARAM, RUN_HISTORY_SAVED_FILTER_STORAGE_KEY_PREFIX, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_TAB_ID_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_BROWSER_STATE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_PAYLOAD_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_SIGNING_SECRET_STORAGE_KEY, SHOW_COMPARISON_TOOLTIP_TUNING_PANEL, TOUCH_GAP_WINDOW_SWEEP_HOLD_MS, TOUCH_GAP_WINDOW_SWEEP_MOVE_TOLERANCE_PX, BenchmarkArtifact, ParameterSchema, ComparisonCueKind, ComparisonHistoryBrowserState, ComparisonHistoryPanelEntry, ComparisonHistoryPanelState, ComparisonHistoryPanelSyncState, ComparisonHistoryStepDescriptor, ComparisonHistorySyncAuditEntry, ComparisonHistorySyncAuditFilter, ComparisonHistorySyncAuditKind, ComparisonHistorySyncAuditTrailState, ComparisonHistorySyncConflictFieldKey, ComparisonHistorySyncConflictFieldSource, ComparisonHistorySyncConflictReview, ComparisonHistorySyncConflictReviewGroup, ComparisonHistorySyncPreferenceFieldKey, ComparisonHistorySyncPreferenceReview, ComparisonHistorySyncPreferenceReviewRow, ComparisonHistorySyncPreferenceState, ComparisonHistorySyncWorkspaceRecommendationOverview, ComparisonHistorySyncWorkspaceReview, ComparisonHistorySyncWorkspaceReviewRow, ComparisonHistorySyncWorkspaceReviewSelectionKey, ComparisonHistorySyncWorkspaceSemanticSignal, ComparisonHistorySyncWorkspaceSignalDetailNestedKey, ComparisonHistorySyncWorkspaceSignalDetailSubviewKey, ComparisonHistorySyncWorkspaceSignalMicroInteractionKey, ComparisonHistorySyncWorkspaceSignalMicroViewKey, ComparisonHistorySyncWorkspaceState, ComparisonHistoryTabIdentity, ComparisonHistoryWriteMode, ComparisonIntent, ComparisonScoreDrillBackOptions, ComparisonScoreLinkedRunRole, ComparisonScoreLinkSource, ComparisonScoreLinkTarget, ComparisonScoreSection, ComparisonTooltipConflictSessionSummary, ComparisonTooltipConflictSessionSummarySession, ComparisonTooltipConflictSessionUiState, ComparisonTooltipConflictUiStateV1, ComparisonTooltipInteractionOptions, ComparisonTooltipLayout, ComparisonTooltipPendingPresetImportConflict, ComparisonTooltipPresetConflictPreviewGroup, ComparisonTooltipPresetConflictPreviewRow, ComparisonTooltipPresetImportConflictPolicy, ComparisonTooltipPresetImportResolution, ComparisonTooltipTargetProps, ComparisonTooltipTuning, ComparisonTooltipTuningPresetStateV1, ComparisonTooltipTuningShareImport, ComparisonTooltipTuningSinglePresetShareV1, ControlRoomComparisonHistoryPanelUiState, ControlRoomComparisonSelectionState, ControlRoomUiStateV1, ControlRoomUiStateV2, ControlRoomUiStateV3, ControlRoomUiStateV4, ExpandedGapWindowSelections, ExperimentPreset, ExperimentPresetRevision, GapWindowDragSelectionState, GuardedLiveStatus, MarketDataIngestionJobRecord, MarketDataProvenanceExportFilterState, MarketDataProvenanceExportHistoryEntry, MarketDataProvenanceExportSort, MarketDataProvenanceExportStateV1, MarketDataLineageHistoryRecord, MarketDataStatus, OperatorAlertMarketContextProvenance, OperatorAlertPrimaryFocus, OperatorVisibility, PendingTouchGapWindowSweepState, PresetDraftConflict, PresetRevisionDiff, PresetRevisionFilterState, PresetStructuredDiffDeltaValue, PresetStructuredDiffGroup, PresetStructuredDiffRow, ProviderProvenanceAnalyticsPresetEntry, ProviderProvenanceDashboardLayout, ProviderProvenanceDashboardViewEntry, ProviderProvenanceExportAnalyticsPayload, ProviderProvenanceExportJobEntry, ProviderProvenanceExportJobEscalationResult, ProviderProvenanceExportJobHistoryPayload, ProviderProvenanceExportJobPolicyResult, ProviderProvenanceSchedulerAlertHistoryPayload, ProviderProvenanceSchedulerHealthExportPayload, ProviderProvenanceSchedulerHealthAnalyticsPayload, ProviderProvenanceSchedulerHealthHistoryPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditRecord, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditRecord, ProviderProvenanceSchedulerSearchModerationPlanListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogListPayload, ProviderProvenanceSchedulerSearchFeedbackBatchModerationResult, ProviderProvenanceSchedulerSearchDashboardPayload, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditRecord, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionListPayload, ProviderProvenanceSchedulerStitchedReportViewAuditRecord, ProviderProvenanceSchedulerStitchedReportViewEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionListPayload, ProviderProvenanceSchedulerNarrativeBulkGovernanceResult, ProviderProvenanceSchedulerNarrativeGovernancePlan, ProviderProvenanceSchedulerNarrativeGovernancePlanBatchResult, ProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyStep, ProviderProvenanceSchedulerNarrativeGovernanceQueueView, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeRegistryEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionListPayload, ProviderProvenanceSchedulerNarrativeTemplateEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionListPayload, ProviderProvenanceScheduledReportEntry, ProviderProvenanceScheduledReportHistoryPayload, ProvenanceArtifactLineDetailView, ProvenanceArtifactLineMicroView, Run, RunComparison, RunHistoryFilter, RunHistorySurfaceKey, RunListBoundaryContract, RunListBoundaryEligibility, RunListBoundaryGroupKey, RunListBoundarySurfaceId, RunSurfaceCapabilities, RunSurfaceCapabilityFamily, RunSurfaceCapabilityFamilyContract, RunSurfaceCapabilityFamilyKey, RunSurfaceCapabilitySchemaContract, RunSurfaceCapabilitySurfaceKey, RunSurfaceCollectionQueryBuilderReplayIntentSnapshot, RunSurfaceCollectionQueryBuilderReplayLinkAliasRecordPayload, RunSurfaceCollectionQueryBuilderReplayLinkRedactionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkRetentionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobDownloadPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobPrunePayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditPrunePayload, RunSurfaceCollectionQueryContract, RunSurfaceCollectionQueryElementField, RunSurfaceCollectionQueryExpressionAuthoring, RunSurfaceCollectionQueryParameterDomainDescriptor, RunSurfaceCollectionQuerySchema, RunSurfaceSharedContract, RunSurfaceSubresourceContract, SavedRunHistoryFilterPreset, SavedRunHistoryFilterPresetStateV1, Strategy, TouchGapWindowActivationFeedbackState, TouchGapWindowHoldProgressState } from "./ControlRoomCoreHelpersContext";
import { defaultRunForm, defaultPresetForm, defaultPresetRevisionFilter, defaultMarketDataProvenanceExportFilterState, ProviderProvenanceAnalyticsScope, ProviderProvenanceSchedulerOccurrenceNarrativeFacet, ProviderProvenanceAnalyticsQueryState, ProviderProvenanceSchedulerSearchDashboardFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, ProviderProvenanceSchedulerSearchModerationQueueFilterState, ProviderProvenanceSchedulerSearchModerationStageDraft, ProviderProvenanceSchedulerExportPolicyDraft, OperatorVisibilityAlertEntry, defaultProviderProvenanceAnalyticsQueryState, defaultProviderProvenanceSchedulerSearchDashboardFilterState, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilter, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, defaultProviderProvenanceSchedulerSearchModerationQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationStageDraft, normalizeProviderProvenanceSchedulerRoutingPolicyDraftValue, normalizeProviderProvenanceSchedulerApprovalPolicyDraftValue, buildProviderProvenanceSchedulerExportPolicyDraft, getProviderProvenanceSchedulerNarrativeGovernanceQueuePriorityRank, getProviderProvenanceSchedulerNarrativeGovernanceQueueState, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchySummary, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepSummary, formatProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyPosition, isProviderProvenanceSchedulerAlertCategory, getOperatorAlertOccurrenceKey, formatProviderProvenanceSchedulerTimelineSummary, formatProviderProvenanceSchedulerSearchMatchSummary, formatProviderProvenanceSchedulerRetrievalClusterSummary, buildProviderProvenanceSchedulerAlertWorkflowReason } from "./ControlRoomCoreDefaults";
import { defaultProviderProvenanceDashboardLayout, DEFAULT_PROVIDER_PROVENANCE_SCHEDULER_NARRATIVE_GOVERNANCE_QUEUE_SORT, defaultProviderProvenanceWorkspaceDraft, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraftState, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraft, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraftState, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraft, KEEP_CURRENT_BULK_GOVERNANCE_VALUE, CLEAR_TEMPLATE_LINK_BULK_GOVERNANCE_VALUE, ProviderProvenanceSchedulerNarrativeBulkToggleValue, ProviderProvenanceSchedulerNarrativeTemplateBulkDraftState, defaultProviderProvenanceSchedulerNarrativeTemplateBulkDraft, ProviderProvenanceSchedulerStitchedReportViewBulkDraftState, defaultProviderProvenanceSchedulerStitchedReportViewBulkDraft, ProviderProvenanceSchedulerNarrativeRegistryDraftState, defaultProviderProvenanceSchedulerNarrativeRegistryDraft, ProviderProvenanceSchedulerNarrativeRegistryBulkDraftState, defaultProviderProvenanceSchedulerNarrativeRegistryBulkDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraft, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraftState, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraft, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraftState, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepVersionEntry, ProviderProvenanceSchedulerNarrativeGovernanceQueueFilterState, defaultProviderProvenanceSchedulerNarrativeGovernanceQueueFilter, ProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterState, defaultProviderProvenanceSchedulerStitchedReportGovernanceQueueFilter, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilterState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilter, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilterState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilter, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilterState, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilter, ProviderProvenanceSchedulerStitchedReportViewAuditFilterState, defaultProviderProvenanceSchedulerStitchedReportViewAuditFilter, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilterState, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilter, ProviderProvenanceReportDraftState, defaultProviderProvenanceReportDraft } from "./ControlRoomCoreProviderDrafts";
import { buildPresetFormFromPreset, buildCurrentPresetRevisionSnapshot, buildEmptyPresetRevisionSnapshot, formatPresetStructuredDiffDisplayValue, isPresetStructuredDiffObject, isPresetStructuredDiffScalar, arePresetStructuredDiffValuesEquivalent, matchesPresetParameterSchemaType, joinPresetStructuredDiffHints, tokenizePresetParameterPath, parsePresetTimeframeToMinutes, buildPresetRankedStringDelta, buildPresetParameterStrategyContext, buildPresetParameterDomainContext, formatPresetParameterSchemaHint, getPresetParameterSchemaEntry, buildPresetStructuredDiffDelta, summarizePresetStructuredDiffGroup, groupPresetStructuredDiffRows, buildPresetStructuredDiffRows, describePresetRevisionDiff, describePresetDraftConflict, matchesPresetRevisionFilter } from "./ControlRoomCorePresetDiff";

export const defaultRunHistoryFilter: RunHistoryFilter = {
  strategy_id: ALL_FILTER_VALUE,
  strategy_version: ALL_FILTER_VALUE,
  preset_id: "",
  benchmark_family: "",
  tag: "",
  dataset_identity: "",
  filter_expr: "",
  collection_query_label: "",
};

export function sanitizeRunHistoryFilter(filter: RunHistoryFilter): RunHistoryFilter {
  return {
    strategy_id: filter.strategy_id || ALL_FILTER_VALUE,
    strategy_version: filter.strategy_version || ALL_FILTER_VALUE,
    preset_id: filter.preset_id.trim(),
    benchmark_family: filter.benchmark_family.trim(),
    tag: filter.tag.trim(),
    dataset_identity: filter.dataset_identity.trim(),
    filter_expr: filter.filter_expr.trim(),
    collection_query_label: filter.collection_query_label.trim(),
  };
}

export function cloneRunHistoryFilter(filter: RunHistoryFilter): RunHistoryFilter {
  return sanitizeRunHistoryFilter({ ...filter });
}

export function hasRunHistoryFilterCriteria(filter: RunHistoryFilter) {
  const candidate = sanitizeRunHistoryFilter(filter);
  return Boolean(
    candidate.strategy_id !== ALL_FILTER_VALUE
    || candidate.strategy_version !== ALL_FILTER_VALUE
    || candidate.preset_id
    || candidate.benchmark_family
    || candidate.tag
    || candidate.dataset_identity
    || candidate.filter_expr,
  );
}

export function areRunHistoryFiltersEquivalent(left: RunHistoryFilter, right: RunHistoryFilter) {
  const normalizedLeft = sanitizeRunHistoryFilter(left);
  const normalizedRight = sanitizeRunHistoryFilter(right);
  return (
    normalizedLeft.strategy_id === normalizedRight.strategy_id
    && normalizedLeft.strategy_version === normalizedRight.strategy_version
    && normalizedLeft.preset_id === normalizedRight.preset_id
    && normalizedLeft.benchmark_family === normalizedRight.benchmark_family
    && normalizedLeft.tag === normalizedRight.tag
    && normalizedLeft.dataset_identity === normalizedRight.dataset_identity
    && normalizedLeft.filter_expr === normalizedRight.filter_expr
  );
}

export function buildRunHistorySavedFilterStorageKey(surfaceKey: RunHistorySurfaceKey) {
  return `${RUN_HISTORY_SAVED_FILTER_STORAGE_KEY_PREFIX}:${surfaceKey}`;
}

export function normalizeSavedRunHistoryFilterPreset(value: unknown): SavedRunHistoryFilterPreset | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const candidate = value as Partial<SavedRunHistoryFilterPreset>;
  if (
    typeof candidate.filter_id !== "string"
    || typeof candidate.label !== "string"
    || typeof candidate.created_at !== "string"
    || typeof candidate.updated_at !== "string"
    || !candidate.filter
    || typeof candidate.filter !== "object"
  ) {
    return null;
  }
  const filterCandidate = candidate.filter as Partial<RunHistoryFilter>;
  return {
    filter_id: candidate.filter_id,
    label: candidate.label,
    created_at: candidate.created_at,
    updated_at: candidate.updated_at,
    filter: sanitizeRunHistoryFilter({
      ...defaultRunHistoryFilter,
      strategy_id:
        typeof filterCandidate.strategy_id === "string"
          ? filterCandidate.strategy_id
          : defaultRunHistoryFilter.strategy_id,
      strategy_version:
        typeof filterCandidate.strategy_version === "string"
          ? filterCandidate.strategy_version
          : defaultRunHistoryFilter.strategy_version,
      preset_id:
        typeof filterCandidate.preset_id === "string"
          ? filterCandidate.preset_id
          : defaultRunHistoryFilter.preset_id,
      benchmark_family:
        typeof filterCandidate.benchmark_family === "string"
          ? filterCandidate.benchmark_family
          : defaultRunHistoryFilter.benchmark_family,
      tag: typeof filterCandidate.tag === "string" ? filterCandidate.tag : defaultRunHistoryFilter.tag,
      dataset_identity:
        typeof filterCandidate.dataset_identity === "string"
          ? filterCandidate.dataset_identity
          : defaultRunHistoryFilter.dataset_identity,
      filter_expr:
        typeof filterCandidate.filter_expr === "string"
          ? filterCandidate.filter_expr
          : defaultRunHistoryFilter.filter_expr,
      collection_query_label:
        typeof filterCandidate.collection_query_label === "string"
          ? filterCandidate.collection_query_label
          : defaultRunHistoryFilter.collection_query_label,
    }),
  };
}

export function loadSavedRunHistoryFilterPresets(surfaceKey: RunHistorySurfaceKey): SavedRunHistoryFilterPreset[] {
  if (typeof window === "undefined") {
    return [];
  }
  try {
    const raw = window.localStorage.getItem(buildRunHistorySavedFilterStorageKey(surfaceKey));
    if (!raw) {
      return [];
    }
    const parsed = JSON.parse(raw) as Partial<SavedRunHistoryFilterPresetStateV1> | null;
    if (parsed?.version !== 1 || !Array.isArray(parsed.filters)) {
      return [];
    }
    return parsed.filters
      .map((entry) => normalizeSavedRunHistoryFilterPreset(entry))
      .filter((entry): entry is SavedRunHistoryFilterPreset => entry !== null);
  } catch {
    return [];
  }
}

export function persistSavedRunHistoryFilterPresets(
  surfaceKey: RunHistorySurfaceKey,
  presets: SavedRunHistoryFilterPreset[],
) {
  if (typeof window === "undefined") {
    return;
  }
  try {
    window.localStorage.setItem(
      buildRunHistorySavedFilterStorageKey(surfaceKey),
      JSON.stringify({
        version: 1,
        filters: presets.map((entry) => ({
          ...entry,
          filter: sanitizeRunHistoryFilter(entry.filter),
        })),
      } satisfies SavedRunHistoryFilterPresetStateV1),
    );
  } catch {
    // Ignore localStorage failures for saved run-history filters.
  }
}

export function describeRunHistoryFilter(filter: RunHistoryFilter, presets: ExperimentPreset[], strategies: Strategy[]) {
  const candidate = sanitizeRunHistoryFilter(filter);
  const parts: string[] = [];
  if (candidate.strategy_id !== ALL_FILTER_VALUE) {
    const strategy = strategies.find((item) => item.strategy_id === candidate.strategy_id);
    parts.push(`Strategy ${strategy?.name ?? candidate.strategy_id}`);
  }
  if (candidate.strategy_version !== ALL_FILTER_VALUE) {
    parts.push(`Version ${candidate.strategy_version}`);
  }
  if (candidate.preset_id) {
    const preset = presets.find((item) => item.preset_id === candidate.preset_id);
    parts.push(`Preset ${preset?.name ?? candidate.preset_id}`);
  }
  if (candidate.benchmark_family) {
    parts.push(`Benchmark ${candidate.benchmark_family}`);
  }
  if (candidate.tag) {
    parts.push(`Tag ${candidate.tag}`);
  }
  if (candidate.dataset_identity) {
    parts.push(`Dataset ${candidate.dataset_identity}`);
  }
  if (candidate.filter_expr) {
    parts.push(
      candidate.collection_query_label
        ? `Collection ${candidate.collection_query_label}`
        : "Collection expression",
    );
  }
  return parts;
}

export const DEFAULT_COMPARISON_INTENT: ComparisonIntent = "benchmark_validation";
export const comparisonIntentOptions: ComparisonIntent[] = [
  "benchmark_validation",
  "execution_regression",
  "strategy_tuning",
];

export function parseExperimentTags(value: string) {
  return Array.from(
    new Set(
      value
        .split(",")
        .map((tag) => tag.trim())
        .filter(Boolean),
    ),
  );
}

export function parseJsonObjectInput(value: string) {
  const trimmed = value.trim();
  if (!trimmed) {
    return {};
  }
  const parsed = JSON.parse(trimmed) as unknown;
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("Parameter bundle must be a JSON object.");
  }
  return parsed as Record<string, unknown>;
}

export function formatPresetLifecycleStage(stage: string) {
  return stage.replaceAll("_", " ");
}

function formatRunDateBoundary(dateValue: string, boundary: "start" | "end") {
  const trimmed = dateValue.trim();
  if (!trimmed) {
    return null;
  }
  return boundary === "start" ? `${trimmed}T00:00:00Z` : `${trimmed}T23:59:59Z`;
}

export function buildRunSubmissionPayload(form: typeof defaultRunForm, extras: Record<string, unknown> = {}) {
  const presetId = form.preset_id.trim();
  const benchmarkFamily = form.benchmark_family.trim();
  return {
    strategy_id: form.strategy_id,
    symbol: form.symbol,
    timeframe: form.timeframe,
    initial_cash: form.initial_cash,
    fee_rate: form.fee_rate,
    slippage_bps: form.slippage_bps,
    parameters: {},
    start_at: formatRunDateBoundary(form.start_date, "start"),
    end_at: formatRunDateBoundary(form.end_date, "end"),
    tags: parseExperimentTags(form.tags_text),
    preset_id: presetId || null,
    benchmark_family: benchmarkFamily || null,
    ...extras,
  };
}

export function normalizeRunFormPreset(
  current: typeof defaultRunForm,
  presets: ExperimentPreset[],
) {
  if (!current.preset_id) {
    return current;
  }
  const matchingPreset = presets.find((preset) => preset.preset_id === current.preset_id);
  if (
    matchingPreset &&
    matchingPreset.lifecycle.stage !== "archived" &&
    (!matchingPreset.strategy_id || matchingPreset.strategy_id === current.strategy_id) &&
    (!matchingPreset.timeframe || matchingPreset.timeframe === current.timeframe)
  ) {
    return current;
  }
  return {
    ...current,
    preset_id: "",
  };
}
