// @ts-nocheck
import { CSSProperties, FormEvent, KeyboardEvent, MouseEvent, PointerEvent, ReactNode, forwardRef, useCallback, useEffect, useId, useLayoutEffect, useMemo, useRef, useState, AKRA_TOUCH_FEEDBACK_BRIDGE_VERSION, AKRA_TOUCH_FEEDBACK_EVENT_NAME, AkraTouchFeedbackDetail, AkraTouchFeedbackEnvelope, triggerAkraTouchFeedbackBridge, WorkspaceShell, buildControlWorkspaceDescriptors, ControlWorkspaceDescriptor, ControlStripMetric, useWorkspaceRoute, WorkspaceRouteContent, buildRunHistoryWorkspacePanels, LiveOrderReplacementDraft, RunHistoryWorkspaceSectionProps, RunOrderControls, getRunListBoundaryContractSnapshot, getRunListBoundarySurfaceLabel, getRunSurfaceCapabilityFamily, getRunSurfaceCapabilityFamilyOrder, getRunSurfaceCapabilityGroupOrder, getRunSurfaceCapabilitySchemaContract, getRunSurfaceCollectionQueryContracts, getRunSurfaceSharedContracts, getRunSurfaceSubresourceContracts, RunListComparisonBoundaryNote, shouldEnableReferenceProvenanceSemantics, shouldEnableRunListMetricDrillBack, shouldEnableRunSnapshotSemantics, shouldEnableStrategyCatalogSchemaHints, shouldHydratePresetParameterDefaults, shouldRenderOrderActionBoundaryNote, shouldRenderWorkflowControlBoundaryNote, RunSurfaceCollectionQueryBuilder, formatComparisonTooltipTuningDelta, formatComparisonTooltipTuningValue, formatRelativeTimestampLabel, RunSection, RunSurfaceCollectionQueryBuilderApplyPayload, RunSurfaceCollectionQueryRuntimeCandidateContextSelection, RunSurfaceCollectionQueryRuntimeCandidateSample, applyProviderProvenanceSchedulerStitchedReportGovernancePlan, applyProviderProvenanceSchedulerNarrativeGovernancePlan, approveProviderProvenanceSchedulerStitchedReportGovernancePlan, approveProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceAnalyticsPreset, createProviderProvenanceDashboardView, createProviderProvenanceExportJob, createProviderProvenanceSchedulerStitchedReportGovernanceRegistry, createProviderProvenanceSchedulerStitchedReportGovernancePlan, createProviderProvenanceSchedulerStitchedReportView, createProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, captureProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchy, createProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, createProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceSchedulerNarrativeRegistryEntry, createProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceScheduledReport, approveProviderProvenanceExportJob, applyProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, deleteProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, deleteProviderProvenanceSchedulerNarrativeRegistryEntry, deleteProviderProvenanceSchedulerStitchedReportView, deleteProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, createRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, createRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, downloadProviderProvenanceExportJob, downloadRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, escalateProviderProvenanceExportJob, exportProviderProvenanceSchedulerHealth, exportProviderProvenanceSchedulerStitchedNarrativeReport, reconstructProviderProvenanceSchedulerHealthExport, exportRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, fetchJson, getProviderProvenanceExportAnalytics, getProviderProvenanceExportJobHistory, getProviderProvenanceSchedulerHealthAnalytics, getProviderProvenanceScheduledReportHistory, getRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobHistory, listProviderProvenanceAnalyticsPresets, listProviderProvenanceDashboardViews, listProviderProvenanceSchedulerStitchedReportViews, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogs, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplates, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePlans, listProviderProvenanceSchedulerNarrativeRegistryEntries, listProviderProvenanceSchedulerNarrativeRegistryRevisions, listProviderProvenanceSchedulerNarrativeTemplates, listProviderProvenanceSchedulerNarrativeTemplateRevisions, listProviderProvenanceSchedulerStitchedReportGovernancePolicyCatalogs, listProviderProvenanceSchedulerStitchedReportGovernancePolicyTemplates, listProviderProvenanceSchedulerStitchedReportGovernancePlans, rollbackProviderProvenanceSchedulerStitchedReportGovernancePlan, rollbackProviderProvenanceSchedulerNarrativeGovernancePlan, listMarketDataIngestionJobs, listMarketDataLineageHistory, listProviderProvenanceExportJobs, listProviderProvenanceSchedulerAlertHistory, listProviderProvenanceSchedulerHealthHistory, listProviderProvenanceSchedulerStitchedReportGovernanceRegistries, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryAudits, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisions, listProviderProvenanceSchedulerStitchedReportViewAudits, listProviderProvenanceSchedulerStitchedReportViewRevisions, getProviderProvenanceSchedulerSearchDashboard, bulkGovernProviderProvenanceSchedulerSearchModerationPolicyCatalogs, bulkGovernProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, createProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicy, createProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, listProviderProvenanceSchedulerSearchModerationPolicyCatalogs, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlans, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAudits, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisions, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePlans, listProviderProvenanceSchedulerSearchModerationPolicyCatalogAudits, listProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisions, listProviderProvenanceSchedulerSearchModerationPlans, listProviderProvenanceScheduledReports, listRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, listRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, approveProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, approveProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, approveProviderProvenanceSchedulerSearchModerationPlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, applyProviderProvenanceSchedulerSearchModerationPlan, createProviderProvenanceSchedulerSearchModerationPolicyCatalog, deleteProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, deleteProviderProvenanceSchedulerSearchModerationPolicyCatalog, moderateProviderProvenanceSchedulerSearchFeedbackBatch, moderateProviderProvenanceSchedulerSearchFeedback, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, recordProviderProvenanceSchedulerSearchFeedback, resolveRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevision, restoreProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevision, restoreProviderProvenanceSchedulerSearchModerationPolicyCatalogRevision, restoreProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevision, restoreProviderProvenanceSchedulerNarrativeRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportViewRevision, restoreProviderProvenanceSchedulerNarrativeTemplateRevision, revokeRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, runProviderProvenanceSchedulerNarrativeGovernancePlanBatchAction, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkGovernance, stageProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, stageProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, stageProviderProvenanceSchedulerSearchModerationPlan, updateProviderProvenanceSchedulerSearchModerationPolicyCatalog, updateProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, stageProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, runDueProviderProvenanceScheduledReports, runProviderProvenanceScheduledReport, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStep, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, updateProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, updateProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, updateProviderProvenanceSchedulerNarrativeRegistryEntry, updateProviderProvenanceSchedulerStitchedReportGovernanceRegistry, updateProviderProvenanceSchedulerStitchedReportView, updateProviderProvenanceSchedulerNarrativeTemplate, updateProviderProvenanceExportJobPolicy, deleteProviderProvenanceSchedulerStitchedReportGovernanceRegistry, ALL_FILTER_VALUE, apiBase, COMPARISON_FOCUS_ARTIFACT_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_MICRO_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_NOTE_PAGE_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_SCRUB_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_COMPONENT_SEARCH_PARAM, COMPARISON_FOCUS_DETAIL_SEARCH_PARAM, COMPARISON_FOCUS_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ORIGIN_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_SECTION_SEARCH_PARAM, COMPARISON_FOCUS_SOURCE_SEARCH_PARAM, COMPARISON_FOCUS_TOOLTIP_SEARCH_PARAM, COMPARISON_HISTORY_BROWSER_STATE_KEY, COMPARISON_HISTORY_BROWSER_STATE_VERSION, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_KEY, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_VERSION, COMPARISON_HISTORY_SYNC_CONFLICT_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_PREFERENCE_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_WORKSPACE_FIELD_DEFINITIONS, COMPARISON_HISTORY_TAB_ID_SESSION_KEY, COMPARISON_INTENT_SEARCH_PARAM, COMPARISON_RUN_ID_SEARCH_PARAM, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_KEY, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_VERSION, COMPARISON_TOOLTIP_TUNING_GROUPS, COMPARISON_TOOLTIP_TUNING_LABELS, COMPARISON_TOOLTIP_TUNING_SHARE_PARAM, COMPARISON_TOOLTIP_TUNING_STORAGE_KEY, COMPARISON_TOOLTIP_TUNING_STORAGE_VERSION, COMPARISON_TOOLTIP_UNCHANGED_GROUP_COLLAPSE_THRESHOLD, CONTROL_ROOM_UI_STATE_STORAGE_KEY, CONTROL_ROOM_UI_STATE_VERSION, DEFAULT_COMPARISON_TOOLTIP_PRESET_IMPORT_CONFLICT_POLICY, DEFAULT_COMPARISON_TOOLTIP_TUNING, DEFAULT_CONTROL_ROOM_DOCUMENT_TITLE, LEGACY_GAP_WINDOW_EXPANSION_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_VERSION, MAX_COMPARISON_HISTORY_PANEL_ENTRIES, MAX_COMPARISON_HISTORY_SYNC_AUDIT_ENTRIES, MAX_COMPARISON_RUNS, MAX_MARKET_DATA_PROVENANCE_EXPORT_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_REVIEWED_CONFLICT_KEYS, MAX_VISIBLE_COMPARISON_TOOLTIP_CONFLICT_SESSION_SUMMARIES, MAX_VISIBLE_GAP_WINDOWS, PRESET_PROFILE_AGGRESSIVENESS_RANKS, PRESET_PROFILE_CONFIDENCE_RANKS, PRESET_PROFILE_SPEED_RANKS, PRESET_TIMEFRAME_UNIT_TO_MINUTES, REPLAY_INTENT_ACTION_FILTER_SEARCH_PARAM, REPLAY_INTENT_ALIAS_SEARCH_PARAM, REPLAY_INTENT_EDGE_FILTER_SEARCH_PARAM, REPLAY_INTENT_GROUP_FILTER_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_DIFF_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_GROUP_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_TRACE_SEARCH_PARAM, REPLAY_INTENT_SCOPE_SEARCH_PARAM, REPLAY_INTENT_SEARCH_PARAM, REPLAY_INTENT_STEP_SEARCH_PARAM, REPLAY_INTENT_TEMPLATE_SEARCH_PARAM, RUN_HISTORY_SAVED_FILTER_STORAGE_KEY_PREFIX, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_TAB_ID_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_BROWSER_STATE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_PAYLOAD_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_SIGNING_SECRET_STORAGE_KEY, SHOW_COMPARISON_TOOLTIP_TUNING_PANEL, TOUCH_GAP_WINDOW_SWEEP_HOLD_MS, TOUCH_GAP_WINDOW_SWEEP_MOVE_TOLERANCE_PX, BenchmarkArtifact, ParameterSchema, ComparisonCueKind, ComparisonHistoryBrowserState, ComparisonHistoryPanelEntry, ComparisonHistoryPanelState, ComparisonHistoryPanelSyncState, ComparisonHistoryStepDescriptor, ComparisonHistorySyncAuditEntry, ComparisonHistorySyncAuditFilter, ComparisonHistorySyncAuditKind, ComparisonHistorySyncAuditTrailState, ComparisonHistorySyncConflictFieldKey, ComparisonHistorySyncConflictFieldSource, ComparisonHistorySyncConflictReview, ComparisonHistorySyncConflictReviewGroup, ComparisonHistorySyncPreferenceFieldKey, ComparisonHistorySyncPreferenceReview, ComparisonHistorySyncPreferenceReviewRow, ComparisonHistorySyncPreferenceState, ComparisonHistorySyncWorkspaceRecommendationOverview, ComparisonHistorySyncWorkspaceReview, ComparisonHistorySyncWorkspaceReviewRow, ComparisonHistorySyncWorkspaceReviewSelectionKey, ComparisonHistorySyncWorkspaceSemanticSignal, ComparisonHistorySyncWorkspaceSignalDetailNestedKey, ComparisonHistorySyncWorkspaceSignalDetailSubviewKey, ComparisonHistorySyncWorkspaceSignalMicroInteractionKey, ComparisonHistorySyncWorkspaceSignalMicroViewKey, ComparisonHistorySyncWorkspaceState, ComparisonHistoryTabIdentity, ComparisonHistoryWriteMode, ComparisonIntent, ComparisonScoreDrillBackOptions, ComparisonScoreLinkedRunRole, ComparisonScoreLinkSource, ComparisonScoreLinkTarget, ComparisonScoreSection, ComparisonTooltipConflictSessionSummary, ComparisonTooltipConflictSessionSummarySession, ComparisonTooltipConflictSessionUiState, ComparisonTooltipConflictUiStateV1, ComparisonTooltipInteractionOptions, ComparisonTooltipLayout, ComparisonTooltipPendingPresetImportConflict, ComparisonTooltipPresetConflictPreviewGroup, ComparisonTooltipPresetConflictPreviewRow, ComparisonTooltipPresetImportConflictPolicy, ComparisonTooltipPresetImportResolution, ComparisonTooltipTargetProps, ComparisonTooltipTuning, ComparisonTooltipTuningPresetStateV1, ComparisonTooltipTuningShareImport, ComparisonTooltipTuningSinglePresetShareV1, ControlRoomComparisonHistoryPanelUiState, ControlRoomComparisonSelectionState, ControlRoomUiStateV1, ControlRoomUiStateV2, ControlRoomUiStateV3, ControlRoomUiStateV4, ExpandedGapWindowSelections, ExperimentPreset, ExperimentPresetRevision, GapWindowDragSelectionState, GuardedLiveStatus, MarketDataIngestionJobRecord, MarketDataProvenanceExportFilterState, MarketDataProvenanceExportHistoryEntry, MarketDataProvenanceExportSort, MarketDataProvenanceExportStateV1, MarketDataLineageHistoryRecord, MarketDataStatus, OperatorAlertMarketContextProvenance, OperatorAlertPrimaryFocus, OperatorVisibility, PendingTouchGapWindowSweepState, PresetDraftConflict, PresetRevisionDiff, PresetRevisionFilterState, PresetStructuredDiffDeltaValue, PresetStructuredDiffGroup, PresetStructuredDiffRow, ProviderProvenanceAnalyticsPresetEntry, ProviderProvenanceDashboardLayout, ProviderProvenanceDashboardViewEntry, ProviderProvenanceExportAnalyticsPayload, ProviderProvenanceExportJobEntry, ProviderProvenanceExportJobEscalationResult, ProviderProvenanceExportJobHistoryPayload, ProviderProvenanceExportJobPolicyResult, ProviderProvenanceSchedulerAlertHistoryPayload, ProviderProvenanceSchedulerHealthExportPayload, ProviderProvenanceSchedulerHealthAnalyticsPayload, ProviderProvenanceSchedulerHealthHistoryPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditRecord, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditRecord, ProviderProvenanceSchedulerSearchModerationPlanListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogListPayload, ProviderProvenanceSchedulerSearchFeedbackBatchModerationResult, ProviderProvenanceSchedulerSearchDashboardPayload, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditRecord, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionListPayload, ProviderProvenanceSchedulerStitchedReportViewAuditRecord, ProviderProvenanceSchedulerStitchedReportViewEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionListPayload, ProviderProvenanceSchedulerNarrativeBulkGovernanceResult, ProviderProvenanceSchedulerNarrativeGovernancePlan, ProviderProvenanceSchedulerNarrativeGovernancePlanBatchResult, ProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyStep, ProviderProvenanceSchedulerNarrativeGovernanceQueueView, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeRegistryEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionListPayload, ProviderProvenanceSchedulerNarrativeTemplateEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionListPayload, ProviderProvenanceScheduledReportEntry, ProviderProvenanceScheduledReportHistoryPayload, ProvenanceArtifactLineDetailView, ProvenanceArtifactLineMicroView, ReferenceSource, Run, RunComparison, RunHistoryFilter, RunHistorySurfaceKey, RunListBoundaryContract, RunListBoundaryEligibility, RunListBoundaryGroupKey, RunListBoundarySurfaceId, RunSurfaceCapabilities, RunSurfaceCapabilityFamily, RunSurfaceCapabilityFamilyContract, RunSurfaceCapabilityFamilyKey, RunSurfaceCapabilitySchemaContract, RunSurfaceCapabilitySurfaceKey, RunSurfaceCollectionQueryBuilderReplayIntentSnapshot, RunSurfaceCollectionQueryBuilderReplayLinkAliasRecordPayload, RunSurfaceCollectionQueryBuilderReplayLinkRedactionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkRetentionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobDownloadPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobPrunePayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditPrunePayload, RunSurfaceCollectionQueryContract, RunSurfaceCollectionQueryElementField, RunSurfaceCollectionQueryExpressionAuthoring, RunSurfaceCollectionQueryParameterDomainDescriptor, RunSurfaceCollectionQuerySchema, RunSurfaceSharedContract, RunSurfaceSubresourceContract, SavedRunHistoryFilterPreset, SavedRunHistoryFilterPresetStateV1, Strategy, TouchGapWindowActivationFeedbackState, TouchGapWindowHoldProgressState, defaultRunForm, defaultPresetForm, defaultPresetRevisionFilter, defaultMarketDataProvenanceExportFilterState, defaultProviderProvenanceAnalyticsQueryState, defaultProviderProvenanceSchedulerSearchDashboardFilterState, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilter, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, defaultProviderProvenanceSchedulerSearchModerationQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationStageDraft, normalizeProviderProvenanceSchedulerRoutingPolicyDraftValue, normalizeProviderProvenanceSchedulerApprovalPolicyDraftValue, buildProviderProvenanceSchedulerExportPolicyDraft, getProviderProvenanceSchedulerNarrativeGovernanceQueuePriorityRank, getProviderProvenanceSchedulerNarrativeGovernanceQueueState, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchySummary, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepSummary, formatProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyPosition, isProviderProvenanceSchedulerAlertCategory, getOperatorAlertOccurrenceKey, formatProviderProvenanceSchedulerTimelineSummary, formatProviderProvenanceSchedulerSearchMatchSummary, formatProviderProvenanceSchedulerRetrievalClusterSummary, buildProviderProvenanceSchedulerAlertWorkflowReason, defaultProviderProvenanceDashboardLayout, DEFAULT_PROVIDER_PROVENANCE_SCHEDULER_NARRATIVE_GOVERNANCE_QUEUE_SORT, defaultProviderProvenanceWorkspaceDraft, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraft, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraft, KEEP_CURRENT_BULK_GOVERNANCE_VALUE, CLEAR_TEMPLATE_LINK_BULK_GOVERNANCE_VALUE, defaultProviderProvenanceSchedulerNarrativeTemplateBulkDraft, defaultProviderProvenanceSchedulerStitchedReportViewBulkDraft, defaultProviderProvenanceSchedulerNarrativeRegistryDraft, defaultProviderProvenanceSchedulerNarrativeRegistryBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceQueueFilter, defaultProviderProvenanceSchedulerStitchedReportGovernanceQueueFilter, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilter, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilter, defaultProviderProvenanceSchedulerStitchedReportViewAuditFilter, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilter, defaultProviderProvenanceReportDraft, buildPresetFormFromPreset, buildCurrentPresetRevisionSnapshot, buildEmptyPresetRevisionSnapshot, formatPresetStructuredDiffDisplayValue, isPresetStructuredDiffObject, isPresetStructuredDiffScalar, arePresetStructuredDiffValuesEquivalent, matchesPresetParameterSchemaType, joinPresetStructuredDiffHints, tokenizePresetParameterPath, parsePresetTimeframeToMinutes, buildPresetRankedStringDelta, buildPresetParameterStrategyContext, buildPresetParameterDomainContext, formatPresetParameterSchemaHint, getPresetParameterSchemaEntry, buildPresetStructuredDiffDelta, summarizePresetStructuredDiffGroup, groupPresetStructuredDiffRows, buildPresetStructuredDiffRows, describePresetRevisionDiff, describePresetDraftConflict, matchesPresetRevisionFilter, defaultRunHistoryFilter, sanitizeRunHistoryFilter, cloneRunHistoryFilter, hasRunHistoryFilterCriteria, areRunHistoryFiltersEquivalent, buildRunHistorySavedFilterStorageKey, normalizeSavedRunHistoryFilterPreset, loadSavedRunHistoryFilterPresets, persistSavedRunHistoryFilterPresets, describeRunHistoryFilter, DEFAULT_COMPARISON_INTENT, comparisonIntentOptions, parseExperimentTags, parseJsonObjectInput, formatPresetLifecycleStage, buildRunSubmissionPayload, normalizeRunFormPreset, resolveMarketDataSymbol, buildMarketDataInstrumentFocusKey, isMarketDataInstrumentAtRisk, resolvePreferredMarketDataInstrument, formatWorkflowToken, formatMarketContextFieldProvenance, summarizeProviderRecoveryMarketContextProvenance, serializeLinkedMarketInstrumentContext, getOperatorSeverityRank, normalizeMarketDataProvenanceExportSort, normalizeMarketDataProvenanceExportFilterState, normalizeMarketDataProvenanceExportHistoryEntry, loadPersistedMarketDataProvenanceExportState, persistMarketDataProvenanceExportState, formatMarketDataProvenanceExportFilterSummary, formatProviderProvenanceAnalyticsQuerySummary, normalizeProviderProvenanceDashboardLayoutState, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueSort, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkQueueViewPatch, formatProviderProvenanceSchedulerNarrativeGovernanceQueueSortLabel, providerProvenanceSchedulerNarrativeGovernancePolicySupportsItemType, formatProviderProvenanceSchedulerNarrativeGovernanceQueueViewSummary, buildProviderProvenanceAnalyticsWorkspaceQuery, buildProviderProvenanceAnalyticsQueryStateFromWorkspaceQuery, formatProviderProvenanceSchedulerNarrativeFacet, resolveProviderProvenanceSeriesBarWidth, formatProviderDriftIntensity, formatSchedulerLagSeconds, downloadTextExport, escapeRegExp, normalizeMarketSymbol, buildMarketSymbolSearchVariants, matchesMarketSymbolInText, dedupeMarketDataInstruments, formatMarketDataInstrumentLabel, getMarketDataInstrumentSyncSeverityRank, getMarketDataInstrumentRiskScore, buildLiveMarketDataPreference, getMarketDataInstrumentLiveRelevance, selectPrimaryMarketDataInstrument, extractMatchingMarketTimeframe, extractMatchingMarketSymbols, buildLinkedMarketInstrumentContext, buildLinkedMarketInstrumentContextFromPayload, formatLinkedMarketPrimaryFocusNote, resolveInstrumentsBySymbolsAndTimeframe, resolveMarketDataInstrumentLink, getAlertLinkPriority, compareAlertLinkPriority, resolveAutoLinkedMarketInstrument, formatTimestamp, formatProviderRecoverySchema, formatProviderRecoveryTelemetry, shortenIdentifier, truncateLabel, formatRange, benchmarkArtifactSummaryOrder, benchmarkArtifactSummaryLabels, benchmarkArtifactSectionOrder, benchmarkArtifactSectionLabels, formatBenchmarkArtifactSummaryEntries, benchmarkArtifactSummarySortIndex, formatBenchmarkArtifactSummaryLabel, formatBenchmarkArtifactSummaryValue, formatBenchmarkArtifactSectionEntries, benchmarkArtifactSectionSortIndex, formatBenchmarkArtifactSectionLabel, formatBenchmarkArtifactSectionLines, formatBenchmarkArtifactSectionValue, formatBenchmarkArtifactInlineValue, ProviderProvenanceAnalyticsScope, ProviderProvenanceSchedulerOccurrenceNarrativeFacet, ProviderProvenanceAnalyticsQueryState, ProviderProvenanceSchedulerSearchDashboardFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, ProviderProvenanceSchedulerSearchModerationQueueFilterState, ProviderProvenanceSchedulerSearchModerationStageDraft, ProviderProvenanceSchedulerExportPolicyDraft, OperatorVisibilityAlertEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraftState, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraftState, ProviderProvenanceSchedulerNarrativeBulkToggleValue, ProviderProvenanceSchedulerNarrativeTemplateBulkDraftState, ProviderProvenanceSchedulerStitchedReportViewBulkDraftState, ProviderProvenanceSchedulerNarrativeRegistryDraftState, ProviderProvenanceSchedulerNarrativeRegistryBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraftState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepVersionEntry, ProviderProvenanceSchedulerNarrativeGovernanceQueueFilterState, ProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterState, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilterState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilterState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilterState, ProviderProvenanceSchedulerStitchedReportViewAuditFilterState, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilterState, ProviderProvenanceReportDraftState, LinkedMarketInstrumentContext, MarketDataLinkableAlertRecord, MarketDataIncidentHistoryEntry, ProviderRecoveryMarketContextSummary, MarketDataProviderProvenanceEventRecord, MarketDataPrimaryFocusSelection } from "./ControlRoomViewHelpersContext";
import { PanelDisclosure, BackfillCountStatus, BackfillQualityStatus, SyncCheckpointStatus, SyncFailureStatus, formatCompletion, summarizeGapWindows, formatGapWindows, buildLegacyGapWindowKey, buildGapWindowKey, parseGapWindowKey, formatGapWindowKeyLabel, normalizeExpandedGapWindowSelectionList, resolveGapWindowSelectionList, buildGapWindowSelectionUpdate, isSameGapWindowSelectionList, filterExpandedGapWindowSelections, buildGapWindowSelectionLookup, instrumentGapRowKey, toggleExpandedGapRow, pruneExpandedGapRows, pruneExpandedGapWindowSelections } from "./ControlRoomViewStatusPanels";
import { loadExpandedGapRows, loadExpandedGapWindowSelections, defaultControlRoomComparisonSelectionState, loadPersistedComparisonSelection, defaultComparisonHistoryPanelState, defaultComparisonHistoryPanelUiState, loadPersistedComparisonHistoryPanelUiState, loadControlRoomUiState, readControlRoomUiStateValue, persistControlRoomUiState, loadComparisonHistorySyncAuditTrail, persistComparisonHistorySyncAuditTrail, loadComparisonSelectionFromUrl, buildComparisonSelectionHistoryUrl, readComparisonHistoryBrowserState, buildComparisonHistoryBrowserState, isSameComparisonHistoryBrowserState, persistComparisonSelectionToUrl, buildComparisonHistoryEntryId, buildComparisonHistoryTabId, formatComparisonHistoryTabLabel, loadComparisonHistoryTabIdentity, buildComparisonHistoryPanelSyncState, buildComparisonHistorySyncSignature, buildComparisonHistorySyncAuditId, buildComparisonHistoryPanelEntry, findComparisonHistoryPanelEntryForSelection, mergeComparisonHistoryPanelState, mergeComparisonHistoryPanelEntries, reconcileComparisonHistoryPanelState, sortComparisonHistoryPanelEntries, limitComparisonHistoryPanelEntries } from "./ControlRoomViewComparisonStorage";
import { normalizeComparisonHistoryPanelUiState, normalizeComparisonHistorySyncAuditFilter, normalizeComparisonHistoryPanelSyncState, normalizeComparisonHistoryPanelState, normalizeComparisonHistoryPanelEntry, normalizeComparisonHistorySyncAuditEntry, normalizeComparisonHistorySyncConflictReview, normalizeComparisonHistorySyncConflictSelectedSources, normalizeComparisonHistorySyncPreferenceReview, normalizeComparisonHistorySyncWorkspaceReview, normalizeComparisonHistorySyncPreferenceState, normalizeComparisonHistorySyncWorkspaceState, normalizeComparisonHistorySyncPreferenceSelectedSources, normalizeComparisonHistorySyncWorkspaceSelectedSources, limitComparisonHistorySyncAuditEntries, appendComparisonHistorySyncAuditEntries, isSameComparisonHistoryPanelState, isSameComparisonHistoryPanelSyncState, isSameComparisonHistoryPanelEntry, getComparisonHistoryPanelEntryChangedFields, formatComparisonHistorySyncConflictScoreLinkValue, formatComparisonHistorySyncConflictRunSelectionValue, formatComparisonHistorySyncConflictFieldValue, hasComparisonHistorySyncConflictFieldDifference, buildDefaultComparisonHistorySyncConflictSelectedSources, buildComparisonHistorySyncConflictReview, buildComparisonHistorySyncConflictReviewGroups, summarizeComparisonHistoryPanelEntryConflict, formatComparisonHistorySyncConflictResolutionSummary, resolveComparisonHistorySyncConflictReviewEntry, applyResolvedComparisonHistoryPanelEntry, summarizeComparisonHistorySyncPreferenceChanges, buildComparisonHistorySyncPreferenceState, formatComparisonHistorySyncPreferenceFieldValue, hasComparisonHistorySyncPreferenceFieldDifference, buildDefaultComparisonHistorySyncPreferenceSelectedSources, buildComparisonHistorySyncPreferenceReview, buildComparisonHistorySyncPreferenceReviewRows, formatComparisonHistorySyncPreferenceResolutionSummary, resolveComparisonHistorySyncPreferenceReview } from "./ControlRoomViewComparisonNormalize";
import { loadLegacyExpandedGapRows, filterExpandedGapRows, normalizeControlRoomComparisonSelection, isSameComparisonSelection, formatComparisonHistoryPanelEntryMeta, matchesComparisonHistoryPanelEntry, formatComparisonHistorySyncAuditKindLabel, buildComparisonHistoryStepDescriptor, resolveComparisonHistoryRunLabel, normalizeComparisonRunIdList, normalizeComparisonIntent, normalizeComparisonScoreSection, normalizeComparisonScoreLinkSource, normalizeComparisonScoreLinkSubFocusKey, normalizeComparisonScoreLinkExpandedState, normalizeComparisonScoreLinkTooltipKey, normalizeComparisonScoreLinkArtifactLineDetailView, normalizeComparisonScoreLinkArtifactLineMicroView, normalizeComparisonScoreLinkArtifactLineNotePage, normalizeComparisonScoreLinkArtifactLineDetailHoverKey, normalizeComparisonScoreLinkArtifactLineScrubStep, normalizeComparisonScoreLinkArtifactHoverKey, normalizeComparisonScoreLinkTarget, isControlRoomUiStateV1, isControlRoomUiStateV2, isControlRoomUiStateV3, isControlRoomUiStateV4, buildRunsPath, buildRunComparisonPath, normalizeRunHistoryFilter, normalizeRunHistoryPresetFilter, getStrategyVersionOptions, pickLatestBenchmarkRun } from "./ControlRoomViewRunFilters";
import { StrategyColumn, ReferenceCatalog, PresetStructuredDiffPreview, PresetCatalogPanel, RunForm, ExperimentMetadataPills } from "./ControlRoomViewCatalogPanels";
import { RunListBoundarySurfaceContract, RunListBoundaryGroupContract, RunSurfaceCapabilityDiscoveryPanel, Metric, formatMetric, formatLineagePosture, formatLineageIndicator, formatComparisonScoreValue } from "./ControlRoomViewCapabilities";
import { buildComparisonScoreHighlights, buildComparisonScoreDetailRows, formatComparisonScoreHighlight, formatComparisonScoreComponentLabel, formatComparisonScoreLinkSourceLabel, encodeComparisonScoreLinkToken, decodeComparisonScoreLinkToken, buildComparisonProvenanceLineSubFocusKey, buildComparisonRunCardLineSubFocusKey, buildComparisonRunListLineSubFocusKey, buildComparisonRunListOrderPreviewSubFocusKey, buildComparisonRunListDataSymbolSubFocusKey, buildComparisonProvenanceArtifactSubFocusKey, buildComparisonProvenanceArtifactSectionSubFocusKey, buildComparisonProvenanceArtifactSummaryHoverKey, buildComparisonProvenanceArtifactSectionLineHoverKey, buildComparisonProvenanceArtifactLineDetailHoverKey, buildComparisonMetricTooltipKey, formatComparisonScoreLinkSubFocusLabel, formatComparisonScoreLinkTooltipLabel, formatComparisonScoreLinkArtifactHoverLabel, formatComparisonScoreLinkArtifactLineDetailViewLabel, formatComparisonScoreLinkArtifactLineMicroViewLabel, formatComparisonScoreLinkArtifactLineDetailHoverLabel, formatComparisonScoreComponentDetail, buildComparisonScoreComponentDetails, formatComparisonScoreComponentRawValue, formatComparisonScoreSignedValue, getComparisonScoreLinkedRunRole, isSameComparisonScoreLinkTarget, isSameComparisonScoreLinkSurface, resolveComparisonScoreDrillBackTarget, isComparisonScoreLinkMatch, formatEditableNumber } from "./ControlRoomViewComparisonLinks";
import { formatFixedNumber, buildLiveOrderDraftKey, formatComparisonMetric, formatComparisonDelta, formatComparisonNarrativeLabel, formatComparisonIntentLabel, formatComparisonIntentLegend, formatComparisonIntentTooltip, formatComparisonCueTooltip, buildComparisonCellTooltip, getComparisonIntentClassName, formatLaneLabel, formatVersionLineage, extractDefaultParameters, formatParameterMap, formatParameterValue, summarizeRunNotes } from "./ControlRoomViewFormatting";
import { listComparisonHistoryExpandedGapRowKeys, listComparisonHistoryExpandedGapRowDiffKeys, buildComparisonHistoryExpandedGapRowSelectionKey, parseComparisonHistoryExpandedGapRowSelectionKey, buildComparisonHistoryExpandedGapWindowSelectionKey, parseComparisonHistoryExpandedGapWindowSelectionKey, listComparisonHistoryExpandedGapWindowDiffKeys, isSameComparisonHistoryExpandedGapRows, isSameExpandedGapWindowSelections, formatComparisonHistoryExpandedGapRowKey, formatComparisonHistoryExpandedGapRowsValue, formatComparisonHistoryExpandedGapRowsDiffValue, formatComparisonHistorySyncWorkspaceSelectionKeyLabel, rankComparisonHistorySyncWorkspaceSelectionKey, ComparisonHistorySyncWorkspaceSemanticRanking, listComparisonHistorySyncWorkspaceDiffSelectionKeys, resolveComparisonHistorySyncWorkspaceFieldSource, listComparisonHistorySyncWorkspaceConflictSelectionKeys, scoreComparisonHistorySyncWorkspaceCandidateSource, sortComparisonHistorySyncWorkspaceSemanticSignals, rankComparisonHistorySyncWorkspaceFieldSemantics, buildComparisonHistorySyncWorkspaceRecommendedSources, summarizeComparisonHistorySyncWorkspaceChanges } from "./ControlRoomViewComparisonWorkspaceSignals";
export function buildComparisonHistorySyncWorkspaceState(state: {
  comparisonSelection: ControlRoomComparisonSelectionState;
  expandedGapRows: Record<string, boolean>;
  expandedGapWindowSelections: ExpandedGapWindowSelections;
}): ComparisonHistorySyncWorkspaceState {
  return {
    comparisonSelection: normalizeControlRoomComparisonSelection(state.comparisonSelection),
    expandedGapRows: filterExpandedGapRows(state.expandedGapRows),
    expandedGapWindowSelections: filterExpandedGapWindowSelections(state.expandedGapWindowSelections),
  };
}

export function formatComparisonHistorySyncWorkspaceFieldValue(
  fieldKey: ComparisonHistorySyncWorkspaceReviewSelectionKey,
  state: ComparisonHistorySyncWorkspaceState,
) {
  const expandedGapWindowSelection = parseComparisonHistoryExpandedGapWindowSelectionKey(fieldKey);
  if (expandedGapWindowSelection) {
    return (state.expandedGapWindowSelections[expandedGapWindowSelection.rowKey] ?? []).includes(
      expandedGapWindowSelection.windowKey,
    )
      ? "Visible"
      : "Hidden";
  }
  const expandedGapRowKey = parseComparisonHistoryExpandedGapRowSelectionKey(fieldKey);
  if (expandedGapRowKey) {
    return state.expandedGapRows[expandedGapRowKey] ? "Expanded" : "Collapsed";
  }
  switch (fieldKey) {
    case "comparisonSelection.intent":
      return formatComparisonIntentLabel(state.comparisonSelection.intent);
    case "comparisonSelection.selectedRunIds":
      return formatComparisonHistorySyncConflictRunSelectionValue(state.comparisonSelection.selectedRunIds);
    case "comparisonSelection.scoreLink":
      return formatComparisonHistorySyncConflictScoreLinkValue(state.comparisonSelection.scoreLink);
    case "expandedGapRows":
      return formatComparisonHistoryExpandedGapRowsValue(state.expandedGapRows);
    default:
      return "n/a";
  }
}

export function hasComparisonHistorySyncWorkspaceFieldDifference(
  fieldKey: ComparisonHistorySyncWorkspaceReviewSelectionKey,
  localState: ComparisonHistorySyncWorkspaceState,
  remoteState: ComparisonHistorySyncWorkspaceState,
) {
  const expandedGapWindowSelection = parseComparisonHistoryExpandedGapWindowSelectionKey(fieldKey);
  if (expandedGapWindowSelection) {
    return (localState.expandedGapWindowSelections[expandedGapWindowSelection.rowKey] ?? []).includes(
      expandedGapWindowSelection.windowKey,
    )
      !== (remoteState.expandedGapWindowSelections[expandedGapWindowSelection.rowKey] ?? []).includes(
        expandedGapWindowSelection.windowKey,
      );
  }
  const expandedGapRowKey = parseComparisonHistoryExpandedGapRowSelectionKey(fieldKey);
  if (expandedGapRowKey) {
    return Boolean(localState.expandedGapRows[expandedGapRowKey])
      !== Boolean(remoteState.expandedGapRows[expandedGapRowKey]);
  }
  switch (fieldKey) {
    case "comparisonSelection.intent":
      return localState.comparisonSelection.intent !== remoteState.comparisonSelection.intent;
    case "comparisonSelection.selectedRunIds":
      return !(
        localState.comparisonSelection.selectedRunIds.length
          === remoteState.comparisonSelection.selectedRunIds.length
        && localState.comparisonSelection.selectedRunIds.every(
          (runId, index) => runId === remoteState.comparisonSelection.selectedRunIds[index],
        )
      );
    case "comparisonSelection.scoreLink":
      return !(
        localState.comparisonSelection.scoreLink?.narrativeRunId
          === remoteState.comparisonSelection.scoreLink?.narrativeRunId
        && localState.comparisonSelection.scoreLink?.section
          === remoteState.comparisonSelection.scoreLink?.section
        && localState.comparisonSelection.scoreLink?.componentKey
          === remoteState.comparisonSelection.scoreLink?.componentKey
      );
    case "expandedGapRows":
      return !isSameComparisonHistoryExpandedGapRows(
        localState.expandedGapRows,
        remoteState.expandedGapRows,
      );
    default:
      return false;
  }
}

export function buildDefaultComparisonHistorySyncWorkspaceSelectedSources(
  localState: ComparisonHistorySyncWorkspaceState,
  remoteState: ComparisonHistorySyncWorkspaceState,
) {
  return buildComparisonHistorySyncWorkspaceRecommendedSources(localState, remoteState);
}

export function buildComparisonHistorySyncWorkspaceReview(state: {
  localComparisonSelection: ControlRoomComparisonSelectionState;
  remoteComparisonSelection: ControlRoomComparisonSelectionState;
  localExpandedGapRows: Record<string, boolean>;
  remoteExpandedGapRows: Record<string, boolean>;
  localExpandedGapWindowSelections: ExpandedGapWindowSelections;
  remoteExpandedGapWindowSelections: ExpandedGapWindowSelections;
}): ComparisonHistorySyncWorkspaceReview {
  const localState = buildComparisonHistorySyncWorkspaceState({
    comparisonSelection: state.localComparisonSelection,
    expandedGapRows: state.localExpandedGapRows,
    expandedGapWindowSelections: state.localExpandedGapWindowSelections,
  });
  const remoteState = buildComparisonHistorySyncWorkspaceState({
    comparisonSelection: state.remoteComparisonSelection,
    expandedGapRows: state.remoteExpandedGapRows,
    expandedGapWindowSelections: state.remoteExpandedGapWindowSelections,
  });
  return {
    localState,
    remoteState,
    selectedSources: buildDefaultComparisonHistorySyncWorkspaceSelectedSources(localState, remoteState),
    resolvedAt: null,
    resolutionSummary: null,
  };
}

export function buildComparisonHistorySyncWorkspaceReviewRows(
  review: ComparisonHistorySyncWorkspaceReview,
  latestLocalState?: ComparisonHistorySyncWorkspaceState,
): ComparisonHistorySyncWorkspaceReviewRow[] {
  const effectiveLocalState = latestLocalState ?? review.localState;
  const rows: ComparisonHistorySyncWorkspaceReviewRow[] = [];
  const pushWorkspaceRow = (
    fieldKey: ComparisonHistorySyncWorkspaceReviewSelectionKey,
    label: string,
  ) => {
    const localSnapshotValue = formatComparisonHistorySyncWorkspaceFieldValue(fieldKey, review.localState);
    const localValue = formatComparisonHistorySyncWorkspaceFieldValue(fieldKey, effectiveLocalState);
    const hasLatestLocalDrift =
      Boolean(latestLocalState)
      && hasComparisonHistorySyncWorkspaceFieldDifference(fieldKey, review.localState, effectiveLocalState);
    const semanticRanking = rankComparisonHistorySyncWorkspaceFieldSemantics({
      fieldKey,
      auditLocalState: review.localState,
      effectiveLocalState,
      remoteState: review.remoteState,
    });
    rows.push({
      fieldKey,
      hasLatestLocalDrift,
      label,
      localHint: hasLatestLocalDrift ? `Audit snapshot: ${localSnapshotValue}` : null,
      localScore: semanticRanking.localScore,
      localSignals: semanticRanking.localSignals,
      localValue,
      remoteScore: semanticRanking.remoteScore,
      remoteSignals: semanticRanking.remoteSignals,
      remoteValue: formatComparisonHistorySyncWorkspaceFieldValue(fieldKey, review.remoteState),
      recommendedSource: semanticRanking.recommendedSource,
      recommendationReason: semanticRanking.recommendationReason,
      recommendationStrength: semanticRanking.recommendationStrength,
      semanticRank: rankComparisonHistorySyncWorkspaceSelectionKey(fieldKey)
        + semanticRanking.recommendationStrength,
      selectedSource: resolveComparisonHistorySyncWorkspaceFieldSource(review, fieldKey),
    });
  };
  COMPARISON_HISTORY_SYNC_WORKSPACE_FIELD_DEFINITIONS.forEach((definition) => {
    if (
      definition.fieldKey === "expandedGapRows"
      || !hasComparisonHistorySyncWorkspaceFieldDifference(
        definition.fieldKey,
        review.localState,
        review.remoteState,
      )
    ) {
      return;
    }
    pushWorkspaceRow(definition.fieldKey, definition.label);
  });
  listComparisonHistoryExpandedGapRowDiffKeys(
    review.localState.expandedGapRows,
    review.remoteState.expandedGapRows,
  ).forEach((key) => {
    const fieldKey = buildComparisonHistoryExpandedGapRowSelectionKey(key);
    pushWorkspaceRow(fieldKey, formatComparisonHistorySyncWorkspaceSelectionKeyLabel(fieldKey));
  });
  [...new Set([
    ...Object.keys(review.localState.expandedGapWindowSelections),
    ...Object.keys(review.remoteState.expandedGapWindowSelections),
  ])].forEach((rowKey) => {
    listComparisonHistoryExpandedGapWindowDiffKeys(
      review.localState.expandedGapWindowSelections,
      review.remoteState.expandedGapWindowSelections,
      rowKey,
    ).forEach((windowKey) => {
      const fieldKey = buildComparisonHistoryExpandedGapWindowSelectionKey(rowKey, windowKey);
      pushWorkspaceRow(fieldKey, formatComparisonHistorySyncWorkspaceSelectionKeyLabel(fieldKey));
    });
  });
  return rows.sort((left, right) => (
    Number(right.hasLatestLocalDrift) - Number(left.hasLatestLocalDrift)
    || right.recommendationStrength - left.recommendationStrength
    || right.semanticRank - left.semanticRank
    || left.label.localeCompare(right.label)
  ));
}

export function buildComparisonHistorySyncWorkspaceRecommendationOverview(
  rows: ComparisonHistorySyncWorkspaceReviewRow[],
): ComparisonHistorySyncWorkspaceRecommendationOverview {
  const rankedRows = [...rows].sort((left, right) => (
    right.recommendationStrength - left.recommendationStrength
    || Number(right.hasLatestLocalDrift) - Number(left.hasLatestLocalDrift)
    || right.semanticRank - left.semanticRank
    || left.label.localeCompare(right.label)
  ));
  const topLocal = rankedRows
    .filter((row) => row.recommendedSource === "local")
    .slice(0, 2);
  const topRemote = rankedRows
    .filter((row) => row.recommendedSource === "remote")
    .slice(0, 2);
  return {
    totalFieldCount: rows.length,
    localCount: rows.filter((row) => row.recommendedSource === "local").length,
    remoteCount: rows.filter((row) => row.recommendedSource === "remote").length,
    latestLocalDriftCount: rows.filter((row) => row.hasLatestLocalDrift).length,
    rankedDiffCount: rows.filter((row) => row.selectedSource !== row.recommendedSource).length,
    strongest: rankedRows[0] ?? null,
    topLocal,
    topRemote,
  };
}

export function formatComparisonHistorySyncWorkspaceResolutionSummary(
  review: ComparisonHistorySyncWorkspaceReview,
  latestLocalState?: ComparisonHistorySyncWorkspaceState,
) {
  const selectedFields = Object.entries(review.selectedSources) as Array<
    [ComparisonHistorySyncWorkspaceReviewSelectionKey, ComparisonHistorySyncConflictFieldSource]
  >;
  const localFields = selectedFields
    .filter(([, source]) => source === "local")
    .map(([fieldKey]) => formatComparisonHistorySyncWorkspaceSelectionKeyLabel(fieldKey));
  const remoteFields = selectedFields
    .filter(([, source]) => source === "remote")
    .map(([fieldKey]) => formatComparisonHistorySyncWorkspaceSelectionKeyLabel(fieldKey));
  const parts: string[] = [];
  if (!selectedFields.length) {
    parts.push("Kept remote workspace values for all fields.");
  }
  if (localFields.length) {
    parts.push(`Local: ${localFields.join(", ")}`);
  }
  if (remoteFields.length) {
    parts.push(`Remote: ${remoteFields.join(", ")}`);
  }
  if (latestLocalState) {
    const latestLocalDriftCount = listComparisonHistorySyncWorkspaceConflictSelectionKeys(review)
      .filter((fieldKey) =>
        resolveComparisonHistorySyncWorkspaceFieldSource(review, fieldKey) === "local"
        && hasComparisonHistorySyncWorkspaceFieldDifference(fieldKey, review.localState, latestLocalState),
      ).length;
    if (latestLocalDriftCount > 0) {
      parts.push(
        `Latest local drift kept for ${latestLocalDriftCount} field${latestLocalDriftCount === 1 ? "" : "s"}`,
      );
    }
    parts.push("3-way merge keeps current local workspace outside remote-selected fields");
  }
  return parts.join(" · ");
}

export function resolveComparisonHistorySyncWorkspaceReview(
  review: ComparisonHistorySyncWorkspaceReview,
  latestLocalState?: ComparisonHistorySyncWorkspaceState,
): ComparisonHistorySyncWorkspaceState {
  const effectiveLocalState = latestLocalState ?? review.localState;
  const resolvedSelection = normalizeControlRoomComparisonSelection(effectiveLocalState.comparisonSelection);
  if (resolveComparisonHistorySyncWorkspaceFieldSource(review, "comparisonSelection.intent") === "remote") {
    resolvedSelection.intent = review.remoteState.comparisonSelection.intent;
  }
  if (
    resolveComparisonHistorySyncWorkspaceFieldSource(review, "comparisonSelection.selectedRunIds")
    === "remote"
  ) {
    resolvedSelection.selectedRunIds = [...review.remoteState.comparisonSelection.selectedRunIds];
  }
  if (resolveComparisonHistorySyncWorkspaceFieldSource(review, "comparisonSelection.scoreLink") === "remote") {
    resolvedSelection.scoreLink = review.remoteState.comparisonSelection.scoreLink
      ? { ...review.remoteState.comparisonSelection.scoreLink }
      : null;
  }
  const auditLocalExpandedGapRows = filterExpandedGapRows(review.localState.expandedGapRows);
  const localExpandedGapRows = filterExpandedGapRows(effectiveLocalState.expandedGapRows);
  const remoteExpandedGapRows = filterExpandedGapRows(review.remoteState.expandedGapRows);
  const auditLocalExpandedGapWindowSelections = filterExpandedGapWindowSelections(
    review.localState.expandedGapWindowSelections,
  );
  const localExpandedGapWindowSelections = filterExpandedGapWindowSelections(
    effectiveLocalState.expandedGapWindowSelections,
  );
  const remoteExpandedGapWindowSelections = filterExpandedGapWindowSelections(
    review.remoteState.expandedGapWindowSelections,
  );
  const resolvedExpandedGapRows = { ...localExpandedGapRows };
  const resolvedExpandedGapWindowSelections = { ...localExpandedGapWindowSelections };
  listComparisonHistoryExpandedGapRowDiffKeys(
    auditLocalExpandedGapRows,
    remoteExpandedGapRows,
  ).forEach((key) => {
    const fieldKey = buildComparisonHistoryExpandedGapRowSelectionKey(key);
    if (resolveComparisonHistorySyncWorkspaceFieldSource(review, fieldKey) !== "remote") {
      return;
    }
    if (remoteExpandedGapRows[key]) {
      resolvedExpandedGapRows[key] = true;
      return;
    }
    delete resolvedExpandedGapRows[key];
  });
  new Set([
    ...Object.keys(auditLocalExpandedGapWindowSelections),
    ...Object.keys(remoteExpandedGapWindowSelections),
  ]).forEach((rowKey) => {
    listComparisonHistoryExpandedGapWindowDiffKeys(
      auditLocalExpandedGapWindowSelections,
      remoteExpandedGapWindowSelections,
      rowKey,
    ).forEach((windowKey) => {
      const fieldKey = buildComparisonHistoryExpandedGapWindowSelectionKey(rowKey, windowKey);
      if (resolveComparisonHistorySyncWorkspaceFieldSource(review, fieldKey) !== "remote") {
        return;
      }
      const nextSelections = new Set(resolvedExpandedGapWindowSelections[rowKey] ?? []);
      if ((remoteExpandedGapWindowSelections[rowKey] ?? []).includes(windowKey)) {
        nextSelections.add(windowKey);
      } else {
        nextSelections.delete(windowKey);
      }
      if (nextSelections.size) {
        resolvedExpandedGapWindowSelections[rowKey] = [...nextSelections].sort();
        return;
      }
      delete resolvedExpandedGapWindowSelections[rowKey];
    });
    if (!resolvedExpandedGapWindowSelections[rowKey]?.length) {
      delete resolvedExpandedGapWindowSelections[rowKey];
    }
  });
  return {
    comparisonSelection: normalizeControlRoomComparisonSelection(resolvedSelection),
    expandedGapRows: resolvedExpandedGapRows,
    expandedGapWindowSelections: resolvedExpandedGapWindowSelections,
  };
}

export function buildComparisonHistorySyncAuditEntries(state: {
  localPanel: ComparisonHistoryPanelState;
  remotePanel: ComparisonHistoryPanelState;
  localComparisonSelection: ControlRoomComparisonSelectionState;
  remoteComparisonSelection: ControlRoomComparisonSelectionState;
  localExpandedGapRows: Record<string, boolean>;
  remoteExpandedGapRows: Record<string, boolean>;
  localExpandedGapWindowSelections: ExpandedGapWindowSelections;
  remoteExpandedGapWindowSelections: ExpandedGapWindowSelections;
  localOpen: boolean;
  remoteOpen: boolean;
  localSearchQuery: string;
  remoteSearchQuery: string;
  localShowPinnedOnly: boolean;
  remoteShowPinnedOnly: boolean;
  localAuditFilter: ComparisonHistorySyncAuditFilter;
  remoteAuditFilter: ComparisonHistorySyncAuditFilter;
  localShowResolvedAuditEntries: boolean;
  remoteShowResolvedAuditEntries: boolean;
  remoteSync: ComparisonHistoryPanelSyncState | null;
}): ComparisonHistorySyncAuditEntry[] {
  const sourceTabId = state.remoteSync?.tabId ?? "unknown";
  const sourceTabLabel = state.remoteSync?.tabLabel ?? "Remote tab";
  const recordedAt = new Date().toISOString();
  const localEntriesById = new Map(
    state.localPanel.entries.map((entry) => [entry.entryId, entry]),
  );
  const remoteAdditions = state.remotePanel.entries.filter(
    (entry) => !entry.hidden && !localEntriesById.has(entry.entryId),
  );
  const conflictingEntries = state.remotePanel.entries.flatMap((remoteEntry) => {
    const localEntry = localEntriesById.get(remoteEntry.entryId);
    if (!localEntry) {
      return [];
    }
    const fields = getComparisonHistoryPanelEntryChangedFields(localEntry, remoteEntry);
    return fields.length ? [{ localEntry, remoteEntry, fields }] : [];
  });
  const preferenceChanges = summarizeComparisonHistorySyncPreferenceChanges({
    localOpen: state.localOpen,
    remoteOpen: state.remoteOpen,
    localSearchQuery: state.localSearchQuery,
    remoteSearchQuery: state.remoteSearchQuery,
    localShowPinnedOnly: state.localShowPinnedOnly,
    remoteShowPinnedOnly: state.remoteShowPinnedOnly,
    localAuditFilter: state.localAuditFilter,
    remoteAuditFilter: state.remoteAuditFilter,
    localShowResolvedAuditEntries: state.localShowResolvedAuditEntries,
    remoteShowResolvedAuditEntries: state.remoteShowResolvedAuditEntries,
  });
  const workspaceChanges = summarizeComparisonHistorySyncWorkspaceChanges({
    localComparisonSelection: state.localComparisonSelection,
    remoteComparisonSelection: state.remoteComparisonSelection,
    localExpandedGapRows: state.localExpandedGapRows,
    remoteExpandedGapRows: state.remoteExpandedGapRows,
    localExpandedGapWindowSelections: state.localExpandedGapWindowSelections,
    remoteExpandedGapWindowSelections: state.remoteExpandedGapWindowSelections,
  });
  const nextEntries: ComparisonHistorySyncAuditEntry[] = [];
  if (remoteAdditions.length) {
    const labels = remoteAdditions
      .slice(0, 2)
      .map((entry) => entry.label)
      .join(" · ");
    const remainderCount = Math.max(remoteAdditions.length - 2, 0);
    nextEntries.push({
      auditId: buildComparisonHistorySyncAuditId(),
      kind: "merge",
      summary: `Merged ${remoteAdditions.length} step${remoteAdditions.length === 1 ? "" : "s"} from ${sourceTabLabel}`,
      detail: remainderCount > 0 ? `${labels} +${remainderCount} more` : labels,
      recordedAt,
      sourceTabId,
      sourceTabLabel,
    });
  }
  conflictingEntries.forEach(({ localEntry, remoteEntry, fields }) => {
    nextEntries.push({
      auditId: buildComparisonHistorySyncAuditId(),
      kind: "conflict",
      summary: `Review conflict on ${remoteEntry.label}`,
      detail: summarizeComparisonHistoryPanelEntryConflict(remoteEntry, fields),
      recordedAt,
      sourceTabId,
      sourceTabLabel,
      conflictReview: buildComparisonHistorySyncConflictReview(localEntry, remoteEntry),
    });
  });
  if (workspaceChanges.length) {
    nextEntries.push({
      auditId: buildComparisonHistorySyncAuditId(),
      kind: "workspace",
      summary: `Review workspace state from ${sourceTabLabel}`,
      detail: workspaceChanges.join(" · "),
      recordedAt,
      sourceTabId,
      sourceTabLabel,
      workspaceReview: buildComparisonHistorySyncWorkspaceReview({
        localComparisonSelection: state.localComparisonSelection,
        remoteComparisonSelection: state.remoteComparisonSelection,
        localExpandedGapRows: state.localExpandedGapRows,
        remoteExpandedGapRows: state.remoteExpandedGapRows,
        localExpandedGapWindowSelections: state.localExpandedGapWindowSelections,
        remoteExpandedGapWindowSelections: state.remoteExpandedGapWindowSelections,
      }),
    });
  }
  if (preferenceChanges.length) {
    nextEntries.push({
      auditId: buildComparisonHistorySyncAuditId(),
      kind: "preferences",
      summary: `Review browser state from ${sourceTabLabel}`,
      detail: preferenceChanges.join(" · "),
      recordedAt,
      sourceTabId,
      sourceTabLabel,
      preferenceReview: buildComparisonHistorySyncPreferenceReview({
        localOpen: state.localOpen,
        remoteOpen: state.remoteOpen,
        localSearchQuery: state.localSearchQuery,
        remoteSearchQuery: state.remoteSearchQuery,
        localShowPinnedOnly: state.localShowPinnedOnly,
        remoteShowPinnedOnly: state.remoteShowPinnedOnly,
        localAuditFilter: state.localAuditFilter,
        remoteAuditFilter: state.remoteAuditFilter,
        localShowResolvedAuditEntries: state.localShowResolvedAuditEntries,
        remoteShowResolvedAuditEntries: state.remoteShowResolvedAuditEntries,
      }),
    });
  }
  return nextEntries;
}
