// @ts-nocheck

import { CSSProperties, FormEvent, KeyboardEvent, MouseEvent, PointerEvent, ReactNode, forwardRef, useCallback, useEffect, useId, useLayoutEffect, useMemo, useRef, useState, AKRA_TOUCH_FEEDBACK_BRIDGE_VERSION, AKRA_TOUCH_FEEDBACK_EVENT_NAME, AkraTouchFeedbackDetail, AkraTouchFeedbackEnvelope, triggerAkraTouchFeedbackBridge, WorkspaceShell, buildControlWorkspaceDescriptors, ControlWorkspaceDescriptor, ControlStripMetric, useWorkspaceRoute, WorkspaceRouteContent, buildRunHistoryWorkspacePanels, LiveOrderReplacementDraft, RunHistoryWorkspaceSectionProps, RunOrderControls, getRunListBoundaryContractSnapshot, getRunListBoundarySurfaceLabel, getRunSurfaceCapabilityFamily, getRunSurfaceCapabilityFamilyOrder, getRunSurfaceCapabilityGroupOrder, getRunSurfaceCapabilitySchemaContract, getRunSurfaceCollectionQueryContracts, getRunSurfaceSharedContracts, getRunSurfaceSubresourceContracts, RunListComparisonBoundaryNote, shouldEnableStrategyProvenanceSemantics, shouldEnableRunListMetricDrillBack, shouldEnableRunSnapshotSemantics, shouldEnableStrategyCatalogSchemaHints, shouldHydratePresetParameterDefaults, shouldRenderOrderActionBoundaryNote, shouldRenderWorkflowControlBoundaryNote, RunSurfaceCollectionQueryBuilder, formatComparisonTooltipTuningDelta, formatComparisonTooltipTuningValue, formatRelativeTimestampLabel, RunSection, RunSurfaceCollectionQueryBuilderApplyPayload, RunSurfaceCollectionQueryRuntimeCandidateContextSelection, RunSurfaceCollectionQueryRuntimeCandidateSample, applyProviderProvenanceSchedulerStitchedReportGovernancePlan, applyProviderProvenanceSchedulerNarrativeGovernancePlan, approveProviderProvenanceSchedulerStitchedReportGovernancePlan, approveProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceAnalyticsPreset, createProviderProvenanceDashboardView, createProviderProvenanceExportJob, createProviderProvenanceSchedulerStitchedReportGovernanceRegistry, createProviderProvenanceSchedulerStitchedReportGovernancePlan, createProviderProvenanceSchedulerStitchedReportView, createProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, captureProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchy, createProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, createProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceSchedulerNarrativeRegistryEntry, createProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceScheduledReport, approveProviderProvenanceExportJob, applyProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, deleteProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, deleteProviderProvenanceSchedulerNarrativeRegistryEntry, deleteProviderProvenanceSchedulerStitchedReportView, deleteProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, createRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, createRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, downloadProviderProvenanceExportJob, downloadRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, escalateProviderProvenanceExportJob, exportProviderProvenanceSchedulerHealth, exportProviderProvenanceSchedulerStitchedNarrativeReport, reconstructProviderProvenanceSchedulerHealthExport, exportRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, fetchJson, getProviderProvenanceExportAnalytics, getProviderProvenanceExportJobHistory, getProviderProvenanceSchedulerHealthAnalytics, getProviderProvenanceScheduledReportHistory, getRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobHistory, listProviderProvenanceAnalyticsPresets, listProviderProvenanceDashboardViews, listProviderProvenanceSchedulerStitchedReportViews, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogs, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplates, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePlans, listProviderProvenanceSchedulerNarrativeRegistryEntries, listProviderProvenanceSchedulerNarrativeRegistryRevisions, listProviderProvenanceSchedulerNarrativeTemplates, listProviderProvenanceSchedulerNarrativeTemplateRevisions, listProviderProvenanceSchedulerStitchedReportGovernancePolicyCatalogs, listProviderProvenanceSchedulerStitchedReportGovernancePolicyTemplates, listProviderProvenanceSchedulerStitchedReportGovernancePlans, rollbackProviderProvenanceSchedulerStitchedReportGovernancePlan, rollbackProviderProvenanceSchedulerNarrativeGovernancePlan, listMarketDataIngestionJobs, listMarketDataLineageHistory, listProviderProvenanceExportJobs, listProviderProvenanceSchedulerAlertHistory, listProviderProvenanceSchedulerHealthHistory, listProviderProvenanceSchedulerStitchedReportGovernanceRegistries, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryAudits, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisions, listProviderProvenanceSchedulerStitchedReportViewAudits, listProviderProvenanceSchedulerStitchedReportViewRevisions, getProviderProvenanceSchedulerSearchDashboard, bulkGovernProviderProvenanceSchedulerSearchModerationPolicyCatalogs, bulkGovernProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, createProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicy, createProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, listProviderProvenanceSchedulerSearchModerationPolicyCatalogs, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlans, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAudits, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisions, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePlans, listProviderProvenanceSchedulerSearchModerationPolicyCatalogAudits, listProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisions, listProviderProvenanceSchedulerSearchModerationPlans, listProviderProvenanceScheduledReports, listRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, listRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, approveProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, approveProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, approveProviderProvenanceSchedulerSearchModerationPlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, applyProviderProvenanceSchedulerSearchModerationPlan, createProviderProvenanceSchedulerSearchModerationPolicyCatalog, deleteProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, deleteProviderProvenanceSchedulerSearchModerationPolicyCatalog, moderateProviderProvenanceSchedulerSearchFeedbackBatch, moderateProviderProvenanceSchedulerSearchFeedback, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, recordProviderProvenanceSchedulerSearchFeedback, resolveRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevision, restoreProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevision, restoreProviderProvenanceSchedulerSearchModerationPolicyCatalogRevision, restoreProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevision, restoreProviderProvenanceSchedulerNarrativeRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportViewRevision, restoreProviderProvenanceSchedulerNarrativeTemplateRevision, revokeRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, runProviderProvenanceSchedulerNarrativeGovernancePlanBatchAction, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkGovernance, stageProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, stageProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, stageProviderProvenanceSchedulerSearchModerationPlan, updateProviderProvenanceSchedulerSearchModerationPolicyCatalog, updateProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, stageProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, runDueProviderProvenanceScheduledReports, runProviderProvenanceScheduledReport, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStep, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, updateProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, updateProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, updateProviderProvenanceSchedulerNarrativeRegistryEntry, updateProviderProvenanceSchedulerStitchedReportGovernanceRegistry, updateProviderProvenanceSchedulerStitchedReportView, updateProviderProvenanceSchedulerNarrativeTemplate, updateProviderProvenanceExportJobPolicy, deleteProviderProvenanceSchedulerStitchedReportGovernanceRegistry, ALL_FILTER_VALUE, apiBase, COMPARISON_FOCUS_ARTIFACT_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_MICRO_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_NOTE_PAGE_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_SCRUB_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_COMPONENT_SEARCH_PARAM, COMPARISON_FOCUS_DETAIL_SEARCH_PARAM, COMPARISON_FOCUS_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ORIGIN_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_SECTION_SEARCH_PARAM, COMPARISON_FOCUS_SOURCE_SEARCH_PARAM, COMPARISON_FOCUS_TOOLTIP_SEARCH_PARAM, COMPARISON_HISTORY_BROWSER_STATE_KEY, COMPARISON_HISTORY_BROWSER_STATE_VERSION, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_KEY, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_VERSION, COMPARISON_HISTORY_SYNC_CONFLICT_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_PREFERENCE_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_WORKSPACE_FIELD_DEFINITIONS, COMPARISON_HISTORY_TAB_ID_SESSION_KEY, COMPARISON_INTENT_SEARCH_PARAM, COMPARISON_RUN_ID_SEARCH_PARAM, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_KEY, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_VERSION, COMPARISON_TOOLTIP_TUNING_GROUPS, COMPARISON_TOOLTIP_TUNING_LABELS, COMPARISON_TOOLTIP_TUNING_SHARE_PARAM, COMPARISON_TOOLTIP_TUNING_STORAGE_KEY, COMPARISON_TOOLTIP_TUNING_STORAGE_VERSION, COMPARISON_TOOLTIP_UNCHANGED_GROUP_COLLAPSE_THRESHOLD, CONTROL_ROOM_UI_STATE_STORAGE_KEY, CONTROL_ROOM_UI_STATE_VERSION, DEFAULT_COMPARISON_TOOLTIP_PRESET_IMPORT_CONFLICT_POLICY, DEFAULT_COMPARISON_TOOLTIP_TUNING, DEFAULT_CONTROL_ROOM_DOCUMENT_TITLE, LEGACY_GAP_WINDOW_EXPANSION_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_VERSION, MAX_COMPARISON_HISTORY_PANEL_ENTRIES, MAX_COMPARISON_HISTORY_SYNC_AUDIT_ENTRIES, MAX_COMPARISON_RUNS, MAX_MARKET_DATA_PROVENANCE_EXPORT_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_REVIEWED_CONFLICT_KEYS, MAX_VISIBLE_COMPARISON_TOOLTIP_CONFLICT_SESSION_SUMMARIES, MAX_VISIBLE_GAP_WINDOWS, PRESET_PROFILE_AGGRESSIVENESS_RANKS, PRESET_PROFILE_CONFIDENCE_RANKS, PRESET_PROFILE_SPEED_RANKS, PRESET_TIMEFRAME_UNIT_TO_MINUTES, REPLAY_INTENT_ACTION_FILTER_SEARCH_PARAM, REPLAY_INTENT_ALIAS_SEARCH_PARAM, REPLAY_INTENT_EDGE_FILTER_SEARCH_PARAM, REPLAY_INTENT_GROUP_FILTER_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_DIFF_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_GROUP_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_TRACE_SEARCH_PARAM, REPLAY_INTENT_SCOPE_SEARCH_PARAM, REPLAY_INTENT_SEARCH_PARAM, REPLAY_INTENT_STEP_SEARCH_PARAM, REPLAY_INTENT_TEMPLATE_SEARCH_PARAM, RUN_HISTORY_SAVED_FILTER_STORAGE_KEY_PREFIX, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_TAB_ID_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_BROWSER_STATE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_PAYLOAD_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_SIGNING_SECRET_STORAGE_KEY, SHOW_COMPARISON_TOOLTIP_TUNING_PANEL, TOUCH_GAP_WINDOW_SWEEP_HOLD_MS, TOUCH_GAP_WINDOW_SWEEP_MOVE_TOLERANCE_PX, BenchmarkArtifact, ParameterSchema, ComparisonCueKind, ComparisonHistoryBrowserState, ComparisonHistoryPanelEntry, ComparisonHistoryPanelState, ComparisonHistoryPanelSyncState, ComparisonHistoryStepDescriptor, ComparisonHistorySyncAuditEntry, ComparisonHistorySyncAuditFilter, ComparisonHistorySyncAuditKind, ComparisonHistorySyncAuditTrailState, ComparisonHistorySyncConflictFieldKey, ComparisonHistorySyncConflictFieldSource, ComparisonHistorySyncConflictReview, ComparisonHistorySyncConflictReviewGroup, ComparisonHistorySyncPreferenceFieldKey, ComparisonHistorySyncPreferenceReview, ComparisonHistorySyncPreferenceReviewRow, ComparisonHistorySyncPreferenceState, ComparisonHistorySyncWorkspaceRecommendationOverview, ComparisonHistorySyncWorkspaceReview, ComparisonHistorySyncWorkspaceReviewRow, ComparisonHistorySyncWorkspaceReviewSelectionKey, ComparisonHistorySyncWorkspaceSemanticSignal, ComparisonHistorySyncWorkspaceSignalDetailNestedKey, ComparisonHistorySyncWorkspaceSignalDetailSubviewKey, ComparisonHistorySyncWorkspaceSignalMicroInteractionKey, ComparisonHistorySyncWorkspaceSignalMicroViewKey, ComparisonHistorySyncWorkspaceState, ComparisonHistoryTabIdentity, ComparisonHistoryWriteMode, ComparisonIntent, ComparisonScoreDrillBackOptions, ComparisonScoreLinkedRunRole, ComparisonScoreLinkSource, ComparisonScoreLinkTarget, ComparisonScoreSection, ComparisonTooltipConflictSessionSummary, ComparisonTooltipConflictSessionSummarySession, ComparisonTooltipConflictSessionUiState, ComparisonTooltipConflictUiStateV1, ComparisonTooltipInteractionOptions, ComparisonTooltipLayout, ComparisonTooltipPendingPresetImportConflict, ComparisonTooltipPresetConflictPreviewGroup, ComparisonTooltipPresetConflictPreviewRow, ComparisonTooltipPresetImportConflictPolicy, ComparisonTooltipPresetImportResolution, ComparisonTooltipTargetProps, ComparisonTooltipTuning, ComparisonTooltipTuningPresetStateV1, ComparisonTooltipTuningShareImport, ComparisonTooltipTuningSinglePresetShareV1, ControlRoomComparisonHistoryPanelUiState, ControlRoomComparisonSelectionState, ControlRoomUiStateV1, ControlRoomUiStateV2, ControlRoomUiStateV3, ControlRoomUiStateV4, ExpandedGapWindowSelections, ExperimentPreset, ExperimentPresetRevision, GapWindowDragSelectionState, GuardedLiveStatus, MarketDataIngestionJobRecord, MarketDataProvenanceExportFilterState, MarketDataProvenanceExportHistoryEntry, MarketDataProvenanceExportSort, MarketDataProvenanceExportStateV1, MarketDataLineageHistoryRecord, MarketDataStatus, OperatorAlertMarketContextProvenance, OperatorAlertPrimaryFocus, OperatorVisibility, PendingTouchGapWindowSweepState, PresetDraftConflict, PresetRevisionDiff, PresetRevisionFilterState, PresetStructuredDiffDeltaValue, PresetStructuredDiffGroup, PresetStructuredDiffRow, ProviderProvenanceAnalyticsPresetEntry, ProviderProvenanceDashboardLayout, ProviderProvenanceDashboardViewEntry, ProviderProvenanceExportAnalyticsPayload, ProviderProvenanceExportJobEntry, ProviderProvenanceExportJobEscalationResult, ProviderProvenanceExportJobHistoryPayload, ProviderProvenanceExportJobPolicyResult, ProviderProvenanceSchedulerAlertHistoryPayload, ProviderProvenanceSchedulerHealthExportPayload, ProviderProvenanceSchedulerHealthAnalyticsPayload, ProviderProvenanceSchedulerHealthHistoryPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditRecord, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditRecord, ProviderProvenanceSchedulerSearchModerationPlanListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogListPayload, ProviderProvenanceSchedulerSearchFeedbackBatchModerationResult, ProviderProvenanceSchedulerSearchDashboardPayload, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditRecord, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionListPayload, ProviderProvenanceSchedulerStitchedReportViewAuditRecord, ProviderProvenanceSchedulerStitchedReportViewEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionListPayload, ProviderProvenanceSchedulerNarrativeBulkGovernanceResult, ProviderProvenanceSchedulerNarrativeGovernancePlan, ProviderProvenanceSchedulerNarrativeGovernancePlanBatchResult, ProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyStep, ProviderProvenanceSchedulerNarrativeGovernanceQueueView, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeRegistryEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionListPayload, ProviderProvenanceSchedulerNarrativeTemplateEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionListPayload, ProviderProvenanceScheduledReportEntry, ProviderProvenanceScheduledReportHistoryPayload, ProvenanceArtifactLineDetailView, ProvenanceArtifactLineMicroView, Run, RunComparison, RunHistoryFilter, RunHistorySurfaceKey, RunListBoundaryContract, RunListBoundaryEligibility, RunListBoundaryGroupKey, RunListBoundarySurfaceId, RunSurfaceCapabilities, RunSurfaceCapabilityFamily, RunSurfaceCapabilityFamilyContract, RunSurfaceCapabilityFamilyKey, RunSurfaceCapabilitySchemaContract, RunSurfaceCapabilitySurfaceKey, RunSurfaceCollectionQueryBuilderReplayIntentSnapshot, RunSurfaceCollectionQueryBuilderReplayLinkAliasRecordPayload, RunSurfaceCollectionQueryBuilderReplayLinkRedactionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkRetentionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobDownloadPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobPrunePayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditPrunePayload, RunSurfaceCollectionQueryContract, RunSurfaceCollectionQueryElementField, RunSurfaceCollectionQueryExpressionAuthoring, RunSurfaceCollectionQueryParameterDomainDescriptor, RunSurfaceCollectionQuerySchema, RunSurfaceSharedContract, RunSurfaceSubresourceContract, SavedRunHistoryFilterPreset, SavedRunHistoryFilterPresetStateV1, Strategy, TouchGapWindowActivationFeedbackState, TouchGapWindowHoldProgressState } from "./ControlRoomCoreHelpersContext";
import { defaultRunForm, defaultPresetForm, defaultPresetRevisionFilter, defaultMarketDataProvenanceExportFilterState, ProviderProvenanceAnalyticsScope, ProviderProvenanceSchedulerOccurrenceNarrativeFacet, ProviderProvenanceAnalyticsQueryState, ProviderProvenanceSchedulerSearchDashboardFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, ProviderProvenanceSchedulerSearchModerationQueueFilterState, ProviderProvenanceSchedulerSearchModerationStageDraft, ProviderProvenanceSchedulerExportPolicyDraft, OperatorVisibilityAlertEntry, defaultProviderProvenanceAnalyticsQueryState, defaultProviderProvenanceSchedulerSearchDashboardFilterState, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilter, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, defaultProviderProvenanceSchedulerSearchModerationQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationStageDraft, normalizeProviderProvenanceSchedulerRoutingPolicyDraftValue, normalizeProviderProvenanceSchedulerApprovalPolicyDraftValue, buildProviderProvenanceSchedulerExportPolicyDraft, getProviderProvenanceSchedulerNarrativeGovernanceQueuePriorityRank, getProviderProvenanceSchedulerNarrativeGovernanceQueueState, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchySummary, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepSummary, formatProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyPosition, isProviderProvenanceSchedulerAlertCategory, getOperatorAlertOccurrenceKey, formatProviderProvenanceSchedulerTimelineSummary, formatProviderProvenanceSchedulerSearchMatchSummary, formatProviderProvenanceSchedulerRetrievalClusterSummary, buildProviderProvenanceSchedulerAlertWorkflowReason } from "./ControlRoomCoreDefaults";
import { defaultProviderProvenanceDashboardLayout, DEFAULT_PROVIDER_PROVENANCE_SCHEDULER_NARRATIVE_GOVERNANCE_QUEUE_SORT, defaultProviderProvenanceWorkspaceDraft, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraftState, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraft, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraftState, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraft, KEEP_CURRENT_BULK_GOVERNANCE_VALUE, CLEAR_TEMPLATE_LINK_BULK_GOVERNANCE_VALUE, ProviderProvenanceSchedulerNarrativeBulkToggleValue, ProviderProvenanceSchedulerNarrativeTemplateBulkDraftState, defaultProviderProvenanceSchedulerNarrativeTemplateBulkDraft, ProviderProvenanceSchedulerStitchedReportViewBulkDraftState, defaultProviderProvenanceSchedulerStitchedReportViewBulkDraft, ProviderProvenanceSchedulerNarrativeRegistryDraftState, defaultProviderProvenanceSchedulerNarrativeRegistryDraft, ProviderProvenanceSchedulerNarrativeRegistryBulkDraftState, defaultProviderProvenanceSchedulerNarrativeRegistryBulkDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraftState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraft, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraftState, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraft, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraftState, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraft, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepVersionEntry, ProviderProvenanceSchedulerNarrativeGovernanceQueueFilterState, defaultProviderProvenanceSchedulerNarrativeGovernanceQueueFilter, ProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterState, defaultProviderProvenanceSchedulerStitchedReportGovernanceQueueFilter, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilterState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilter, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilterState, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilter, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilterState, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilter, ProviderProvenanceSchedulerStitchedReportViewAuditFilterState, defaultProviderProvenanceSchedulerStitchedReportViewAuditFilter, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilterState, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilter, ProviderProvenanceReportDraftState, defaultProviderProvenanceReportDraft } from "./ControlRoomCoreProviderDrafts";
import { buildPresetFormFromPreset, buildCurrentPresetRevisionSnapshot, buildEmptyPresetRevisionSnapshot, formatPresetStructuredDiffDisplayValue, isPresetStructuredDiffObject, isPresetStructuredDiffScalar, arePresetStructuredDiffValuesEquivalent, matchesPresetParameterSchemaType, joinPresetStructuredDiffHints, tokenizePresetParameterPath, parsePresetTimeframeToMinutes, buildPresetRankedStringDelta, buildPresetParameterStrategyContext, buildPresetParameterDomainContext, formatPresetParameterSchemaHint, getPresetParameterSchemaEntry, buildPresetStructuredDiffDelta, summarizePresetStructuredDiffGroup, groupPresetStructuredDiffRows, buildPresetStructuredDiffRows, describePresetRevisionDiff, describePresetDraftConflict, matchesPresetRevisionFilter } from "./ControlRoomCorePresetDiff";
import { defaultRunHistoryFilter, sanitizeRunHistoryFilter, cloneRunHistoryFilter, hasRunHistoryFilterCriteria, areRunHistoryFiltersEquivalent, buildRunHistorySavedFilterStorageKey, normalizeSavedRunHistoryFilterPreset, loadSavedRunHistoryFilterPresets, persistSavedRunHistoryFilterPresets, describeRunHistoryFilter, DEFAULT_COMPARISON_INTENT, comparisonIntentOptions, parseExperimentTags, parseJsonObjectInput, formatPresetLifecycleStage, buildRunSubmissionPayload, normalizeRunFormPreset } from "./ControlRoomCoreRunHistory";
import { resolveMarketDataSymbol, buildMarketDataInstrumentFocusKey, isMarketDataInstrumentAtRisk, resolvePreferredMarketDataInstrument, formatWorkflowToken, LinkedMarketInstrumentContext, MarketDataLinkableAlertRecord, MarketDataIncidentHistoryEntry, ProviderRecoveryMarketContextSummary, MarketDataProviderProvenanceEventRecord, MarketDataPrimaryFocusSelection, formatMarketContextFieldProvenance, summarizeProviderRecoveryMarketContextProvenance, serializeLinkedMarketInstrumentContext, getOperatorSeverityRank, normalizeMarketDataProvenanceExportSort, normalizeMarketDataProvenanceExportFilterState, normalizeMarketDataProvenanceExportHistoryEntry, loadPersistedMarketDataProvenanceExportState, persistMarketDataProvenanceExportState, formatMarketDataProvenanceExportFilterSummary, formatProviderProvenanceAnalyticsQuerySummary, normalizeProviderProvenanceDashboardLayoutState } from "./ControlRoomCoreMarketData";
import { normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueSort, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkQueueViewPatch, formatProviderProvenanceSchedulerNarrativeGovernanceQueueSortLabel, providerProvenanceSchedulerNarrativeGovernancePolicySupportsItemType, formatProviderProvenanceSchedulerNarrativeGovernanceQueueViewSummary, buildProviderProvenanceAnalyticsWorkspaceQuery, buildProviderProvenanceAnalyticsQueryStateFromWorkspaceQuery, formatProviderProvenanceSchedulerNarrativeFacet, resolveProviderProvenanceSeriesBarWidth, formatProviderDriftIntensity, formatSchedulerLagSeconds } from "./ControlRoomCoreGovernance";

export function downloadTextExport(payload: ProviderProvenanceSchedulerHealthExportPayload) {
  const blob = new Blob([payload.content], { type: payload.content_type });
  const objectUrl = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = objectUrl;
  link.download = payload.filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(objectUrl);
}

export function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function normalizeMarketSymbol(value: string) {
  return value.trim().toUpperCase();
}

export function buildMarketSymbolSearchVariants(symbol: string) {
  const normalized = normalizeMarketSymbol(symbol);
  return Array.from(new Set([normalized, normalized.replaceAll("/", ""), normalized.replaceAll("-", "")])).filter(
    (variant) => variant.length > 0,
  );
}

export function matchesMarketSymbolInText(text: string, symbol: string) {
  const upperText = text.toUpperCase();
  return buildMarketSymbolSearchVariants(symbol).some((variant) => upperText.includes(variant));
}

export function dedupeMarketDataInstruments(
  candidates: MarketDataStatus["instruments"][number][],
) {
  return Array.from(
    new Map(
      candidates.map((instrument) => [buildMarketDataInstrumentFocusKey(instrument), instrument]),
    ).values(),
  );
}

export function formatMarketDataInstrumentLabel(
  instrument: MarketDataStatus["instruments"][number],
) {
  return `${resolveMarketDataSymbol(instrument.instrument_id)} · ${instrument.timeframe}`;
}

export function getMarketDataInstrumentSyncSeverityRank(syncStatus: string) {
  switch (syncStatus) {
    case "error":
      return 4;
    case "stale":
      return 3;
    case "lagging":
      return 2;
    case "syncing":
      return 1;
    case "synced":
      return 0;
    default:
      return syncStatus !== "synced" ? 1 : 0;
  }
}

export function getMarketDataInstrumentRiskScore(
  instrument: MarketDataStatus["instruments"][number],
) {
  return (
    getMarketDataInstrumentSyncSeverityRank(instrument.sync_status) * 1000
    + Math.min(instrument.failure_count_24h, 99) * 100
    + instrument.backfill_gap_windows.length * 40
    + instrument.issues.length * 35
    + ((instrument.backfill_contiguous_missing_candles ?? 0) > 0 ? 20 : 0)
    + (instrument.backfill_target_candles !== null && instrument.backfill_complete === false ? 10 : 0)
    + Math.min(Math.ceil((instrument.lag_seconds ?? 0) / 60), 15)
  );
}

export function buildLiveMarketDataPreference(args: {
  guardedLive: GuardedLiveStatus | null;
  liveRuns: Run[];
}) {
  const { guardedLive, liveRuns } = args;
  const exactKeys = new Set<string>();
  const symbolSet = new Set<string>();
  const register = (symbol?: string | null, timeframe?: string | null) => {
    if (!symbol) {
      return;
    }
    const normalizedSymbol = normalizeMarketSymbol(symbol);
    symbolSet.add(normalizedSymbol);
    if (timeframe) {
      exactKeys.add(`${normalizedSymbol}|${timeframe}`);
    }
  };

  liveRuns.forEach((run) => {
    run.config.symbols.forEach((symbol) => {
      register(symbol, run.config.timeframe);
    });
  });

  register(guardedLive?.session_handoff.symbol, guardedLive?.session_handoff.kline_snapshot?.timeframe ?? null);
  register(guardedLive?.ownership.symbol);
  register(guardedLive?.order_book.symbol);
  register(guardedLive?.session_restore.symbol);

  return { exactKeys, symbolSet };
}

export function getMarketDataInstrumentLiveRelevance(
  instrument: MarketDataStatus["instruments"][number],
  livePreference: ReturnType<typeof buildLiveMarketDataPreference>,
) {
  const symbol = normalizeMarketSymbol(resolveMarketDataSymbol(instrument.instrument_id));
  if (livePreference.exactKeys.has(`${symbol}|${instrument.timeframe}`)) {
    return 2;
  }
  if (livePreference.symbolSet.has(symbol)) {
    return 1;
  }
  return 0;
}

export function selectPrimaryMarketDataInstrument(args: {
  candidates: MarketDataStatus["instruments"][number][],
  guardedLive: GuardedLiveStatus | null;
  liveRuns: Run[];
  symbolOrder?: string[];
}) {
  const { candidates, guardedLive, liveRuns, symbolOrder = [] } = args;
  const deduped = dedupeMarketDataInstruments(candidates);
  if (!deduped.length) {
    return null;
  }

  const livePreference = buildLiveMarketDataPreference({ guardedLive, liveRuns });
  const symbolOrderBySymbol = new Map<string, number>();
  symbolOrder.forEach((symbol, index) => {
    const normalizedSymbol = normalizeMarketSymbol(symbol);
    if (!symbolOrderBySymbol.has(normalizedSymbol)) {
      symbolOrderBySymbol.set(normalizedSymbol, index);
    }
  });

  const rankedCandidates = deduped
    .map((instrument) => {
      const normalizedSymbol = normalizeMarketSymbol(resolveMarketDataSymbol(instrument.instrument_id));
      return {
        instrument,
        label: formatMarketDataInstrumentLabel(instrument),
        riskScore: getMarketDataInstrumentRiskScore(instrument),
        liveRelevance: getMarketDataInstrumentLiveRelevance(instrument, livePreference),
        payloadOrder: symbolOrderBySymbol.get(normalizedSymbol) ?? Number.MAX_SAFE_INTEGER,
        lexicalKey: `${normalizedSymbol}|${instrument.timeframe}|${instrument.instrument_id}`,
      };
    })
    .sort(
      (left, right) =>
        right.riskScore - left.riskScore
        || right.liveRelevance - left.liveRelevance
        || left.payloadOrder - right.payloadOrder
        || left.lexicalKey.localeCompare(right.lexicalKey),
    );

  const primary = rankedCandidates[0];
  const nextCandidate = rankedCandidates[1] ?? null;
  let primaryFocusReason = "Only one matching market-data instrument was linked.";
  if (nextCandidate) {
    if (primary.riskScore !== nextCandidate.riskScore) {
      primaryFocusReason = `Selected the highest-risk market-data candidate from ${rankedCandidates.length} linked instruments.`;
    } else if (primary.liveRelevance !== nextCandidate.liveRelevance) {
      primaryFocusReason =
        primary.liveRelevance === 2
          ? "Risk tied, so the exact live symbol/timeframe candidate became the primary triage focus."
          : "Risk tied, so the active live symbol candidate became the primary triage focus.";
    } else if (
      primary.payloadOrder !== nextCandidate.payloadOrder
      && primary.payloadOrder !== Number.MAX_SAFE_INTEGER
    ) {
      primaryFocusReason = "Risk and live relevance tied, so payload symbol order broke the tie.";
    } else {
      primaryFocusReason = "Risk, live relevance, and payload order tied, so lexical ordering kept focus stable.";
    }
  }

  return {
    instrument: primary.instrument,
    candidateCount: rankedCandidates.length,
    candidateLabels: rankedCandidates.map((candidate) => candidate.label),
    primaryFocusPolicy: "risk -> live -> payload order -> lexical",
    primaryFocusReason,
  } satisfies MarketDataPrimaryFocusSelection;
}

export function extractMatchingMarketTimeframe(
  text: string,
  marketStatus: MarketDataStatus,
) {
  const knownTimeframes = Array.from(
    new Set(marketStatus.instruments.map((instrument) => instrument.timeframe)),
  ).sort((left, right) => right.length - left.length);
  return (
    knownTimeframes.find((timeframe) =>
      new RegExp(`(^|[^A-Za-z0-9])${escapeRegExp(timeframe)}($|[^A-Za-z0-9])`, "i").test(text),
    )
    ?? null
  );
}

export function extractMatchingMarketSymbols(
  text: string,
  marketStatus: MarketDataStatus,
) {
  const knownSymbols = Array.from(
    new Set(marketStatus.instruments.map((instrument) => resolveMarketDataSymbol(instrument.instrument_id))),
  );
  return knownSymbols.filter((symbol) => matchesMarketSymbolInText(text, symbol));
}

export function buildLinkedMarketInstrumentContext(
  selection: MarketDataPrimaryFocusSelection,
  matchReason: string,
): LinkedMarketInstrumentContext {
  const { instrument } = selection;
  return {
    instrument,
    focusKey: buildMarketDataInstrumentFocusKey(instrument),
    symbol: resolveMarketDataSymbol(instrument.instrument_id),
    timeframe: instrument.timeframe,
    matchReason,
    candidateCount: selection.candidateCount,
    candidateLabels: selection.candidateLabels,
    primaryFocusPolicy: selection.primaryFocusPolicy,
    primaryFocusReason: selection.primaryFocusReason,
  };
}

export function buildLinkedMarketInstrumentContextFromPayload(args: {
  instrument: MarketDataStatus["instruments"][number];
  primaryFocus: OperatorAlertPrimaryFocus;
  matchReason: string;
}): LinkedMarketInstrumentContext {
  const { instrument, primaryFocus, matchReason } = args;
  const candidateSymbols = Array.from(
    new Set(
      primaryFocus.candidate_symbols
        .map((symbol) => normalizeMarketSymbol(symbol))
        .filter((symbol) => symbol.length > 0),
    ),
  );
  const candidateTimeframe = primaryFocus.timeframe?.trim() || instrument.timeframe;
  return {
    instrument,
    focusKey: buildMarketDataInstrumentFocusKey(instrument),
    symbol: resolveMarketDataSymbol(instrument.instrument_id),
    timeframe: instrument.timeframe,
    matchReason,
    candidateCount: primaryFocus.candidate_count || candidateSymbols.length || 1,
    candidateLabels: (candidateSymbols.length ? candidateSymbols : [resolveMarketDataSymbol(instrument.instrument_id)])
      .map((symbol) => `${symbol} · ${candidateTimeframe}`),
    primaryFocusPolicy: primaryFocus.policy || "payload_primary_focus",
    primaryFocusReason: primaryFocus.reason?.trim() || "Backend supplied explicit primary-focus metadata.",
  };
}

export function formatLinkedMarketPrimaryFocusNote(
  link: LinkedMarketInstrumentContext | null,
) {
  if (!link || link.candidateCount <= 1) {
    return null;
  }
  return `Primary focus policy (${link.primaryFocusPolicy}): ${link.primaryFocusReason} Candidate order: ${link.candidateLabels.join(", ")}.`;
}

export function resolveInstrumentsBySymbolsAndTimeframe(args: {
  marketStatus: MarketDataStatus;
  symbols: string[];
  timeframe?: string | null;
}) {
  const { marketStatus, symbols, timeframe } = args;
  const symbolSet = new Set(symbols.map((symbol) => normalizeMarketSymbol(symbol)));
  return marketStatus.instruments.filter((instrument) => {
    if (!symbolSet.has(normalizeMarketSymbol(resolveMarketDataSymbol(instrument.instrument_id)))) {
      return false;
    }
    return timeframe ? instrument.timeframe === timeframe : true;
  });
}

export function resolveMarketDataInstrumentLink(args: {
  guardedLive: GuardedLiveStatus | null;
  liveRuns: Run[];
  marketStatus: MarketDataStatus | null;
  record: MarketDataLinkableAlertRecord;
  runById: Map<string, Run>;
}) {
  const { guardedLive, liveRuns, marketStatus, record, runById } = args;
  if (!marketStatus) {
    return null;
  }

  const category = record.category?.trim() ?? "";
  const payloadPrimaryFocus = record.primary_focus ?? null;
  const payloadPrimaryFocusSymbol = payloadPrimaryFocus?.symbol?.trim() || null;
  const payloadPrimaryFocusTimeframe = payloadPrimaryFocus?.timeframe?.trim() || null;
  if (payloadPrimaryFocus && payloadPrimaryFocusSymbol) {
    const primaryFocusInstrument = resolveInstrumentsBySymbolsAndTimeframe({
      marketStatus,
      symbols: [payloadPrimaryFocusSymbol],
      timeframe: payloadPrimaryFocusTimeframe,
    })[0];
    if (primaryFocusInstrument) {
      return buildLinkedMarketInstrumentContextFromPayload({
        instrument: primaryFocusInstrument,
        primaryFocus: payloadPrimaryFocus,
        matchReason: "payload_primary_focus",
      });
    }
  }
  const explicitSymbols = Array.from(
    new Set(
      [record.symbol ?? null, ...(record.symbols ?? [])]
        .filter((symbol): symbol is string => typeof symbol === "string" && symbol.trim().length > 0)
        .map((symbol) => normalizeMarketSymbol(symbol)),
    ),
  );
  const explicitTimeframe = record.timeframe?.trim() || null;
  if (explicitSymbols.length) {
    const explicitSelection = selectPrimaryMarketDataInstrument({
      candidates: resolveInstrumentsBySymbolsAndTimeframe({
        marketStatus,
        symbols: explicitSymbols,
        timeframe: explicitTimeframe,
      }),
      guardedLive,
      liveRuns,
      symbolOrder: explicitSymbols,
    });
    if (explicitSelection) {
      return buildLinkedMarketInstrumentContext(explicitSelection, "payload_market_context");
    }
  }
  const run = record.run_id ? runById.get(record.run_id) : undefined;
  if (run) {
    const runSelection = selectPrimaryMarketDataInstrument({
      candidates: resolveInstrumentsBySymbolsAndTimeframe({
        marketStatus,
        symbols: run.config.symbols,
        timeframe: run.config.timeframe,
      }),
      guardedLive,
      liveRuns,
      symbolOrder: run.config.symbols,
    });
    if (runSelection) {
      return buildLinkedMarketInstrumentContext(runSelection, "run_context");
    }
  }

  if (record.provider_recovery_symbols?.length) {
    const providerRecoverySelection = selectPrimaryMarketDataInstrument({
      candidates: resolveInstrumentsBySymbolsAndTimeframe({
        marketStatus,
        symbols: record.provider_recovery_symbols,
        timeframe: record.provider_recovery_timeframe,
      }),
      guardedLive,
      liveRuns,
      symbolOrder: record.provider_recovery_symbols,
    });
    if (providerRecoverySelection) {
      return buildLinkedMarketInstrumentContext(providerRecoverySelection, "provider_recovery");
    }
  }

  const combinedText = `${record.summary} ${record.detail}`.trim();
  const matchedSymbols = extractMatchingMarketSymbols(combinedText, marketStatus);
  const guardedLiveTimeframe = guardedLive?.session_handoff.kline_snapshot?.timeframe ?? null;
  const guardedLiveSymbol =
    guardedLive?.session_handoff.symbol
    ?? guardedLive?.ownership.symbol
    ?? guardedLive?.order_book.symbol
    ?? guardedLive?.session_restore.symbol
    ?? null;
  const matchedTimeframe =
    explicitTimeframe
    ?? extractMatchingMarketTimeframe(combinedText, marketStatus)
    ?? guardedLiveTimeframe;

  if (matchedSymbols.length && matchedTimeframe) {
    const exactSelection = selectPrimaryMarketDataInstrument({
      candidates: resolveInstrumentsBySymbolsAndTimeframe({
        marketStatus,
        symbols: matchedSymbols,
        timeframe: matchedTimeframe,
      }),
      guardedLive,
      liveRuns,
      symbolOrder: matchedSymbols,
    });
    if (exactSelection) {
      return buildLinkedMarketInstrumentContext(exactSelection, "symbol_timeframe_match");
    }
  }

  if (record.source === "guarded_live" && guardedLiveSymbol && matchedTimeframe) {
    const guardedLiveSelection = selectPrimaryMarketDataInstrument({
      candidates: resolveInstrumentsBySymbolsAndTimeframe({
        marketStatus,
        symbols: [guardedLiveSymbol],
        timeframe: matchedTimeframe,
      }),
      guardedLive,
      liveRuns,
      symbolOrder: [guardedLiveSymbol],
    });
    if (guardedLiveSelection) {
      return buildLinkedMarketInstrumentContext(guardedLiveSelection, "guarded_live_context");
    }
  }

  if (matchedSymbols.length) {
    const symbolSelection = selectPrimaryMarketDataInstrument({
      candidates: resolveInstrumentsBySymbolsAndTimeframe({
        marketStatus,
        symbols: matchedSymbols,
      }),
      guardedLive,
      liveRuns,
      symbolOrder: matchedSymbols,
    });
    if (symbolSelection) {
      return buildLinkedMarketInstrumentContext(symbolSelection, "symbol_match");
    }
  }

  const isMarketDataRecord =
    category.startsWith("market_data_")
    || combinedText.toLowerCase().includes("market-data");
  if (isMarketDataRecord && matchedTimeframe) {
    const liveSymbolSet = new Set(
      liveRuns.flatMap((liveRun) => liveRun.config.symbols.map((symbol) => normalizeMarketSymbol(symbol))),
    );
    let timeframeCandidates = marketStatus.instruments.filter(
      (instrument) => instrument.timeframe === matchedTimeframe,
    );
    if (liveSymbolSet.size > 0) {
      const liveScopedCandidates = timeframeCandidates.filter((instrument) =>
        liveSymbolSet.has(normalizeMarketSymbol(resolveMarketDataSymbol(instrument.instrument_id))),
      );
      if (liveScopedCandidates.length) {
        timeframeCandidates = liveScopedCandidates;
      }
    }
    const timeframeSelection = selectPrimaryMarketDataInstrument({
      candidates: timeframeCandidates,
      guardedLive,
      liveRuns,
      symbolOrder: liveRuns.flatMap((liveRun) => liveRun.config.symbols),
    });
    if (timeframeSelection) {
      return buildLinkedMarketInstrumentContext(timeframeSelection, "timeframe_market_data_match");
    }
  }

  if (record.source === "guarded_live" && guardedLiveSymbol) {
    const guardedLiveSelection = selectPrimaryMarketDataInstrument({
      candidates: resolveInstrumentsBySymbolsAndTimeframe({
        marketStatus,
        symbols: [guardedLiveSymbol],
        timeframe: guardedLiveTimeframe,
      }),
      guardedLive,
      liveRuns,
      symbolOrder: [guardedLiveSymbol],
    });
    if (guardedLiveSelection) {
      return buildLinkedMarketInstrumentContext(guardedLiveSelection, "guarded_live_symbol");
    }
  }

  return null;
}

export function getAlertLinkPriority(alert: Pick<OperatorVisibility["alerts"][number], "category" | "severity" | "detected_at">) {
  const categoryRank = alert.category.startsWith("market_data_") ? 2 : alert.category === "worker_failure" ? 1 : 0;
  const severityRank = alert.severity === "critical" ? 2 : alert.severity === "warning" ? 1 : 0;
  const detectedAt = Date.parse(alert.detected_at);
  return {
    categoryRank,
    severityRank,
    detectedAt: Number.isFinite(detectedAt) ? detectedAt : Number.NEGATIVE_INFINITY,
  };
}

export function compareAlertLinkPriority(
  left: Pick<OperatorVisibility["alerts"][number], "category" | "severity" | "detected_at">,
  right: Pick<OperatorVisibility["alerts"][number], "category" | "severity" | "detected_at">,
) {
  const leftPriority = getAlertLinkPriority(left);
  const rightPriority = getAlertLinkPriority(right);
  return (
    rightPriority.categoryRank - leftPriority.categoryRank
    || rightPriority.severityRank - leftPriority.severityRank
    || rightPriority.detectedAt - leftPriority.detectedAt
  );
}

export function resolveAutoLinkedMarketInstrument(args: {
  guardedLive: GuardedLiveStatus | null;
  liveRuns: Run[];
  marketStatus: MarketDataStatus | null;
  operatorVisibility: OperatorVisibility | null;
  runById: Map<string, Run>;
}) {
  const { guardedLive, liveRuns, marketStatus, operatorVisibility, runById } = args;
  if (!marketStatus || !operatorVisibility) {
    return null;
  }
  const linkedAlerts = operatorVisibility.alerts
    .map((alert) => ({
      alert,
      link: resolveMarketDataInstrumentLink({
        guardedLive,
        liveRuns,
        marketStatus,
        record: alert,
        runById,
      }),
    }))
    .filter(
      (entry): entry is {
        alert: OperatorVisibility["alerts"][number];
        link: LinkedMarketInstrumentContext;
      } => entry.link !== null,
    )
    .sort((left, right) => compareAlertLinkPriority(left.alert, right.alert));
  return linkedAlerts[0]?.link ?? null;
}
