// @ts-nocheck

import { CSSProperties, FormEvent, KeyboardEvent, MouseEvent, PointerEvent, ReactNode, forwardRef, useCallback, useEffect, useId, useLayoutEffect, useMemo, useRef, useState, AKRA_TOUCH_FEEDBACK_BRIDGE_VERSION, AKRA_TOUCH_FEEDBACK_EVENT_NAME, AkraTouchFeedbackDetail, AkraTouchFeedbackEnvelope, triggerAkraTouchFeedbackBridge, WorkspaceShell, buildControlWorkspaceDescriptors, ControlWorkspaceDescriptor, ControlStripMetric, useWorkspaceRoute, WorkspaceRouteContent, buildRunHistoryWorkspacePanels, LiveOrderReplacementDraft, RunHistoryWorkspaceSectionProps, RunOrderControls, getRunListBoundaryContractSnapshot, getRunListBoundarySurfaceLabel, getRunSurfaceCapabilityFamily, getRunSurfaceCapabilityFamilyOrder, getRunSurfaceCapabilityGroupOrder, getRunSurfaceCapabilitySchemaContract, getRunSurfaceCollectionQueryContracts, getRunSurfaceSharedContracts, getRunSurfaceSubresourceContracts, RunListComparisonBoundaryNote, shouldEnableStrategyProvenanceSemantics, shouldEnableRunListMetricDrillBack, shouldEnableRunSnapshotSemantics, shouldEnableStrategyCatalogSchemaHints, shouldHydratePresetParameterDefaults, shouldRenderOrderActionBoundaryNote, shouldRenderWorkflowControlBoundaryNote, RunSurfaceCollectionQueryBuilder, formatComparisonTooltipTuningDelta, formatComparisonTooltipTuningValue, formatRelativeTimestampLabel, RunSection, RunSurfaceCollectionQueryBuilderApplyPayload, RunSurfaceCollectionQueryRuntimeCandidateContextSelection, RunSurfaceCollectionQueryRuntimeCandidateSample, applyProviderProvenanceSchedulerStitchedReportGovernancePlan, applyProviderProvenanceSchedulerNarrativeGovernancePlan, approveProviderProvenanceSchedulerStitchedReportGovernancePlan, approveProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceAnalyticsPreset, createProviderProvenanceDashboardView, createProviderProvenanceExportJob, createProviderProvenanceSchedulerStitchedReportGovernanceRegistry, createProviderProvenanceSchedulerStitchedReportGovernancePlan, createProviderProvenanceSchedulerStitchedReportView, createProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, captureProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchy, createProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, createProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceSchedulerNarrativeRegistryEntry, createProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceScheduledReport, approveProviderProvenanceExportJob, applyProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, deleteProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, deleteProviderProvenanceSchedulerNarrativeRegistryEntry, deleteProviderProvenanceSchedulerStitchedReportView, deleteProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, createRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, createRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, downloadProviderProvenanceExportJob, downloadRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, escalateProviderProvenanceExportJob, exportProviderProvenanceSchedulerHealth, exportProviderProvenanceSchedulerStitchedNarrativeReport, reconstructProviderProvenanceSchedulerHealthExport, exportRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, fetchJson, getProviderProvenanceExportAnalytics, getProviderProvenanceExportJobHistory, getProviderProvenanceSchedulerHealthAnalytics, getProviderProvenanceScheduledReportHistory, getRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobHistory, listProviderProvenanceAnalyticsPresets, listProviderProvenanceDashboardViews, listProviderProvenanceSchedulerStitchedReportViews, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogs, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplates, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePlans, listProviderProvenanceSchedulerNarrativeRegistryEntries, listProviderProvenanceSchedulerNarrativeRegistryRevisions, listProviderProvenanceSchedulerNarrativeTemplates, listProviderProvenanceSchedulerNarrativeTemplateRevisions, listProviderProvenanceSchedulerStitchedReportGovernancePolicyCatalogs, listProviderProvenanceSchedulerStitchedReportGovernancePolicyTemplates, listProviderProvenanceSchedulerStitchedReportGovernancePlans, rollbackProviderProvenanceSchedulerStitchedReportGovernancePlan, rollbackProviderProvenanceSchedulerNarrativeGovernancePlan, listMarketDataIngestionJobs, listMarketDataLineageHistory, listProviderProvenanceExportJobs, listProviderProvenanceSchedulerAlertHistory, listProviderProvenanceSchedulerHealthHistory, listProviderProvenanceSchedulerStitchedReportGovernanceRegistries, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryAudits, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisions, listProviderProvenanceSchedulerStitchedReportViewAudits, listProviderProvenanceSchedulerStitchedReportViewRevisions, getProviderProvenanceSchedulerSearchDashboard, bulkGovernProviderProvenanceSchedulerSearchModerationPolicyCatalogs, bulkGovernProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, createProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicy, createProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, listProviderProvenanceSchedulerSearchModerationPolicyCatalogs, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlans, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAudits, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisions, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePlans, listProviderProvenanceSchedulerSearchModerationPolicyCatalogAudits, listProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisions, listProviderProvenanceSchedulerSearchModerationPlans, listProviderProvenanceScheduledReports, listRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, listRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, approveProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, approveProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, approveProviderProvenanceSchedulerSearchModerationPlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, applyProviderProvenanceSchedulerSearchModerationPlan, createProviderProvenanceSchedulerSearchModerationPolicyCatalog, deleteProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, deleteProviderProvenanceSchedulerSearchModerationPolicyCatalog, moderateProviderProvenanceSchedulerSearchFeedbackBatch, moderateProviderProvenanceSchedulerSearchFeedback, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, recordProviderProvenanceSchedulerSearchFeedback, resolveRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevision, restoreProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevision, restoreProviderProvenanceSchedulerSearchModerationPolicyCatalogRevision, restoreProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevision, restoreProviderProvenanceSchedulerNarrativeRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportViewRevision, restoreProviderProvenanceSchedulerNarrativeTemplateRevision, revokeRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, runProviderProvenanceSchedulerNarrativeGovernancePlanBatchAction, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkGovernance, stageProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, stageProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, stageProviderProvenanceSchedulerSearchModerationPlan, updateProviderProvenanceSchedulerSearchModerationPolicyCatalog, updateProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, stageProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, runDueProviderProvenanceScheduledReports, runProviderProvenanceScheduledReport, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStep, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, updateProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, updateProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, updateProviderProvenanceSchedulerNarrativeRegistryEntry, updateProviderProvenanceSchedulerStitchedReportGovernanceRegistry, updateProviderProvenanceSchedulerStitchedReportView, updateProviderProvenanceSchedulerNarrativeTemplate, updateProviderProvenanceExportJobPolicy, deleteProviderProvenanceSchedulerStitchedReportGovernanceRegistry, ALL_FILTER_VALUE, apiBase, COMPARISON_FOCUS_ARTIFACT_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_MICRO_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_NOTE_PAGE_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_SCRUB_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_COMPONENT_SEARCH_PARAM, COMPARISON_FOCUS_DETAIL_SEARCH_PARAM, COMPARISON_FOCUS_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ORIGIN_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_SECTION_SEARCH_PARAM, COMPARISON_FOCUS_SOURCE_SEARCH_PARAM, COMPARISON_FOCUS_TOOLTIP_SEARCH_PARAM, COMPARISON_HISTORY_BROWSER_STATE_KEY, COMPARISON_HISTORY_BROWSER_STATE_VERSION, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_KEY, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_VERSION, COMPARISON_HISTORY_SYNC_CONFLICT_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_PREFERENCE_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_WORKSPACE_FIELD_DEFINITIONS, COMPARISON_HISTORY_TAB_ID_SESSION_KEY, COMPARISON_INTENT_SEARCH_PARAM, COMPARISON_RUN_ID_SEARCH_PARAM, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_KEY, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_VERSION, COMPARISON_TOOLTIP_TUNING_GROUPS, COMPARISON_TOOLTIP_TUNING_LABELS, COMPARISON_TOOLTIP_TUNING_SHARE_PARAM, COMPARISON_TOOLTIP_TUNING_STORAGE_KEY, COMPARISON_TOOLTIP_TUNING_STORAGE_VERSION, COMPARISON_TOOLTIP_UNCHANGED_GROUP_COLLAPSE_THRESHOLD, CONTROL_ROOM_UI_STATE_STORAGE_KEY, CONTROL_ROOM_UI_STATE_VERSION, DEFAULT_COMPARISON_TOOLTIP_PRESET_IMPORT_CONFLICT_POLICY, DEFAULT_COMPARISON_TOOLTIP_TUNING, DEFAULT_CONTROL_ROOM_DOCUMENT_TITLE, LEGACY_GAP_WINDOW_EXPANSION_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_VERSION, MAX_COMPARISON_HISTORY_PANEL_ENTRIES, MAX_COMPARISON_HISTORY_SYNC_AUDIT_ENTRIES, MAX_COMPARISON_RUNS, MAX_MARKET_DATA_PROVENANCE_EXPORT_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_REVIEWED_CONFLICT_KEYS, MAX_VISIBLE_COMPARISON_TOOLTIP_CONFLICT_SESSION_SUMMARIES, MAX_VISIBLE_GAP_WINDOWS, PRESET_PROFILE_AGGRESSIVENESS_RANKS, PRESET_PROFILE_CONFIDENCE_RANKS, PRESET_PROFILE_SPEED_RANKS, PRESET_TIMEFRAME_UNIT_TO_MINUTES, REPLAY_INTENT_ACTION_FILTER_SEARCH_PARAM, REPLAY_INTENT_ALIAS_SEARCH_PARAM, REPLAY_INTENT_EDGE_FILTER_SEARCH_PARAM, REPLAY_INTENT_GROUP_FILTER_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_DIFF_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_GROUP_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_TRACE_SEARCH_PARAM, REPLAY_INTENT_SCOPE_SEARCH_PARAM, REPLAY_INTENT_SEARCH_PARAM, REPLAY_INTENT_STEP_SEARCH_PARAM, REPLAY_INTENT_TEMPLATE_SEARCH_PARAM, RUN_HISTORY_SAVED_FILTER_STORAGE_KEY_PREFIX, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_TAB_ID_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_BROWSER_STATE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_PAYLOAD_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_SIGNING_SECRET_STORAGE_KEY, SHOW_COMPARISON_TOOLTIP_TUNING_PANEL, TOUCH_GAP_WINDOW_SWEEP_HOLD_MS, TOUCH_GAP_WINDOW_SWEEP_MOVE_TOLERANCE_PX, BenchmarkArtifact, ParameterSchema, ComparisonCueKind, ComparisonHistoryBrowserState, ComparisonHistoryPanelEntry, ComparisonHistoryPanelState, ComparisonHistoryPanelSyncState, ComparisonHistoryStepDescriptor, ComparisonHistorySyncAuditEntry, ComparisonHistorySyncAuditFilter, ComparisonHistorySyncAuditKind, ComparisonHistorySyncAuditTrailState, ComparisonHistorySyncConflictFieldKey, ComparisonHistorySyncConflictFieldSource, ComparisonHistorySyncConflictReview, ComparisonHistorySyncConflictReviewGroup, ComparisonHistorySyncPreferenceFieldKey, ComparisonHistorySyncPreferenceReview, ComparisonHistorySyncPreferenceReviewRow, ComparisonHistorySyncPreferenceState, ComparisonHistorySyncWorkspaceRecommendationOverview, ComparisonHistorySyncWorkspaceReview, ComparisonHistorySyncWorkspaceReviewRow, ComparisonHistorySyncWorkspaceReviewSelectionKey, ComparisonHistorySyncWorkspaceSemanticSignal, ComparisonHistorySyncWorkspaceSignalDetailNestedKey, ComparisonHistorySyncWorkspaceSignalDetailSubviewKey, ComparisonHistorySyncWorkspaceSignalMicroInteractionKey, ComparisonHistorySyncWorkspaceSignalMicroViewKey, ComparisonHistorySyncWorkspaceState, ComparisonHistoryTabIdentity, ComparisonHistoryWriteMode, ComparisonIntent, ComparisonScoreDrillBackOptions, ComparisonScoreLinkedRunRole, ComparisonScoreLinkSource, ComparisonScoreLinkTarget, ComparisonScoreSection, ComparisonTooltipConflictSessionSummary, ComparisonTooltipConflictSessionSummarySession, ComparisonTooltipConflictSessionUiState, ComparisonTooltipConflictUiStateV1, ComparisonTooltipInteractionOptions, ComparisonTooltipLayout, ComparisonTooltipPendingPresetImportConflict, ComparisonTooltipPresetConflictPreviewGroup, ComparisonTooltipPresetConflictPreviewRow, ComparisonTooltipPresetImportConflictPolicy, ComparisonTooltipPresetImportResolution, ComparisonTooltipTargetProps, ComparisonTooltipTuning, ComparisonTooltipTuningPresetStateV1, ComparisonTooltipTuningShareImport, ComparisonTooltipTuningSinglePresetShareV1, ControlRoomComparisonHistoryPanelUiState, ControlRoomComparisonSelectionState, ControlRoomUiStateV1, ControlRoomUiStateV2, ControlRoomUiStateV3, ControlRoomUiStateV4, ExpandedGapWindowSelections, ExperimentPreset, ExperimentPresetRevision, GapWindowDragSelectionState, GuardedLiveStatus, MarketDataIngestionJobRecord, MarketDataProvenanceExportFilterState, MarketDataProvenanceExportHistoryEntry, MarketDataProvenanceExportSort, MarketDataProvenanceExportStateV1, MarketDataLineageHistoryRecord, MarketDataStatus, OperatorAlertMarketContextProvenance, OperatorAlertPrimaryFocus, OperatorVisibility, PendingTouchGapWindowSweepState, PresetDraftConflict, PresetRevisionDiff, PresetRevisionFilterState, PresetStructuredDiffDeltaValue, PresetStructuredDiffGroup, PresetStructuredDiffRow, ProviderProvenanceAnalyticsPresetEntry, ProviderProvenanceDashboardLayout, ProviderProvenanceDashboardViewEntry, ProviderProvenanceExportAnalyticsPayload, ProviderProvenanceExportJobEntry, ProviderProvenanceExportJobEscalationResult, ProviderProvenanceExportJobHistoryPayload, ProviderProvenanceExportJobPolicyResult, ProviderProvenanceSchedulerAlertHistoryPayload, ProviderProvenanceSchedulerHealthExportPayload, ProviderProvenanceSchedulerHealthAnalyticsPayload, ProviderProvenanceSchedulerHealthHistoryPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditRecord, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditRecord, ProviderProvenanceSchedulerSearchModerationPlanListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogListPayload, ProviderProvenanceSchedulerSearchFeedbackBatchModerationResult, ProviderProvenanceSchedulerSearchDashboardPayload, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditRecord, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionListPayload, ProviderProvenanceSchedulerStitchedReportViewAuditRecord, ProviderProvenanceSchedulerStitchedReportViewEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionListPayload, ProviderProvenanceSchedulerNarrativeBulkGovernanceResult, ProviderProvenanceSchedulerNarrativeGovernancePlan, ProviderProvenanceSchedulerNarrativeGovernancePlanBatchResult, ProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyStep, ProviderProvenanceSchedulerNarrativeGovernanceQueueView, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeRegistryEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionListPayload, ProviderProvenanceSchedulerNarrativeTemplateEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionListPayload, ProviderProvenanceScheduledReportEntry, ProviderProvenanceScheduledReportHistoryPayload, ProvenanceArtifactLineDetailView, ProvenanceArtifactLineMicroView, Run, RunComparison, RunHistoryFilter, RunHistorySurfaceKey, RunListBoundaryContract, RunListBoundaryEligibility, RunListBoundaryGroupKey, RunListBoundarySurfaceId, RunSurfaceCapabilities, RunSurfaceCapabilityFamily, RunSurfaceCapabilityFamilyContract, RunSurfaceCapabilityFamilyKey, RunSurfaceCapabilitySchemaContract, RunSurfaceCapabilitySurfaceKey, RunSurfaceCollectionQueryBuilderReplayIntentSnapshot, RunSurfaceCollectionQueryBuilderReplayLinkAliasRecordPayload, RunSurfaceCollectionQueryBuilderReplayLinkRedactionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkRetentionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobDownloadPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobPrunePayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditPrunePayload, RunSurfaceCollectionQueryContract, RunSurfaceCollectionQueryElementField, RunSurfaceCollectionQueryExpressionAuthoring, RunSurfaceCollectionQueryParameterDomainDescriptor, RunSurfaceCollectionQuerySchema, RunSurfaceSharedContract, RunSurfaceSubresourceContract, SavedRunHistoryFilterPreset, SavedRunHistoryFilterPresetStateV1, Strategy, TouchGapWindowActivationFeedbackState, TouchGapWindowHoldProgressState, defaultRunForm, defaultPresetForm, defaultPresetRevisionFilter, defaultMarketDataProvenanceExportFilterState, defaultProviderProvenanceAnalyticsQueryState, defaultProviderProvenanceSchedulerSearchDashboardFilterState, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilter, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, defaultProviderProvenanceSchedulerSearchModerationQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationStageDraft, normalizeProviderProvenanceSchedulerRoutingPolicyDraftValue, normalizeProviderProvenanceSchedulerApprovalPolicyDraftValue, buildProviderProvenanceSchedulerExportPolicyDraft, getProviderProvenanceSchedulerNarrativeGovernanceQueuePriorityRank, getProviderProvenanceSchedulerNarrativeGovernanceQueueState, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchySummary, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepSummary, formatProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyPosition, isProviderProvenanceSchedulerAlertCategory, getOperatorAlertOccurrenceKey, formatProviderProvenanceSchedulerTimelineSummary, formatProviderProvenanceSchedulerSearchMatchSummary, formatProviderProvenanceSchedulerRetrievalClusterSummary, buildProviderProvenanceSchedulerAlertWorkflowReason, defaultProviderProvenanceDashboardLayout, DEFAULT_PROVIDER_PROVENANCE_SCHEDULER_NARRATIVE_GOVERNANCE_QUEUE_SORT, defaultProviderProvenanceWorkspaceDraft, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraft, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraft, KEEP_CURRENT_BULK_GOVERNANCE_VALUE, CLEAR_TEMPLATE_LINK_BULK_GOVERNANCE_VALUE, defaultProviderProvenanceSchedulerNarrativeTemplateBulkDraft, defaultProviderProvenanceSchedulerStitchedReportViewBulkDraft, defaultProviderProvenanceSchedulerNarrativeRegistryDraft, defaultProviderProvenanceSchedulerNarrativeRegistryBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceQueueFilter, defaultProviderProvenanceSchedulerStitchedReportGovernanceQueueFilter, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilter, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilter, defaultProviderProvenanceSchedulerStitchedReportViewAuditFilter, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilter, defaultProviderProvenanceReportDraft, buildPresetFormFromPreset, buildCurrentPresetRevisionSnapshot, buildEmptyPresetRevisionSnapshot, formatPresetStructuredDiffDisplayValue, isPresetStructuredDiffObject, isPresetStructuredDiffScalar, arePresetStructuredDiffValuesEquivalent, matchesPresetParameterSchemaType, joinPresetStructuredDiffHints, tokenizePresetParameterPath, parsePresetTimeframeToMinutes, buildPresetRankedStringDelta, buildPresetParameterStrategyContext, buildPresetParameterDomainContext, formatPresetParameterSchemaHint, getPresetParameterSchemaEntry, buildPresetStructuredDiffDelta, summarizePresetStructuredDiffGroup, groupPresetStructuredDiffRows, buildPresetStructuredDiffRows, describePresetRevisionDiff, describePresetDraftConflict, matchesPresetRevisionFilter, defaultRunHistoryFilter, sanitizeRunHistoryFilter, cloneRunHistoryFilter, hasRunHistoryFilterCriteria, areRunHistoryFiltersEquivalent, buildRunHistorySavedFilterStorageKey, normalizeSavedRunHistoryFilterPreset, loadSavedRunHistoryFilterPresets, persistSavedRunHistoryFilterPresets, describeRunHistoryFilter, DEFAULT_COMPARISON_INTENT, comparisonIntentOptions, parseExperimentTags, parseJsonObjectInput, formatPresetLifecycleStage, buildRunSubmissionPayload, normalizeRunFormPreset, resolveMarketDataSymbol, buildMarketDataInstrumentFocusKey, isMarketDataInstrumentAtRisk, resolvePreferredMarketDataInstrument, formatWorkflowToken, formatMarketContextFieldProvenance, summarizeProviderRecoveryMarketContextProvenance, serializeLinkedMarketInstrumentContext, getOperatorSeverityRank, normalizeMarketDataProvenanceExportSort, normalizeMarketDataProvenanceExportFilterState, normalizeMarketDataProvenanceExportHistoryEntry, loadPersistedMarketDataProvenanceExportState, persistMarketDataProvenanceExportState, formatMarketDataProvenanceExportFilterSummary, formatProviderProvenanceAnalyticsQuerySummary, normalizeProviderProvenanceDashboardLayoutState, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueSort, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkQueueViewPatch, formatProviderProvenanceSchedulerNarrativeGovernanceQueueSortLabel, providerProvenanceSchedulerNarrativeGovernancePolicySupportsItemType, formatProviderProvenanceSchedulerNarrativeGovernanceQueueViewSummary, buildProviderProvenanceAnalyticsWorkspaceQuery, buildProviderProvenanceAnalyticsQueryStateFromWorkspaceQuery, formatProviderProvenanceSchedulerNarrativeFacet, resolveProviderProvenanceSeriesBarWidth, formatProviderDriftIntensity, formatSchedulerLagSeconds, downloadTextExport, escapeRegExp, normalizeMarketSymbol, buildMarketSymbolSearchVariants, matchesMarketSymbolInText, dedupeMarketDataInstruments, formatMarketDataInstrumentLabel, getMarketDataInstrumentSyncSeverityRank, getMarketDataInstrumentRiskScore, buildLiveMarketDataPreference, getMarketDataInstrumentLiveRelevance, selectPrimaryMarketDataInstrument, extractMatchingMarketTimeframe, extractMatchingMarketSymbols, buildLinkedMarketInstrumentContext, buildLinkedMarketInstrumentContextFromPayload, formatLinkedMarketPrimaryFocusNote, resolveInstrumentsBySymbolsAndTimeframe, resolveMarketDataInstrumentLink, getAlertLinkPriority, compareAlertLinkPriority, resolveAutoLinkedMarketInstrument, formatTimestamp, formatProviderRecoverySchema, formatProviderRecoveryTelemetry, shortenIdentifier, truncateLabel, formatRange, benchmarkArtifactSummaryOrder, benchmarkArtifactSummaryLabels, benchmarkArtifactSectionOrder, benchmarkArtifactSectionLabels, formatBenchmarkArtifactSummaryEntries, benchmarkArtifactSummarySortIndex, formatBenchmarkArtifactSummaryLabel, formatBenchmarkArtifactSummaryValue, formatBenchmarkArtifactSectionEntries, benchmarkArtifactSectionSortIndex, formatBenchmarkArtifactSectionLabel, formatBenchmarkArtifactSectionLines, formatBenchmarkArtifactSectionValue, formatBenchmarkArtifactInlineValue, ProviderProvenanceAnalyticsScope, ProviderProvenanceSchedulerOccurrenceNarrativeFacet, ProviderProvenanceAnalyticsQueryState, ProviderProvenanceSchedulerSearchDashboardFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, ProviderProvenanceSchedulerSearchModerationQueueFilterState, ProviderProvenanceSchedulerSearchModerationStageDraft, ProviderProvenanceSchedulerExportPolicyDraft, OperatorVisibilityAlertEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraftState, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraftState, ProviderProvenanceSchedulerNarrativeBulkToggleValue, ProviderProvenanceSchedulerNarrativeTemplateBulkDraftState, ProviderProvenanceSchedulerStitchedReportViewBulkDraftState, ProviderProvenanceSchedulerNarrativeRegistryDraftState, ProviderProvenanceSchedulerNarrativeRegistryBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraftState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepVersionEntry, ProviderProvenanceSchedulerNarrativeGovernanceQueueFilterState, ProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterState, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilterState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilterState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilterState, ProviderProvenanceSchedulerStitchedReportViewAuditFilterState, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilterState, ProviderProvenanceReportDraftState, LinkedMarketInstrumentContext, MarketDataLinkableAlertRecord, MarketDataIncidentHistoryEntry, ProviderRecoveryMarketContextSummary, MarketDataProviderProvenanceEventRecord, MarketDataPrimaryFocusSelection } from "./ControlRoomViewHelpersContext";
import { PanelDisclosure, BackfillCountStatus, BackfillQualityStatus, SyncCheckpointStatus, SyncFailureStatus, formatCompletion, summarizeGapWindows, formatGapWindows, buildLegacyGapWindowKey, buildGapWindowKey, parseGapWindowKey, formatGapWindowKeyLabel, normalizeExpandedGapWindowSelectionList, resolveGapWindowSelectionList, buildGapWindowSelectionUpdate, isSameGapWindowSelectionList, filterExpandedGapWindowSelections, buildGapWindowSelectionLookup, instrumentGapRowKey, toggleExpandedGapRow, pruneExpandedGapRows, pruneExpandedGapWindowSelections } from "./ControlRoomViewStatusPanels";
import { normalizeComparisonHistoryPanelUiState, normalizeComparisonHistorySyncAuditFilter, normalizeComparisonHistoryPanelSyncState, normalizeComparisonHistoryPanelState, normalizeComparisonHistoryPanelEntry, normalizeComparisonHistorySyncAuditEntry, normalizeComparisonHistorySyncConflictReview, normalizeComparisonHistorySyncConflictSelectedSources, normalizeComparisonHistorySyncPreferenceReview, normalizeComparisonHistorySyncWorkspaceReview, normalizeComparisonHistorySyncPreferenceState, normalizeComparisonHistorySyncWorkspaceState, normalizeComparisonHistorySyncPreferenceSelectedSources, normalizeComparisonHistorySyncWorkspaceSelectedSources, limitComparisonHistorySyncAuditEntries, appendComparisonHistorySyncAuditEntries, isSameComparisonHistoryPanelState, isSameComparisonHistoryPanelSyncState, isSameComparisonHistoryPanelEntry, getComparisonHistoryPanelEntryChangedFields, formatComparisonHistorySyncConflictScoreLinkValue, formatComparisonHistorySyncConflictRunSelectionValue, formatComparisonHistorySyncConflictFieldValue, hasComparisonHistorySyncConflictFieldDifference, buildDefaultComparisonHistorySyncConflictSelectedSources, buildComparisonHistorySyncConflictReview, buildComparisonHistorySyncConflictReviewGroups, summarizeComparisonHistoryPanelEntryConflict, formatComparisonHistorySyncConflictResolutionSummary, resolveComparisonHistorySyncConflictReviewEntry, applyResolvedComparisonHistoryPanelEntry, summarizeComparisonHistorySyncPreferenceChanges, buildComparisonHistorySyncPreferenceState, formatComparisonHistorySyncPreferenceFieldValue, hasComparisonHistorySyncPreferenceFieldDifference, buildDefaultComparisonHistorySyncPreferenceSelectedSources, buildComparisonHistorySyncPreferenceReview, buildComparisonHistorySyncPreferenceReviewRows, formatComparisonHistorySyncPreferenceResolutionSummary, resolveComparisonHistorySyncPreferenceReview } from "./ControlRoomViewComparisonNormalize";
import { listComparisonHistoryExpandedGapRowKeys, listComparisonHistoryExpandedGapRowDiffKeys, buildComparisonHistoryExpandedGapRowSelectionKey, parseComparisonHistoryExpandedGapRowSelectionKey, buildComparisonHistoryExpandedGapWindowSelectionKey, parseComparisonHistoryExpandedGapWindowSelectionKey, listComparisonHistoryExpandedGapWindowDiffKeys, isSameComparisonHistoryExpandedGapRows, isSameExpandedGapWindowSelections, formatComparisonHistoryExpandedGapRowKey, formatComparisonHistoryExpandedGapRowsValue, formatComparisonHistoryExpandedGapRowsDiffValue, formatComparisonHistorySyncWorkspaceSelectionKeyLabel, rankComparisonHistorySyncWorkspaceSelectionKey, ComparisonHistorySyncWorkspaceSemanticRanking, listComparisonHistorySyncWorkspaceDiffSelectionKeys, resolveComparisonHistorySyncWorkspaceFieldSource, listComparisonHistorySyncWorkspaceConflictSelectionKeys, scoreComparisonHistorySyncWorkspaceCandidateSource, sortComparisonHistorySyncWorkspaceSemanticSignals, rankComparisonHistorySyncWorkspaceFieldSemantics, buildComparisonHistorySyncWorkspaceRecommendedSources, summarizeComparisonHistorySyncWorkspaceChanges, buildComparisonHistorySyncWorkspaceState, formatComparisonHistorySyncWorkspaceFieldValue, hasComparisonHistorySyncWorkspaceFieldDifference, buildDefaultComparisonHistorySyncWorkspaceSelectedSources, buildComparisonHistorySyncWorkspaceReview, buildComparisonHistorySyncWorkspaceReviewRows, buildComparisonHistorySyncWorkspaceRecommendationOverview, formatComparisonHistorySyncWorkspaceResolutionSummary, resolveComparisonHistorySyncWorkspaceReview, buildComparisonHistorySyncAuditEntries } from "./ControlRoomViewComparisonWorkspace";
import { loadLegacyExpandedGapRows, filterExpandedGapRows, normalizeControlRoomComparisonSelection, isSameComparisonSelection, formatComparisonHistoryPanelEntryMeta, matchesComparisonHistoryPanelEntry, formatComparisonHistorySyncAuditKindLabel, buildComparisonHistoryStepDescriptor, resolveComparisonHistoryRunLabel, normalizeComparisonRunIdList, normalizeComparisonIntent, normalizeComparisonScoreSection, normalizeComparisonScoreLinkSource, normalizeComparisonScoreLinkSubFocusKey, normalizeComparisonScoreLinkExpandedState, normalizeComparisonScoreLinkTooltipKey, normalizeComparisonScoreLinkArtifactLineDetailView, normalizeComparisonScoreLinkArtifactLineMicroView, normalizeComparisonScoreLinkArtifactLineNotePage, normalizeComparisonScoreLinkArtifactLineDetailHoverKey, normalizeComparisonScoreLinkArtifactLineScrubStep, normalizeComparisonScoreLinkArtifactHoverKey, normalizeComparisonScoreLinkTarget, isControlRoomUiStateV1, isControlRoomUiStateV2, isControlRoomUiStateV3, isControlRoomUiStateV4, buildRunsPath, buildRunComparisonPath, normalizeRunHistoryFilter, normalizeRunHistoryPresetFilter, getStrategyVersionOptions, pickLatestBenchmarkRun } from "./ControlRoomViewRunFilters";
import { StrategyColumn, PresetStructuredDiffPreview, PresetCatalogPanel, RunForm, ExperimentMetadataPills } from "./ControlRoomViewCatalogPanels";
import { RunListBoundarySurfaceContract, RunListBoundaryGroupContract, RunSurfaceCapabilityDiscoveryPanel, Metric, formatMetric, formatLineagePosture, formatLineageIndicator, formatComparisonScoreValue } from "./ControlRoomViewCapabilities";
import { buildComparisonScoreHighlights, buildComparisonScoreDetailRows, formatComparisonScoreHighlight, formatComparisonScoreComponentLabel, formatComparisonScoreLinkSourceLabel, encodeComparisonScoreLinkToken, decodeComparisonScoreLinkToken, buildComparisonProvenanceLineSubFocusKey, buildComparisonRunCardLineSubFocusKey, buildComparisonRunListLineSubFocusKey, buildComparisonRunListOrderPreviewSubFocusKey, buildComparisonRunListDataSymbolSubFocusKey, buildComparisonProvenanceArtifactSubFocusKey, buildComparisonProvenanceArtifactSectionSubFocusKey, buildComparisonProvenanceArtifactSummaryHoverKey, buildComparisonProvenanceArtifactSectionLineHoverKey, buildComparisonProvenanceArtifactLineDetailHoverKey, buildComparisonMetricTooltipKey, formatComparisonScoreLinkSubFocusLabel, formatComparisonScoreLinkTooltipLabel, formatComparisonScoreLinkArtifactHoverLabel, formatComparisonScoreLinkArtifactLineDetailViewLabel, formatComparisonScoreLinkArtifactLineMicroViewLabel, formatComparisonScoreLinkArtifactLineDetailHoverLabel, formatComparisonScoreComponentDetail, buildComparisonScoreComponentDetails, formatComparisonScoreComponentRawValue, formatComparisonScoreSignedValue, getComparisonScoreLinkedRunRole, isSameComparisonScoreLinkTarget, isSameComparisonScoreLinkSurface, resolveComparisonScoreDrillBackTarget, isComparisonScoreLinkMatch, formatEditableNumber } from "./ControlRoomViewComparisonLinks";
import { formatFixedNumber, buildLiveOrderDraftKey, formatComparisonMetric, formatComparisonDelta, formatComparisonNarrativeLabel, formatComparisonIntentLabel, formatComparisonIntentLegend, formatComparisonIntentTooltip, formatComparisonCueTooltip, buildComparisonCellTooltip, getComparisonIntentClassName, formatLaneLabel, formatVersionLineage, extractDefaultParameters, formatParameterMap, formatParameterValue, summarizeRunNotes } from "./ControlRoomViewFormatting";

export function loadExpandedGapRows() {
  const persistedState = loadControlRoomUiState();
  if (persistedState) {
    return persistedState.expandedGapRows;
  }
  return loadLegacyExpandedGapRows();
}

export function loadExpandedGapWindowSelections() {
  return loadControlRoomUiState()?.expandedGapWindowSelections ?? {};
}

export function defaultControlRoomComparisonSelectionState(): ControlRoomComparisonSelectionState {
  return {
    selectedRunIds: [],
    intent: DEFAULT_COMPARISON_INTENT,
    scoreLink: null,
  };
}

export function loadPersistedComparisonSelection(): ControlRoomComparisonSelectionState {
  const urlSelection = loadComparisonSelectionFromUrl();
  if (urlSelection) {
    return urlSelection;
  }
  return loadControlRoomUiState()?.comparisonSelection ?? defaultControlRoomComparisonSelectionState();
}

export function defaultComparisonHistoryPanelState(): ComparisonHistoryPanelState {
  return {
    entries: [],
    activeEntryId: null,
  };
}

export function defaultComparisonHistoryPanelUiState(): ControlRoomComparisonHistoryPanelUiState {
  return {
    open: false,
    panel: defaultComparisonHistoryPanelState(),
    searchQuery: "",
    showPinnedOnly: false,
    auditFilter: "all",
    showResolvedAuditEntries: true,
    expandedConflictReviewIds: {},
    expandedWorkspaceScoreDetailIds: {},
    focusedWorkspaceScoreDetailSources: {},
    focusedWorkspaceScoreDetailSignalKeys: {},
    expandedWorkspaceScoreSignalDetailIds: {},
    collapsedWorkspaceScoreSignalSubviewIds: {},
    collapsedWorkspaceScoreSignalNestedSubviewIds: {},
    focusedWorkspaceScoreSignalMicroViews: {},
    focusedWorkspaceScoreSignalMicroInteractions: {},
    hoveredWorkspaceScoreSignalMicroTargets: {},
    scrubbedWorkspaceScoreSignalMicroSteps: {},
    selectedWorkspaceScoreSignalMicroNotePages: {},
    activeWorkspaceOverviewRowId: null,
    sync: null,
  };
}

export function loadPersistedComparisonHistoryPanelUiState(): ControlRoomComparisonHistoryPanelUiState {
  return loadControlRoomUiState()?.comparisonHistoryPanel ?? defaultComparisonHistoryPanelUiState();
}

export function loadControlRoomUiState(): ControlRoomUiStateV4 | null {
  if (typeof window === "undefined") {
    return null;
  }
  return readControlRoomUiStateValue(window.localStorage.getItem(CONTROL_ROOM_UI_STATE_STORAGE_KEY));
}

export function readControlRoomUiStateValue(raw: string | null): ControlRoomUiStateV4 | null {
  if (!raw) {
    return null;
  }
  try {
    const parsed = JSON.parse(raw);
    if (isControlRoomUiStateV4(parsed)) {
      return {
        version: parsed.version,
        expandedGapRows: filterExpandedGapRows(parsed.expandedGapRows),
        expandedGapWindowSelections: filterExpandedGapWindowSelections(parsed.expandedGapWindowSelections),
        comparisonSelection: normalizeControlRoomComparisonSelection(parsed.comparisonSelection),
        comparisonHistoryPanel: normalizeComparisonHistoryPanelUiState(parsed.comparisonHistoryPanel),
      };
    }
    if (isControlRoomUiStateV3(parsed)) {
      return {
        version: CONTROL_ROOM_UI_STATE_VERSION,
        expandedGapRows: filterExpandedGapRows(parsed.expandedGapRows),
        expandedGapWindowSelections: {},
        comparisonSelection: normalizeControlRoomComparisonSelection(parsed.comparisonSelection),
        comparisonHistoryPanel: normalizeComparisonHistoryPanelUiState(parsed.comparisonHistoryPanel),
      };
    }
    if (isControlRoomUiStateV2(parsed)) {
      return {
        version: CONTROL_ROOM_UI_STATE_VERSION,
        expandedGapRows: filterExpandedGapRows(parsed.expandedGapRows),
        expandedGapWindowSelections: {},
        comparisonSelection: normalizeControlRoomComparisonSelection(parsed.comparisonSelection),
        comparisonHistoryPanel: defaultComparisonHistoryPanelUiState(),
      };
    }
    if (!isControlRoomUiStateV1(parsed)) {
      return null;
    }
    return {
      version: CONTROL_ROOM_UI_STATE_VERSION,
      expandedGapRows: filterExpandedGapRows(parsed.expandedGapRows),
      expandedGapWindowSelections: {},
      comparisonSelection: defaultControlRoomComparisonSelectionState(),
      comparisonHistoryPanel: defaultComparisonHistoryPanelUiState(),
    };
  } catch {
    return null;
  }
}

export function persistControlRoomUiState(state: {
  comparisonSelection: ControlRoomComparisonSelectionState;
  comparisonHistoryPanel: ControlRoomComparisonHistoryPanelUiState;
  expandedGapRows: Record<string, boolean>;
  expandedGapWindowSelections: ExpandedGapWindowSelections;
}) {
  if (typeof window === "undefined") {
    return;
  }
  try {
    const nextState: ControlRoomUiStateV4 = {
      version: CONTROL_ROOM_UI_STATE_VERSION,
      comparisonSelection: normalizeControlRoomComparisonSelection(state.comparisonSelection),
      comparisonHistoryPanel: normalizeComparisonHistoryPanelUiState(state.comparisonHistoryPanel),
      expandedGapRows: filterExpandedGapRows(state.expandedGapRows),
      expandedGapWindowSelections: filterExpandedGapWindowSelections(state.expandedGapWindowSelections),
    };
    window.localStorage.setItem(
      CONTROL_ROOM_UI_STATE_STORAGE_KEY,
      JSON.stringify(nextState),
    );
    window.localStorage.removeItem(LEGACY_GAP_WINDOW_EXPANSION_STORAGE_KEY);
  } catch {
    return;
  }
}

export function loadComparisonHistorySyncAuditTrail(
  tabId: string,
): ComparisonHistorySyncAuditEntry[] {
  if (typeof window === "undefined") {
    return [];
  }
  try {
    const raw = window.sessionStorage.getItem(COMPARISON_HISTORY_SYNC_AUDIT_SESSION_KEY);
    if (!raw) {
      return [];
    }
    const parsed = JSON.parse(raw) as Partial<ComparisonHistorySyncAuditTrailState> | null;
    if (
      !parsed
      || parsed.version !== COMPARISON_HISTORY_SYNC_AUDIT_SESSION_VERSION
      || typeof parsed.tabId !== "string"
      || parsed.tabId !== tabId
      || !Array.isArray(parsed.entries)
    ) {
      return [];
    }
    return limitComparisonHistorySyncAuditEntries(
      parsed.entries
        .map((entry) => normalizeComparisonHistorySyncAuditEntry(entry))
        .filter((entry): entry is ComparisonHistorySyncAuditEntry => entry !== null),
    );
  } catch {
    return [];
  }
}

export function persistComparisonHistorySyncAuditTrail(
  tabId: string,
  entries: ComparisonHistorySyncAuditEntry[],
) {
  if (typeof window === "undefined") {
    return;
  }
  try {
    const nextState: ComparisonHistorySyncAuditTrailState = {
      version: COMPARISON_HISTORY_SYNC_AUDIT_SESSION_VERSION,
      tabId,
      entries: limitComparisonHistorySyncAuditEntries(entries),
    };
    window.sessionStorage.setItem(COMPARISON_HISTORY_SYNC_AUDIT_SESSION_KEY, JSON.stringify(nextState));
  } catch {
    return;
  }
}

export function loadComparisonSelectionFromUrl(): ControlRoomComparisonSelectionState | null {
  if (typeof window === "undefined") {
    return null;
  }
  const params = new URLSearchParams(window.location.search);
  const hasComparisonParams = [
    COMPARISON_RUN_ID_SEARCH_PARAM,
    COMPARISON_INTENT_SEARCH_PARAM,
    COMPARISON_FOCUS_RUN_ID_SEARCH_PARAM,
    COMPARISON_FOCUS_SECTION_SEARCH_PARAM,
    COMPARISON_FOCUS_COMPONENT_SEARCH_PARAM,
    COMPARISON_FOCUS_SOURCE_SEARCH_PARAM,
    COMPARISON_FOCUS_ORIGIN_RUN_ID_SEARCH_PARAM,
    COMPARISON_FOCUS_DETAIL_SEARCH_PARAM,
    COMPARISON_FOCUS_EXPANDED_SEARCH_PARAM,
    COMPARISON_FOCUS_ARTIFACT_EXPANDED_SEARCH_PARAM,
    COMPARISON_FOCUS_ARTIFACT_LINE_EXPANDED_SEARCH_PARAM,
    COMPARISON_FOCUS_ARTIFACT_LINE_VIEW_SEARCH_PARAM,
    COMPARISON_FOCUS_ARTIFACT_LINE_MICRO_VIEW_SEARCH_PARAM,
    COMPARISON_FOCUS_ARTIFACT_LINE_NOTE_PAGE_SEARCH_PARAM,
    COMPARISON_FOCUS_ARTIFACT_LINE_HOVER_SEARCH_PARAM,
    COMPARISON_FOCUS_ARTIFACT_LINE_SCRUB_SEARCH_PARAM,
    COMPARISON_FOCUS_TOOLTIP_SEARCH_PARAM,
    COMPARISON_FOCUS_ARTIFACT_HOVER_SEARCH_PARAM,
  ].some((key) => params.has(key));
  if (!hasComparisonParams) {
    return null;
  }
  const selectedRunIds = normalizeComparisonRunIdList(params.getAll(COMPARISON_RUN_ID_SEARCH_PARAM));
  const intent = normalizeComparisonIntent(params.get(COMPARISON_INTENT_SEARCH_PARAM));
  const focusRunId = params.get(COMPARISON_FOCUS_RUN_ID_SEARCH_PARAM)?.trim() ?? "";
  const focusSection = normalizeComparisonScoreSection(
    params.get(COMPARISON_FOCUS_SECTION_SEARCH_PARAM),
  );
  const focusComponent = params.get(COMPARISON_FOCUS_COMPONENT_SEARCH_PARAM)?.trim() ?? "";
  const focusSource = normalizeComparisonScoreLinkSource(
    params.get(COMPARISON_FOCUS_SOURCE_SEARCH_PARAM),
  ) ?? "drillback";
  const focusOriginRunId = params.get(COMPARISON_FOCUS_ORIGIN_RUN_ID_SEARCH_PARAM)?.trim() ?? "";
  const focusDetail = normalizeComparisonScoreLinkSubFocusKey(
    params.get(COMPARISON_FOCUS_DETAIL_SEARCH_PARAM),
  );
  const focusExpanded = normalizeComparisonScoreLinkExpandedState(
    params.get(COMPARISON_FOCUS_EXPANDED_SEARCH_PARAM),
  );
  const focusArtifactExpanded = normalizeComparisonScoreLinkExpandedState(
    params.get(COMPARISON_FOCUS_ARTIFACT_EXPANDED_SEARCH_PARAM),
  );
  const focusArtifactLineExpanded = normalizeComparisonScoreLinkExpandedState(
    params.get(COMPARISON_FOCUS_ARTIFACT_LINE_EXPANDED_SEARCH_PARAM),
  );
  const focusArtifactLineView = normalizeComparisonScoreLinkArtifactLineDetailView(
    params.get(COMPARISON_FOCUS_ARTIFACT_LINE_VIEW_SEARCH_PARAM),
  );
  const focusArtifactLineMicroView = normalizeComparisonScoreLinkArtifactLineMicroView(
    params.get(COMPARISON_FOCUS_ARTIFACT_LINE_MICRO_VIEW_SEARCH_PARAM),
  );
  const focusArtifactLineNotePage = normalizeComparisonScoreLinkArtifactLineNotePage(
    params.get(COMPARISON_FOCUS_ARTIFACT_LINE_NOTE_PAGE_SEARCH_PARAM),
  );
  const focusArtifactLineHoverKey = normalizeComparisonScoreLinkArtifactLineDetailHoverKey(
    params.get(COMPARISON_FOCUS_ARTIFACT_LINE_HOVER_SEARCH_PARAM),
  );
  const focusArtifactLineScrubStep = normalizeComparisonScoreLinkArtifactLineScrubStep(
    params.get(COMPARISON_FOCUS_ARTIFACT_LINE_SCRUB_SEARCH_PARAM),
  );
  const focusTooltipKey = normalizeComparisonScoreLinkTooltipKey(
    params.get(COMPARISON_FOCUS_TOOLTIP_SEARCH_PARAM),
  );
  const focusArtifactHoverKey = normalizeComparisonScoreLinkArtifactHoverKey(
    params.get(COMPARISON_FOCUS_ARTIFACT_HOVER_SEARCH_PARAM),
  );

  return {
    intent,
    scoreLink:
      focusRunId && focusSection && focusComponent
        ? {
            componentKey: focusComponent,
            detailExpanded: focusExpanded,
            artifactDetailExpanded: focusArtifactExpanded,
            artifactLineDetailExpanded: focusArtifactLineExpanded,
            artifactLineDetailView: focusArtifactLineView,
            artifactLineMicroView: focusArtifactLineMicroView,
            artifactLineNotePage: focusArtifactLineNotePage,
            artifactLineDetailHoverKey: focusArtifactLineHoverKey,
            artifactLineDetailScrubStep: focusArtifactLineScrubStep,
            narrativeRunId: focusRunId,
            originRunId: focusOriginRunId || null,
            section: focusSection,
            source: focusSource,
            subFocusKey: focusDetail,
            tooltipKey: focusTooltipKey,
            artifactHoverKey: focusArtifactHoverKey,
          }
        : null,
    selectedRunIds,
  };
}

export function buildComparisonSelectionHistoryUrl(
  selection: ControlRoomComparisonSelectionState,
  baseHref?: string,
) {
  const url =
    typeof window !== "undefined"
      ? new URL(baseHref ?? window.location.href)
      : new URL(baseHref ?? "http://localhost/");
  const params = url.searchParams;
  params.delete(COMPARISON_RUN_ID_SEARCH_PARAM);
  params.delete(COMPARISON_INTENT_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_RUN_ID_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_SECTION_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_COMPONENT_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_SOURCE_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_ORIGIN_RUN_ID_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_DETAIL_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_EXPANDED_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_ARTIFACT_EXPANDED_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_ARTIFACT_LINE_EXPANDED_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_ARTIFACT_LINE_VIEW_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_ARTIFACT_LINE_MICRO_VIEW_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_ARTIFACT_LINE_NOTE_PAGE_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_ARTIFACT_LINE_HOVER_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_ARTIFACT_LINE_SCRUB_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_TOOLTIP_SEARCH_PARAM);
  params.delete(COMPARISON_FOCUS_ARTIFACT_HOVER_SEARCH_PARAM);

  const normalizedSelection = normalizeControlRoomComparisonSelection(selection);
  normalizedSelection.selectedRunIds.forEach((runId) => params.append(COMPARISON_RUN_ID_SEARCH_PARAM, runId));
  if (normalizedSelection.intent !== DEFAULT_COMPARISON_INTENT || normalizedSelection.selectedRunIds.length) {
    params.set(COMPARISON_INTENT_SEARCH_PARAM, normalizedSelection.intent);
  }
  if (normalizedSelection.scoreLink && normalizedSelection.selectedRunIds.length) {
    params.set(COMPARISON_FOCUS_RUN_ID_SEARCH_PARAM, normalizedSelection.scoreLink.narrativeRunId);
    params.set(COMPARISON_FOCUS_SECTION_SEARCH_PARAM, normalizedSelection.scoreLink.section);
    params.set(COMPARISON_FOCUS_COMPONENT_SEARCH_PARAM, normalizedSelection.scoreLink.componentKey);
    params.set(COMPARISON_FOCUS_SOURCE_SEARCH_PARAM, normalizedSelection.scoreLink.source);
    if (normalizedSelection.scoreLink.originRunId) {
      params.set(COMPARISON_FOCUS_ORIGIN_RUN_ID_SEARCH_PARAM, normalizedSelection.scoreLink.originRunId);
    }
    if (normalizedSelection.scoreLink.subFocusKey) {
      params.set(COMPARISON_FOCUS_DETAIL_SEARCH_PARAM, normalizedSelection.scoreLink.subFocusKey);
    }
    if (normalizedSelection.scoreLink.detailExpanded !== null) {
      params.set(
        COMPARISON_FOCUS_EXPANDED_SEARCH_PARAM,
        normalizedSelection.scoreLink.detailExpanded ? "1" : "0",
      );
    }
    if (normalizedSelection.scoreLink.artifactDetailExpanded !== null) {
      params.set(
        COMPARISON_FOCUS_ARTIFACT_EXPANDED_SEARCH_PARAM,
        normalizedSelection.scoreLink.artifactDetailExpanded ? "1" : "0",
      );
    }
    if (normalizedSelection.scoreLink.artifactLineDetailExpanded !== null) {
      params.set(
        COMPARISON_FOCUS_ARTIFACT_LINE_EXPANDED_SEARCH_PARAM,
        normalizedSelection.scoreLink.artifactLineDetailExpanded ? "1" : "0",
      );
    }
    if (normalizedSelection.scoreLink.artifactLineDetailView) {
      params.set(
        COMPARISON_FOCUS_ARTIFACT_LINE_VIEW_SEARCH_PARAM,
        normalizedSelection.scoreLink.artifactLineDetailView,
      );
    }
    if (normalizedSelection.scoreLink.artifactLineMicroView) {
      params.set(
        COMPARISON_FOCUS_ARTIFACT_LINE_MICRO_VIEW_SEARCH_PARAM,
        normalizedSelection.scoreLink.artifactLineMicroView,
      );
    }
    if (normalizedSelection.scoreLink.artifactLineNotePage !== null) {
      params.set(
        COMPARISON_FOCUS_ARTIFACT_LINE_NOTE_PAGE_SEARCH_PARAM,
        String(normalizedSelection.scoreLink.artifactLineNotePage),
      );
    }
    if (normalizedSelection.scoreLink.artifactLineDetailHoverKey) {
      params.set(
        COMPARISON_FOCUS_ARTIFACT_LINE_HOVER_SEARCH_PARAM,
        normalizedSelection.scoreLink.artifactLineDetailHoverKey,
      );
    }
    if (normalizedSelection.scoreLink.artifactLineDetailScrubStep !== null) {
      params.set(
        COMPARISON_FOCUS_ARTIFACT_LINE_SCRUB_SEARCH_PARAM,
        String(normalizedSelection.scoreLink.artifactLineDetailScrubStep),
      );
    }
    if (normalizedSelection.scoreLink.tooltipKey) {
      params.set(COMPARISON_FOCUS_TOOLTIP_SEARCH_PARAM, normalizedSelection.scoreLink.tooltipKey);
    }
    if (normalizedSelection.scoreLink.artifactHoverKey) {
      params.set(
        COMPARISON_FOCUS_ARTIFACT_HOVER_SEARCH_PARAM,
        normalizedSelection.scoreLink.artifactHoverKey,
      );
    }
  }
  const nextSearch = params.toString();
  return `${url.pathname}${nextSearch ? `?${nextSearch}` : ""}${url.hash}`;
}

export function readComparisonHistoryBrowserState(value: unknown): ComparisonHistoryBrowserState | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return null;
  }
  const candidate = (value as Record<string, unknown>)[COMPARISON_HISTORY_BROWSER_STATE_KEY];
  if (!candidate || typeof candidate !== "object" || Array.isArray(candidate)) {
    return null;
  }
  const parsed = candidate as Partial<ComparisonHistoryBrowserState>;
  if (
    parsed.version !== COMPARISON_HISTORY_BROWSER_STATE_VERSION
    || typeof parsed.entryId !== "string"
    || typeof parsed.stepIndex !== "number"
    || typeof parsed.label !== "string"
    || typeof parsed.summary !== "string"
    || typeof parsed.title !== "string"
  ) {
    return null;
  }
  return {
    version: parsed.version,
    entryId: parsed.entryId,
    stepIndex: parsed.stepIndex,
    label: parsed.label,
    summary: parsed.summary,
    title: parsed.title,
    selection: normalizeControlRoomComparisonSelection(parsed.selection),
  };
}

export function buildComparisonHistoryBrowserState(
  currentState: unknown,
  selection: ControlRoomComparisonSelectionState,
  step: ComparisonHistoryStepDescriptor,
  entryId: string,
  stepIndex: number,
) {
  const nextState =
    currentState && typeof currentState === "object" && !Array.isArray(currentState)
      ? { ...(currentState as Record<string, unknown>) }
      : {};
  nextState[COMPARISON_HISTORY_BROWSER_STATE_KEY] = {
    version: COMPARISON_HISTORY_BROWSER_STATE_VERSION,
    entryId,
    stepIndex,
    label: step.label,
    summary: step.summary,
    title: step.title,
    selection: normalizeControlRoomComparisonSelection(selection),
  } satisfies ComparisonHistoryBrowserState;
  return nextState;
}

export function isSameComparisonHistoryBrowserState(
  left: ComparisonHistoryBrowserState | null,
  right: ComparisonHistoryBrowserState | null,
) {
  if (left === right) {
    return true;
  }
  if (!left || !right) {
    return false;
  }
  return (
    left.label === right.label
    && left.summary === right.summary
    && left.title === right.title
    && left.stepIndex === right.stepIndex
    && isSameComparisonSelection(left.selection, right.selection)
  );
}

export function persistComparisonSelectionToUrl(
  selection: ControlRoomComparisonSelectionState,
  step: ComparisonHistoryStepDescriptor,
  entryId: string,
  stepIndex: number,
  mode: Exclude<ComparisonHistoryWriteMode, "skip"> = "replace",
) {
  if (typeof window === "undefined") {
    return;
  }
  const nextUrl = buildComparisonSelectionHistoryUrl(selection);
  const nextState = buildComparisonHistoryBrowserState(
    window.history.state,
    selection,
    step,
    entryId,
    stepIndex,
  );
  if (typeof document !== "undefined") {
    document.title = step.title;
  }
  if (mode === "push") {
    window.history.pushState(nextState, step.title, nextUrl);
    return;
  }
  window.history.replaceState(nextState, step.title, nextUrl);
}

export function buildComparisonHistoryEntryId() {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  return `compare-step-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

export function buildComparisonHistoryTabId() {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  return `compare-tab-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

export function formatComparisonHistoryTabLabel(tabId: string) {
  return `Tab ${tabId.replace(/[^a-z0-9]/gi, "").slice(0, 4).toUpperCase() || "SYNC"}`;
}

export function loadComparisonHistoryTabIdentity(): ComparisonHistoryTabIdentity {
  const fallbackTabId = buildComparisonHistoryTabId();
  if (typeof window === "undefined") {
    return {
      tabId: fallbackTabId,
      label: formatComparisonHistoryTabLabel(fallbackTabId),
    };
  }
  try {
    const existingTabId = window.sessionStorage.getItem(COMPARISON_HISTORY_TAB_ID_SESSION_KEY)?.trim();
    const tabId = existingTabId || fallbackTabId;
    if (!existingTabId) {
      window.sessionStorage.setItem(COMPARISON_HISTORY_TAB_ID_SESSION_KEY, tabId);
    }
    return {
      tabId,
      label: formatComparisonHistoryTabLabel(tabId),
    };
  } catch {
    return {
      tabId: fallbackTabId,
      label: formatComparisonHistoryTabLabel(fallbackTabId),
    };
  }
}

export function buildComparisonHistoryPanelSyncState(
  tabIdentity: ComparisonHistoryTabIdentity,
  updatedAt = new Date().toISOString(),
): ComparisonHistoryPanelSyncState {
  return {
    tabId: tabIdentity.tabId,
    tabLabel: tabIdentity.label,
    updatedAt,
  };
}

export function buildComparisonHistorySyncSignature(state: {
  comparisonSelection: ControlRoomComparisonSelectionState;
  comparisonHistoryPanel: ComparisonHistoryPanelState;
  expandedGapRows: Record<string, boolean>;
  expandedGapWindowSelections: ExpandedGapWindowSelections;
  historyBrowserOpen: boolean;
  historySearchQuery: string;
  showPinnedHistoryOnly: boolean;
  auditFilter: ComparisonHistorySyncAuditFilter;
  showResolvedAuditEntries: boolean;
}) {
  return JSON.stringify({
    comparisonSelection: normalizeControlRoomComparisonSelection(state.comparisonSelection),
    comparisonHistoryPanel: normalizeComparisonHistoryPanelState(state.comparisonHistoryPanel),
    expandedGapRowKeys: listComparisonHistoryExpandedGapRowKeys(state.expandedGapRows),
    expandedGapWindowSelections: filterExpandedGapWindowSelections(state.expandedGapWindowSelections),
    historyBrowserOpen: state.historyBrowserOpen,
    historySearchQuery: state.historySearchQuery.trim(),
    showPinnedHistoryOnly: state.showPinnedHistoryOnly,
    auditFilter: state.auditFilter,
    showResolvedAuditEntries: state.showResolvedAuditEntries,
  });
}

export function buildComparisonHistorySyncAuditId() {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  return `compare-sync-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

export function buildComparisonHistoryPanelEntry(
  browserState: ComparisonHistoryBrowserState,
  url: string,
): ComparisonHistoryPanelEntry {
  const now = new Date().toISOString();
  return {
    entryId: browserState.entryId,
    stepIndex: browserState.stepIndex,
    label: browserState.label,
    summary: browserState.summary,
    title: browserState.title,
    url,
    hidden: false,
    pinned: false,
    recordedAt: now,
    selection: normalizeControlRoomComparisonSelection(browserState.selection),
  };
}

export function findComparisonHistoryPanelEntryForSelection(
  panel: ComparisonHistoryPanelState,
  selection: ControlRoomComparisonSelectionState,
) {
  const matchingEntries = panel.entries.filter((entry) =>
    !entry.hidden && isSameComparisonSelection(entry.selection, selection),
  );
  if (!matchingEntries.length) {
    return null;
  }
  if (panel.activeEntryId) {
    const activeMatch = matchingEntries.find((entry) => entry.entryId === panel.activeEntryId);
    if (activeMatch) {
      return activeMatch;
    }
  }
  return matchingEntries[matchingEntries.length - 1] ?? null;
}

export function mergeComparisonHistoryPanelState(
  local: ComparisonHistoryPanelState,
  remote: ComparisonHistoryPanelState,
  selection: ControlRoomComparisonSelectionState,
): ComparisonHistoryPanelState {
  const mergedEntries = mergeComparisonHistoryPanelEntries(local.entries, remote.entries);
  const selectionMatch = findComparisonHistoryPanelEntryForSelection(
    {
      entries: mergedEntries,
      activeEntryId: local.activeEntryId,
    },
    selection,
  );
  if (selectionMatch) {
    return {
      entries: mergedEntries,
      activeEntryId: selectionMatch.entryId,
    };
  }
  if (local.activeEntryId && mergedEntries.some((entry) => entry.entryId === local.activeEntryId)) {
    return {
      entries: mergedEntries,
      activeEntryId: local.activeEntryId,
    };
  }
  if (remote.activeEntryId && mergedEntries.some((entry) => entry.entryId === remote.activeEntryId)) {
    return {
      entries: mergedEntries,
      activeEntryId: remote.activeEntryId,
    };
  }
  return {
    entries: mergedEntries,
    activeEntryId: mergedEntries[mergedEntries.length - 1]?.entryId ?? null,
  };
}

export function mergeComparisonHistoryPanelEntries(
  localEntries: ComparisonHistoryPanelEntry[],
  remoteEntries: ComparisonHistoryPanelEntry[],
) {
  const mergedEntries = new Map<string, ComparisonHistoryPanelEntry>();
  localEntries.forEach((entry) => {
    mergedEntries.set(entry.entryId, entry);
  });
  remoteEntries.forEach((entry) => {
    mergedEntries.set(entry.entryId, entry);
  });
  return limitComparisonHistoryPanelEntries(
    sortComparisonHistoryPanelEntries([...mergedEntries.values()]),
  );
}

export function reconcileComparisonHistoryPanelState(
  current: ComparisonHistoryPanelState,
  entry: ComparisonHistoryPanelEntry,
  mode: "push" | "replace" | "activate",
): ComparisonHistoryPanelState {
  const existingIndex = current.entries.findIndex((candidate) => candidate.entryId === entry.entryId);
  const existingEntry = existingIndex >= 0 ? current.entries[existingIndex] : null;
  const mergedEntry = existingEntry
    ? {
        ...entry,
        pinned: existingEntry.pinned,
        recordedAt: existingEntry.recordedAt,
      }
    : entry;

  if (mode === "activate") {
    if (existingIndex >= 0) {
      return {
        entries: sortComparisonHistoryPanelEntries(
          current.entries.map((candidate, index) => (index === existingIndex ? mergedEntry : candidate)),
        ),
        activeEntryId: mergedEntry.entryId,
      };
    }
    return {
      entries: limitComparisonHistoryPanelEntries(
        sortComparisonHistoryPanelEntries([...current.entries, mergedEntry]),
      ),
      activeEntryId: mergedEntry.entryId,
    };
  }

  if (mode === "push") {
    const activeStepIndex = current.activeEntryId
      ? current.entries.find((candidate) => candidate.entryId === current.activeEntryId)?.stepIndex ?? -1
      : -1;
    const baseEntries = current.entries.filter((candidate) => candidate.stepIndex <= activeStepIndex);
    const nextEntries = [...baseEntries.filter((candidate) => candidate.entryId !== mergedEntry.entryId), mergedEntry];
    return {
      entries: limitComparisonHistoryPanelEntries(sortComparisonHistoryPanelEntries(nextEntries)),
      activeEntryId: mergedEntry.entryId,
    };
  }

  if (existingIndex >= 0) {
    return {
      entries: sortComparisonHistoryPanelEntries(
        current.entries.map((candidate, index) => (index === existingIndex ? mergedEntry : candidate)),
      ),
      activeEntryId: mergedEntry.entryId,
    };
  }

  const activeIndex = current.activeEntryId
    ? current.entries.findIndex((candidate) => candidate.entryId === current.activeEntryId)
    : -1;
  if (activeIndex >= 0) {
    return {
      entries: sortComparisonHistoryPanelEntries(
        current.entries.map((candidate, index) => (index === activeIndex ? mergedEntry : candidate)),
      ),
      activeEntryId: mergedEntry.entryId,
    };
  }

  return {
    entries: [mergedEntry],
    activeEntryId: mergedEntry.entryId,
  };
}

export function sortComparisonHistoryPanelEntries(entries: ComparisonHistoryPanelEntry[]) {
  return [...entries].sort((left, right) => left.stepIndex - right.stepIndex);
}

export function limitComparisonHistoryPanelEntries(entries: ComparisonHistoryPanelEntry[]) {
  if (entries.length <= MAX_COMPARISON_HISTORY_PANEL_ENTRIES) {
    return entries;
  }
  const visibleEntries = entries.filter((entry) => !entry.hidden);
  const hiddenEntries = entries.filter((entry) => entry.hidden);
  const pinnedEntries = visibleEntries.filter((entry) => entry.pinned);
  if (pinnedEntries.length >= MAX_COMPARISON_HISTORY_PANEL_ENTRIES) {
    return sortComparisonHistoryPanelEntries(
      pinnedEntries.slice(-MAX_COMPARISON_HISTORY_PANEL_ENTRIES),
    );
  }
  const unpinnedEntries = visibleEntries.filter((entry) => !entry.pinned);
  return sortComparisonHistoryPanelEntries([
    ...pinnedEntries,
    ...unpinnedEntries.slice(-(MAX_COMPARISON_HISTORY_PANEL_ENTRIES - pinnedEntries.length)),
    ...hiddenEntries.slice(-MAX_COMPARISON_HISTORY_PANEL_ENTRIES),
  ]).slice(-MAX_COMPARISON_HISTORY_PANEL_ENTRIES);
}
