// @ts-nocheck

import { CSSProperties, FormEvent, KeyboardEvent, MouseEvent, PointerEvent, ReactNode, forwardRef, useCallback, useEffect, useId, useLayoutEffect, useMemo, useRef, useState, AKRA_TOUCH_FEEDBACK_BRIDGE_VERSION, AKRA_TOUCH_FEEDBACK_EVENT_NAME, AkraTouchFeedbackDetail, AkraTouchFeedbackEnvelope, triggerAkraTouchFeedbackBridge, WorkspaceShell, buildControlWorkspaceDescriptors, ControlWorkspaceDescriptor, ControlStripMetric, useWorkspaceRoute, WorkspaceRouteContent, buildRunHistoryWorkspacePanels, LiveOrderReplacementDraft, RunHistoryWorkspaceSectionProps, RunOrderControls, getRunListBoundaryContractSnapshot, getRunListBoundarySurfaceLabel, getRunSurfaceCapabilityFamily, getRunSurfaceCapabilityFamilyOrder, getRunSurfaceCapabilityGroupOrder, getRunSurfaceCapabilitySchemaContract, getRunSurfaceCollectionQueryContracts, getRunSurfaceSharedContracts, getRunSurfaceSubresourceContracts, RunListComparisonBoundaryNote, shouldEnableStrategyProvenanceSemantics, shouldEnableRunListMetricDrillBack, shouldEnableRunSnapshotSemantics, shouldEnableStrategyCatalogSchemaHints, shouldHydratePresetParameterDefaults, shouldRenderOrderActionBoundaryNote, shouldRenderWorkflowControlBoundaryNote, RunSurfaceCollectionQueryBuilder, formatComparisonTooltipTuningDelta, formatComparisonTooltipTuningValue, formatRelativeTimestampLabel, RunSection, RunSurfaceCollectionQueryBuilderApplyPayload, RunSurfaceCollectionQueryRuntimeCandidateContextSelection, RunSurfaceCollectionQueryRuntimeCandidateSample, applyProviderProvenanceSchedulerStitchedReportGovernancePlan, applyProviderProvenanceSchedulerNarrativeGovernancePlan, approveProviderProvenanceSchedulerStitchedReportGovernancePlan, approveProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceAnalyticsPreset, createProviderProvenanceDashboardView, createProviderProvenanceExportJob, createProviderProvenanceSchedulerStitchedReportGovernanceRegistry, createProviderProvenanceSchedulerStitchedReportGovernancePlan, createProviderProvenanceSchedulerStitchedReportView, createProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, captureProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchy, createProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, createProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceSchedulerNarrativeRegistryEntry, createProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceScheduledReport, approveProviderProvenanceExportJob, applyProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, deleteProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, deleteProviderProvenanceSchedulerNarrativeRegistryEntry, deleteProviderProvenanceSchedulerStitchedReportView, deleteProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, createRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, createRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, downloadProviderProvenanceExportJob, downloadRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, escalateProviderProvenanceExportJob, exportProviderProvenanceSchedulerHealth, exportProviderProvenanceSchedulerStitchedNarrativeReport, reconstructProviderProvenanceSchedulerHealthExport, exportRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, fetchJson, getProviderProvenanceExportAnalytics, getProviderProvenanceExportJobHistory, getProviderProvenanceSchedulerHealthAnalytics, getProviderProvenanceScheduledReportHistory, getRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobHistory, listProviderProvenanceAnalyticsPresets, listProviderProvenanceDashboardViews, listProviderProvenanceSchedulerStitchedReportViews, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogs, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplates, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePlans, listProviderProvenanceSchedulerNarrativeRegistryEntries, listProviderProvenanceSchedulerNarrativeRegistryRevisions, listProviderProvenanceSchedulerNarrativeTemplates, listProviderProvenanceSchedulerNarrativeTemplateRevisions, listProviderProvenanceSchedulerStitchedReportGovernancePolicyCatalogs, listProviderProvenanceSchedulerStitchedReportGovernancePolicyTemplates, listProviderProvenanceSchedulerStitchedReportGovernancePlans, rollbackProviderProvenanceSchedulerStitchedReportGovernancePlan, rollbackProviderProvenanceSchedulerNarrativeGovernancePlan, listMarketDataIngestionJobs, listMarketDataLineageHistory, listProviderProvenanceExportJobs, listProviderProvenanceSchedulerAlertHistory, listProviderProvenanceSchedulerHealthHistory, listProviderProvenanceSchedulerStitchedReportGovernanceRegistries, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryAudits, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisions, listProviderProvenanceSchedulerStitchedReportViewAudits, listProviderProvenanceSchedulerStitchedReportViewRevisions, getProviderProvenanceSchedulerSearchDashboard, bulkGovernProviderProvenanceSchedulerSearchModerationPolicyCatalogs, bulkGovernProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, createProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicy, createProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, listProviderProvenanceSchedulerSearchModerationPolicyCatalogs, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlans, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAudits, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisions, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePlans, listProviderProvenanceSchedulerSearchModerationPolicyCatalogAudits, listProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisions, listProviderProvenanceSchedulerSearchModerationPlans, listProviderProvenanceScheduledReports, listRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, listRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, approveProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, approveProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, approveProviderProvenanceSchedulerSearchModerationPlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, applyProviderProvenanceSchedulerSearchModerationPlan, createProviderProvenanceSchedulerSearchModerationPolicyCatalog, deleteProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, deleteProviderProvenanceSchedulerSearchModerationPolicyCatalog, moderateProviderProvenanceSchedulerSearchFeedbackBatch, moderateProviderProvenanceSchedulerSearchFeedback, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, recordProviderProvenanceSchedulerSearchFeedback, resolveRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevision, restoreProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevision, restoreProviderProvenanceSchedulerSearchModerationPolicyCatalogRevision, restoreProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevision, restoreProviderProvenanceSchedulerNarrativeRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportViewRevision, restoreProviderProvenanceSchedulerNarrativeTemplateRevision, revokeRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, runProviderProvenanceSchedulerNarrativeGovernancePlanBatchAction, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkGovernance, stageProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, stageProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, stageProviderProvenanceSchedulerSearchModerationPlan, updateProviderProvenanceSchedulerSearchModerationPolicyCatalog, updateProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, stageProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, runDueProviderProvenanceScheduledReports, runProviderProvenanceScheduledReport, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStep, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, updateProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, updateProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, updateProviderProvenanceSchedulerNarrativeRegistryEntry, updateProviderProvenanceSchedulerStitchedReportGovernanceRegistry, updateProviderProvenanceSchedulerStitchedReportView, updateProviderProvenanceSchedulerNarrativeTemplate, updateProviderProvenanceExportJobPolicy, deleteProviderProvenanceSchedulerStitchedReportGovernanceRegistry, ALL_FILTER_VALUE, apiBase, COMPARISON_FOCUS_ARTIFACT_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_MICRO_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_NOTE_PAGE_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_SCRUB_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_COMPONENT_SEARCH_PARAM, COMPARISON_FOCUS_DETAIL_SEARCH_PARAM, COMPARISON_FOCUS_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ORIGIN_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_SECTION_SEARCH_PARAM, COMPARISON_FOCUS_SOURCE_SEARCH_PARAM, COMPARISON_FOCUS_TOOLTIP_SEARCH_PARAM, COMPARISON_HISTORY_BROWSER_STATE_KEY, COMPARISON_HISTORY_BROWSER_STATE_VERSION, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_KEY, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_VERSION, COMPARISON_HISTORY_SYNC_CONFLICT_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_PREFERENCE_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_WORKSPACE_FIELD_DEFINITIONS, COMPARISON_HISTORY_TAB_ID_SESSION_KEY, COMPARISON_INTENT_SEARCH_PARAM, COMPARISON_RUN_ID_SEARCH_PARAM, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_KEY, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_VERSION, COMPARISON_TOOLTIP_TUNING_GROUPS, COMPARISON_TOOLTIP_TUNING_LABELS, COMPARISON_TOOLTIP_TUNING_SHARE_PARAM, COMPARISON_TOOLTIP_TUNING_STORAGE_KEY, COMPARISON_TOOLTIP_TUNING_STORAGE_VERSION, COMPARISON_TOOLTIP_UNCHANGED_GROUP_COLLAPSE_THRESHOLD, CONTROL_ROOM_UI_STATE_STORAGE_KEY, CONTROL_ROOM_UI_STATE_VERSION, DEFAULT_COMPARISON_TOOLTIP_PRESET_IMPORT_CONFLICT_POLICY, DEFAULT_COMPARISON_TOOLTIP_TUNING, DEFAULT_CONTROL_ROOM_DOCUMENT_TITLE, LEGACY_GAP_WINDOW_EXPANSION_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_VERSION, MAX_COMPARISON_HISTORY_PANEL_ENTRIES, MAX_COMPARISON_HISTORY_SYNC_AUDIT_ENTRIES, MAX_COMPARISON_RUNS, MAX_MARKET_DATA_PROVENANCE_EXPORT_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_REVIEWED_CONFLICT_KEYS, MAX_VISIBLE_COMPARISON_TOOLTIP_CONFLICT_SESSION_SUMMARIES, MAX_VISIBLE_GAP_WINDOWS, PRESET_PROFILE_AGGRESSIVENESS_RANKS, PRESET_PROFILE_CONFIDENCE_RANKS, PRESET_PROFILE_SPEED_RANKS, PRESET_TIMEFRAME_UNIT_TO_MINUTES, REPLAY_INTENT_ACTION_FILTER_SEARCH_PARAM, REPLAY_INTENT_ALIAS_SEARCH_PARAM, REPLAY_INTENT_EDGE_FILTER_SEARCH_PARAM, REPLAY_INTENT_GROUP_FILTER_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_DIFF_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_GROUP_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_TRACE_SEARCH_PARAM, REPLAY_INTENT_SCOPE_SEARCH_PARAM, REPLAY_INTENT_SEARCH_PARAM, REPLAY_INTENT_STEP_SEARCH_PARAM, REPLAY_INTENT_TEMPLATE_SEARCH_PARAM, RUN_HISTORY_SAVED_FILTER_STORAGE_KEY_PREFIX, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_TAB_ID_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_BROWSER_STATE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_PAYLOAD_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_SIGNING_SECRET_STORAGE_KEY, SHOW_COMPARISON_TOOLTIP_TUNING_PANEL, TOUCH_GAP_WINDOW_SWEEP_HOLD_MS, TOUCH_GAP_WINDOW_SWEEP_MOVE_TOLERANCE_PX, BenchmarkArtifact, ParameterSchema, ComparisonCueKind, ComparisonHistoryBrowserState, ComparisonHistoryPanelEntry, ComparisonHistoryPanelState, ComparisonHistoryPanelSyncState, ComparisonHistoryStepDescriptor, ComparisonHistorySyncAuditEntry, ComparisonHistorySyncAuditFilter, ComparisonHistorySyncAuditKind, ComparisonHistorySyncAuditTrailState, ComparisonHistorySyncConflictFieldKey, ComparisonHistorySyncConflictFieldSource, ComparisonHistorySyncConflictReview, ComparisonHistorySyncConflictReviewGroup, ComparisonHistorySyncPreferenceFieldKey, ComparisonHistorySyncPreferenceReview, ComparisonHistorySyncPreferenceReviewRow, ComparisonHistorySyncPreferenceState, ComparisonHistorySyncWorkspaceRecommendationOverview, ComparisonHistorySyncWorkspaceReview, ComparisonHistorySyncWorkspaceReviewRow, ComparisonHistorySyncWorkspaceReviewSelectionKey, ComparisonHistorySyncWorkspaceSemanticSignal, ComparisonHistorySyncWorkspaceSignalDetailNestedKey, ComparisonHistorySyncWorkspaceSignalDetailSubviewKey, ComparisonHistorySyncWorkspaceSignalMicroInteractionKey, ComparisonHistorySyncWorkspaceSignalMicroViewKey, ComparisonHistorySyncWorkspaceState, ComparisonHistoryTabIdentity, ComparisonHistoryWriteMode, ComparisonIntent, ComparisonScoreDrillBackOptions, ComparisonScoreLinkedRunRole, ComparisonScoreLinkSource, ComparisonScoreLinkTarget, ComparisonScoreSection, ComparisonTooltipConflictSessionSummary, ComparisonTooltipConflictSessionSummarySession, ComparisonTooltipConflictSessionUiState, ComparisonTooltipConflictUiStateV1, ComparisonTooltipInteractionOptions, ComparisonTooltipLayout, ComparisonTooltipPendingPresetImportConflict, ComparisonTooltipPresetConflictPreviewGroup, ComparisonTooltipPresetConflictPreviewRow, ComparisonTooltipPresetImportConflictPolicy, ComparisonTooltipPresetImportResolution, ComparisonTooltipTargetProps, ComparisonTooltipTuning, ComparisonTooltipTuningPresetStateV1, ComparisonTooltipTuningShareImport, ComparisonTooltipTuningSinglePresetShareV1, ControlRoomComparisonHistoryPanelUiState, ControlRoomComparisonSelectionState, ControlRoomUiStateV1, ControlRoomUiStateV2, ControlRoomUiStateV3, ControlRoomUiStateV4, ExpandedGapWindowSelections, ExperimentPreset, ExperimentPresetRevision, GapWindowDragSelectionState, GuardedLiveStatus, MarketDataIngestionJobRecord, MarketDataProvenanceExportFilterState, MarketDataProvenanceExportHistoryEntry, MarketDataProvenanceExportSort, MarketDataProvenanceExportStateV1, MarketDataLineageHistoryRecord, MarketDataStatus, OperatorAlertMarketContextProvenance, OperatorAlertPrimaryFocus, OperatorVisibility, PendingTouchGapWindowSweepState, PresetDraftConflict, PresetRevisionDiff, PresetRevisionFilterState, PresetStructuredDiffDeltaValue, PresetStructuredDiffGroup, PresetStructuredDiffRow, ProviderProvenanceAnalyticsPresetEntry, ProviderProvenanceDashboardLayout, ProviderProvenanceDashboardViewEntry, ProviderProvenanceExportAnalyticsPayload, ProviderProvenanceExportJobEntry, ProviderProvenanceExportJobEscalationResult, ProviderProvenanceExportJobHistoryPayload, ProviderProvenanceExportJobPolicyResult, ProviderProvenanceSchedulerAlertHistoryPayload, ProviderProvenanceSchedulerHealthExportPayload, ProviderProvenanceSchedulerHealthAnalyticsPayload, ProviderProvenanceSchedulerHealthHistoryPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditRecord, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditRecord, ProviderProvenanceSchedulerSearchModerationPlanListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogListPayload, ProviderProvenanceSchedulerSearchFeedbackBatchModerationResult, ProviderProvenanceSchedulerSearchDashboardPayload, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditRecord, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionListPayload, ProviderProvenanceSchedulerStitchedReportViewAuditRecord, ProviderProvenanceSchedulerStitchedReportViewEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionListPayload, ProviderProvenanceSchedulerNarrativeBulkGovernanceResult, ProviderProvenanceSchedulerNarrativeGovernancePlan, ProviderProvenanceSchedulerNarrativeGovernancePlanBatchResult, ProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyStep, ProviderProvenanceSchedulerNarrativeGovernanceQueueView, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeRegistryEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionListPayload, ProviderProvenanceSchedulerNarrativeTemplateEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionListPayload, ProviderProvenanceScheduledReportEntry, ProviderProvenanceScheduledReportHistoryPayload, ProvenanceArtifactLineDetailView, ProvenanceArtifactLineMicroView, Run, RunComparison, RunHistoryFilter, RunHistorySurfaceKey, RunListBoundaryContract, RunListBoundaryEligibility, RunListBoundaryGroupKey, RunListBoundarySurfaceId, RunSurfaceCapabilities, RunSurfaceCapabilityFamily, RunSurfaceCapabilityFamilyContract, RunSurfaceCapabilityFamilyKey, RunSurfaceCapabilitySchemaContract, RunSurfaceCapabilitySurfaceKey, RunSurfaceCollectionQueryBuilderReplayIntentSnapshot, RunSurfaceCollectionQueryBuilderReplayLinkAliasRecordPayload, RunSurfaceCollectionQueryBuilderReplayLinkRedactionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkRetentionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobDownloadPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobPrunePayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditPrunePayload, RunSurfaceCollectionQueryContract, RunSurfaceCollectionQueryElementField, RunSurfaceCollectionQueryExpressionAuthoring, RunSurfaceCollectionQueryParameterDomainDescriptor, RunSurfaceCollectionQuerySchema, RunSurfaceSharedContract, RunSurfaceSubresourceContract, SavedRunHistoryFilterPreset, SavedRunHistoryFilterPresetStateV1, Strategy, TouchGapWindowActivationFeedbackState, TouchGapWindowHoldProgressState, defaultRunForm, defaultPresetForm, defaultPresetRevisionFilter, defaultMarketDataProvenanceExportFilterState, defaultProviderProvenanceAnalyticsQueryState, defaultProviderProvenanceSchedulerSearchDashboardFilterState, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilter, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, defaultProviderProvenanceSchedulerSearchModerationQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationStageDraft, normalizeProviderProvenanceSchedulerRoutingPolicyDraftValue, normalizeProviderProvenanceSchedulerApprovalPolicyDraftValue, buildProviderProvenanceSchedulerExportPolicyDraft, getProviderProvenanceSchedulerNarrativeGovernanceQueuePriorityRank, getProviderProvenanceSchedulerNarrativeGovernanceQueueState, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchySummary, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepSummary, formatProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyPosition, isProviderProvenanceSchedulerAlertCategory, getOperatorAlertOccurrenceKey, formatProviderProvenanceSchedulerTimelineSummary, formatProviderProvenanceSchedulerSearchMatchSummary, formatProviderProvenanceSchedulerRetrievalClusterSummary, buildProviderProvenanceSchedulerAlertWorkflowReason, defaultProviderProvenanceDashboardLayout, DEFAULT_PROVIDER_PROVENANCE_SCHEDULER_NARRATIVE_GOVERNANCE_QUEUE_SORT, defaultProviderProvenanceWorkspaceDraft, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraft, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraft, KEEP_CURRENT_BULK_GOVERNANCE_VALUE, CLEAR_TEMPLATE_LINK_BULK_GOVERNANCE_VALUE, defaultProviderProvenanceSchedulerNarrativeTemplateBulkDraft, defaultProviderProvenanceSchedulerStitchedReportViewBulkDraft, defaultProviderProvenanceSchedulerNarrativeRegistryDraft, defaultProviderProvenanceSchedulerNarrativeRegistryBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceQueueFilter, defaultProviderProvenanceSchedulerStitchedReportGovernanceQueueFilter, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilter, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilter, defaultProviderProvenanceSchedulerStitchedReportViewAuditFilter, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilter, defaultProviderProvenanceReportDraft, buildPresetFormFromPreset, buildCurrentPresetRevisionSnapshot, buildEmptyPresetRevisionSnapshot, formatPresetStructuredDiffDisplayValue, isPresetStructuredDiffObject, isPresetStructuredDiffScalar, arePresetStructuredDiffValuesEquivalent, matchesPresetParameterSchemaType, joinPresetStructuredDiffHints, tokenizePresetParameterPath, parsePresetTimeframeToMinutes, buildPresetRankedStringDelta, buildPresetParameterStrategyContext, buildPresetParameterDomainContext, formatPresetParameterSchemaHint, getPresetParameterSchemaEntry, buildPresetStructuredDiffDelta, summarizePresetStructuredDiffGroup, groupPresetStructuredDiffRows, buildPresetStructuredDiffRows, describePresetRevisionDiff, describePresetDraftConflict, matchesPresetRevisionFilter, defaultRunHistoryFilter, sanitizeRunHistoryFilter, cloneRunHistoryFilter, hasRunHistoryFilterCriteria, areRunHistoryFiltersEquivalent, buildRunHistorySavedFilterStorageKey, normalizeSavedRunHistoryFilterPreset, loadSavedRunHistoryFilterPresets, persistSavedRunHistoryFilterPresets, describeRunHistoryFilter, DEFAULT_COMPARISON_INTENT, comparisonIntentOptions, parseExperimentTags, parseJsonObjectInput, formatPresetLifecycleStage, buildRunSubmissionPayload, normalizeRunFormPreset, resolveMarketDataSymbol, buildMarketDataInstrumentFocusKey, isMarketDataInstrumentAtRisk, resolvePreferredMarketDataInstrument, formatWorkflowToken, formatMarketContextFieldProvenance, summarizeProviderRecoveryMarketContextProvenance, serializeLinkedMarketInstrumentContext, getOperatorSeverityRank, normalizeMarketDataProvenanceExportSort, normalizeMarketDataProvenanceExportFilterState, normalizeMarketDataProvenanceExportHistoryEntry, loadPersistedMarketDataProvenanceExportState, persistMarketDataProvenanceExportState, formatMarketDataProvenanceExportFilterSummary, formatProviderProvenanceAnalyticsQuerySummary, normalizeProviderProvenanceDashboardLayoutState, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueSort, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkQueueViewPatch, formatProviderProvenanceSchedulerNarrativeGovernanceQueueSortLabel, providerProvenanceSchedulerNarrativeGovernancePolicySupportsItemType, formatProviderProvenanceSchedulerNarrativeGovernanceQueueViewSummary, buildProviderProvenanceAnalyticsWorkspaceQuery, buildProviderProvenanceAnalyticsQueryStateFromWorkspaceQuery, formatProviderProvenanceSchedulerNarrativeFacet, resolveProviderProvenanceSeriesBarWidth, formatProviderDriftIntensity, formatSchedulerLagSeconds, downloadTextExport, escapeRegExp, normalizeMarketSymbol, buildMarketSymbolSearchVariants, matchesMarketSymbolInText, dedupeMarketDataInstruments, formatMarketDataInstrumentLabel, getMarketDataInstrumentSyncSeverityRank, getMarketDataInstrumentRiskScore, buildLiveMarketDataPreference, getMarketDataInstrumentLiveRelevance, selectPrimaryMarketDataInstrument, extractMatchingMarketTimeframe, extractMatchingMarketSymbols, buildLinkedMarketInstrumentContext, buildLinkedMarketInstrumentContextFromPayload, formatLinkedMarketPrimaryFocusNote, resolveInstrumentsBySymbolsAndTimeframe, resolveMarketDataInstrumentLink, getAlertLinkPriority, compareAlertLinkPriority, resolveAutoLinkedMarketInstrument, formatTimestamp, formatProviderRecoverySchema, formatProviderRecoveryTelemetry, shortenIdentifier, truncateLabel, formatRange, benchmarkArtifactSummaryOrder, benchmarkArtifactSummaryLabels, benchmarkArtifactSectionOrder, benchmarkArtifactSectionLabels, formatBenchmarkArtifactSummaryEntries, benchmarkArtifactSummarySortIndex, formatBenchmarkArtifactSummaryLabel, formatBenchmarkArtifactSummaryValue, formatBenchmarkArtifactSectionEntries, benchmarkArtifactSectionSortIndex, formatBenchmarkArtifactSectionLabel, formatBenchmarkArtifactSectionLines, formatBenchmarkArtifactSectionValue, formatBenchmarkArtifactInlineValue, ProviderProvenanceAnalyticsScope, ProviderProvenanceSchedulerOccurrenceNarrativeFacet, ProviderProvenanceAnalyticsQueryState, ProviderProvenanceSchedulerSearchDashboardFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, ProviderProvenanceSchedulerSearchModerationQueueFilterState, ProviderProvenanceSchedulerSearchModerationStageDraft, ProviderProvenanceSchedulerExportPolicyDraft, OperatorVisibilityAlertEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraftState, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraftState, ProviderProvenanceSchedulerNarrativeBulkToggleValue, ProviderProvenanceSchedulerNarrativeTemplateBulkDraftState, ProviderProvenanceSchedulerStitchedReportViewBulkDraftState, ProviderProvenanceSchedulerNarrativeRegistryDraftState, ProviderProvenanceSchedulerNarrativeRegistryBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraftState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepVersionEntry, ProviderProvenanceSchedulerNarrativeGovernanceQueueFilterState, ProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterState, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilterState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilterState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilterState, ProviderProvenanceSchedulerStitchedReportViewAuditFilterState, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilterState, ProviderProvenanceReportDraftState, LinkedMarketInstrumentContext, MarketDataLinkableAlertRecord, MarketDataIncidentHistoryEntry, ProviderRecoveryMarketContextSummary, MarketDataProviderProvenanceEventRecord, MarketDataPrimaryFocusSelection } from "./ControlRoomViewHelpersContext";
import { PanelDisclosure, BackfillCountStatus, BackfillQualityStatus, SyncCheckpointStatus, SyncFailureStatus, formatCompletion, summarizeGapWindows, formatGapWindows, buildLegacyGapWindowKey, buildGapWindowKey, parseGapWindowKey, formatGapWindowKeyLabel, normalizeExpandedGapWindowSelectionList, resolveGapWindowSelectionList, buildGapWindowSelectionUpdate, isSameGapWindowSelectionList, filterExpandedGapWindowSelections, buildGapWindowSelectionLookup, instrumentGapRowKey, toggleExpandedGapRow, pruneExpandedGapRows, pruneExpandedGapWindowSelections } from "./ControlRoomViewStatusPanels";
import { loadExpandedGapRows, loadExpandedGapWindowSelections, defaultControlRoomComparisonSelectionState, loadPersistedComparisonSelection, defaultComparisonHistoryPanelState, defaultComparisonHistoryPanelUiState, loadPersistedComparisonHistoryPanelUiState, loadControlRoomUiState, readControlRoomUiStateValue, persistControlRoomUiState, loadComparisonHistorySyncAuditTrail, persistComparisonHistorySyncAuditTrail, loadComparisonSelectionFromUrl, buildComparisonSelectionHistoryUrl, readComparisonHistoryBrowserState, buildComparisonHistoryBrowserState, isSameComparisonHistoryBrowserState, persistComparisonSelectionToUrl, buildComparisonHistoryEntryId, buildComparisonHistoryTabId, formatComparisonHistoryTabLabel, loadComparisonHistoryTabIdentity, buildComparisonHistoryPanelSyncState, buildComparisonHistorySyncSignature, buildComparisonHistorySyncAuditId, buildComparisonHistoryPanelEntry, findComparisonHistoryPanelEntryForSelection, mergeComparisonHistoryPanelState, mergeComparisonHistoryPanelEntries, reconcileComparisonHistoryPanelState, sortComparisonHistoryPanelEntries, limitComparisonHistoryPanelEntries } from "./ControlRoomViewComparisonStorage";
import { normalizeComparisonHistoryPanelUiState, normalizeComparisonHistorySyncAuditFilter, normalizeComparisonHistoryPanelSyncState, normalizeComparisonHistoryPanelState, normalizeComparisonHistoryPanelEntry, normalizeComparisonHistorySyncAuditEntry, normalizeComparisonHistorySyncConflictReview, normalizeComparisonHistorySyncConflictSelectedSources, normalizeComparisonHistorySyncPreferenceReview, normalizeComparisonHistorySyncWorkspaceReview, normalizeComparisonHistorySyncPreferenceState, normalizeComparisonHistorySyncWorkspaceState, normalizeComparisonHistorySyncPreferenceSelectedSources, normalizeComparisonHistorySyncWorkspaceSelectedSources, limitComparisonHistorySyncAuditEntries, appendComparisonHistorySyncAuditEntries, isSameComparisonHistoryPanelState, isSameComparisonHistoryPanelSyncState, isSameComparisonHistoryPanelEntry, getComparisonHistoryPanelEntryChangedFields, formatComparisonHistorySyncConflictScoreLinkValue, formatComparisonHistorySyncConflictRunSelectionValue, formatComparisonHistorySyncConflictFieldValue, hasComparisonHistorySyncConflictFieldDifference, buildDefaultComparisonHistorySyncConflictSelectedSources, buildComparisonHistorySyncConflictReview, buildComparisonHistorySyncConflictReviewGroups, summarizeComparisonHistoryPanelEntryConflict, formatComparisonHistorySyncConflictResolutionSummary, resolveComparisonHistorySyncConflictReviewEntry, applyResolvedComparisonHistoryPanelEntry, summarizeComparisonHistorySyncPreferenceChanges, buildComparisonHistorySyncPreferenceState, formatComparisonHistorySyncPreferenceFieldValue, hasComparisonHistorySyncPreferenceFieldDifference, buildDefaultComparisonHistorySyncPreferenceSelectedSources, buildComparisonHistorySyncPreferenceReview, buildComparisonHistorySyncPreferenceReviewRows, formatComparisonHistorySyncPreferenceResolutionSummary, resolveComparisonHistorySyncPreferenceReview } from "./ControlRoomViewComparisonNormalize";
import { listComparisonHistoryExpandedGapRowKeys, listComparisonHistoryExpandedGapRowDiffKeys, buildComparisonHistoryExpandedGapRowSelectionKey, parseComparisonHistoryExpandedGapRowSelectionKey, buildComparisonHistoryExpandedGapWindowSelectionKey, parseComparisonHistoryExpandedGapWindowSelectionKey, listComparisonHistoryExpandedGapWindowDiffKeys, isSameComparisonHistoryExpandedGapRows, isSameExpandedGapWindowSelections, formatComparisonHistoryExpandedGapRowKey, formatComparisonHistoryExpandedGapRowsValue, formatComparisonHistoryExpandedGapRowsDiffValue, formatComparisonHistorySyncWorkspaceSelectionKeyLabel, rankComparisonHistorySyncWorkspaceSelectionKey, ComparisonHistorySyncWorkspaceSemanticRanking, listComparisonHistorySyncWorkspaceDiffSelectionKeys, resolveComparisonHistorySyncWorkspaceFieldSource, listComparisonHistorySyncWorkspaceConflictSelectionKeys, scoreComparisonHistorySyncWorkspaceCandidateSource, sortComparisonHistorySyncWorkspaceSemanticSignals, rankComparisonHistorySyncWorkspaceFieldSemantics, buildComparisonHistorySyncWorkspaceRecommendedSources, summarizeComparisonHistorySyncWorkspaceChanges, buildComparisonHistorySyncWorkspaceState, formatComparisonHistorySyncWorkspaceFieldValue, hasComparisonHistorySyncWorkspaceFieldDifference, buildDefaultComparisonHistorySyncWorkspaceSelectedSources, buildComparisonHistorySyncWorkspaceReview, buildComparisonHistorySyncWorkspaceReviewRows, buildComparisonHistorySyncWorkspaceRecommendationOverview, formatComparisonHistorySyncWorkspaceResolutionSummary, resolveComparisonHistorySyncWorkspaceReview, buildComparisonHistorySyncAuditEntries } from "./ControlRoomViewComparisonWorkspace";
import { loadLegacyExpandedGapRows, filterExpandedGapRows, normalizeControlRoomComparisonSelection, isSameComparisonSelection, formatComparisonHistoryPanelEntryMeta, matchesComparisonHistoryPanelEntry, formatComparisonHistorySyncAuditKindLabel, buildComparisonHistoryStepDescriptor, resolveComparisonHistoryRunLabel, normalizeComparisonRunIdList, normalizeComparisonIntent, normalizeComparisonScoreSection, normalizeComparisonScoreLinkSource, normalizeComparisonScoreLinkSubFocusKey, normalizeComparisonScoreLinkExpandedState, normalizeComparisonScoreLinkTooltipKey, normalizeComparisonScoreLinkArtifactLineDetailView, normalizeComparisonScoreLinkArtifactLineMicroView, normalizeComparisonScoreLinkArtifactLineNotePage, normalizeComparisonScoreLinkArtifactLineDetailHoverKey, normalizeComparisonScoreLinkArtifactLineScrubStep, normalizeComparisonScoreLinkArtifactHoverKey, normalizeComparisonScoreLinkTarget, isControlRoomUiStateV1, isControlRoomUiStateV2, isControlRoomUiStateV3, isControlRoomUiStateV4, buildRunsPath, buildRunComparisonPath, normalizeRunHistoryFilter, normalizeRunHistoryPresetFilter, getStrategyVersionOptions, pickLatestBenchmarkRun } from "./ControlRoomViewRunFilters";
import { RunListBoundarySurfaceContract, RunListBoundaryGroupContract, Metric, formatMetric, formatLineagePosture, formatLineageIndicator, formatComparisonScoreValue } from "./ControlRoomViewCapabilities";
import { buildComparisonScoreHighlights, buildComparisonScoreDetailRows, formatComparisonScoreHighlight, formatComparisonScoreComponentLabel, formatComparisonScoreLinkSourceLabel, encodeComparisonScoreLinkToken, decodeComparisonScoreLinkToken, buildComparisonProvenanceLineSubFocusKey, buildComparisonRunCardLineSubFocusKey, buildComparisonRunListLineSubFocusKey, buildComparisonRunListOrderPreviewSubFocusKey, buildComparisonRunListDataSymbolSubFocusKey, buildComparisonProvenanceArtifactSubFocusKey, buildComparisonProvenanceArtifactSectionSubFocusKey, buildComparisonProvenanceArtifactSummaryHoverKey, buildComparisonProvenanceArtifactSectionLineHoverKey, buildComparisonProvenanceArtifactLineDetailHoverKey, buildComparisonMetricTooltipKey, formatComparisonScoreLinkSubFocusLabel, formatComparisonScoreLinkTooltipLabel, formatComparisonScoreLinkArtifactHoverLabel, formatComparisonScoreLinkArtifactLineDetailViewLabel, formatComparisonScoreLinkArtifactLineMicroViewLabel, formatComparisonScoreLinkArtifactLineDetailHoverLabel, formatComparisonScoreComponentDetail, buildComparisonScoreComponentDetails, formatComparisonScoreComponentRawValue, formatComparisonScoreSignedValue, getComparisonScoreLinkedRunRole, isSameComparisonScoreLinkTarget, isSameComparisonScoreLinkSurface, resolveComparisonScoreDrillBackTarget, isComparisonScoreLinkMatch, formatEditableNumber } from "./ControlRoomViewComparisonLinks";
import { formatFixedNumber, buildLiveOrderDraftKey, formatComparisonMetric, formatComparisonDelta, formatComparisonNarrativeLabel, formatComparisonIntentLabel, formatComparisonIntentLegend, formatComparisonIntentTooltip, formatComparisonCueTooltip, buildComparisonCellTooltip, getComparisonIntentClassName, formatLaneLabel, formatVersionLineage, extractDefaultParameters, formatParameterMap, formatParameterValue, summarizeRunNotes } from "./ControlRoomViewFormatting";

export function StrategyColumn({
  title,
  strategies,
  accent,
}: {
  title: string;
  strategies: Strategy[];
  accent: string;
}) {
  return (
    <div className={`strategy-column ${accent}`}>
      <h3>{title}</h3>
      {strategies.length ? (
        strategies.map((strategy) => (
          <article className="strategy-card" key={strategy.strategy_id}>
            <div className="strategy-head">
              <div>
                <strong>{strategy.name}</strong>
                <div className="strategy-badges">
                  <span className="meta-pill">{formatLaneLabel(strategy.runtime)}</span>
                  <span className="meta-pill subtle">{strategy.lifecycle.stage}</span>
                  <span className="meta-pill subtle">{strategy.version}</span>
                </div>
              </div>
              <span>{formatVersionLineage(strategy.version_lineage, strategy.version)}</span>
            </div>
            <p>{strategy.description}</p>
            <dl>
              <div>
                <dt>전략 ID</dt>
                <dd>{strategy.strategy_id}</dd>
              </div>
              <div>
                <dt>운용 주기</dt>
                <dd>{strategy.supported_timeframes.join(", ")}</dd>
              </div>
              <div>
                <dt>대상 시장</dt>
                <dd>{strategy.asset_types.join(", ")}</dd>
              </div>
              {strategy.lifecycle.registered_at ? (
                <div>
                  <dt>등록 시각</dt>
                  <dd>{formatTimestamp(strategy.lifecycle.registered_at)}</dd>
                </div>
              ) : null}
            </dl>
          </article>
        ))
      ) : (
        <p className="empty-state">등록된 전략이 없습니다.</p>
      )}
    </div>
  );
}

export function PresetStructuredDiffPreview({
  changedGroups,
  emptyMessage,
  leftColumnLabel,
  rightColumnLabel,
  title,
  unchangedGroups,
}: {
  changedGroups: PresetStructuredDiffGroup[];
  emptyMessage: string;
  leftColumnLabel: string;
  rightColumnLabel: string;
  title: string;
  unchangedGroups: PresetStructuredDiffGroup[];
}) {
  const [showUnchangedGroups, setShowUnchangedGroups] = useState(false);
  const unchangedRowCount = unchangedGroups.reduce((total, group) => total + group.rows.length, 0);
  const renderGroupRows = (group: PresetStructuredDiffGroup) =>
    group.rows.map((row) => (
      <div
        className={`comparison-dev-conflict-preview-row ${row.changed ? "is-changed" : ""}`}
        key={row.key}
      >
        <span className="comparison-dev-conflict-preview-label-group">
          <span className="comparison-dev-conflict-preview-label">{row.label}</span>
          {row.semantic_hint ? (
            <span className="comparison-dev-conflict-preview-hint">{row.semantic_hint}</span>
          ) : null}
          <span className={`comparison-dev-conflict-delta comparison-dev-conflict-delta-${row.delta_direction}`}>
            {row.delta_label}
          </span>
        </span>
        <span className="comparison-dev-conflict-preview-value comparison-dev-conflict-preview-value-existing">
          {row.existing_value}
        </span>
        <span
          className={`comparison-dev-conflict-preview-value comparison-dev-conflict-preview-value-incoming comparison-dev-conflict-preview-value-${
            row.changed ? row.delta_direction : "same"
          }`}
        >
          {row.incoming_value}
        </span>
      </div>
    ));

  return (
    <div className="comparison-dev-session-summary">
      <p className="comparison-dev-session-summary-title">{title}</p>
      <div className="comparison-dev-conflict-preview">
        <div className="comparison-dev-conflict-preview-row comparison-dev-conflict-preview-head">
          <span>Field</span>
          <span>{leftColumnLabel}</span>
          <span>{rightColumnLabel}</span>
        </div>
        {changedGroups.length ? (
          changedGroups.map((group) => (
            <div className="comparison-dev-conflict-preview-group" key={group.key}>
              <div className="comparison-dev-conflict-preview-group-title">
                <span>{group.label}</span>
                <span className="comparison-dev-conflict-preview-group-meta">
                  <span className="comparison-dev-conflict-preview-group-summary">{group.summary_label}</span>
                </span>
              </div>
              {renderGroupRows(group)}
            </div>
          ))
        ) : (
          <p className="empty-state">{emptyMessage}</p>
        )}
        {unchangedRowCount ? (
          <button
            className="comparison-dev-conflict-toggle"
            onClick={() => setShowUnchangedGroups((current) => !current)}
            type="button"
          >
            {showUnchangedGroups
              ? `Hide ${unchangedRowCount} unchanged field${unchangedRowCount === 1 ? "" : "s"}`
              : `Show ${unchangedRowCount} unchanged field${unchangedRowCount === 1 ? "" : "s"}`}
          </button>
        ) : null}
        {showUnchangedGroups
          ? unchangedGroups.map((group) => (
              <div className="comparison-dev-conflict-preview-group" key={group.key}>
                <div className="comparison-dev-conflict-preview-group-title">
                  <span>{group.label}</span>
                  <span className="comparison-dev-conflict-preview-group-meta">
                    <span className="comparison-dev-conflict-preview-group-summary">{group.summary_label}</span>
                  </span>
                </div>
                {renderGroupRows(group)}
              </div>
            ))
          : null}
      </div>
    </div>
  );
}

export function PresetCatalogPanel({
  form,
  presets,
  runSurfaceCapabilities,
  setForm,
  strategies,
  editingPresetId,
  expandedPresetRevisionIds,
  onEditPreset,
  onResetEditor,
  onLifecycleAction,
  onRestoreRevision,
  onSubmit,
  onToggleRevisions,
}: {
  form: typeof defaultPresetForm;
  presets: ExperimentPreset[];
  runSurfaceCapabilities: RunSurfaceCapabilities | null;
  setForm: (updater: (value: typeof defaultPresetForm) => typeof defaultPresetForm) => void;
  strategies: Strategy[];
  editingPresetId: string | null;
  expandedPresetRevisionIds: Record<string, boolean>;
  onEditPreset: (preset: ExperimentPreset) => void;
  onResetEditor: () => void;
  onLifecycleAction: (presetId: string, action: "promote" | "archive" | "restore") => Promise<void> | void;
  onRestoreRevision: (presetId: string, revisionId: string) => Promise<void> | void;
  onSubmit: (event: FormEvent) => Promise<void> | void;
  onToggleRevisions: (presetId: string) => void;
}) {
  const isEditing = editingPresetId !== null;
  const findStrategyParameterSchema = (strategyId?: string | null) =>
    strategies.find((strategy) => strategy.strategy_id === strategyId)?.parameter_schema;
  const presetParameterDefaultsEnabled = shouldHydratePresetParameterDefaults(runSurfaceCapabilities);
  const selectedStrategyParameterSchema = findStrategyParameterSchema(form.strategy_id);
  const selectedStrategyDefaultParameters = selectedStrategyParameterSchema
    ? extractDefaultParameters(selectedStrategyParameterSchema)
    : {};
  const selectedStrategyDefaultParametersJson = Object.keys(selectedStrategyDefaultParameters).length
    ? JSON.stringify(selectedStrategyDefaultParameters, null, 2)
    : "";
  const [revisionFiltersByPreset, setRevisionFiltersByPreset] = useState<
    Record<string, PresetRevisionFilterState>
  >({});
  const [expandedRevisionDiffIds, setExpandedRevisionDiffIds] = useState<Record<string, boolean>>({});
  const [restoreDraftConflictAcknowledgements, setRestoreDraftConflictAcknowledgements] = useState<
    Record<string, boolean>
  >({});
  const [pendingRestoreTarget, setPendingRestoreTarget] = useState<{
    presetId: string;
    revisionId: string;
  } | null>(null);
  const lastAutoHydratedStrategyId = useRef<string | null>(null);

  useEffect(() => {
    const strategyId = form.strategy_id || null;
    const strategyChanged = lastAutoHydratedStrategyId.current !== strategyId;
    lastAutoHydratedStrategyId.current = strategyId;
    if (!strategyChanged || !presetParameterDefaultsEnabled || !strategyId) {
      return;
    }
    if (!selectedStrategyDefaultParametersJson) {
      return;
    }
    if (form.parameters_text.trim()) {
      return;
    }
    setForm((current) => {
      if ((current.strategy_id || null) !== strategyId || current.parameters_text.trim()) {
        return current;
      }
      return {
        ...current,
        parameters_text: selectedStrategyDefaultParametersJson,
      };
    });
  }, [
    form.parameters_text,
    form.strategy_id,
    presetParameterDefaultsEnabled,
    selectedStrategyDefaultParametersJson,
    setForm,
  ]);

  async function confirmRevisionRestore(presetId: string, revisionId: string) {
    await onRestoreRevision(presetId, revisionId);
    setRestoreDraftConflictAcknowledgements((current) => {
      const next = { ...current };
      delete next[`${presetId}:${revisionId}`];
      return next;
    });
    setPendingRestoreTarget((current) =>
      current?.presetId === presetId && current?.revisionId === revisionId ? null : current,
    );
  }

  return (
    <>
      <form className="run-form" onSubmit={onSubmit}>
        <label>
          이름
          <input
            placeholder="Core 5m"
            value={form.name}
            onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))}
          />
        </label>
        <label>
          프리셋 ID
          <input
            disabled={isEditing}
            placeholder="core_5m"
            value={form.preset_id}
            onChange={(event) => setForm((current) => ({ ...current, preset_id: event.target.value }))}
          />
        </label>
        <label>
          전략
          <select
            value={form.strategy_id}
            onChange={(event) => setForm((current) => ({ ...current, strategy_id: event.target.value }))}
          >
            <option value="">전체 전략</option>
            {strategies.map((strategy) => (
              <option key={strategy.strategy_id} value={strategy.strategy_id}>
                {strategy.name}
              </option>
            ))}
          </select>
        </label>
        <label>
          운용 주기
          <input
            placeholder="5m"
            value={form.timeframe}
            onChange={(event) => setForm((current) => ({ ...current, timeframe: event.target.value }))}
          />
        </label>
        <label>
          벤치마크 묶음
          <input
            placeholder="native_validation"
            value={form.benchmark_family}
            onChange={(event) =>
              setForm((current) => ({ ...current, benchmark_family: event.target.value }))
            }
          />
        </label>
        <label>
          태그
          <input
            placeholder="baseline, momentum"
            value={form.tags_text}
            onChange={(event) => setForm((current) => ({ ...current, tags_text: event.target.value }))}
          />
        </label>
        <label>
          설명
          <input
            placeholder="재사용 가능한 backtest 기준"
            value={form.description}
            onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))}
          />
        </label>
        <label>
          파라미터 JSON
          <textarea
            placeholder={selectedStrategyDefaultParametersJson || '{"short_window": 5, "long_window": 13}'}
            rows={4}
            value={form.parameters_text}
            onChange={(event) =>
              setForm((current) => ({ ...current, parameters_text: event.target.value }))
            }
          />
        </label>
        {presetParameterDefaultsEnabled && selectedStrategyDefaultParametersJson ? (
          <p className="run-note">
            비어 있는 파라미터 묶음은 선택한 전략의 기본값으로 자동 보강됩니다.
          </p>
        ) : null}
        {isEditing ? (
          <p className="run-note">
            {editingPresetId} 수정 중입니다. 프리셋 ID는 유지되고 현재 묶음만 갱신되며 새 변경 이력이 기록됩니다.
          </p>
        ) : null}
        <div className="run-actions">
          <button type="submit">{isEditing ? "변경 이력 저장" : "프리셋 저장"}</button>
          {isEditing ? (
            <button className="ghost-button" onClick={onResetEditor} type="button">
              새 프리셋
            </button>
          ) : null}
        </div>
      </form>

      {presets.length ? (
        <div className="run-list">
          {presets.map((preset) => (
            <article className="run-card" key={preset.preset_id}>
              {(() => {
                const revisions = [...preset.revisions].reverse();
                const latestRevisionId = revisions[0]?.revision_id;
                const revisionsExpanded = Boolean(expandedPresetRevisionIds[preset.preset_id]);
                const revisionFilter = revisionFiltersByPreset[preset.preset_id] ?? defaultPresetRevisionFilter;
                const draftConflict =
                  editingPresetId === preset.preset_id
                    ? describePresetDraftConflict(
                        preset,
                        form,
                        findStrategyParameterSchema(form.strategy_id || preset.strategy_id),
                      )
                    : null;
                const visibleRevisionEntries = revisions
                  .map((revision, index) => {
                    const diffReference =
                      revision.revision_id === latestRevisionId
                        ? revisions[index + 1] ?? null
                        : buildCurrentPresetRevisionSnapshot(preset);
                    const diffBasisLabel =
                      revision.revision_id === latestRevisionId
                        ? revisions[index + 1]
                          ? "이전 스냅샷"
                          : "최초 이력"
                        : "현재 묶음";
                    const diff = describePresetRevisionDiff(
                      revision,
                      diffReference,
                      diffBasisLabel,
                      findStrategyParameterSchema(revision.strategy_id ?? preset.strategy_id),
                    );
                    return { diff, revision };
                  })
                  .filter(({ diff, revision }) => matchesPresetRevisionFilter(revision, diff, revisionFilter));
                return (
                  <>
                    <div className="run-card-head">
                      <div>
                        <strong>{preset.name}</strong>
                        <span>{preset.preset_id}</span>
                      </div>
                      <div className={`run-status ${preset.lifecycle.stage === "archived" ? "failed" : "completed"}`}>
                        {formatPresetLifecycleStage(preset.lifecycle.stage)}
                      </div>
                    </div>
                    <div className="run-metrics">
                      <Metric label="전략" value={preset.strategy_id ?? "전체"} />
                      <Metric label="주기" value={preset.timeframe ?? "전체"} />
                      <Metric label="파라미터" value={formatParameterMap(preset.parameters)} />
                      <Metric label="변경 이력" value={String(preset.revisions.length)} />
                      <Metric label="갱신" value={formatTimestamp(preset.updated_at)} />
                    </div>
                    <ExperimentMetadataPills
                      benchmarkFamily={preset.benchmark_family}
                      presetId={preset.preset_id}
                      tags={preset.tags}
                    />
                    <p className="run-note">
                      상태: {formatPresetLifecycleStage(preset.lifecycle.stage)} · 처리{" "}
                      {preset.lifecycle.last_action} · 담당 {preset.lifecycle.updated_by} ·{" "}
                      {formatTimestamp(preset.lifecycle.updated_at)}.
                    </p>
                    {preset.description ? <p className="run-note">{preset.description}</p> : null}
                    <div className="run-actions">
                      <button className="ghost-button" onClick={() => onEditPreset(preset)} type="button">
                        {editingPresetId === preset.preset_id ? "수정 중" : "프리셋 수정"}
                      </button>
                      <button
                        className="ghost-button"
                        onClick={() => onToggleRevisions(preset.preset_id)}
                        type="button"
                      >
                        {revisionsExpanded ? "변경 이력 접기" : `변경 이력 보기 (${preset.revisions.length})`}
                      </button>
                      {preset.lifecycle.stage !== "archived" ? (
                        <>
                          {preset.lifecycle.stage !== "live_candidate" ? (
                            <button
                              className="ghost-button"
                              onClick={() => void onLifecycleAction(preset.preset_id, "promote")}
                              type="button"
                            >
                              실전 후보로 승격
                            </button>
                          ) : null}
                          <button
                            className="ghost-button danger"
                            onClick={() => void onLifecycleAction(preset.preset_id, "archive")}
                            type="button"
                          >
                            보관
                          </button>
                        </>
                      ) : (
                        <button
                          className="ghost-button"
                          onClick={() => void onLifecycleAction(preset.preset_id, "restore")}
                          type="button"
                        >
                          초안으로 복구
                        </button>
                      )}
                    </div>
                    {revisionsExpanded ? (
                      <>
                        <div className="run-form">
                          <label>
                            변경 이력 검색
                            <input
                              placeholder="actor, reason, parameter, tag"
                              value={revisionFilter.query}
                              onChange={(event) =>
                                setRevisionFiltersByPreset((current) => ({
                                  ...current,
                                  [preset.preset_id]: {
                                    ...(current[preset.preset_id] ?? defaultPresetRevisionFilter),
                                    query: event.target.value,
                                  },
                                }))
                              }
                            />
                          </label>
                          <label>
                            처리 유형
                            <select
                              value={revisionFilter.action}
                              onChange={(event) =>
                                setRevisionFiltersByPreset((current) => ({
                                  ...current,
                                  [preset.preset_id]: {
                                    ...(current[preset.preset_id] ?? defaultPresetRevisionFilter),
                                    action: event.target.value,
                                  },
                                }))
                              }
                            >
                              <option value="all">전체 처리</option>
                              <option value="created">생성</option>
                              <option value="updated">수정</option>
                              <option value="restored">복구</option>
                              <option value="migrated">마이그레이션</option>
                            </select>
                          </label>
                        </div>
                        <p className="run-note">
                          변경 이력 {revisions.length}개 중 {visibleRevisionEntries.length}개 표시.
                        </p>
                        {visibleRevisionEntries.length ? (
                          <div className="run-list">
                            {visibleRevisionEntries.map(({ revision, diff }) => {
                              const diffExpanded = Boolean(expandedRevisionDiffIds[revision.revision_id]);
                              const confirmingRestore =
                                pendingRestoreTarget?.presetId === preset.preset_id &&
                                pendingRestoreTarget?.revisionId === revision.revision_id;
                              const acknowledgementKey = `${preset.preset_id}:${revision.revision_id}`;
                              const hasDraftConflict = Boolean(draftConflict && draftConflict.changeCount);
                              const draftConflictAcknowledged = Boolean(
                                restoreDraftConflictAcknowledgements[acknowledgementKey],
                              );
                              return (
                                <article className="run-card" key={revision.revision_id}>
                                  <div className="run-card-head">
                                    <div>
                                      <strong>{revision.revision_id}</strong>
                                      <span>{revision.action}</span>
                                    </div>
                                    <div
                                      className={`run-status ${
                                        revision.revision_id === latestRevisionId ? "completed" : "pending"
                                      }`}
                                    >
                                      {revision.revision_id === latestRevisionId ? "현재 묶음" : "스냅샷"}
                                    </div>
                                  </div>
                                  <div className="run-metrics">
                                    <Metric label="담당" value={revision.actor} />
                                    <Metric label="기록" value={formatRelativeTimestampLabel(revision.created_at)} />
                                    <Metric label="전략" value={revision.strategy_id ?? "전체"} />
                                    <Metric label="변경" value={`${diff.changeCount}건`} />
                                  </div>
                                  <ExperimentMetadataPills
                                    benchmarkFamily={revision.benchmark_family}
                                    tags={revision.tags}
                                  />
                                  <p className="run-note">
                                    사유: {revision.reason}. {diff.summary}
                                    {revision.source_revision_id ? ` ${revision.source_revision_id}에서 복구됨.` : ""}
                                  </p>
                                  {revision.description ? <p className="run-note">{revision.description}</p> : null}
                                  <div className="run-actions">
                                    <button
                                      className="ghost-button"
                                      onClick={() =>
                                        setExpandedRevisionDiffIds((current) => ({
                                          ...current,
                                          [revision.revision_id]: !current[revision.revision_id],
                                        }))
                                      }
                                      type="button"
                                    >
                                      {diffExpanded ? "차이 접기" : `차이 보기: ${diff.basisLabel}`}
                                    </button>
                                    {revision.revision_id !== latestRevisionId ? (
                                      <button
                                        className="ghost-button"
                                        onClick={() => {
                                          setPendingRestoreTarget({
                                            presetId: preset.preset_id,
                                            revisionId: revision.revision_id,
                                          });
                                          setRestoreDraftConflictAcknowledgements((current) => ({
                                            ...current,
                                            [acknowledgementKey]: false,
                                          }));
                                        }}
                                        type="button"
                                      >
                                        이 묶음으로 복구
                                      </button>
                                    ) : null}
                                  </div>
                                  {diffExpanded ? (
                                    <PresetStructuredDiffPreview
                                      changedGroups={diff.changedGroups}
                                      emptyMessage={diff.summary}
                                      leftColumnLabel={diff.basisLabel}
                                      rightColumnLabel="변경 스냅샷"
                                      title={`차이: ${diff.basisLabel}`}
                                      unchangedGroups={diff.unchangedGroups}
                                    />
                                  ) : null}
                                  {confirmingRestore ? (
                                    <div className="comparison-dev-confirm-card">
                                      <p className="comparison-dev-feedback">
                                        {revision.revision_id}를 {preset.preset_id}에 복구할까요? 선택한 스냅샷으로 새 현재 이력이 생성됩니다.
                                      </p>
                                      <p className="run-note">{diff.summary}</p>
                                      <PresetStructuredDiffPreview
                                        changedGroups={diff.changedGroups}
                                        emptyMessage={diff.summary}
                                        leftColumnLabel="현재 묶음"
                                        rightColumnLabel="복구 대상"
                                        title="복구 영향"
                                        unchangedGroups={diff.unchangedGroups}
                                      />
                                      {hasDraftConflict && draftConflict ? (
                                        <>
                                          <p className="comparison-dev-feedback">
                                            {draftConflict.summary}
                                            {draftConflict.hasInvalidParameters
                                              ? " 현재 초안에도 유효하지 않은 파라미터 JSON이 있습니다."
                                              : ""}
                                          </p>
                                          <PresetStructuredDiffPreview
                                            changedGroups={draftConflict.groups}
                                            emptyMessage={draftConflict.summary}
                                            leftColumnLabel="저장된 묶음"
                                            rightColumnLabel="현재 초안"
                                            title="저장 전 초안 충돌"
                                            unchangedGroups={[]}
                                          />
                                          <label className="run-note">
                                            <input
                                              checked={draftConflictAcknowledged}
                                              onChange={(event) =>
                                                setRestoreDraftConflictAcknowledgements((current) => ({
                                                  ...current,
                                                  [acknowledgementKey]: event.target.checked,
                                                }))
                                              }
                                              type="checkbox"
                                            />{" "}
                                            이 복구가 {preset.preset_id}의 저장 전 초안을 버린다는 점을 확인합니다.
                                          </label>
                                        </>
                                      ) : null}
                                      <div className="comparison-dev-actions comparison-dev-actions-inline">
                                        <button
                                          className="ghost-button comparison-dev-reset"
                                          disabled={hasDraftConflict && !draftConflictAcknowledged}
                                          onClick={() => void confirmRevisionRestore(preset.preset_id, revision.revision_id)}
                                          type="button"
                                        >
                                          {hasDraftConflict ? "초안 폐기 후 복구" : "복구 확정"}
                                        </button>
                                        <button
                                          className="ghost-button comparison-dev-reset"
                                          onClick={() => {
                                            setPendingRestoreTarget(null);
                                            setRestoreDraftConflictAcknowledgements((current) => {
                                              const next = { ...current };
                                              delete next[acknowledgementKey];
                                              return next;
                                            });
                                          }}
                                          type="button"
                                        >
                                          취소
                                        </button>
                                      </div>
                                    </div>
                                  ) : null}
                                </article>
                              );
                            })}
                          </div>
                        ) : (
                          <p className="empty-state">현재 필터에 맞는 revision이 없습니다.</p>
                        )}
                      </>
                    ) : null}
                  </>
                );
              })()}
            </article>
          ))}
        </div>
      ) : (
        <p className="empty-state">저장된 durable Preset이 아직 없습니다.</p>
      )}
    </>
  );
}

export function RunForm({
  form,
  setForm,
  strategies,
  presets,
  showDateRange = false,
  onSubmit,
}: {
  form: typeof defaultRunForm;
  setForm: (updater: (value: typeof defaultRunForm) => typeof defaultRunForm) => void;
  strategies: Strategy[];
  presets: ExperimentPreset[];
  showDateRange?: boolean;
  onSubmit: (event: FormEvent) => Promise<void> | void;
}) {
  const availablePresets = presets.filter(
    (preset) =>
      preset.lifecycle.stage !== "archived" &&
      (!preset.strategy_id || preset.strategy_id === form.strategy_id) &&
      (!preset.timeframe || preset.timeframe === form.timeframe),
  );
  const selectedPreset = availablePresets.find((preset) => preset.preset_id === form.preset_id) ?? null;

  return (
    <form className="run-form" onSubmit={onSubmit}>
      <label>
        전략
        <select
          value={form.strategy_id}
          onChange={(event) => setForm((current) => ({ ...current, strategy_id: event.target.value }))}
        >
          {strategies.map((strategy) => (
            <option key={strategy.strategy_id} value={strategy.strategy_id}>
              {strategy.name} / {formatLaneLabel(strategy.runtime)}
            </option>
          ))}
        </select>
      </label>
      <label>
        종목
        <input
          value={form.symbol}
          onChange={(event) => setForm((current) => ({ ...current, symbol: event.target.value }))}
        />
      </label>
      <label>
        운용 주기
        <input
          value={form.timeframe}
          onChange={(event) => setForm((current) => ({ ...current, timeframe: event.target.value }))}
        />
      </label>
      <label>
        초기 현금
        <input
          type="number"
          value={form.initial_cash}
          onChange={(event) => setForm((current) => ({ ...current, initial_cash: Number(event.target.value) }))}
        />
      </label>
      <label>
        수수료율
        <input
          type="number"
          step="0.0001"
          value={form.fee_rate}
          onChange={(event) => setForm((current) => ({ ...current, fee_rate: Number(event.target.value) }))}
        />
      </label>
      <label>
        슬리피지 (bps)
        <input
          type="number"
          value={form.slippage_bps}
          onChange={(event) => setForm((current) => ({ ...current, slippage_bps: Number(event.target.value) }))}
        />
      </label>
      {showDateRange ? (
        <>
          <label>
            시작일
            <input
              max={form.end_date || undefined}
              type="date"
              value={form.start_date}
              onChange={(event) => setForm((current) => ({ ...current, start_date: event.target.value }))}
            />
          </label>
          <label>
            종료일
            <input
              min={form.start_date || undefined}
              type="date"
              value={form.end_date}
              onChange={(event) => setForm((current) => ({ ...current, end_date: event.target.value }))}
            />
          </label>
        </>
      ) : null}
      <label>
        프리셋
        <select
          value={form.preset_id}
          onChange={(event) => setForm((current) => ({ ...current, preset_id: event.target.value }))}
        >
          <option value="">프리셋 없음</option>
          {availablePresets.map((preset) => (
            <option key={preset.preset_id} value={preset.preset_id}>
              {preset.name} ({preset.preset_id})
            </option>
          ))}
        </select>
      </label>
      <label>
        벤치마크 묶음
        <input
          placeholder={selectedPreset?.benchmark_family ?? "native_validation"}
          value={form.benchmark_family}
          onChange={(event) =>
            setForm((current) => ({ ...current, benchmark_family: event.target.value }))
          }
        />
      </label>
      <label>
        태그
        <input
          placeholder="baseline, momentum"
          value={form.tags_text}
          onChange={(event) => setForm((current) => ({ ...current, tags_text: event.target.value }))}
        />
      </label>
      {selectedPreset ? (
        <div className="run-note">
          프리셋 단계: {formatPresetLifecycleStage(selectedPreset.lifecycle.stage)}. 파라미터:{" "}
          {formatParameterMap(selectedPreset.parameters)}.
        </div>
      ) : null}
      <button type="submit">실행</button>
    </form>
  );
}

export function ExperimentMetadataPills({
  benchmarkFamily,
  datasetIdentity,
  interactionSource = "run_list",
  linkedScore,
  onDrillBackScoreLink,
  panelRunId,
  presetId,
  registerSubFocusRef,
  tags,
}: {
  benchmarkFamily?: string | null;
  datasetIdentity?: string | null;
  interactionSource?: ComparisonScoreLinkSource;
  linkedScore?: (ComparisonScoreLinkTarget & { role: ComparisonScoreLinkedRunRole }) | null;
  onDrillBackScoreLink?: (
    section: ComparisonScoreSection,
    componentKey: string,
    options?: ComparisonScoreDrillBackOptions,
  ) => void;
  panelRunId?: string;
  presetId?: string | null;
  registerSubFocusRef?: (runId: string, subFocusKey: string) => (node: HTMLElement | null) => void;
  tags: string[];
}) {
  if (!tags.length && !presetId && !benchmarkFamily && !datasetIdentity) {
    return null;
  }
  const activeRunListSubFocusKey =
    linkedScore?.source === interactionSource
      ? linkedScore.subFocusKey
      : null;
  const renderPill = (
    label: string,
    title: string | undefined,
    componentKey: string,
    subFocusKey: string,
    highlighted: boolean,
  ) => {
    const isPressed =
      linkedScore?.section === "context"
      && linkedScore.componentKey === componentKey
      && activeRunListSubFocusKey === subFocusKey;
    const className = `meta-pill subtle comparison-run-card-pill-button ${
      highlighted ? "comparison-linked-badge" : ""
    } ${
      isPressed ? "comparison-linked-badge-origin comparison-linked-subfocus" : ""
    }`.trim();
    if (!onDrillBackScoreLink || !panelRunId) {
      return (
        <span className={className} title={title}>
          {label}
        </span>
      );
    }
    return (
      <button
        aria-pressed={isPressed}
        className={className}
        onClick={() =>
          onDrillBackScoreLink("context", componentKey, {
            subFocusKey,
          })
        }
        ref={(node) => registerSubFocusRef?.(panelRunId, subFocusKey)(node)}
        title={title}
        type="button"
      >
        {label}
      </button>
    );
  };
  const highlightProvenance =
    Boolean(linkedScore)
    && isComparisonScoreLinkMatch(linkedScore ?? null, ["provenance_richness"], "context");
  const highlightBenchmarkStory =
    Boolean(linkedScore)
    && isComparisonScoreLinkMatch(linkedScore ?? null, ["benchmark_story_bonus"], "context");
  return (
    <div className="strategy-badges">
      {presetId ? (
        renderPill(
          `preset ${presetId}`,
          presetId,
          "provenance_richness",
          buildComparisonRunListLineSubFocusKey("experiment_preset"),
          highlightProvenance,
        )
      ) : null}
      {benchmarkFamily ? (
        renderPill(
          `benchmark ${benchmarkFamily}`,
          benchmarkFamily,
          "benchmark_story_bonus",
          buildComparisonRunListLineSubFocusKey("experiment_benchmark"),
          highlightBenchmarkStory,
        )
      ) : null}
      {datasetIdentity ? (
        renderPill(
          `dataset ${shortenIdentifier(datasetIdentity)}`,
          datasetIdentity,
          "provenance_richness",
          buildComparisonRunListLineSubFocusKey("experiment_dataset"),
          highlightProvenance,
        )
      ) : null}
      {tags.map((tag) => (
        <span key={tag}>
          {renderPill(
            `#${tag}`,
            tag,
            "benchmark_story_bonus",
            buildComparisonRunListLineSubFocusKey(`experiment_tag:${tag}`),
            highlightBenchmarkStory,
          )}
        </span>
      ))}
    </div>
  );
}
