// @ts-nocheck

import { CSSProperties, FormEvent, KeyboardEvent, MouseEvent, PointerEvent, ReactNode, forwardRef, useCallback, useEffect, useId, useLayoutEffect, useMemo, useRef, useState, AKRA_TOUCH_FEEDBACK_BRIDGE_VERSION, AKRA_TOUCH_FEEDBACK_EVENT_NAME, AkraTouchFeedbackDetail, AkraTouchFeedbackEnvelope, triggerAkraTouchFeedbackBridge, WorkspaceShell, buildControlWorkspaceDescriptors, ControlWorkspaceDescriptor, ControlStripMetric, useWorkspaceRoute, WorkspaceRouteContent, buildRunHistoryWorkspacePanels, LiveOrderReplacementDraft, RunHistoryWorkspaceSectionProps, RunOrderControls, getRunListBoundaryContractSnapshot, getRunListBoundarySurfaceLabel, getRunSurfaceCapabilityFamily, getRunSurfaceCapabilityFamilyOrder, getRunSurfaceCapabilityGroupOrder, getRunSurfaceCapabilitySchemaContract, getRunSurfaceCollectionQueryContracts, getRunSurfaceSharedContracts, getRunSurfaceSubresourceContracts, RunListComparisonBoundaryNote, shouldEnableStrategyProvenanceSemantics, shouldEnableRunListMetricDrillBack, shouldEnableRunSnapshotSemantics, shouldEnableStrategyCatalogSchemaHints, shouldHydratePresetParameterDefaults, shouldRenderOrderActionBoundaryNote, shouldRenderWorkflowControlBoundaryNote, RunSurfaceCollectionQueryBuilder, formatComparisonTooltipTuningDelta, formatComparisonTooltipTuningValue, formatRelativeTimestampLabel, RunSection, RunSurfaceCollectionQueryBuilderApplyPayload, RunSurfaceCollectionQueryRuntimeCandidateContextSelection, RunSurfaceCollectionQueryRuntimeCandidateSample, applyProviderProvenanceSchedulerStitchedReportGovernancePlan, applyProviderProvenanceSchedulerNarrativeGovernancePlan, approveProviderProvenanceSchedulerStitchedReportGovernancePlan, approveProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceAnalyticsPreset, createProviderProvenanceDashboardView, createProviderProvenanceExportJob, createProviderProvenanceSchedulerStitchedReportGovernanceRegistry, createProviderProvenanceSchedulerStitchedReportGovernancePlan, createProviderProvenanceSchedulerStitchedReportView, createProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, captureProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchy, createProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, createProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceSchedulerNarrativeRegistryEntry, createProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceScheduledReport, approveProviderProvenanceExportJob, applyProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, deleteProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, deleteProviderProvenanceSchedulerNarrativeRegistryEntry, deleteProviderProvenanceSchedulerStitchedReportView, deleteProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, createRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, createRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, downloadProviderProvenanceExportJob, downloadRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, escalateProviderProvenanceExportJob, exportProviderProvenanceSchedulerHealth, exportProviderProvenanceSchedulerStitchedNarrativeReport, reconstructProviderProvenanceSchedulerHealthExport, exportRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, fetchJson, getProviderProvenanceExportAnalytics, getProviderProvenanceExportJobHistory, getProviderProvenanceSchedulerHealthAnalytics, getProviderProvenanceScheduledReportHistory, getRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobHistory, listProviderProvenanceAnalyticsPresets, listProviderProvenanceDashboardViews, listProviderProvenanceSchedulerStitchedReportViews, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogs, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplates, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePlans, listProviderProvenanceSchedulerNarrativeRegistryEntries, listProviderProvenanceSchedulerNarrativeRegistryRevisions, listProviderProvenanceSchedulerNarrativeTemplates, listProviderProvenanceSchedulerNarrativeTemplateRevisions, listProviderProvenanceSchedulerStitchedReportGovernancePolicyCatalogs, listProviderProvenanceSchedulerStitchedReportGovernancePolicyTemplates, listProviderProvenanceSchedulerStitchedReportGovernancePlans, rollbackProviderProvenanceSchedulerStitchedReportGovernancePlan, rollbackProviderProvenanceSchedulerNarrativeGovernancePlan, listMarketDataIngestionJobs, listMarketDataLineageHistory, listProviderProvenanceExportJobs, listProviderProvenanceSchedulerAlertHistory, listProviderProvenanceSchedulerHealthHistory, listProviderProvenanceSchedulerStitchedReportGovernanceRegistries, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryAudits, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisions, listProviderProvenanceSchedulerStitchedReportViewAudits, listProviderProvenanceSchedulerStitchedReportViewRevisions, getProviderProvenanceSchedulerSearchDashboard, bulkGovernProviderProvenanceSchedulerSearchModerationPolicyCatalogs, bulkGovernProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, createProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicy, createProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, listProviderProvenanceSchedulerSearchModerationPolicyCatalogs, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlans, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAudits, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisions, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePlans, listProviderProvenanceSchedulerSearchModerationPolicyCatalogAudits, listProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisions, listProviderProvenanceSchedulerSearchModerationPlans, listProviderProvenanceScheduledReports, listRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, listRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, approveProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, approveProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, approveProviderProvenanceSchedulerSearchModerationPlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, applyProviderProvenanceSchedulerSearchModerationPlan, createProviderProvenanceSchedulerSearchModerationPolicyCatalog, deleteProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, deleteProviderProvenanceSchedulerSearchModerationPolicyCatalog, moderateProviderProvenanceSchedulerSearchFeedbackBatch, moderateProviderProvenanceSchedulerSearchFeedback, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, recordProviderProvenanceSchedulerSearchFeedback, resolveRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevision, restoreProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevision, restoreProviderProvenanceSchedulerSearchModerationPolicyCatalogRevision, restoreProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevision, restoreProviderProvenanceSchedulerNarrativeRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportViewRevision, restoreProviderProvenanceSchedulerNarrativeTemplateRevision, revokeRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, runProviderProvenanceSchedulerNarrativeGovernancePlanBatchAction, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkGovernance, stageProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, stageProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, stageProviderProvenanceSchedulerSearchModerationPlan, updateProviderProvenanceSchedulerSearchModerationPolicyCatalog, updateProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, stageProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, runDueProviderProvenanceScheduledReports, runProviderProvenanceScheduledReport, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStep, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, updateProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, updateProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, updateProviderProvenanceSchedulerNarrativeRegistryEntry, updateProviderProvenanceSchedulerStitchedReportGovernanceRegistry, updateProviderProvenanceSchedulerStitchedReportView, updateProviderProvenanceSchedulerNarrativeTemplate, updateProviderProvenanceExportJobPolicy, deleteProviderProvenanceSchedulerStitchedReportGovernanceRegistry, ALL_FILTER_VALUE, apiBase, COMPARISON_FOCUS_ARTIFACT_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_MICRO_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_NOTE_PAGE_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_SCRUB_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_COMPONENT_SEARCH_PARAM, COMPARISON_FOCUS_DETAIL_SEARCH_PARAM, COMPARISON_FOCUS_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ORIGIN_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_SECTION_SEARCH_PARAM, COMPARISON_FOCUS_SOURCE_SEARCH_PARAM, COMPARISON_FOCUS_TOOLTIP_SEARCH_PARAM, COMPARISON_HISTORY_BROWSER_STATE_KEY, COMPARISON_HISTORY_BROWSER_STATE_VERSION, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_KEY, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_VERSION, COMPARISON_HISTORY_SYNC_CONFLICT_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_PREFERENCE_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_WORKSPACE_FIELD_DEFINITIONS, COMPARISON_HISTORY_TAB_ID_SESSION_KEY, COMPARISON_INTENT_SEARCH_PARAM, COMPARISON_RUN_ID_SEARCH_PARAM, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_KEY, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_VERSION, COMPARISON_TOOLTIP_TUNING_GROUPS, COMPARISON_TOOLTIP_TUNING_LABELS, COMPARISON_TOOLTIP_TUNING_SHARE_PARAM, COMPARISON_TOOLTIP_TUNING_STORAGE_KEY, COMPARISON_TOOLTIP_TUNING_STORAGE_VERSION, COMPARISON_TOOLTIP_UNCHANGED_GROUP_COLLAPSE_THRESHOLD, CONTROL_ROOM_UI_STATE_STORAGE_KEY, CONTROL_ROOM_UI_STATE_VERSION, DEFAULT_COMPARISON_TOOLTIP_PRESET_IMPORT_CONFLICT_POLICY, DEFAULT_COMPARISON_TOOLTIP_TUNING, DEFAULT_CONTROL_ROOM_DOCUMENT_TITLE, LEGACY_GAP_WINDOW_EXPANSION_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_VERSION, MAX_COMPARISON_HISTORY_PANEL_ENTRIES, MAX_COMPARISON_HISTORY_SYNC_AUDIT_ENTRIES, MAX_COMPARISON_RUNS, MAX_MARKET_DATA_PROVENANCE_EXPORT_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_REVIEWED_CONFLICT_KEYS, MAX_VISIBLE_COMPARISON_TOOLTIP_CONFLICT_SESSION_SUMMARIES, MAX_VISIBLE_GAP_WINDOWS, PRESET_PROFILE_AGGRESSIVENESS_RANKS, PRESET_PROFILE_CONFIDENCE_RANKS, PRESET_PROFILE_SPEED_RANKS, PRESET_TIMEFRAME_UNIT_TO_MINUTES, REPLAY_INTENT_ACTION_FILTER_SEARCH_PARAM, REPLAY_INTENT_ALIAS_SEARCH_PARAM, REPLAY_INTENT_EDGE_FILTER_SEARCH_PARAM, REPLAY_INTENT_GROUP_FILTER_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_DIFF_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_GROUP_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_TRACE_SEARCH_PARAM, REPLAY_INTENT_SCOPE_SEARCH_PARAM, REPLAY_INTENT_SEARCH_PARAM, REPLAY_INTENT_STEP_SEARCH_PARAM, REPLAY_INTENT_TEMPLATE_SEARCH_PARAM, RUN_HISTORY_SAVED_FILTER_STORAGE_KEY_PREFIX, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_TAB_ID_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_BROWSER_STATE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_PAYLOAD_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_SIGNING_SECRET_STORAGE_KEY, SHOW_COMPARISON_TOOLTIP_TUNING_PANEL, TOUCH_GAP_WINDOW_SWEEP_HOLD_MS, TOUCH_GAP_WINDOW_SWEEP_MOVE_TOLERANCE_PX, BenchmarkArtifact, ParameterSchema, ComparisonCueKind, ComparisonHistoryBrowserState, ComparisonHistoryPanelEntry, ComparisonHistoryPanelState, ComparisonHistoryPanelSyncState, ComparisonHistoryStepDescriptor, ComparisonHistorySyncAuditEntry, ComparisonHistorySyncAuditFilter, ComparisonHistorySyncAuditKind, ComparisonHistorySyncAuditTrailState, ComparisonHistorySyncConflictFieldKey, ComparisonHistorySyncConflictFieldSource, ComparisonHistorySyncConflictReview, ComparisonHistorySyncConflictReviewGroup, ComparisonHistorySyncPreferenceFieldKey, ComparisonHistorySyncPreferenceReview, ComparisonHistorySyncPreferenceReviewRow, ComparisonHistorySyncPreferenceState, ComparisonHistorySyncWorkspaceRecommendationOverview, ComparisonHistorySyncWorkspaceReview, ComparisonHistorySyncWorkspaceReviewRow, ComparisonHistorySyncWorkspaceReviewSelectionKey, ComparisonHistorySyncWorkspaceSemanticSignal, ComparisonHistorySyncWorkspaceSignalDetailNestedKey, ComparisonHistorySyncWorkspaceSignalDetailSubviewKey, ComparisonHistorySyncWorkspaceSignalMicroInteractionKey, ComparisonHistorySyncWorkspaceSignalMicroViewKey, ComparisonHistorySyncWorkspaceState, ComparisonHistoryTabIdentity, ComparisonHistoryWriteMode, ComparisonIntent, ComparisonScoreDrillBackOptions, ComparisonScoreLinkedRunRole, ComparisonScoreLinkSource, ComparisonScoreLinkTarget, ComparisonScoreSection, ComparisonTooltipConflictSessionSummary, ComparisonTooltipConflictSessionSummarySession, ComparisonTooltipConflictSessionUiState, ComparisonTooltipConflictUiStateV1, ComparisonTooltipInteractionOptions, ComparisonTooltipLayout, ComparisonTooltipPendingPresetImportConflict, ComparisonTooltipPresetConflictPreviewGroup, ComparisonTooltipPresetConflictPreviewRow, ComparisonTooltipPresetImportConflictPolicy, ComparisonTooltipPresetImportResolution, ComparisonTooltipTargetProps, ComparisonTooltipTuning, ComparisonTooltipTuningPresetStateV1, ComparisonTooltipTuningShareImport, ComparisonTooltipTuningSinglePresetShareV1, ControlRoomComparisonHistoryPanelUiState, ControlRoomComparisonSelectionState, ControlRoomUiStateV1, ControlRoomUiStateV2, ControlRoomUiStateV3, ControlRoomUiStateV4, ExpandedGapWindowSelections, ExperimentPreset, ExperimentPresetRevision, GapWindowDragSelectionState, GuardedLiveStatus, MarketDataIngestionJobRecord, MarketDataProvenanceExportFilterState, MarketDataProvenanceExportHistoryEntry, MarketDataProvenanceExportSort, MarketDataProvenanceExportStateV1, MarketDataLineageHistoryRecord, MarketDataStatus, OperatorAlertMarketContextProvenance, OperatorAlertPrimaryFocus, OperatorVisibility, PendingTouchGapWindowSweepState, PresetDraftConflict, PresetRevisionDiff, PresetRevisionFilterState, PresetStructuredDiffDeltaValue, PresetStructuredDiffGroup, PresetStructuredDiffRow, ProviderProvenanceAnalyticsPresetEntry, ProviderProvenanceDashboardLayout, ProviderProvenanceDashboardViewEntry, ProviderProvenanceExportAnalyticsPayload, ProviderProvenanceExportJobEntry, ProviderProvenanceExportJobEscalationResult, ProviderProvenanceExportJobHistoryPayload, ProviderProvenanceExportJobPolicyResult, ProviderProvenanceSchedulerAlertHistoryPayload, ProviderProvenanceSchedulerHealthExportPayload, ProviderProvenanceSchedulerHealthAnalyticsPayload, ProviderProvenanceSchedulerHealthHistoryPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditRecord, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditRecord, ProviderProvenanceSchedulerSearchModerationPlanListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogListPayload, ProviderProvenanceSchedulerSearchFeedbackBatchModerationResult, ProviderProvenanceSchedulerSearchDashboardPayload, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditRecord, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionListPayload, ProviderProvenanceSchedulerStitchedReportViewAuditRecord, ProviderProvenanceSchedulerStitchedReportViewEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionListPayload, ProviderProvenanceSchedulerNarrativeBulkGovernanceResult, ProviderProvenanceSchedulerNarrativeGovernancePlan, ProviderProvenanceSchedulerNarrativeGovernancePlanBatchResult, ProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyStep, ProviderProvenanceSchedulerNarrativeGovernanceQueueView, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeRegistryEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionListPayload, ProviderProvenanceSchedulerNarrativeTemplateEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionListPayload, ProviderProvenanceScheduledReportEntry, ProviderProvenanceScheduledReportHistoryPayload, ProvenanceArtifactLineDetailView, ProvenanceArtifactLineMicroView, Run, RunComparison, RunHistoryFilter, RunHistorySurfaceKey, RunListBoundaryContract, RunListBoundaryEligibility, RunListBoundaryGroupKey, RunListBoundarySurfaceId, RunSurfaceCapabilities, RunSurfaceCapabilityFamily, RunSurfaceCapabilityFamilyContract, RunSurfaceCapabilityFamilyKey, RunSurfaceCapabilitySchemaContract, RunSurfaceCapabilitySurfaceKey, RunSurfaceCollectionQueryBuilderReplayIntentSnapshot, RunSurfaceCollectionQueryBuilderReplayLinkAliasRecordPayload, RunSurfaceCollectionQueryBuilderReplayLinkRedactionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkRetentionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobDownloadPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobPrunePayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditPrunePayload, RunSurfaceCollectionQueryContract, RunSurfaceCollectionQueryElementField, RunSurfaceCollectionQueryExpressionAuthoring, RunSurfaceCollectionQueryParameterDomainDescriptor, RunSurfaceCollectionQuerySchema, RunSurfaceSharedContract, RunSurfaceSubresourceContract, SavedRunHistoryFilterPreset, SavedRunHistoryFilterPresetStateV1, Strategy, TouchGapWindowActivationFeedbackState, TouchGapWindowHoldProgressState, defaultRunForm, defaultPresetForm, defaultPresetRevisionFilter, defaultMarketDataProvenanceExportFilterState, defaultProviderProvenanceAnalyticsQueryState, defaultProviderProvenanceSchedulerSearchDashboardFilterState, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilter, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, defaultProviderProvenanceSchedulerSearchModerationQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationStageDraft, normalizeProviderProvenanceSchedulerRoutingPolicyDraftValue, normalizeProviderProvenanceSchedulerApprovalPolicyDraftValue, buildProviderProvenanceSchedulerExportPolicyDraft, getProviderProvenanceSchedulerNarrativeGovernanceQueuePriorityRank, getProviderProvenanceSchedulerNarrativeGovernanceQueueState, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchySummary, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepSummary, formatProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyPosition, isProviderProvenanceSchedulerAlertCategory, getOperatorAlertOccurrenceKey, formatProviderProvenanceSchedulerTimelineSummary, formatProviderProvenanceSchedulerSearchMatchSummary, formatProviderProvenanceSchedulerRetrievalClusterSummary, buildProviderProvenanceSchedulerAlertWorkflowReason, defaultProviderProvenanceDashboardLayout, DEFAULT_PROVIDER_PROVENANCE_SCHEDULER_NARRATIVE_GOVERNANCE_QUEUE_SORT, defaultProviderProvenanceWorkspaceDraft, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraft, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraft, KEEP_CURRENT_BULK_GOVERNANCE_VALUE, CLEAR_TEMPLATE_LINK_BULK_GOVERNANCE_VALUE, defaultProviderProvenanceSchedulerNarrativeTemplateBulkDraft, defaultProviderProvenanceSchedulerStitchedReportViewBulkDraft, defaultProviderProvenanceSchedulerNarrativeRegistryDraft, defaultProviderProvenanceSchedulerNarrativeRegistryBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceQueueFilter, defaultProviderProvenanceSchedulerStitchedReportGovernanceQueueFilter, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilter, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilter, defaultProviderProvenanceSchedulerStitchedReportViewAuditFilter, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilter, defaultProviderProvenanceReportDraft, buildPresetFormFromPreset, buildCurrentPresetRevisionSnapshot, buildEmptyPresetRevisionSnapshot, formatPresetStructuredDiffDisplayValue, isPresetStructuredDiffObject, isPresetStructuredDiffScalar, arePresetStructuredDiffValuesEquivalent, matchesPresetParameterSchemaType, joinPresetStructuredDiffHints, tokenizePresetParameterPath, parsePresetTimeframeToMinutes, buildPresetRankedStringDelta, buildPresetParameterStrategyContext, buildPresetParameterDomainContext, formatPresetParameterSchemaHint, getPresetParameterSchemaEntry, buildPresetStructuredDiffDelta, summarizePresetStructuredDiffGroup, groupPresetStructuredDiffRows, buildPresetStructuredDiffRows, describePresetRevisionDiff, describePresetDraftConflict, matchesPresetRevisionFilter, defaultRunHistoryFilter, sanitizeRunHistoryFilter, cloneRunHistoryFilter, hasRunHistoryFilterCriteria, areRunHistoryFiltersEquivalent, buildRunHistorySavedFilterStorageKey, normalizeSavedRunHistoryFilterPreset, loadSavedRunHistoryFilterPresets, persistSavedRunHistoryFilterPresets, describeRunHistoryFilter, DEFAULT_COMPARISON_INTENT, comparisonIntentOptions, parseExperimentTags, parseJsonObjectInput, formatPresetLifecycleStage, buildRunSubmissionPayload, normalizeRunFormPreset, resolveMarketDataSymbol, buildMarketDataInstrumentFocusKey, isMarketDataInstrumentAtRisk, resolvePreferredMarketDataInstrument, formatWorkflowToken, formatMarketContextFieldProvenance, summarizeProviderRecoveryMarketContextProvenance, serializeLinkedMarketInstrumentContext, getOperatorSeverityRank, normalizeMarketDataProvenanceExportSort, normalizeMarketDataProvenanceExportFilterState, normalizeMarketDataProvenanceExportHistoryEntry, loadPersistedMarketDataProvenanceExportState, persistMarketDataProvenanceExportState, formatMarketDataProvenanceExportFilterSummary, formatProviderProvenanceAnalyticsQuerySummary, normalizeProviderProvenanceDashboardLayoutState, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueSort, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkQueueViewPatch, formatProviderProvenanceSchedulerNarrativeGovernanceQueueSortLabel, providerProvenanceSchedulerNarrativeGovernancePolicySupportsItemType, formatProviderProvenanceSchedulerNarrativeGovernanceQueueViewSummary, buildProviderProvenanceAnalyticsWorkspaceQuery, buildProviderProvenanceAnalyticsQueryStateFromWorkspaceQuery, formatProviderProvenanceSchedulerNarrativeFacet, resolveProviderProvenanceSeriesBarWidth, formatProviderDriftIntensity, formatSchedulerLagSeconds, downloadTextExport, escapeRegExp, normalizeMarketSymbol, buildMarketSymbolSearchVariants, matchesMarketSymbolInText, dedupeMarketDataInstruments, formatMarketDataInstrumentLabel, getMarketDataInstrumentSyncSeverityRank, getMarketDataInstrumentRiskScore, buildLiveMarketDataPreference, getMarketDataInstrumentLiveRelevance, selectPrimaryMarketDataInstrument, extractMatchingMarketTimeframe, extractMatchingMarketSymbols, buildLinkedMarketInstrumentContext, buildLinkedMarketInstrumentContextFromPayload, formatLinkedMarketPrimaryFocusNote, resolveInstrumentsBySymbolsAndTimeframe, resolveMarketDataInstrumentLink, getAlertLinkPriority, compareAlertLinkPriority, resolveAutoLinkedMarketInstrument, formatTimestamp, formatProviderRecoverySchema, formatProviderRecoveryTelemetry, shortenIdentifier, truncateLabel, formatRange, benchmarkArtifactSummaryOrder, benchmarkArtifactSummaryLabels, benchmarkArtifactSectionOrder, benchmarkArtifactSectionLabels, formatBenchmarkArtifactSummaryEntries, benchmarkArtifactSummarySortIndex, formatBenchmarkArtifactSummaryLabel, formatBenchmarkArtifactSummaryValue, formatBenchmarkArtifactSectionEntries, benchmarkArtifactSectionSortIndex, formatBenchmarkArtifactSectionLabel, formatBenchmarkArtifactSectionLines, formatBenchmarkArtifactSectionValue, formatBenchmarkArtifactInlineValue, ProviderProvenanceAnalyticsScope, ProviderProvenanceSchedulerOccurrenceNarrativeFacet, ProviderProvenanceAnalyticsQueryState, ProviderProvenanceSchedulerSearchDashboardFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, ProviderProvenanceSchedulerSearchModerationQueueFilterState, ProviderProvenanceSchedulerSearchModerationStageDraft, ProviderProvenanceSchedulerExportPolicyDraft, OperatorVisibilityAlertEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraftState, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraftState, ProviderProvenanceSchedulerNarrativeBulkToggleValue, ProviderProvenanceSchedulerNarrativeTemplateBulkDraftState, ProviderProvenanceSchedulerStitchedReportViewBulkDraftState, ProviderProvenanceSchedulerNarrativeRegistryDraftState, ProviderProvenanceSchedulerNarrativeRegistryBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraftState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepVersionEntry, ProviderProvenanceSchedulerNarrativeGovernanceQueueFilterState, ProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterState, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilterState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilterState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilterState, ProviderProvenanceSchedulerStitchedReportViewAuditFilterState, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilterState, ProviderProvenanceReportDraftState, LinkedMarketInstrumentContext, MarketDataLinkableAlertRecord, MarketDataIncidentHistoryEntry, ProviderRecoveryMarketContextSummary, MarketDataProviderProvenanceEventRecord, MarketDataPrimaryFocusSelection } from "./ControlRoomViewHelpersContext";
import { loadExpandedGapRows, loadExpandedGapWindowSelections, defaultControlRoomComparisonSelectionState, loadPersistedComparisonSelection, defaultComparisonHistoryPanelState, defaultComparisonHistoryPanelUiState, loadPersistedComparisonHistoryPanelUiState, loadControlRoomUiState, readControlRoomUiStateValue, persistControlRoomUiState, loadComparisonHistorySyncAuditTrail, persistComparisonHistorySyncAuditTrail, loadComparisonSelectionFromUrl, buildComparisonSelectionHistoryUrl, readComparisonHistoryBrowserState, buildComparisonHistoryBrowserState, isSameComparisonHistoryBrowserState, persistComparisonSelectionToUrl, buildComparisonHistoryEntryId, buildComparisonHistoryTabId, formatComparisonHistoryTabLabel, loadComparisonHistoryTabIdentity, buildComparisonHistoryPanelSyncState, buildComparisonHistorySyncSignature, buildComparisonHistorySyncAuditId, buildComparisonHistoryPanelEntry, findComparisonHistoryPanelEntryForSelection, mergeComparisonHistoryPanelState, mergeComparisonHistoryPanelEntries, reconcileComparisonHistoryPanelState, sortComparisonHistoryPanelEntries, limitComparisonHistoryPanelEntries } from "./ControlRoomViewComparisonStorage";
import { normalizeComparisonHistoryPanelUiState, normalizeComparisonHistorySyncAuditFilter, normalizeComparisonHistoryPanelSyncState, normalizeComparisonHistoryPanelState, normalizeComparisonHistoryPanelEntry, normalizeComparisonHistorySyncAuditEntry, normalizeComparisonHistorySyncConflictReview, normalizeComparisonHistorySyncConflictSelectedSources, normalizeComparisonHistorySyncPreferenceReview, normalizeComparisonHistorySyncWorkspaceReview, normalizeComparisonHistorySyncPreferenceState, normalizeComparisonHistorySyncWorkspaceState, normalizeComparisonHistorySyncPreferenceSelectedSources, normalizeComparisonHistorySyncWorkspaceSelectedSources, limitComparisonHistorySyncAuditEntries, appendComparisonHistorySyncAuditEntries, isSameComparisonHistoryPanelState, isSameComparisonHistoryPanelSyncState, isSameComparisonHistoryPanelEntry, getComparisonHistoryPanelEntryChangedFields, formatComparisonHistorySyncConflictScoreLinkValue, formatComparisonHistorySyncConflictRunSelectionValue, formatComparisonHistorySyncConflictFieldValue, hasComparisonHistorySyncConflictFieldDifference, buildDefaultComparisonHistorySyncConflictSelectedSources, buildComparisonHistorySyncConflictReview, buildComparisonHistorySyncConflictReviewGroups, summarizeComparisonHistoryPanelEntryConflict, formatComparisonHistorySyncConflictResolutionSummary, resolveComparisonHistorySyncConflictReviewEntry, applyResolvedComparisonHistoryPanelEntry, summarizeComparisonHistorySyncPreferenceChanges, buildComparisonHistorySyncPreferenceState, formatComparisonHistorySyncPreferenceFieldValue, hasComparisonHistorySyncPreferenceFieldDifference, buildDefaultComparisonHistorySyncPreferenceSelectedSources, buildComparisonHistorySyncPreferenceReview, buildComparisonHistorySyncPreferenceReviewRows, formatComparisonHistorySyncPreferenceResolutionSummary, resolveComparisonHistorySyncPreferenceReview } from "./ControlRoomViewComparisonNormalize";
import { listComparisonHistoryExpandedGapRowKeys, listComparisonHistoryExpandedGapRowDiffKeys, buildComparisonHistoryExpandedGapRowSelectionKey, parseComparisonHistoryExpandedGapRowSelectionKey, buildComparisonHistoryExpandedGapWindowSelectionKey, parseComparisonHistoryExpandedGapWindowSelectionKey, listComparisonHistoryExpandedGapWindowDiffKeys, isSameComparisonHistoryExpandedGapRows, isSameExpandedGapWindowSelections, formatComparisonHistoryExpandedGapRowKey, formatComparisonHistoryExpandedGapRowsValue, formatComparisonHistoryExpandedGapRowsDiffValue, formatComparisonHistorySyncWorkspaceSelectionKeyLabel, rankComparisonHistorySyncWorkspaceSelectionKey, ComparisonHistorySyncWorkspaceSemanticRanking, listComparisonHistorySyncWorkspaceDiffSelectionKeys, resolveComparisonHistorySyncWorkspaceFieldSource, listComparisonHistorySyncWorkspaceConflictSelectionKeys, scoreComparisonHistorySyncWorkspaceCandidateSource, sortComparisonHistorySyncWorkspaceSemanticSignals, rankComparisonHistorySyncWorkspaceFieldSemantics, buildComparisonHistorySyncWorkspaceRecommendedSources, summarizeComparisonHistorySyncWorkspaceChanges, buildComparisonHistorySyncWorkspaceState, formatComparisonHistorySyncWorkspaceFieldValue, hasComparisonHistorySyncWorkspaceFieldDifference, buildDefaultComparisonHistorySyncWorkspaceSelectedSources, buildComparisonHistorySyncWorkspaceReview, buildComparisonHistorySyncWorkspaceReviewRows, buildComparisonHistorySyncWorkspaceRecommendationOverview, formatComparisonHistorySyncWorkspaceResolutionSummary, resolveComparisonHistorySyncWorkspaceReview, buildComparisonHistorySyncAuditEntries } from "./ControlRoomViewComparisonWorkspace";
import { loadLegacyExpandedGapRows, filterExpandedGapRows, normalizeControlRoomComparisonSelection, isSameComparisonSelection, formatComparisonHistoryPanelEntryMeta, matchesComparisonHistoryPanelEntry, formatComparisonHistorySyncAuditKindLabel, buildComparisonHistoryStepDescriptor, resolveComparisonHistoryRunLabel, normalizeComparisonRunIdList, normalizeComparisonIntent, normalizeComparisonScoreSection, normalizeComparisonScoreLinkSource, normalizeComparisonScoreLinkSubFocusKey, normalizeComparisonScoreLinkExpandedState, normalizeComparisonScoreLinkTooltipKey, normalizeComparisonScoreLinkArtifactLineDetailView, normalizeComparisonScoreLinkArtifactLineMicroView, normalizeComparisonScoreLinkArtifactLineNotePage, normalizeComparisonScoreLinkArtifactLineDetailHoverKey, normalizeComparisonScoreLinkArtifactLineScrubStep, normalizeComparisonScoreLinkArtifactHoverKey, normalizeComparisonScoreLinkTarget, isControlRoomUiStateV1, isControlRoomUiStateV2, isControlRoomUiStateV3, isControlRoomUiStateV4, buildRunsPath, buildRunComparisonPath, normalizeRunHistoryFilter, normalizeRunHistoryPresetFilter, getStrategyVersionOptions, pickLatestBenchmarkRun } from "./ControlRoomViewRunFilters";
import { StrategyColumn, PresetStructuredDiffPreview, PresetCatalogPanel, RunForm, ExperimentMetadataPills } from "./ControlRoomViewCatalogPanels";
import { RunListBoundarySurfaceContract, RunListBoundaryGroupContract, RunSurfaceCapabilityDiscoveryPanel, Metric, formatMetric, formatLineagePosture, formatLineageIndicator, formatComparisonScoreValue } from "./ControlRoomViewCapabilities";
import { buildComparisonScoreHighlights, buildComparisonScoreDetailRows, formatComparisonScoreHighlight, formatComparisonScoreComponentLabel, formatComparisonScoreLinkSourceLabel, encodeComparisonScoreLinkToken, decodeComparisonScoreLinkToken, buildComparisonProvenanceLineSubFocusKey, buildComparisonRunCardLineSubFocusKey, buildComparisonRunListLineSubFocusKey, buildComparisonRunListOrderPreviewSubFocusKey, buildComparisonRunListDataSymbolSubFocusKey, buildComparisonProvenanceArtifactSubFocusKey, buildComparisonProvenanceArtifactSectionSubFocusKey, buildComparisonProvenanceArtifactSummaryHoverKey, buildComparisonProvenanceArtifactSectionLineHoverKey, buildComparisonProvenanceArtifactLineDetailHoverKey, buildComparisonMetricTooltipKey, formatComparisonScoreLinkSubFocusLabel, formatComparisonScoreLinkTooltipLabel, formatComparisonScoreLinkArtifactHoverLabel, formatComparisonScoreLinkArtifactLineDetailViewLabel, formatComparisonScoreLinkArtifactLineMicroViewLabel, formatComparisonScoreLinkArtifactLineDetailHoverLabel, formatComparisonScoreComponentDetail, buildComparisonScoreComponentDetails, formatComparisonScoreComponentRawValue, formatComparisonScoreSignedValue, getComparisonScoreLinkedRunRole, isSameComparisonScoreLinkTarget, isSameComparisonScoreLinkSurface, resolveComparisonScoreDrillBackTarget, isComparisonScoreLinkMatch, formatEditableNumber } from "./ControlRoomViewComparisonLinks";
import { formatFixedNumber, buildLiveOrderDraftKey, formatComparisonMetric, formatComparisonDelta, formatComparisonNarrativeLabel, formatComparisonIntentLabel, formatComparisonIntentLegend, formatComparisonIntentTooltip, formatComparisonCueTooltip, buildComparisonCellTooltip, getComparisonIntentClassName, formatLaneLabel, formatVersionLineage, extractDefaultParameters, formatParameterMap, formatParameterValue, summarizeRunNotes } from "./ControlRoomViewFormatting";

export function PanelDisclosure({
  children,
  defaultOpen = false,
  summary,
  title,
}: {
  children: ReactNode;
  defaultOpen?: boolean;
  summary?: string;
  title: string;
}) {
  const bodyId = useId();
  const [open, setOpen] = useState(defaultOpen);

  return (
    <details
      className={`panel-disclosure ${open ? "is-open" : ""}`.trim()}
      onToggle={(event) => setOpen(event.currentTarget.open)}
      open={open}
    >
      <summary aria-controls={bodyId} className="panel-disclosure-summary">
        <div className="panel-disclosure-summary-copy">
          <strong>{title}</strong>
          {summary ? <p>{summary}</p> : null}
        </div>
        <span className="panel-disclosure-state">{open ? "Collapse" : "Expand"}</span>
      </summary>
      <div className="panel-disclosure-body" id={bodyId}>
        {children}
      </div>
    </details>
  );
}

export function BackfillCountStatus({
  instrument,
}: {
  instrument: MarketDataStatus["instruments"][number];
}) {
  if (instrument.backfill_target_candles === null) {
    return <span>n/a</span>;
  }
  return (
    <div className="progress-stack">
      <strong>{formatCompletion(instrument.backfill_completion_ratio)}</strong>
      <span>
        {Math.min(instrument.candle_count, instrument.backfill_target_candles)} /{" "}
        {instrument.backfill_target_candles}
        {instrument.backfill_complete ? " ready" : ""}
      </span>
      <div className="progress-track" aria-hidden="true">
        <span
          style={{
            width: `${Math.round((instrument.backfill_completion_ratio ?? 0) * 100)}%`,
          }}
        />
      </div>
    </div>
  );
}

export function BackfillQualityStatus({
  expanded,
  gapWindowPickerOpen,
  instrument,
  onChangeGapWindowSelections,
  onToggle,
  onSelectAllGapWindows,
  onToggleGapWindowPicker,
  selectedGapWindowKeys,
}: {
  expanded: boolean;
  gapWindowPickerOpen: boolean;
  instrument: MarketDataStatus["instruments"][number];
  onChangeGapWindowSelections?: (gapWindowKeys: string[]) => void;
  onToggle: () => void;
  onSelectAllGapWindows?: () => void;
  onToggleGapWindowPicker?: () => void;
  selectedGapWindowKeys?: string[] | null;
}) {
  const [rangeAnchorGapWindowKey, setRangeAnchorGapWindowKey] = useState<string | null>(null);
  const [dragSelectionState, setDragSelectionState] = useState<GapWindowDragSelectionState | null>(null);
  const [touchSweepHoldProgressState, setTouchSweepHoldProgressState] =
    useState<TouchGapWindowHoldProgressState | null>(null);
  const [touchSweepActivationFeedbackState, setTouchSweepActivationFeedbackState] =
    useState<TouchGapWindowActivationFeedbackState | null>(null);
  const gapWindowPickerListRef = useRef<HTMLDivElement | null>(null);
  const pendingTouchSweepStateRef = useRef<PendingTouchGapWindowSweepState | null>(null);
  const touchSweepHoldTimeoutRef = useRef<number | null>(null);
  const touchSweepActivationFeedbackTimeoutRef = useRef<number | null>(null);
  const touchSweepActivationFeedbackIdRef = useRef(0);
  const orderedGapWindowKeys = instrument.backfill_gap_windows.map((gapWindow) =>
    buildGapWindowKey(gapWindow),
  );
  const clearTouchSweepHoldTimeout = () => {
    if (touchSweepHoldTimeoutRef.current !== null) {
      window.clearTimeout(touchSweepHoldTimeoutRef.current);
      touchSweepHoldTimeoutRef.current = null;
    }
  };
  const clearTouchSweepActivationFeedbackTimeout = () => {
    if (touchSweepActivationFeedbackTimeoutRef.current !== null) {
      window.clearTimeout(touchSweepActivationFeedbackTimeoutRef.current);
      touchSweepActivationFeedbackTimeoutRef.current = null;
    }
  };
  useEffect(() => {
    if (!rangeAnchorGapWindowKey) {
      return;
    }
    if (!orderedGapWindowKeys.includes(rangeAnchorGapWindowKey)) {
      setRangeAnchorGapWindowKey(null);
    }
  }, [orderedGapWindowKeys, rangeAnchorGapWindowKey]);
  useEffect(() => {
    if (
      touchSweepHoldProgressState
      && !orderedGapWindowKeys.includes(touchSweepHoldProgressState.anchorGapWindowKey)
    ) {
      setTouchSweepHoldProgressState(null);
    }
  }, [orderedGapWindowKeys, touchSweepHoldProgressState]);
  useEffect(() => {
    if (!dragSelectionState) {
      return;
    }
    if (
      !orderedGapWindowKeys.includes(dragSelectionState.anchorGapWindowKey)
      || !orderedGapWindowKeys.includes(dragSelectionState.latestGapWindowKey)
    ) {
      setDragSelectionState(null);
    }
  }, [dragSelectionState, orderedGapWindowKeys]);
  useEffect(() => {
    if (!gapWindowPickerOpen && dragSelectionState) {
      setDragSelectionState(null);
    }
  }, [dragSelectionState, gapWindowPickerOpen]);
  useEffect(() => {
    if (gapWindowPickerOpen) {
      return;
    }
    clearTouchSweepHoldTimeout();
    pendingTouchSweepStateRef.current = null;
    setTouchSweepHoldProgressState(null);
    clearTouchSweepActivationFeedbackTimeout();
    setTouchSweepActivationFeedbackState(null);
  }, [gapWindowPickerOpen]);
  useEffect(() => {
    if (!dragSelectionState) {
      return;
    }
    const finishDragSelection = () => {
      setRangeAnchorGapWindowKey(dragSelectionState.latestGapWindowKey);
      setDragSelectionState(null);
    };
    window.addEventListener("pointerup", finishDragSelection);
    window.addEventListener("pointercancel", finishDragSelection);
    return () => {
      window.removeEventListener("pointerup", finishDragSelection);
      window.removeEventListener("pointercancel", finishDragSelection);
    };
  }, [dragSelectionState]);
  useEffect(() => () => {
    clearTouchSweepHoldTimeout();
    clearTouchSweepActivationFeedbackTimeout();
  }, []);
  if (instrument.backfill_contiguous_completion_ratio === null) {
    return <span>n/a</span>;
  }
  const resolvedSelectedGapWindowKeys = resolveGapWindowSelectionList(
    orderedGapWindowKeys,
    selectedGapWindowKeys,
  );
  const visibleGapWindowKeys = new Set(resolvedSelectedGapWindowKeys);
  const hasGapWindowSubset =
    resolvedSelectedGapWindowKeys.length < instrument.backfill_gap_windows.length;
  const selectedGapWindows = resolvedSelectedGapWindowKeys.length
    ? instrument.backfill_gap_windows.filter((gap) => visibleGapWindowKeys.has(buildGapWindowKey(gap)))
    : instrument.backfill_gap_windows;
  const canToggleGapWindows = instrument.backfill_gap_windows.length > MAX_VISIBLE_GAP_WINDOWS;
  const canPickGapWindows = instrument.backfill_gap_windows.length > 1;
  const showExactGapLines =
    expanded
    || hasGapWindowSubset
    || instrument.backfill_gap_windows.length <= MAX_VISIBLE_GAP_WINDOWS;
  const gapLines = showExactGapLines
    ? formatGapWindows(selectedGapWindows)
    : summarizeGapWindows(instrument.backfill_gap_windows);
  const selectedGapWindowCount = selectedGapWindows.length;
  const selectedGapWindowMissingCandles = selectedGapWindows.reduce(
    (total, gapWindow) => total + gapWindow.missing_candles,
    0,
  );
  const rangeAnchorLabel = rangeAnchorGapWindowKey
    ? formatGapWindowKeyLabel(rangeAnchorGapWindowKey)
    : null;
  const touchSweepHoldLabel = touchSweepHoldProgressState
    ? formatGapWindowKeyLabel(touchSweepHoldProgressState.anchorGapWindowKey)
    : null;
  const touchSweepHoldProgressStyle = {
    "--gap-window-touch-hold-duration": `${TOUCH_GAP_WINDOW_SWEEP_HOLD_MS}ms`,
  } as CSSProperties;
  const triggerTouchSweepActivationFeedback = (anchorGapWindowKey: string) => {
    const touchFeedbackDetail: AkraTouchFeedbackDetail = {
      anchorGapWindowKey,
      effect: "impact",
      impactStyle: "light",
      source: "gap-window-picker-sweep-activation",
      trigger: "touch-hold",
    };
    const touchFeedbackEnvelope: AkraTouchFeedbackEnvelope = {
      detail: touchFeedbackDetail,
      type: AKRA_TOUCH_FEEDBACK_EVENT_NAME,
      version: AKRA_TOUCH_FEEDBACK_BRIDGE_VERSION,
    };
    triggerAkraTouchFeedbackBridge(touchFeedbackEnvelope);
    const nextActivationId = touchSweepActivationFeedbackIdRef.current + 1;
    touchSweepActivationFeedbackIdRef.current = nextActivationId;
    clearTouchSweepActivationFeedbackTimeout();
    setTouchSweepActivationFeedbackState({
      activationId: nextActivationId,
      anchorGapWindowKey,
    });
    touchSweepActivationFeedbackTimeoutRef.current = window.setTimeout(() => {
      setTouchSweepActivationFeedbackState((current) =>
        current?.activationId === nextActivationId ? null : current,
      );
      touchSweepActivationFeedbackTimeoutRef.current = null;
    }, 320);
  };
  const applyGapWindowSelectionChange = ({
    anchorGapWindowKey,
    selectedGapWindowKeys,
    targetGapWindowKey,
    targetSelected,
  }: {
    anchorGapWindowKey?: string | null;
    selectedGapWindowKeys?: string[] | null;
    targetGapWindowKey: string;
    targetSelected: boolean;
  }) => {
    const nextSelectedGapWindowKeys = buildGapWindowSelectionUpdate({
      orderedGapWindowKeys,
      rangeAnchorGapWindowKey: anchorGapWindowKey,
      selectedGapWindowKeys,
      targetGapWindowKey,
      targetSelected,
    });
    onChangeGapWindowSelections?.(nextSelectedGapWindowKeys);
    return nextSelectedGapWindowKeys;
  };
  const updateActiveGapWindowSweepTarget = ({
    anchorGapWindowKey,
    baselineSelectedGapWindowKeys,
    latestGapWindowKey,
    pointerId,
    targetSelected,
  }: GapWindowDragSelectionState) => {
    applyGapWindowSelectionChange({
      anchorGapWindowKey,
      selectedGapWindowKeys: baselineSelectedGapWindowKeys,
      targetGapWindowKey: latestGapWindowKey,
      targetSelected,
    });
    setDragSelectionState({
      anchorGapWindowKey,
      baselineSelectedGapWindowKeys,
      latestGapWindowKey,
      pointerId,
      targetSelected,
    });
  };
  const resolveGapWindowKeyFromPointerPoint = (clientX: number, clientY: number) => {
    const pointerTarget = document.elementFromPoint(clientX, clientY);
    if (!(pointerTarget instanceof HTMLElement)) {
      return null;
    }
    const option = pointerTarget.closest<HTMLElement>("[data-gap-window-key]");
    if (!option || !gapWindowPickerListRef.current?.contains(option)) {
      return null;
    }
    return option.dataset.gapWindowKey ?? null;
  };
  const handleGapWindowPointerDown = (
    event: PointerEvent<HTMLLabelElement>,
    gapWindowKey: string,
    checked: boolean,
  ) => {
    if (event.button !== 0) {
      return;
    }
    if (event.pointerType === "touch") {
      clearTouchSweepHoldTimeout();
      pendingTouchSweepStateRef.current = {
        anchorGapWindowKey: gapWindowKey,
        baselineSelectedGapWindowKeys: resolvedSelectedGapWindowKeys,
        latestGapWindowKey: gapWindowKey,
        pointerId: event.pointerId,
        startClientX: event.clientX,
        startClientY: event.clientY,
        targetSelected: !checked,
      };
      setTouchSweepHoldProgressState({
        anchorGapWindowKey: gapWindowKey,
        targetSelected: !checked,
      });
      event.currentTarget.setPointerCapture(event.pointerId);
      touchSweepHoldTimeoutRef.current = window.setTimeout(() => {
        const pendingTouchSweepState = pendingTouchSweepStateRef.current;
        if (
          !pendingTouchSweepState
          || pendingTouchSweepState.pointerId !== event.pointerId
        ) {
          return;
        }
        setTouchSweepHoldProgressState(null);
        triggerTouchSweepActivationFeedback(pendingTouchSweepState.anchorGapWindowKey);
        setRangeAnchorGapWindowKey(pendingTouchSweepState.anchorGapWindowKey);
        updateActiveGapWindowSweepTarget({
          anchorGapWindowKey: pendingTouchSweepState.anchorGapWindowKey,
          baselineSelectedGapWindowKeys: pendingTouchSweepState.baselineSelectedGapWindowKeys,
          latestGapWindowKey: pendingTouchSweepState.anchorGapWindowKey,
          pointerId: pendingTouchSweepState.pointerId,
          targetSelected: pendingTouchSweepState.targetSelected,
        });
      }, TOUCH_GAP_WINDOW_SWEEP_HOLD_MS);
      return;
    }
    event.preventDefault();
    applyGapWindowSelectionChange({
      selectedGapWindowKeys: resolvedSelectedGapWindowKeys,
      targetGapWindowKey: gapWindowKey,
      targetSelected: !checked,
    });
    setRangeAnchorGapWindowKey(gapWindowKey);
    setDragSelectionState({
      anchorGapWindowKey: gapWindowKey,
      baselineSelectedGapWindowKeys: resolvedSelectedGapWindowKeys,
      latestGapWindowKey: gapWindowKey,
      pointerId: event.pointerId,
      targetSelected: !checked,
    });
  };
  const handleGapWindowPointerEnter = (
    event: PointerEvent<HTMLLabelElement>,
    gapWindowKey: string,
  ) => {
    if (
      !dragSelectionState
      || event.pointerId !== dragSelectionState.pointerId
      || event.buttons === 0
      || dragSelectionState.latestGapWindowKey === gapWindowKey
    ) {
      return;
    }
    updateActiveGapWindowSweepTarget({
      ...dragSelectionState,
      latestGapWindowKey: gapWindowKey,
    });
  };
  const handleTouchGapWindowPointerMove = (
    event: PointerEvent<HTMLLabelElement>,
  ) => {
    const pendingTouchSweepState = pendingTouchSweepStateRef.current;
    if (
      event.pointerType !== "touch"
      || !pendingTouchSweepState
      || pendingTouchSweepState.pointerId !== event.pointerId
    ) {
      return;
    }
    const deltaX = event.clientX - pendingTouchSweepState.startClientX;
    const deltaY = event.clientY - pendingTouchSweepState.startClientY;
    const pointerTravel = Math.hypot(deltaX, deltaY);
    if (!dragSelectionState) {
      if (pointerTravel > TOUCH_GAP_WINDOW_SWEEP_MOVE_TOLERANCE_PX) {
        clearTouchSweepHoldTimeout();
        pendingTouchSweepStateRef.current = null;
        setTouchSweepHoldProgressState(null);
        if (event.currentTarget.hasPointerCapture(event.pointerId)) {
          event.currentTarget.releasePointerCapture(event.pointerId);
        }
      }
      return;
    }
    event.preventDefault();
    const hoveredGapWindowKey =
      resolveGapWindowKeyFromPointerPoint(event.clientX, event.clientY)
      ?? pendingTouchSweepState.anchorGapWindowKey;
    if (hoveredGapWindowKey === dragSelectionState.latestGapWindowKey) {
      return;
    }
    pendingTouchSweepStateRef.current = {
      ...pendingTouchSweepState,
      latestGapWindowKey: hoveredGapWindowKey,
    };
    updateActiveGapWindowSweepTarget({
      anchorGapWindowKey: pendingTouchSweepState.anchorGapWindowKey,
      baselineSelectedGapWindowKeys: pendingTouchSweepState.baselineSelectedGapWindowKeys,
      latestGapWindowKey: hoveredGapWindowKey,
      pointerId: pendingTouchSweepState.pointerId,
      targetSelected: pendingTouchSweepState.targetSelected,
    });
  };
  const handleTouchGapWindowPointerEnd = (
    event: PointerEvent<HTMLLabelElement>,
  ) => {
    const pendingTouchSweepState = pendingTouchSweepStateRef.current;
    if (
      event.pointerType !== "touch"
      || !pendingTouchSweepState
      || pendingTouchSweepState.pointerId !== event.pointerId
    ) {
      return;
    }
    clearTouchSweepHoldTimeout();
    setTouchSweepHoldProgressState(null);
    if (!dragSelectionState) {
      applyGapWindowSelectionChange({
        selectedGapWindowKeys: pendingTouchSweepState.baselineSelectedGapWindowKeys,
        targetGapWindowKey: pendingTouchSweepState.anchorGapWindowKey,
        targetSelected: pendingTouchSweepState.targetSelected,
      });
      setRangeAnchorGapWindowKey(pendingTouchSweepState.anchorGapWindowKey);
    } else {
      setRangeAnchorGapWindowKey(dragSelectionState.latestGapWindowKey);
      setDragSelectionState(null);
    }
    pendingTouchSweepStateRef.current = null;
    if (event.currentTarget.hasPointerCapture(event.pointerId)) {
      event.currentTarget.releasePointerCapture(event.pointerId);
    }
  };
  const handleGapWindowKeyboardToggle = (
    event: KeyboardEvent<HTMLInputElement>,
    gapWindowKey: string,
    checked: boolean,
  ) => {
    if (event.key !== " " && event.key !== "Enter") {
      return;
    }
    event.preventDefault();
    applyGapWindowSelectionChange({
      anchorGapWindowKey: event.shiftKey ? rangeAnchorGapWindowKey : null,
      selectedGapWindowKeys: resolvedSelectedGapWindowKeys,
      targetGapWindowKey: gapWindowKey,
      targetSelected: !checked,
    });
    setRangeAnchorGapWindowKey(gapWindowKey);
  };
  return (
    <div className="progress-stack">
      <strong>{formatCompletion(instrument.backfill_contiguous_completion_ratio)}</strong>
      <span>
        {instrument.backfill_contiguous_complete
          ? "gap-free"
          : `gaps: ${instrument.backfill_contiguous_missing_candles ?? 0}`}
      </span>
      {gapLines.length ? (
        <div className="progress-detail-list">
          {gapLines.map((line) => (
            <span
              className={line.kind === "summary" ? "progress-detail-summary" : undefined}
              key={line.key}
            >
              {line.label}
            </span>
          ))}
        </div>
      ) : null}
      {hasGapWindowSubset ? (
        <span>
          {`${expanded ? "Review subset" : "Focused subset"}: ${selectedGapWindowCount} / ${
            instrument.backfill_gap_windows.length
          } gaps`}
        </span>
      ) : null}
      {canToggleGapWindows || canPickGapWindows ? (
        <div className="progress-action-row">
          {canToggleGapWindows ? (
            <button
              className="progress-toggle"
              onClick={onToggle}
              type="button"
            >
              {expanded
                ? "Collapse gap detail"
                : `Expand ${instrument.backfill_gap_windows.length}-gap detail`}
            </button>
          ) : null}
          {canPickGapWindows && onToggleGapWindowPicker ? (
            <button
              className="progress-toggle"
              onClick={onToggleGapWindowPicker}
              type="button"
            >
              {gapWindowPickerOpen
                ? "Hide gap picker"
                : hasGapWindowSubset
                  ? "Refine focused gaps"
                  : "Pick visible gaps"}
            </button>
          ) : null}
          {gapWindowPickerOpen && hasGapWindowSubset && onSelectAllGapWindows ? (
            <button
              className="progress-toggle"
              onClick={onSelectAllGapWindows}
              type="button"
            >
              Show full range
            </button>
          ) : null}
        </div>
      ) : null}
      {gapWindowPickerOpen && canPickGapWindows ? (
        <div
          className={`gap-window-picker ${dragSelectionState ? "is-sweeping" : ""} ${
            touchSweepActivationFeedbackState ? "has-touch-feedback" : ""
          }`}
        >
          <div className="gap-window-picker-head">
            <span className="gap-window-picker-title">Visible gap windows</span>
            <span className="gap-window-picker-summary">
              {`${selectedGapWindowCount} / ${instrument.backfill_gap_windows.length} selected · ${selectedGapWindowMissingCandles} missing candles`}
            </span>
          </div>
          <span className="gap-window-picker-anchor">
            {dragSelectionState
              ? `Sweep ${dragSelectionState.targetSelected ? "select" : "hide"} mode from ${formatGapWindowKeyLabel(
                  dragSelectionState.anchorGapWindowKey,
                )}.`
              : touchSweepHoldLabel
                ? `Hold to ${
                    touchSweepHoldProgressState?.targetSelected ? "sweep select" : "sweep hide"
                  } from ${touchSweepHoldLabel}.`
              : rangeAnchorLabel
                ? `Range anchor: ${rangeAnchorLabel}. Shift-click another gap to apply the full range.`
                : "Tip: click a gap to set the range anchor, then shift-click or drag across gaps to apply a range."}
          </span>
          {touchSweepHoldProgressState ? (
            <div
              className="gap-window-picker-hold-progress"
              style={touchSweepHoldProgressStyle}
            >
              <span className="gap-window-picker-hold-progress-bar" />
            </div>
          ) : null}
          <div
            className="gap-window-picker-list"
            ref={gapWindowPickerListRef}
          >
            {instrument.backfill_gap_windows.map((gapWindow) => {
              const gapWindowKey = buildGapWindowKey(gapWindow);
              const checked = visibleGapWindowKeys.has(gapWindowKey);
              return (
                <label
                  className={`gap-window-picker-option ${checked ? "is-active" : ""} ${
                    rangeAnchorGapWindowKey === gapWindowKey ? "is-anchor" : ""
                  } ${
                    dragSelectionState?.latestGapWindowKey === gapWindowKey ? "is-sweep-target" : ""
                  } ${
                    touchSweepActivationFeedbackState?.anchorGapWindowKey === gapWindowKey
                      ? "has-touch-feedback"
                      : ""
                  }`}
                  data-gap-window-key={gapWindowKey}
                  key={gapWindowKey}
                  onPointerDown={(event) =>
                    handleGapWindowPointerDown(event, gapWindowKey, checked)
                  }
                  onPointerEnter={(event) =>
                    handleGapWindowPointerEnter(event, gapWindowKey)
                  }
                  onPointerMove={handleTouchGapWindowPointerMove}
                  onPointerUp={handleTouchGapWindowPointerEnd}
                  onPointerCancel={handleTouchGapWindowPointerEnd}
                >
                  <input
                    checked={checked}
                    disabled={checked && selectedGapWindowCount === 1}
                    onClick={(event) => {
                      event.preventDefault();
                    }}
                    onKeyDown={(event) =>
                      handleGapWindowKeyboardToggle(event, gapWindowKey, checked)
                    }
                    readOnly
                    type="checkbox"
                  />
                  <span className="gap-window-picker-option-copy">
                    <span className="gap-window-picker-option-label">
                      {formatGapWindowKeyLabel(gapWindowKey)}
                    </span>
                    <span className="gap-window-picker-option-meta">
                      {`${gapWindow.missing_candles} missing candles`}
                    </span>
                  </span>
                </label>
              );
            })}
          </div>
          <span className="gap-window-picker-footnote">
            Keep at least one gap window visible for review.
          </span>
        </div>
      ) : null}
      <div className="progress-track" aria-hidden="true">
        <span
          style={{
            width: `${Math.round((instrument.backfill_contiguous_completion_ratio ?? 0) * 100)}%`,
          }}
        />
      </div>
    </div>
  );
}

export function SyncCheckpointStatus({
  instrument,
}: {
  instrument: MarketDataStatus["instruments"][number];
}) {
  const checkpoint = instrument.sync_checkpoint;
  if (!checkpoint) {
    return <span>n/a</span>;
  }
  return (
    <div className="progress-stack">
      <strong title={checkpoint.checkpoint_id}>{shortenIdentifier(checkpoint.checkpoint_id)}</strong>
      <span>
        {checkpoint.candle_count} candles
        {checkpoint.contiguous_missing_candles > 0
          ? ` / gaps ${checkpoint.contiguous_missing_candles}`
          : " / gap-free"}
      </span>
      <span>{formatTimestamp(checkpoint.recorded_at)}</span>
    </div>
  );
}

export function SyncFailureStatus({
  instrument,
}: {
  instrument: MarketDataStatus["instruments"][number];
}) {
  if (instrument.failure_count_24h === 0 && instrument.recent_failures.length === 0) {
    return <span>clear</span>;
  }
  const latestFailure = instrument.recent_failures[0];
  return (
    <div className="progress-stack">
      <strong>{instrument.failure_count_24h} in 24h</strong>
      <span>
        {latestFailure
          ? `${latestFailure.operation} @ ${formatTimestamp(latestFailure.failed_at)}`
          : "history unavailable"}
      </span>
      {latestFailure ? (
        <span title={latestFailure.error}>{truncateLabel(latestFailure.error, 56)}</span>
      ) : null}
    </div>
  );
}

export function formatCompletion(value: number | null) {
  if (value === null) {
    return "n/a";
  }
  return `${Math.round(value * 100)}%`;
}

export function summarizeGapWindows(
  gapWindows: MarketDataStatus["instruments"][number]["backfill_gap_windows"],
) {
  if (gapWindows.length <= MAX_VISIBLE_GAP_WINDOWS) {
    return formatGapWindows(gapWindows);
  }

  const recentWindows = gapWindows.slice(-(MAX_VISIBLE_GAP_WINDOWS - 1));
  const collapsedWindows = gapWindows.slice(0, -(MAX_VISIBLE_GAP_WINDOWS - 1));
  const collapsedMissing = collapsedWindows.reduce(
    (total, gap) => total + gap.missing_candles,
    0,
  );
  const lastCollapsedWindow = collapsedWindows[collapsedWindows.length - 1];

  return [
    {
      key: `summary-${collapsedWindows[0].start_at}-${lastCollapsedWindow.end_at}`,
      kind: "summary" as const,
      label:
        `${collapsedWindows.length} older windows | ` +
        `${formatRange(collapsedWindows[0].start_at, lastCollapsedWindow.end_at)} | ` +
        `${collapsedMissing} missing`,
    },
    ...formatGapWindows(recentWindows),
  ];
}

export function formatGapWindows(
  gapWindows: MarketDataStatus["instruments"][number]["backfill_gap_windows"],
) {
  return gapWindows.map((gap) => ({
    key: buildGapWindowKey(gap),
    kind: "exact" as const,
    label: `${formatRange(gap.start_at, gap.end_at)} (${gap.missing_candles})`,
  }));
}

export function buildLegacyGapWindowKey(
  gapWindow: MarketDataStatus["instruments"][number]["backfill_gap_windows"][number],
) {
  return `${gapWindow.start_at}|${gapWindow.end_at}|${gapWindow.missing_candles}`;
}

export function buildGapWindowKey(
  gapWindow: MarketDataStatus["instruments"][number]["backfill_gap_windows"][number],
) {
  return gapWindow.gap_window_id || buildLegacyGapWindowKey(gapWindow);
}

export function parseGapWindowKey(key: string) {
  if (key.startsWith("gw|")) {
    const [, occurrenceIndexRaw, startAt, endAt, missingCandlesRaw] = key.split("|");
    const occurrenceIndex = Number(occurrenceIndexRaw);
    const missingCandles = Number(missingCandlesRaw);
    return {
      startAt: startAt || null,
      endAt: endAt || null,
      missingCandles: Number.isFinite(missingCandles) ? missingCandles : null,
      occurrenceIndex: Number.isFinite(occurrenceIndex) ? occurrenceIndex : null,
    };
  }
  const [startAt, endAt, missingCandlesRaw] = key.split("|");
  const missingCandles = Number(missingCandlesRaw);
  return {
    startAt: startAt || null,
    endAt: endAt || null,
    missingCandles: Number.isFinite(missingCandles) ? missingCandles : null,
    occurrenceIndex: null,
  };
}

export function formatGapWindowKeyLabel(key: string) {
  const parsed = parseGapWindowKey(key);
  return `${formatRange(parsed.startAt, parsed.endAt)} (${parsed.missingCandles ?? "n/a"})${
    parsed.occurrenceIndex !== null ? ` · slot ${parsed.occurrenceIndex + 1}` : ""
  }`;
}

export function normalizeExpandedGapWindowSelectionList(value: unknown) {
  if (!Array.isArray(value)) {
    return [];
  }
  return [...new Set(value.filter((candidate): candidate is string => typeof candidate === "string" && candidate.trim().length > 0))].sort();
}

export function resolveGapWindowSelectionList(
  orderedGapWindowKeys: string[],
  selectedGapWindowKeys?: string[] | null,
) {
  if (!orderedGapWindowKeys.length) {
    return [];
  }
  const allowedGapWindowKeys = new Set(orderedGapWindowKeys);
  const normalizedGapWindowKeys = normalizeExpandedGapWindowSelectionList(
    selectedGapWindowKeys,
  ).filter((gapWindowKey) => allowedGapWindowKeys.has(gapWindowKey));
  if (!normalizedGapWindowKeys.length) {
    return orderedGapWindowKeys;
  }
  const normalizedSelection = new Set(normalizedGapWindowKeys);
  return orderedGapWindowKeys.filter((gapWindowKey) => normalizedSelection.has(gapWindowKey));
}

export function buildGapWindowSelectionUpdate({
  orderedGapWindowKeys,
  rangeAnchorGapWindowKey,
  selectedGapWindowKeys,
  targetGapWindowKey,
  targetSelected,
}: {
  orderedGapWindowKeys: string[];
  rangeAnchorGapWindowKey?: string | null;
  selectedGapWindowKeys?: string[] | null;
  targetGapWindowKey: string;
  targetSelected: boolean;
}) {
  const currentSelection = resolveGapWindowSelectionList(
    orderedGapWindowKeys,
    selectedGapWindowKeys,
  );
  const targetGapWindowIndex = orderedGapWindowKeys.indexOf(targetGapWindowKey);
  if (targetGapWindowIndex < 0) {
    return currentSelection;
  }
  const anchorGapWindowIndex = rangeAnchorGapWindowKey
    ? orderedGapWindowKeys.indexOf(rangeAnchorGapWindowKey)
    : -1;
  const rangeGapWindowKeys =
    anchorGapWindowIndex >= 0 && anchorGapWindowIndex !== targetGapWindowIndex
      ? orderedGapWindowKeys.slice(
          Math.min(anchorGapWindowIndex, targetGapWindowIndex),
          Math.max(anchorGapWindowIndex, targetGapWindowIndex) + 1,
        )
      : [targetGapWindowKey];
  const nextSelection = new Set(currentSelection);
  if (targetSelected) {
    rangeGapWindowKeys.forEach((gapWindowKey) => nextSelection.add(gapWindowKey));
  } else {
    rangeGapWindowKeys.forEach((gapWindowKey) => nextSelection.delete(gapWindowKey));
    if (!nextSelection.size) {
      return currentSelection;
    }
  }
  return orderedGapWindowKeys.filter((gapWindowKey) => nextSelection.has(gapWindowKey));
}

export function isSameGapWindowSelectionList(left: string[], right: string[]) {
  return (
    left.length === right.length
    && left.every((gapWindowKey, index) => gapWindowKey === right[index])
  );
}

export function filterExpandedGapWindowSelections(value: unknown): ExpandedGapWindowSelections {
  if (!value || typeof value !== "object") {
    return {};
  }
  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>)
      .map(([rowKey, selectedWindows]) => [rowKey, normalizeExpandedGapWindowSelectionList(selectedWindows)] as const)
      .filter(([, selectedWindows]) => selectedWindows.length > 0),
  );
}

export function buildGapWindowSelectionLookup(marketStatus: MarketDataStatus) {
  return Object.fromEntries(
    marketStatus.instruments.map((instrument) => [
      instrumentGapRowKey(instrument),
      Object.fromEntries(
        instrument.backfill_gap_windows.flatMap((gapWindow) => {
          const stableKey = buildGapWindowKey(gapWindow);
          const legacyKey = buildLegacyGapWindowKey(gapWindow);
          return [
            [stableKey, stableKey],
            [legacyKey, stableKey],
          ];
        }),
      ),
    ]),
  ) as Record<string, Record<string, string>>;
}

export function instrumentGapRowKey(instrument: MarketDataStatus["instruments"][number]) {
  return `${instrument.instrument_id}:${instrument.timeframe}`;
}

export function toggleExpandedGapRow(current: Record<string, boolean>, key: string) {
  if (current[key]) {
    const next = { ...current };
    delete next[key];
    return next;
  }
  return { ...current, [key]: true };
}

export function pruneExpandedGapRows(
  current: Record<string, boolean>,
  marketStatus: MarketDataStatus,
) {
  const activeKeys = new Set(
    marketStatus.instruments
      .filter((instrument) => instrument.backfill_gap_windows.length > MAX_VISIBLE_GAP_WINDOWS)
      .map((instrument) => instrumentGapRowKey(instrument)),
  );
  const next = Object.fromEntries(
    Object.entries(current).filter(([key, expanded]) => expanded && activeKeys.has(key)),
  );
  const currentKeys = Object.keys(current);
  const nextKeys = Object.keys(next);
  if (
    currentKeys.length === nextKeys.length &&
    currentKeys.every((key) => next[key] === current[key])
  ) {
    return current;
  }
  return next;
}

export function pruneExpandedGapWindowSelections(
  current: ExpandedGapWindowSelections,
  marketStatus: MarketDataStatus,
) {
  const activeSelections = buildGapWindowSelectionLookup(marketStatus);
  const next = Object.fromEntries(
    Object.entries(filterExpandedGapWindowSelections(current)).flatMap(([rowKey, selectedWindows]) => {
      const activeWindowAliases = activeSelections[rowKey] ?? {};
      const activeWindows = new Set(Object.values(activeWindowAliases));
      if (!Object.keys(activeWindowAliases).length) {
        return [];
      }
      const nextSelectedWindows = [...new Set(
        selectedWindows
          .map((windowKey) => activeWindowAliases[windowKey] ?? "")
          .filter((windowKey) => activeWindows.has(windowKey)),
      )].sort();
      return nextSelectedWindows.length ? [[rowKey, nextSelectedWindows]] : [];
    }),
  );
  const currentEntries = Object.entries(filterExpandedGapWindowSelections(current));
  const nextEntries = Object.entries(next);
  if (
    currentEntries.length === nextEntries.length
    && currentEntries.every(([rowKey, selectedWindows], index) => {
      const [nextRowKey, nextSelectedWindows] = nextEntries[index] ?? [];
      return (
        rowKey === nextRowKey
        && selectedWindows.length === (nextSelectedWindows?.length ?? 0)
        && selectedWindows.every((windowKey, windowIndex) => windowKey === nextSelectedWindows?.[windowIndex])
      );
    })
  ) {
    return current;
  }
  return next;
}
