// @ts-nocheck

import { CSSProperties, FormEvent, KeyboardEvent, MouseEvent, PointerEvent, ReactNode, forwardRef, useCallback, useEffect, useId, useLayoutEffect, useMemo, useRef, useState, AKRA_TOUCH_FEEDBACK_BRIDGE_VERSION, AKRA_TOUCH_FEEDBACK_EVENT_NAME, AkraTouchFeedbackDetail, AkraTouchFeedbackEnvelope, triggerAkraTouchFeedbackBridge, WorkspaceShell, buildControlWorkspaceDescriptors, ControlWorkspaceDescriptor, ControlStripMetric, useWorkspaceRoute, WorkspaceRouteContent, buildRunHistoryWorkspacePanels, LiveOrderReplacementDraft, RunHistoryWorkspaceSectionProps, RunOrderControls, getRunListBoundaryContractSnapshot, getRunListBoundarySurfaceLabel, getRunSurfaceCapabilityFamily, getRunSurfaceCapabilityFamilyOrder, getRunSurfaceCapabilityGroupOrder, getRunSurfaceCapabilitySchemaContract, getRunSurfaceCollectionQueryContracts, getRunSurfaceSharedContracts, getRunSurfaceSubresourceContracts, RunListComparisonBoundaryNote, shouldEnableReferenceProvenanceSemantics, shouldEnableRunListMetricDrillBack, shouldEnableRunSnapshotSemantics, shouldEnableStrategyCatalogSchemaHints, shouldHydratePresetParameterDefaults, shouldRenderOrderActionBoundaryNote, shouldRenderWorkflowControlBoundaryNote, RunSurfaceCollectionQueryBuilder, formatComparisonTooltipTuningDelta, formatComparisonTooltipTuningValue, formatRelativeTimestampLabel, RunSection, RunSurfaceCollectionQueryBuilderApplyPayload, RunSurfaceCollectionQueryRuntimeCandidateContextSelection, RunSurfaceCollectionQueryRuntimeCandidateSample, applyProviderProvenanceSchedulerStitchedReportGovernancePlan, applyProviderProvenanceSchedulerNarrativeGovernancePlan, approveProviderProvenanceSchedulerStitchedReportGovernancePlan, approveProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceAnalyticsPreset, createProviderProvenanceDashboardView, createProviderProvenanceExportJob, createProviderProvenanceSchedulerStitchedReportGovernanceRegistry, createProviderProvenanceSchedulerStitchedReportGovernancePlan, createProviderProvenanceSchedulerStitchedReportView, createProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, captureProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchy, createProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, createProviderProvenanceSchedulerNarrativeGovernancePlan, createProviderProvenanceSchedulerNarrativeRegistryEntry, createProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceScheduledReport, approveProviderProvenanceExportJob, applyProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, deleteProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, deleteProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, deleteProviderProvenanceSchedulerNarrativeRegistryEntry, deleteProviderProvenanceSchedulerStitchedReportView, deleteProviderProvenanceSchedulerNarrativeTemplate, createProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, createRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, createRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, downloadProviderProvenanceExportJob, downloadRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJob, escalateProviderProvenanceExportJob, exportProviderProvenanceSchedulerHealth, exportProviderProvenanceSchedulerStitchedNarrativeReport, reconstructProviderProvenanceSchedulerHealthExport, exportRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, fetchJson, getProviderProvenanceExportAnalytics, getProviderProvenanceExportJobHistory, getProviderProvenanceSchedulerHealthAnalytics, getProviderProvenanceScheduledReportHistory, getRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobHistory, listProviderProvenanceAnalyticsPresets, listProviderProvenanceDashboardViews, listProviderProvenanceSchedulerStitchedReportViews, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, listProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogs, listProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisions, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAudits, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplates, listProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisions, listProviderProvenanceSchedulerNarrativeGovernancePlans, listProviderProvenanceSchedulerNarrativeRegistryEntries, listProviderProvenanceSchedulerNarrativeRegistryRevisions, listProviderProvenanceSchedulerNarrativeTemplates, listProviderProvenanceSchedulerNarrativeTemplateRevisions, listProviderProvenanceSchedulerStitchedReportGovernancePolicyCatalogs, listProviderProvenanceSchedulerStitchedReportGovernancePolicyTemplates, listProviderProvenanceSchedulerStitchedReportGovernancePlans, rollbackProviderProvenanceSchedulerStitchedReportGovernancePlan, rollbackProviderProvenanceSchedulerNarrativeGovernancePlan, listMarketDataIngestionJobs, listMarketDataLineageHistory, listProviderProvenanceExportJobs, listProviderProvenanceSchedulerAlertHistory, listProviderProvenanceSchedulerHealthHistory, listProviderProvenanceSchedulerStitchedReportGovernanceRegistries, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryAudits, listProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisions, listProviderProvenanceSchedulerStitchedReportViewAudits, listProviderProvenanceSchedulerStitchedReportViewRevisions, getProviderProvenanceSchedulerSearchDashboard, bulkGovernProviderProvenanceSchedulerSearchModerationPolicyCatalogs, bulkGovernProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, createProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicy, createProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, listProviderProvenanceSchedulerSearchModerationPolicyCatalogs, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlans, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAudits, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicies, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisions, listProviderProvenanceSchedulerSearchModerationCatalogGovernancePlans, listProviderProvenanceSchedulerSearchModerationPolicyCatalogAudits, listProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisions, listProviderProvenanceSchedulerSearchModerationPlans, listProviderProvenanceScheduledReports, listRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, listRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, approveProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, approveProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, approveProviderProvenanceSchedulerSearchModerationPlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, applyProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, applyProviderProvenanceSchedulerSearchModerationPlan, createProviderProvenanceSchedulerSearchModerationPolicyCatalog, deleteProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, deleteProviderProvenanceSchedulerSearchModerationPolicyCatalog, moderateProviderProvenanceSchedulerSearchFeedbackBatch, moderateProviderProvenanceSchedulerSearchFeedback, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAuditExportJobs, pruneRunSurfaceCollectionQueryBuilderServerReplayLinkAudits, recordProviderProvenanceSchedulerSearchFeedback, resolveRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevision, restoreProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevision, restoreProviderProvenanceSchedulerSearchModerationPolicyCatalogRevision, restoreProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevision, restoreProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevision, restoreProviderProvenanceSchedulerNarrativeRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevision, restoreProviderProvenanceSchedulerStitchedReportViewRevision, restoreProviderProvenanceSchedulerNarrativeTemplateRevision, revokeRunSurfaceCollectionQueryBuilderServerReplayLinkAlias, runProviderProvenanceSchedulerNarrativeGovernancePlanBatchAction, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkGovernance, runProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkGovernance, stageProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlan, stageProviderProvenanceSchedulerSearchModerationCatalogGovernancePlan, stageProviderProvenanceSchedulerSearchModerationPlan, updateProviderProvenanceSchedulerSearchModerationPolicyCatalog, updateProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicy, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, stageProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, stageProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, runDueProviderProvenanceScheduledReports, runProviderProvenanceScheduledReport, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStep, updateProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, updateProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, updateProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, updateProviderProvenanceSchedulerNarrativeRegistryEntry, updateProviderProvenanceSchedulerStitchedReportGovernanceRegistry, updateProviderProvenanceSchedulerStitchedReportView, updateProviderProvenanceSchedulerNarrativeTemplate, updateProviderProvenanceExportJobPolicy, deleteProviderProvenanceSchedulerStitchedReportGovernanceRegistry, ALL_FILTER_VALUE, apiBase, COMPARISON_FOCUS_ARTIFACT_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_HOVER_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_MICRO_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_NOTE_PAGE_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_SCRUB_SEARCH_PARAM, COMPARISON_FOCUS_ARTIFACT_LINE_VIEW_SEARCH_PARAM, COMPARISON_FOCUS_COMPONENT_SEARCH_PARAM, COMPARISON_FOCUS_DETAIL_SEARCH_PARAM, COMPARISON_FOCUS_EXPANDED_SEARCH_PARAM, COMPARISON_FOCUS_ORIGIN_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_RUN_ID_SEARCH_PARAM, COMPARISON_FOCUS_SECTION_SEARCH_PARAM, COMPARISON_FOCUS_SOURCE_SEARCH_PARAM, COMPARISON_FOCUS_TOOLTIP_SEARCH_PARAM, COMPARISON_HISTORY_BROWSER_STATE_KEY, COMPARISON_HISTORY_BROWSER_STATE_VERSION, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_KEY, COMPARISON_HISTORY_SYNC_AUDIT_SESSION_VERSION, COMPARISON_HISTORY_SYNC_CONFLICT_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_PREFERENCE_FIELD_DEFINITIONS, COMPARISON_HISTORY_SYNC_WORKSPACE_FIELD_DEFINITIONS, COMPARISON_HISTORY_TAB_ID_SESSION_KEY, COMPARISON_INTENT_SEARCH_PARAM, COMPARISON_RUN_ID_SEARCH_PARAM, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_KEY, COMPARISON_TOOLTIP_CONFLICT_UI_STORAGE_VERSION, COMPARISON_TOOLTIP_TUNING_GROUPS, COMPARISON_TOOLTIP_TUNING_LABELS, COMPARISON_TOOLTIP_TUNING_SHARE_PARAM, COMPARISON_TOOLTIP_TUNING_STORAGE_KEY, COMPARISON_TOOLTIP_TUNING_STORAGE_VERSION, COMPARISON_TOOLTIP_UNCHANGED_GROUP_COLLAPSE_THRESHOLD, CONTROL_ROOM_UI_STATE_STORAGE_KEY, CONTROL_ROOM_UI_STATE_VERSION, DEFAULT_COMPARISON_TOOLTIP_PRESET_IMPORT_CONFLICT_POLICY, DEFAULT_COMPARISON_TOOLTIP_TUNING, DEFAULT_CONTROL_ROOM_DOCUMENT_TITLE, LEGACY_GAP_WINDOW_EXPANSION_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_KEY, MARKET_DATA_PROVENANCE_EXPORT_STORAGE_VERSION, MAX_COMPARISON_HISTORY_PANEL_ENTRIES, MAX_COMPARISON_HISTORY_SYNC_AUDIT_ENTRIES, MAX_COMPARISON_RUNS, MAX_MARKET_DATA_PROVENANCE_EXPORT_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_CONFLICT_ENTRIES, MAX_RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_REVIEWED_CONFLICT_KEYS, MAX_VISIBLE_COMPARISON_TOOLTIP_CONFLICT_SESSION_SUMMARIES, MAX_VISIBLE_GAP_WINDOWS, PRESET_PROFILE_AGGRESSIVENESS_RANKS, PRESET_PROFILE_CONFIDENCE_RANKS, PRESET_PROFILE_SPEED_RANKS, PRESET_TIMEFRAME_UNIT_TO_MINUTES, REPLAY_INTENT_ACTION_FILTER_SEARCH_PARAM, REPLAY_INTENT_ALIAS_SEARCH_PARAM, REPLAY_INTENT_EDGE_FILTER_SEARCH_PARAM, REPLAY_INTENT_GROUP_FILTER_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_DIFF_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_GROUP_SEARCH_PARAM, REPLAY_INTENT_PREVIEW_TRACE_SEARCH_PARAM, REPLAY_INTENT_SCOPE_SEARCH_PARAM, REPLAY_INTENT_SEARCH_PARAM, REPLAY_INTENT_STEP_SEARCH_PARAM, REPLAY_INTENT_TEMPLATE_SEARCH_PARAM, RUN_HISTORY_SAVED_FILTER_STORAGE_KEY_PREFIX, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_CONFLICTS_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_SYNC_AUDIT_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_HISTORY_TAB_ID_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_BROWSER_STATE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_INTENT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_ALIAS_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_AUDIT_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_PAYLOAD_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SESSION_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_KEY, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_GOVERNANCE_SYNC_STORAGE_VERSION, RUN_SURFACE_QUERY_BUILDER_REPLAY_LINK_SIGNING_SECRET_STORAGE_KEY, SHOW_COMPARISON_TOOLTIP_TUNING_PANEL, TOUCH_GAP_WINDOW_SWEEP_HOLD_MS, TOUCH_GAP_WINDOW_SWEEP_MOVE_TOLERANCE_PX, BenchmarkArtifact, ParameterSchema, ComparisonCueKind, ComparisonHistoryBrowserState, ComparisonHistoryPanelEntry, ComparisonHistoryPanelState, ComparisonHistoryPanelSyncState, ComparisonHistoryStepDescriptor, ComparisonHistorySyncAuditEntry, ComparisonHistorySyncAuditFilter, ComparisonHistorySyncAuditKind, ComparisonHistorySyncAuditTrailState, ComparisonHistorySyncConflictFieldKey, ComparisonHistorySyncConflictFieldSource, ComparisonHistorySyncConflictReview, ComparisonHistorySyncConflictReviewGroup, ComparisonHistorySyncPreferenceFieldKey, ComparisonHistorySyncPreferenceReview, ComparisonHistorySyncPreferenceReviewRow, ComparisonHistorySyncPreferenceState, ComparisonHistorySyncWorkspaceRecommendationOverview, ComparisonHistorySyncWorkspaceReview, ComparisonHistorySyncWorkspaceReviewRow, ComparisonHistorySyncWorkspaceReviewSelectionKey, ComparisonHistorySyncWorkspaceSemanticSignal, ComparisonHistorySyncWorkspaceSignalDetailNestedKey, ComparisonHistorySyncWorkspaceSignalDetailSubviewKey, ComparisonHistorySyncWorkspaceSignalMicroInteractionKey, ComparisonHistorySyncWorkspaceSignalMicroViewKey, ComparisonHistorySyncWorkspaceState, ComparisonHistoryTabIdentity, ComparisonHistoryWriteMode, ComparisonIntent, ComparisonScoreDrillBackOptions, ComparisonScoreLinkedRunRole, ComparisonScoreLinkSource, ComparisonScoreLinkTarget, ComparisonScoreSection, ComparisonTooltipConflictSessionSummary, ComparisonTooltipConflictSessionSummarySession, ComparisonTooltipConflictSessionUiState, ComparisonTooltipConflictUiStateV1, ComparisonTooltipInteractionOptions, ComparisonTooltipLayout, ComparisonTooltipPendingPresetImportConflict, ComparisonTooltipPresetConflictPreviewGroup, ComparisonTooltipPresetConflictPreviewRow, ComparisonTooltipPresetImportConflictPolicy, ComparisonTooltipPresetImportResolution, ComparisonTooltipTargetProps, ComparisonTooltipTuning, ComparisonTooltipTuningPresetStateV1, ComparisonTooltipTuningShareImport, ComparisonTooltipTuningSinglePresetShareV1, ControlRoomComparisonHistoryPanelUiState, ControlRoomComparisonSelectionState, ControlRoomUiStateV1, ControlRoomUiStateV2, ControlRoomUiStateV3, ControlRoomUiStateV4, ExpandedGapWindowSelections, ExperimentPreset, ExperimentPresetRevision, GapWindowDragSelectionState, GuardedLiveStatus, MarketDataIngestionJobRecord, MarketDataProvenanceExportFilterState, MarketDataProvenanceExportHistoryEntry, MarketDataProvenanceExportSort, MarketDataProvenanceExportStateV1, MarketDataLineageHistoryRecord, MarketDataStatus, OperatorAlertMarketContextProvenance, OperatorAlertPrimaryFocus, OperatorVisibility, PendingTouchGapWindowSweepState, PresetDraftConflict, PresetRevisionDiff, PresetRevisionFilterState, PresetStructuredDiffDeltaValue, PresetStructuredDiffGroup, PresetStructuredDiffRow, ProviderProvenanceAnalyticsPresetEntry, ProviderProvenanceDashboardLayout, ProviderProvenanceDashboardViewEntry, ProviderProvenanceExportAnalyticsPayload, ProviderProvenanceExportJobEntry, ProviderProvenanceExportJobEscalationResult, ProviderProvenanceExportJobHistoryPayload, ProviderProvenanceExportJobPolicyResult, ProviderProvenanceSchedulerAlertHistoryPayload, ProviderProvenanceSchedulerHealthExportPayload, ProviderProvenanceSchedulerHealthAnalyticsPayload, ProviderProvenanceSchedulerHealthHistoryPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditRecord, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePlanListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyListPayload, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditRecord, ProviderProvenanceSchedulerSearchModerationPlanListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerSearchModerationPolicyCatalogListPayload, ProviderProvenanceSchedulerSearchFeedbackBatchModerationResult, ProviderProvenanceSchedulerSearchDashboardPayload, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditRecord, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryRevisionListPayload, ProviderProvenanceSchedulerStitchedReportViewAuditRecord, ProviderProvenanceSchedulerStitchedReportViewEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionEntry, ProviderProvenanceSchedulerStitchedReportViewRevisionListPayload, ProviderProvenanceSchedulerNarrativeBulkGovernanceResult, ProviderProvenanceSchedulerNarrativeGovernancePlan, ProviderProvenanceSchedulerNarrativeGovernancePlanBatchResult, ProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyStep, ProviderProvenanceSchedulerNarrativeGovernanceQueueView, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplate, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalog, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogRevisionListPayload, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditRecord, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplate, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateRevisionListPayload, ProviderProvenanceSchedulerNarrativeRegistryEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionEntry, ProviderProvenanceSchedulerNarrativeRegistryRevisionListPayload, ProviderProvenanceSchedulerNarrativeTemplateEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionEntry, ProviderProvenanceSchedulerNarrativeTemplateRevisionListPayload, ProviderProvenanceScheduledReportEntry, ProviderProvenanceScheduledReportHistoryPayload, ProvenanceArtifactLineDetailView, ProvenanceArtifactLineMicroView, ReferenceSource, Run, RunComparison, RunHistoryFilter, RunHistorySurfaceKey, RunListBoundaryContract, RunListBoundaryEligibility, RunListBoundaryGroupKey, RunListBoundarySurfaceId, RunSurfaceCapabilities, RunSurfaceCapabilityFamily, RunSurfaceCapabilityFamilyContract, RunSurfaceCapabilityFamilyKey, RunSurfaceCapabilitySchemaContract, RunSurfaceCapabilitySurfaceKey, RunSurfaceCollectionQueryBuilderReplayIntentSnapshot, RunSurfaceCollectionQueryBuilderReplayLinkAliasRecordPayload, RunSurfaceCollectionQueryBuilderReplayLinkRedactionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkRetentionPolicy, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobDownloadPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryEntry, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobHistoryPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditExportJobPrunePayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditListPayload, RunSurfaceCollectionQueryBuilderReplayLinkServerAuditPrunePayload, RunSurfaceCollectionQueryContract, RunSurfaceCollectionQueryElementField, RunSurfaceCollectionQueryExpressionAuthoring, RunSurfaceCollectionQueryParameterDomainDescriptor, RunSurfaceCollectionQuerySchema, RunSurfaceSharedContract, RunSurfaceSubresourceContract, SavedRunHistoryFilterPreset, SavedRunHistoryFilterPresetStateV1, Strategy, TouchGapWindowActivationFeedbackState, TouchGapWindowHoldProgressState, defaultRunForm, defaultPresetForm, defaultPresetRevisionFilter, defaultMarketDataProvenanceExportFilterState, defaultProviderProvenanceAnalyticsQueryState, defaultProviderProvenanceSchedulerSearchDashboardFilterState, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilter, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, defaultProviderProvenanceSchedulerSearchModerationQueueFilterState, defaultProviderProvenanceSchedulerSearchModerationStageDraft, normalizeProviderProvenanceSchedulerRoutingPolicyDraftValue, normalizeProviderProvenanceSchedulerApprovalPolicyDraftValue, buildProviderProvenanceSchedulerExportPolicyDraft, getProviderProvenanceSchedulerNarrativeGovernanceQueuePriorityRank, getProviderProvenanceSchedulerNarrativeGovernanceQueueState, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchySummary, formatProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepSummary, formatProviderProvenanceSchedulerNarrativeGovernancePlanHierarchyPosition, isProviderProvenanceSchedulerAlertCategory, getOperatorAlertOccurrenceKey, formatProviderProvenanceSchedulerTimelineSummary, formatProviderProvenanceSchedulerSearchMatchSummary, formatProviderProvenanceSchedulerRetrievalClusterSummary, buildProviderProvenanceSchedulerAlertWorkflowReason, defaultProviderProvenanceDashboardLayout, DEFAULT_PROVIDER_PROVENANCE_SCHEDULER_NARRATIVE_GOVERNANCE_QUEUE_SORT, defaultProviderProvenanceWorkspaceDraft, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraft, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraft, KEEP_CURRENT_BULK_GOVERNANCE_VALUE, CLEAR_TEMPLATE_LINK_BULK_GOVERNANCE_VALUE, defaultProviderProvenanceSchedulerNarrativeTemplateBulkDraft, defaultProviderProvenanceSchedulerStitchedReportViewBulkDraft, defaultProviderProvenanceSchedulerNarrativeRegistryDraft, defaultProviderProvenanceSchedulerNarrativeRegistryBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraft, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraft, defaultProviderProvenanceSchedulerNarrativeGovernanceQueueFilter, defaultProviderProvenanceSchedulerStitchedReportGovernanceQueueFilter, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilter, defaultProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilter, defaultProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilter, defaultProviderProvenanceSchedulerStitchedReportViewAuditFilter, defaultProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilter, defaultProviderProvenanceReportDraft, buildPresetFormFromPreset, buildCurrentPresetRevisionSnapshot, buildEmptyPresetRevisionSnapshot, formatPresetStructuredDiffDisplayValue, isPresetStructuredDiffObject, isPresetStructuredDiffScalar, arePresetStructuredDiffValuesEquivalent, matchesPresetParameterSchemaType, joinPresetStructuredDiffHints, tokenizePresetParameterPath, parsePresetTimeframeToMinutes, buildPresetRankedStringDelta, buildPresetParameterStrategyContext, buildPresetParameterDomainContext, formatPresetParameterSchemaHint, getPresetParameterSchemaEntry, buildPresetStructuredDiffDelta, summarizePresetStructuredDiffGroup, groupPresetStructuredDiffRows, buildPresetStructuredDiffRows, describePresetRevisionDiff, describePresetDraftConflict, matchesPresetRevisionFilter, defaultRunHistoryFilter, sanitizeRunHistoryFilter, cloneRunHistoryFilter, hasRunHistoryFilterCriteria, areRunHistoryFiltersEquivalent, buildRunHistorySavedFilterStorageKey, normalizeSavedRunHistoryFilterPreset, loadSavedRunHistoryFilterPresets, persistSavedRunHistoryFilterPresets, describeRunHistoryFilter, DEFAULT_COMPARISON_INTENT, comparisonIntentOptions, parseExperimentTags, parseJsonObjectInput, formatPresetLifecycleStage, buildRunSubmissionPayload, normalizeRunFormPreset, resolveMarketDataSymbol, buildMarketDataInstrumentFocusKey, isMarketDataInstrumentAtRisk, resolvePreferredMarketDataInstrument, formatWorkflowToken, formatMarketContextFieldProvenance, summarizeProviderRecoveryMarketContextProvenance, serializeLinkedMarketInstrumentContext, getOperatorSeverityRank, normalizeMarketDataProvenanceExportSort, normalizeMarketDataProvenanceExportFilterState, normalizeMarketDataProvenanceExportHistoryEntry, loadPersistedMarketDataProvenanceExportState, persistMarketDataProvenanceExportState, formatMarketDataProvenanceExportFilterSummary, formatProviderProvenanceAnalyticsQuerySummary, normalizeProviderProvenanceDashboardLayoutState, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueSort, normalizeProviderProvenanceSchedulerNarrativeGovernanceQueueView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterStateFromView, buildProviderProvenanceSchedulerNarrativeGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceQueueViewPayload, buildProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkQueueViewPatch, formatProviderProvenanceSchedulerNarrativeGovernanceQueueSortLabel, providerProvenanceSchedulerNarrativeGovernancePolicySupportsItemType, formatProviderProvenanceSchedulerNarrativeGovernanceQueueViewSummary, buildProviderProvenanceAnalyticsWorkspaceQuery, buildProviderProvenanceAnalyticsQueryStateFromWorkspaceQuery, formatProviderProvenanceSchedulerNarrativeFacet, resolveProviderProvenanceSeriesBarWidth, formatProviderDriftIntensity, formatSchedulerLagSeconds, downloadTextExport, escapeRegExp, normalizeMarketSymbol, buildMarketSymbolSearchVariants, matchesMarketSymbolInText, dedupeMarketDataInstruments, formatMarketDataInstrumentLabel, getMarketDataInstrumentSyncSeverityRank, getMarketDataInstrumentRiskScore, buildLiveMarketDataPreference, getMarketDataInstrumentLiveRelevance, selectPrimaryMarketDataInstrument, extractMatchingMarketTimeframe, extractMatchingMarketSymbols, buildLinkedMarketInstrumentContext, buildLinkedMarketInstrumentContextFromPayload, formatLinkedMarketPrimaryFocusNote, resolveInstrumentsBySymbolsAndTimeframe, resolveMarketDataInstrumentLink, getAlertLinkPriority, compareAlertLinkPriority, resolveAutoLinkedMarketInstrument, formatTimestamp, formatProviderRecoverySchema, formatProviderRecoveryTelemetry, shortenIdentifier, truncateLabel, formatRange, benchmarkArtifactSummaryOrder, benchmarkArtifactSummaryLabels, benchmarkArtifactSectionOrder, benchmarkArtifactSectionLabels, formatBenchmarkArtifactSummaryEntries, benchmarkArtifactSummarySortIndex, formatBenchmarkArtifactSummaryLabel, formatBenchmarkArtifactSummaryValue, formatBenchmarkArtifactSectionEntries, benchmarkArtifactSectionSortIndex, formatBenchmarkArtifactSectionLabel, formatBenchmarkArtifactSectionLines, formatBenchmarkArtifactSectionValue, formatBenchmarkArtifactInlineValue, ProviderProvenanceAnalyticsScope, ProviderProvenanceSchedulerOccurrenceNarrativeFacet, ProviderProvenanceAnalyticsQueryState, ProviderProvenanceSchedulerSearchDashboardFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogDraft, ProviderProvenanceSchedulerSearchModerationPolicyCatalogAuditFilterState, ProviderProvenanceSchedulerSearchModerationPolicyCatalogBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyAuditFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernancePolicyBulkDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaPolicyDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceMetaStageDraft, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceQueueFilterState, ProviderProvenanceSchedulerSearchModerationCatalogGovernanceStageDraft, ProviderProvenanceSchedulerSearchModerationQueueFilterState, ProviderProvenanceSchedulerSearchModerationStageDraft, ProviderProvenanceSchedulerExportPolicyDraft, OperatorVisibilityAlertEntry, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryDraftState, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryBulkDraftState, ProviderProvenanceSchedulerNarrativeBulkToggleValue, ProviderProvenanceSchedulerNarrativeTemplateBulkDraftState, ProviderProvenanceSchedulerStitchedReportViewBulkDraftState, ProviderProvenanceSchedulerNarrativeRegistryDraftState, ProviderProvenanceSchedulerNarrativeRegistryBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateDraftState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateBulkDraftState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepVersionEntry, ProviderProvenanceSchedulerNarrativeGovernanceQueueFilterState, ProviderProvenanceSchedulerStitchedReportGovernanceQueueFilterState, ProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateAuditFilterState, ProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogAuditFilterState, ProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateAuditFilterState, ProviderProvenanceSchedulerStitchedReportViewAuditFilterState, ProviderProvenanceSchedulerStitchedReportGovernanceRegistryAuditFilterState, ProviderProvenanceReportDraftState, LinkedMarketInstrumentContext, MarketDataLinkableAlertRecord, MarketDataIncidentHistoryEntry, ProviderRecoveryMarketContextSummary, MarketDataProviderProvenanceEventRecord, MarketDataPrimaryFocusSelection } from "./ControlRoomViewHelpersContext";
import { PanelDisclosure, BackfillCountStatus, BackfillQualityStatus, SyncCheckpointStatus, SyncFailureStatus, formatCompletion, summarizeGapWindows, formatGapWindows, buildLegacyGapWindowKey, buildGapWindowKey, parseGapWindowKey, formatGapWindowKeyLabel, normalizeExpandedGapWindowSelectionList, resolveGapWindowSelectionList, buildGapWindowSelectionUpdate, isSameGapWindowSelectionList, filterExpandedGapWindowSelections, buildGapWindowSelectionLookup, instrumentGapRowKey, toggleExpandedGapRow, pruneExpandedGapRows, pruneExpandedGapWindowSelections } from "./ControlRoomViewStatusPanels";
import { loadExpandedGapRows, loadExpandedGapWindowSelections, defaultControlRoomComparisonSelectionState, loadPersistedComparisonSelection, defaultComparisonHistoryPanelState, defaultComparisonHistoryPanelUiState, loadPersistedComparisonHistoryPanelUiState, loadControlRoomUiState, readControlRoomUiStateValue, persistControlRoomUiState, loadComparisonHistorySyncAuditTrail, persistComparisonHistorySyncAuditTrail, loadComparisonSelectionFromUrl, buildComparisonSelectionHistoryUrl, readComparisonHistoryBrowserState, buildComparisonHistoryBrowserState, isSameComparisonHistoryBrowserState, persistComparisonSelectionToUrl, buildComparisonHistoryEntryId, buildComparisonHistoryTabId, formatComparisonHistoryTabLabel, loadComparisonHistoryTabIdentity, buildComparisonHistoryPanelSyncState, buildComparisonHistorySyncSignature, buildComparisonHistorySyncAuditId, buildComparisonHistoryPanelEntry, findComparisonHistoryPanelEntryForSelection, mergeComparisonHistoryPanelState, mergeComparisonHistoryPanelEntries, reconcileComparisonHistoryPanelState, sortComparisonHistoryPanelEntries, limitComparisonHistoryPanelEntries } from "./ControlRoomViewComparisonStorage";
import { normalizeComparisonHistoryPanelUiState, normalizeComparisonHistorySyncAuditFilter, normalizeComparisonHistoryPanelSyncState, normalizeComparisonHistoryPanelState, normalizeComparisonHistoryPanelEntry, normalizeComparisonHistorySyncAuditEntry, normalizeComparisonHistorySyncConflictReview, normalizeComparisonHistorySyncConflictSelectedSources, normalizeComparisonHistorySyncPreferenceReview, normalizeComparisonHistorySyncWorkspaceReview, normalizeComparisonHistorySyncPreferenceState, normalizeComparisonHistorySyncWorkspaceState, normalizeComparisonHistorySyncPreferenceSelectedSources, normalizeComparisonHistorySyncWorkspaceSelectedSources, limitComparisonHistorySyncAuditEntries, appendComparisonHistorySyncAuditEntries, isSameComparisonHistoryPanelState, isSameComparisonHistoryPanelSyncState, isSameComparisonHistoryPanelEntry, getComparisonHistoryPanelEntryChangedFields, formatComparisonHistorySyncConflictScoreLinkValue, formatComparisonHistorySyncConflictRunSelectionValue, formatComparisonHistorySyncConflictFieldValue, hasComparisonHistorySyncConflictFieldDifference, buildDefaultComparisonHistorySyncConflictSelectedSources, buildComparisonHistorySyncConflictReview, buildComparisonHistorySyncConflictReviewGroups, summarizeComparisonHistoryPanelEntryConflict, formatComparisonHistorySyncConflictResolutionSummary, resolveComparisonHistorySyncConflictReviewEntry, applyResolvedComparisonHistoryPanelEntry, summarizeComparisonHistorySyncPreferenceChanges, buildComparisonHistorySyncPreferenceState, formatComparisonHistorySyncPreferenceFieldValue, hasComparisonHistorySyncPreferenceFieldDifference, buildDefaultComparisonHistorySyncPreferenceSelectedSources, buildComparisonHistorySyncPreferenceReview, buildComparisonHistorySyncPreferenceReviewRows, formatComparisonHistorySyncPreferenceResolutionSummary, resolveComparisonHistorySyncPreferenceReview } from "./ControlRoomViewComparisonNormalize";
import { listComparisonHistoryExpandedGapRowKeys, listComparisonHistoryExpandedGapRowDiffKeys, buildComparisonHistoryExpandedGapRowSelectionKey, parseComparisonHistoryExpandedGapRowSelectionKey, buildComparisonHistoryExpandedGapWindowSelectionKey, parseComparisonHistoryExpandedGapWindowSelectionKey, listComparisonHistoryExpandedGapWindowDiffKeys, isSameComparisonHistoryExpandedGapRows, isSameExpandedGapWindowSelections, formatComparisonHistoryExpandedGapRowKey, formatComparisonHistoryExpandedGapRowsValue, formatComparisonHistoryExpandedGapRowsDiffValue, formatComparisonHistorySyncWorkspaceSelectionKeyLabel, rankComparisonHistorySyncWorkspaceSelectionKey, ComparisonHistorySyncWorkspaceSemanticRanking, listComparisonHistorySyncWorkspaceDiffSelectionKeys, resolveComparisonHistorySyncWorkspaceFieldSource, listComparisonHistorySyncWorkspaceConflictSelectionKeys, scoreComparisonHistorySyncWorkspaceCandidateSource, sortComparisonHistorySyncWorkspaceSemanticSignals, rankComparisonHistorySyncWorkspaceFieldSemantics, buildComparisonHistorySyncWorkspaceRecommendedSources, summarizeComparisonHistorySyncWorkspaceChanges, buildComparisonHistorySyncWorkspaceState, formatComparisonHistorySyncWorkspaceFieldValue, hasComparisonHistorySyncWorkspaceFieldDifference, buildDefaultComparisonHistorySyncWorkspaceSelectedSources, buildComparisonHistorySyncWorkspaceReview, buildComparisonHistorySyncWorkspaceReviewRows, buildComparisonHistorySyncWorkspaceRecommendationOverview, formatComparisonHistorySyncWorkspaceResolutionSummary, resolveComparisonHistorySyncWorkspaceReview, buildComparisonHistorySyncAuditEntries } from "./ControlRoomViewComparisonWorkspace";
import { loadLegacyExpandedGapRows, filterExpandedGapRows, normalizeControlRoomComparisonSelection, isSameComparisonSelection, formatComparisonHistoryPanelEntryMeta, matchesComparisonHistoryPanelEntry, formatComparisonHistorySyncAuditKindLabel, buildComparisonHistoryStepDescriptor, resolveComparisonHistoryRunLabel, normalizeComparisonRunIdList, normalizeComparisonIntent, normalizeComparisonScoreSection, normalizeComparisonScoreLinkSource, normalizeComparisonScoreLinkSubFocusKey, normalizeComparisonScoreLinkExpandedState, normalizeComparisonScoreLinkTooltipKey, normalizeComparisonScoreLinkArtifactLineDetailView, normalizeComparisonScoreLinkArtifactLineMicroView, normalizeComparisonScoreLinkArtifactLineNotePage, normalizeComparisonScoreLinkArtifactLineDetailHoverKey, normalizeComparisonScoreLinkArtifactLineScrubStep, normalizeComparisonScoreLinkArtifactHoverKey, normalizeComparisonScoreLinkTarget, isControlRoomUiStateV1, isControlRoomUiStateV2, isControlRoomUiStateV3, isControlRoomUiStateV4, buildRunsPath, buildRunComparisonPath, normalizeRunHistoryFilter, normalizeRunHistoryPresetFilter, getStrategyVersionOptions, pickLatestBenchmarkRun } from "./ControlRoomViewRunFilters";
import { StrategyColumn, ReferenceCatalog, PresetStructuredDiffPreview, PresetCatalogPanel, RunForm, ExperimentMetadataPills } from "./ControlRoomViewCatalogPanels";
import { RunListBoundarySurfaceContract, RunListBoundaryGroupContract, RunSurfaceCapabilityDiscoveryPanel, Metric, formatMetric, formatLineagePosture, formatLineageIndicator, formatComparisonScoreValue } from "./ControlRoomViewCapabilities";
import { buildComparisonScoreHighlights, buildComparisonScoreDetailRows, formatComparisonScoreHighlight, formatComparisonScoreComponentLabel, formatComparisonScoreLinkSourceLabel, encodeComparisonScoreLinkToken, decodeComparisonScoreLinkToken, buildComparisonProvenanceLineSubFocusKey, buildComparisonRunCardLineSubFocusKey, buildComparisonRunListLineSubFocusKey, buildComparisonRunListOrderPreviewSubFocusKey, buildComparisonRunListDataSymbolSubFocusKey, buildComparisonProvenanceArtifactSubFocusKey, buildComparisonProvenanceArtifactSectionSubFocusKey, buildComparisonProvenanceArtifactSummaryHoverKey, buildComparisonProvenanceArtifactSectionLineHoverKey, buildComparisonProvenanceArtifactLineDetailHoverKey, buildComparisonMetricTooltipKey, formatComparisonScoreLinkSubFocusLabel, formatComparisonScoreLinkTooltipLabel, formatComparisonScoreLinkArtifactHoverLabel, formatComparisonScoreLinkArtifactLineDetailViewLabel, formatComparisonScoreLinkArtifactLineMicroViewLabel, formatComparisonScoreLinkArtifactLineDetailHoverLabel, formatComparisonScoreComponentDetail, buildComparisonScoreComponentDetails, formatComparisonScoreComponentRawValue, formatComparisonScoreSignedValue, getComparisonScoreLinkedRunRole, isSameComparisonScoreLinkTarget, isSameComparisonScoreLinkSurface, resolveComparisonScoreDrillBackTarget, isComparisonScoreLinkMatch, formatEditableNumber } from "./ControlRoomViewComparisonLinks";

export function formatFixedNumber(value?: number | null) {
  if (value === null || value === undefined) {
    return "n/a";
  }
  return value.toFixed(8);
}

export function buildLiveOrderDraftKey(runId: string, orderId: string) {
  return `${runId}:${orderId}`;
}

export function formatComparisonMetric(value: number | null | undefined, unit: string) {
  if (value === null || value === undefined) {
    return "n/a";
  }
  if (unit === "pct") {
    return `${value}%`;
  }
  return String(value);
}

export function formatComparisonDelta(value: number | null | undefined, unit: string) {
  if (value === null || value === undefined) {
    return "delta n/a";
  }
  const prefix = value > 0 ? "+" : "";
  if (unit === "pct") {
    return `${prefix}${value}% vs baseline`;
  }
  return `${prefix}${value} vs baseline`;
}

export function formatComparisonNarrativeLabel(value: string) {
  switch (value) {
    case "native_vs_reference":
      return "Native vs reference";
    case "reference_vs_reference":
      return "Reference vs reference";
    case "native_vs_native":
      return "Native vs native";
    default:
      return "Run divergence";
  }
}

export function formatComparisonIntentLabel(value: ComparisonIntent) {
  switch (value) {
    case "benchmark_validation":
      return "Benchmark validation";
    case "execution_regression":
      return "Execution regression";
    case "strategy_tuning":
      return "Strategy tuning";
    default:
      return value;
  }
}

export function formatComparisonIntentLegend(value: ComparisonIntent) {
  switch (value) {
    case "benchmark_validation":
      return "Benchmark drift cues";
    case "execution_regression":
      return "Regression risk cues";
    case "strategy_tuning":
      return "Tuning edge cues";
    default:
      return value;
  }
}

export function formatComparisonIntentTooltip(value: ComparisonIntent) {
  switch (value) {
    case "benchmark_validation":
      return "Benchmark validation emphasizes drift from the reference benchmark. Cyan cues point to where native results confirm or diverge from the benchmark.";
    case "execution_regression":
      return "Execution regression emphasizes operational drift and regression risk. Ember cues point to where behavior degraded or recovered versus the control run.";
    case "strategy_tuning":
      return "Strategy tuning emphasizes optimization edge and tradeoffs. Green cues point to where parameter changes improved or hurt the candidate run.";
    default:
      return value;
  }
}

export function formatComparisonCueTooltip(
  intent: ComparisonIntent,
  cue: ComparisonCueKind,
  metricLabel?: string,
) {
  switch (cue) {
    case "mode":
      return formatComparisonIntentTooltip(intent);
    case "baseline":
      switch (intent) {
        case "benchmark_validation":
          return "This baseline run anchors benchmark validation. Read the other runs as benchmark drift versus this control.";
        case "execution_regression":
          return "This baseline run is the control execution. Read the other runs as regression or recovery against it.";
        case "strategy_tuning":
          return "This baseline run is the incumbent tuning point. Read the other runs as edge or penalty against it.";
        default:
          return "This run is the comparison baseline.";
      }
    case "best":
      switch (intent) {
        case "benchmark_validation":
          return `${metricLabel ?? "This metric"} is highlighted because it shows the strongest observed outcome here. In validation mode, treat it as benchmark evidence rather than an automatic winner.`;
        case "execution_regression":
          return `${metricLabel ?? "This metric"} is highlighted because it shows the strongest observed outcome here. In regression mode, use it to spot recovered or degraded execution behavior quickly.`;
        case "strategy_tuning":
          return `${metricLabel ?? "This metric"} is highlighted because it shows the strongest observed outcome here. In tuning mode, use it to spot candidate improvements and tradeoffs quickly.`;
        default:
          return `${metricLabel ?? "This metric"} is highlighted because it is the strongest observed outcome in this row.`;
      }
    case "insight":
      switch (intent) {
        case "benchmark_validation":
          return "The featured insight summarizes the most important benchmark drift to inspect first.";
        case "execution_regression":
          return "The featured insight summarizes the sharpest regression signal to inspect first.";
        case "strategy_tuning":
          return "The featured insight summarizes the most actionable tuning edge or penalty first.";
        default:
          return "This is the primary comparison insight.";
      }
    default:
      return formatComparisonIntentTooltip(intent);
  }
}

export function buildComparisonCellTooltip(
  intent: ComparisonIntent,
  metricLabel: string,
  isBaseline: boolean,
  isBest: boolean,
) {
  const messages: string[] = [];

  if (isBaseline) {
    messages.push(formatComparisonCueTooltip(intent, "baseline"));
  }

  if (isBest) {
    messages.push(formatComparisonCueTooltip(intent, "best", metricLabel));
  }

  return messages.join(" ");
}

export function getComparisonIntentClassName(value: ComparisonIntent) {
  return `comparison-intent-${value.replaceAll("_", "-")}`;
}

export function formatLaneLabel(runtime: string) {
  switch (runtime) {
    case "freqtrade_reference":
      return "reference";
    case "decision_engine":
      return "decision";
    default:
      return runtime;
  }
}

export function formatVersionLineage(versionLineage: string[], fallbackVersion: string) {
  const values = versionLineage.length ? versionLineage : [fallbackVersion];
  return values.join(" -> ");
}

export function extractDefaultParameters(schema: ParameterSchema) {
  return Object.fromEntries(
    Object.entries(schema)
      .filter(([, definition]) => definition.default !== undefined)
      .map(([name, definition]) => [name, definition.default]),
  );
}

export function formatParameterMap(values: Record<string, unknown>) {
  const entries = Object.entries(values);
  if (!entries.length) {
    return "none";
  }
  return entries
    .map(([name, value]) => `${name}=${formatParameterValue(value)}`)
    .join(", ");
}

export function formatParameterValue(value: unknown): string {
  if (Array.isArray(value)) {
    return value.map((item) => formatParameterValue(item)).join("|");
  }
  if (value && typeof value === "object") {
    return JSON.stringify(value);
  }
  return String(value);
}

export function summarizeRunNotes(notes: string[]) {
  if (!notes.length) {
    return "No notes recorded.";
  }
  if (notes.length === 1) {
    return notes[0];
  }
  return `${notes[0]} | Final: ${notes[notes.length - 1]} | ${notes.length} notes`;
}

export {
  PanelDisclosure,
  BackfillCountStatus,
  BackfillQualityStatus,
  SyncCheckpointStatus,
  SyncFailureStatus,
  formatCompletion,
  summarizeGapWindows,
  formatGapWindows,
  buildLegacyGapWindowKey,
  buildGapWindowKey,
  parseGapWindowKey,
  formatGapWindowKeyLabel,
  normalizeExpandedGapWindowSelectionList,
  resolveGapWindowSelectionList,
  buildGapWindowSelectionUpdate,
  isSameGapWindowSelectionList,
  filterExpandedGapWindowSelections,
  buildGapWindowSelectionLookup,
  instrumentGapRowKey,
  toggleExpandedGapRow,
  pruneExpandedGapRows,
  pruneExpandedGapWindowSelections,
  loadExpandedGapRows,
  loadExpandedGapWindowSelections,
  defaultControlRoomComparisonSelectionState,
  loadPersistedComparisonSelection,
  defaultComparisonHistoryPanelState,
  defaultComparisonHistoryPanelUiState,
  loadPersistedComparisonHistoryPanelUiState,
  loadControlRoomUiState,
  readControlRoomUiStateValue,
  persistControlRoomUiState,
  loadComparisonHistorySyncAuditTrail,
  persistComparisonHistorySyncAuditTrail,
  loadComparisonSelectionFromUrl,
  buildComparisonSelectionHistoryUrl,
  readComparisonHistoryBrowserState,
  buildComparisonHistoryBrowserState,
  isSameComparisonHistoryBrowserState,
  persistComparisonSelectionToUrl,
  buildComparisonHistoryEntryId,
  buildComparisonHistoryTabId,
  formatComparisonHistoryTabLabel,
  loadComparisonHistoryTabIdentity,
  buildComparisonHistoryPanelSyncState,
  buildComparisonHistorySyncSignature,
  buildComparisonHistorySyncAuditId,
  buildComparisonHistoryPanelEntry,
  findComparisonHistoryPanelEntryForSelection,
  mergeComparisonHistoryPanelState,
  mergeComparisonHistoryPanelEntries,
  reconcileComparisonHistoryPanelState,
  sortComparisonHistoryPanelEntries,
  limitComparisonHistoryPanelEntries,
  normalizeComparisonHistoryPanelUiState,
  normalizeComparisonHistorySyncAuditFilter,
  normalizeComparisonHistoryPanelSyncState,
  normalizeComparisonHistoryPanelState,
  normalizeComparisonHistoryPanelEntry,
  normalizeComparisonHistorySyncAuditEntry,
  normalizeComparisonHistorySyncConflictReview,
  normalizeComparisonHistorySyncConflictSelectedSources,
  normalizeComparisonHistorySyncPreferenceReview,
  normalizeComparisonHistorySyncWorkspaceReview,
  normalizeComparisonHistorySyncPreferenceState,
  normalizeComparisonHistorySyncWorkspaceState,
  normalizeComparisonHistorySyncPreferenceSelectedSources,
  normalizeComparisonHistorySyncWorkspaceSelectedSources,
  limitComparisonHistorySyncAuditEntries,
  appendComparisonHistorySyncAuditEntries,
  isSameComparisonHistoryPanelState,
  isSameComparisonHistoryPanelSyncState,
  isSameComparisonHistoryPanelEntry,
  getComparisonHistoryPanelEntryChangedFields,
  formatComparisonHistorySyncConflictScoreLinkValue,
  formatComparisonHistorySyncConflictRunSelectionValue,
  formatComparisonHistorySyncConflictFieldValue,
  hasComparisonHistorySyncConflictFieldDifference,
  buildDefaultComparisonHistorySyncConflictSelectedSources,
  buildComparisonHistorySyncConflictReview,
  buildComparisonHistorySyncConflictReviewGroups,
  summarizeComparisonHistoryPanelEntryConflict,
  formatComparisonHistorySyncConflictResolutionSummary,
  resolveComparisonHistorySyncConflictReviewEntry,
  applyResolvedComparisonHistoryPanelEntry,
  summarizeComparisonHistorySyncPreferenceChanges,
  buildComparisonHistorySyncPreferenceState,
  formatComparisonHistorySyncPreferenceFieldValue,
  hasComparisonHistorySyncPreferenceFieldDifference,
  buildDefaultComparisonHistorySyncPreferenceSelectedSources,
  buildComparisonHistorySyncPreferenceReview,
  buildComparisonHistorySyncPreferenceReviewRows,
  formatComparisonHistorySyncPreferenceResolutionSummary,
  resolveComparisonHistorySyncPreferenceReview,
  listComparisonHistoryExpandedGapRowKeys,
  listComparisonHistoryExpandedGapRowDiffKeys,
  buildComparisonHistoryExpandedGapRowSelectionKey,
  parseComparisonHistoryExpandedGapRowSelectionKey,
  buildComparisonHistoryExpandedGapWindowSelectionKey,
  parseComparisonHistoryExpandedGapWindowSelectionKey,
  listComparisonHistoryExpandedGapWindowDiffKeys,
  isSameComparisonHistoryExpandedGapRows,
  isSameExpandedGapWindowSelections,
  formatComparisonHistoryExpandedGapRowKey,
  formatComparisonHistoryExpandedGapRowsValue,
  formatComparisonHistoryExpandedGapRowsDiffValue,
  formatComparisonHistorySyncWorkspaceSelectionKeyLabel,
  rankComparisonHistorySyncWorkspaceSelectionKey,
  listComparisonHistorySyncWorkspaceDiffSelectionKeys,
  resolveComparisonHistorySyncWorkspaceFieldSource,
  listComparisonHistorySyncWorkspaceConflictSelectionKeys,
  scoreComparisonHistorySyncWorkspaceCandidateSource,
  sortComparisonHistorySyncWorkspaceSemanticSignals,
  rankComparisonHistorySyncWorkspaceFieldSemantics,
  buildComparisonHistorySyncWorkspaceRecommendedSources,
  summarizeComparisonHistorySyncWorkspaceChanges,
  buildComparisonHistorySyncWorkspaceState,
  formatComparisonHistorySyncWorkspaceFieldValue,
  hasComparisonHistorySyncWorkspaceFieldDifference,
  buildDefaultComparisonHistorySyncWorkspaceSelectedSources,
  buildComparisonHistorySyncWorkspaceReview,
  buildComparisonHistorySyncWorkspaceReviewRows,
  buildComparisonHistorySyncWorkspaceRecommendationOverview,
  formatComparisonHistorySyncWorkspaceResolutionSummary,
  resolveComparisonHistorySyncWorkspaceReview,
  buildComparisonHistorySyncAuditEntries,
  loadLegacyExpandedGapRows,
  filterExpandedGapRows,
  normalizeControlRoomComparisonSelection,
  isSameComparisonSelection,
  formatComparisonHistoryPanelEntryMeta,
  matchesComparisonHistoryPanelEntry,
  formatComparisonHistorySyncAuditKindLabel,
  buildComparisonHistoryStepDescriptor,
  resolveComparisonHistoryRunLabel,
  normalizeComparisonRunIdList,
  normalizeComparisonIntent,
  normalizeComparisonScoreSection,
  normalizeComparisonScoreLinkSource,
  normalizeComparisonScoreLinkSubFocusKey,
  normalizeComparisonScoreLinkExpandedState,
  normalizeComparisonScoreLinkTooltipKey,
  normalizeComparisonScoreLinkArtifactLineDetailView,
  normalizeComparisonScoreLinkArtifactLineMicroView,
  normalizeComparisonScoreLinkArtifactLineNotePage,
  normalizeComparisonScoreLinkArtifactLineDetailHoverKey,
  normalizeComparisonScoreLinkArtifactLineScrubStep,
  normalizeComparisonScoreLinkArtifactHoverKey,
  normalizeComparisonScoreLinkTarget,
  isControlRoomUiStateV1,
  isControlRoomUiStateV2,
  isControlRoomUiStateV3,
  isControlRoomUiStateV4,
  buildRunsPath,
  buildRunComparisonPath,
  normalizeRunHistoryFilter,
  defaultRunHistoryFilter,
  sanitizeRunHistoryFilter,
  cloneRunHistoryFilter,
  hasRunHistoryFilterCriteria,
  areRunHistoryFiltersEquivalent,
  buildRunHistorySavedFilterStorageKey,
  normalizeRunHistoryPresetFilter,
  loadSavedRunHistoryFilterPresets,
  persistSavedRunHistoryFilterPresets,
  describeRunHistoryFilter,
  DEFAULT_COMPARISON_INTENT,
  comparisonIntentOptions,
  getStrategyVersionOptions,
  pickLatestBenchmarkRun,
  StrategyColumn,
  ReferenceCatalog,
  PresetStructuredDiffPreview,
  PresetCatalogPanel,
  RunForm,
  ExperimentMetadataPills,
  RunSurfaceCapabilityDiscoveryPanel,
  Metric,
  formatMetric,
  formatLineagePosture,
  formatLineageIndicator,
  formatComparisonScoreValue,
  buildComparisonScoreHighlights,
  buildComparisonScoreDetailRows,
  formatComparisonScoreHighlight,
  formatComparisonScoreComponentLabel,
  formatComparisonScoreLinkSourceLabel,
  encodeComparisonScoreLinkToken,
  decodeComparisonScoreLinkToken,
  buildComparisonProvenanceLineSubFocusKey,
  buildComparisonRunCardLineSubFocusKey,
  buildComparisonRunListLineSubFocusKey,
  buildComparisonRunListOrderPreviewSubFocusKey,
  buildComparisonRunListDataSymbolSubFocusKey,
  buildComparisonProvenanceArtifactSubFocusKey,
  buildComparisonProvenanceArtifactSectionSubFocusKey,
  buildComparisonProvenanceArtifactSummaryHoverKey,
  buildComparisonProvenanceArtifactSectionLineHoverKey,
  buildComparisonProvenanceArtifactLineDetailHoverKey,
  buildComparisonMetricTooltipKey,
  formatComparisonScoreLinkSubFocusLabel,
  formatComparisonScoreLinkTooltipLabel,
  formatComparisonScoreLinkArtifactHoverLabel,
  formatComparisonScoreLinkArtifactLineDetailViewLabel,
  formatComparisonScoreLinkArtifactLineMicroViewLabel,
  formatComparisonScoreLinkArtifactLineDetailHoverLabel,
  formatComparisonScoreComponentDetail,
  buildComparisonScoreComponentDetails,
  formatComparisonScoreComponentRawValue,
  formatComparisonScoreSignedValue,
  getComparisonScoreLinkedRunRole,
  isSameComparisonScoreLinkTarget,
  isSameComparisonScoreLinkSurface,
  resolveComparisonScoreDrillBackTarget,
  isComparisonScoreLinkMatch,
  formatEditableNumber,
  formatTimestamp,
  formatProviderRecoverySchema,
  formatProviderRecoveryTelemetry,
  shortenIdentifier,
  truncateLabel,
  formatRange,
  benchmarkArtifactSummaryOrder,
  benchmarkArtifactSummaryLabels,
  benchmarkArtifactSectionOrder,
  benchmarkArtifactSectionLabels,
  formatBenchmarkArtifactSummaryEntries,
  benchmarkArtifactSummarySortIndex,
  formatBenchmarkArtifactSummaryLabel,
  formatBenchmarkArtifactSummaryValue,
  formatBenchmarkArtifactSectionEntries,
  benchmarkArtifactSectionSortIndex,
  formatBenchmarkArtifactSectionLabel,
  formatBenchmarkArtifactSectionLines,
  formatBenchmarkArtifactSectionValue,
  formatBenchmarkArtifactInlineValue
};
