// @ts-nocheck
import { useEffect, useMemo, useRef, useState } from "react";

export function useControlRoomComparisonHistoryState({ model }: { model: any }): any {
  const {
    initialComparisonSelectionRef, DEFAULT_COMPARISON_INTENT, initialComparisonHistoryPanelUiStateRef, defaultComparisonHistoryPanelState, initialComparisonHistorySyncAuditTrailRef, providerProvenanceSchedulerNarrativeTemplates,
    providerProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplates, selectedProviderProvenanceSchedulerStitchedReportViewIds, selectedProviderProvenanceSchedulerStitchedReportGovernanceRegistryIds, selectedProviderProvenanceSchedulerNarrativeTemplateIds, selectedProviderProvenanceSchedulerNarrativeRegistryIds, selectedProviderProvenanceSchedulerNarrativeGovernancePolicyTemplateIds,
    selectedProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogIds, selectedProviderProvenanceSchedulerNarrativeGovernancePlanIds, providerProvenanceSchedulerStitchedReportViews, providerProvenanceSchedulerNarrativeRegistryEntries, providerProvenanceSchedulerNarrativeGovernancePolicyTemplates, providerProvenanceSchedulerNarrativeGovernancePolicyCatalogs,
    selectedProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogId, selectedProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepIds, selectedProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateIds, selectedProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHierarchyStepId, selectedProviderProvenanceSchedulerNarrativeGovernanceHierarchyStepTemplateId, selectedProviderProvenanceSchedulerNarrativeGovernancePolicyCatalogHistory,
    providerProvenanceSchedulerNarrativeGovernancePlans, selectedProviderProvenanceSchedulerNarrativeGovernancePlanId, providerProvenanceSchedulerNarrativeGovernancePlanListSummary, providerProvenanceSchedulerStitchedReportGovernancePlanListSummary, providerProvenanceSchedulerStitchedReportGovernanceRegistryPlanListSummary, providerProvenanceSchedulerStitchedReportGovernanceCatalogSearch,
    providerProvenanceSchedulerNarrativeGovernancePolicySupportsItemType, providerProvenanceSchedulerStitchedReportGovernanceRegistryPolicyCatalogSearch, providerProvenanceSchedulerStitchedReportGovernancePolicyCatalogEntries, providerProvenanceSchedulerStitchedReportGovernanceRegistrySearch, providerProvenanceSchedulerStitchedReportGovernanceRegistries, formatProviderProvenanceSchedulerNarrativeGovernanceQueueViewSummary,
    selectedProviderProvenanceSchedulerExportHistory, providerProvenanceSchedulerExports, selectedProviderProvenanceSchedulerExportJobId, normalizeControlRoomComparisonSelection, buildComparisonHistoryStepDescriptor, backtests,
    buildComparisonHistorySyncSignature, buildComparisonHistorySyncWorkspaceState, setStatusText, fetchJson, buildRunsPath, backtestRunFilter,
    sandboxRunFilter, paperRunFilter, liveRunFilter, setRunSurfaceCapabilities, setStrategies, setReferences,
    setPresets, setBacktests, setSandboxRuns, setPaperRuns, setLiveRuns, setMarketStatus,
    resolveAutoLinkedMarketInstrument, resolvePreferredMarketDataInstrument, activeMarketInstrumentKey, setActiveMarketInstrumentKey, buildMarketDataInstrumentFocusKey, setOperatorVisibility,
    setGuardedLive, loadMarketDataWorkflow, strategies, setBacktestForm, setSandboxForm, setLiveForm,
    normalizeRunFormPreset, presets, setBacktestRunFilter, normalizeRunHistoryPresetFilter, setSandboxRunFilter, setPaperRunFilter,
    setLiveRunFilter, editingPresetId, setEditingPresetId, setPresetForm, defaultPresetForm, buildPresetFormFromPreset,
    normalizeRunHistoryFilter, readComparisonHistoryBrowserState, loadComparisonSelectionFromUrl, defaultControlRoomComparisonSelectionState, reconcileComparisonHistoryPanelState, buildComparisonHistoryPanelEntry,
    findComparisonHistoryPanelEntryForSelection, persistComparisonHistorySyncAuditTrail, persistMarketDataProvenanceExportState, marketDataProvenanceExportFilter, marketDataProvenanceExportHistory, CONTROL_ROOM_UI_STATE_STORAGE_KEY,
    readControlRoomUiStateValue, mergeComparisonHistoryPanelState, buildComparisonHistorySyncAuditEntries, isSameComparisonHistoryPanelState, isSameComparisonHistoryPanelSyncState, appendComparisonHistorySyncAuditEntries,
    buildRunComparisonPath, buildComparisonHistoryPanelSyncState, persistControlRoomUiState, buildComparisonSelectionHistoryUrl, buildComparisonHistoryEntryId, buildComparisonHistoryBrowserState,
    isSameComparisonHistoryBrowserState, persistComparisonSelectionToUrl, limitComparisonHistoryPanelEntries, sortComparisonHistoryPanelEntries, buildDefaultComparisonHistorySyncConflictSelectedSources, resolveComparisonHistorySyncConflictReviewEntry,
    formatComparisonHistorySyncConflictResolutionSummary, applyResolvedComparisonHistoryPanelEntry, buildDefaultComparisonHistorySyncPreferenceSelectedSources, resolveComparisonHistorySyncPreferenceReview, formatComparisonHistorySyncPreferenceResolutionSummary, buildDefaultComparisonHistorySyncWorkspaceSelectedSources,
    buildComparisonHistorySyncWorkspaceRecommendedSources, resolveComparisonHistorySyncWorkspaceReview, formatComparisonHistorySyncWorkspaceResolutionSummary, marketStatus, pruneExpandedGapRows, filterExpandedGapRows,
    pruneExpandedGapWindowSelections, filterExpandedGapWindowSelections, isSameComparisonSelection, isSameComparisonHistoryExpandedGapRows, isSameExpandedGapWindowSelections, instrumentGapRowKey,
  } = model;

}
import "./useControlRoomComparisonHistoryState.presetHelpers";
import "./useControlRoomComparisonHistoryState.marketHelpers";
