from __future__ import annotations

import csv
from copy import deepcopy
from dataclasses import replace
from datetime import UTC
from datetime import datetime
from datetime import timedelta
import io
import json
import math
import re
from typing import Any
from typing import Iterable
from typing import Mapping

from akra_trader.domain.models import *  # noqa: F403


def _serialize_stitched_scheduler_narrative_json_value(value: Any) -> str:
  if isinstance(value, datetime):
    return value.isoformat()
  raise TypeError(f"Object of type {value.__class__.__name__} is not JSON serializable")


from akra_trader.application_flows.provider_provenance.scheduler_health_core_mixin import ProviderProvenanceSchedulerHealthCoreMixin
from akra_trader.application_flows.provider_provenance.scheduler_health_search_eval_mixin import ProviderProvenanceSchedulerHealthSearchEvalMixin
from akra_trader.application_flows.provider_provenance.scheduler_health_search_results_mixin import ProviderProvenanceSchedulerHealthSearchResultsMixin
from akra_trader.application_flows.provider_provenance.scheduler_health_pages_mixin import ProviderProvenanceSchedulerHealthPagesMixin
from akra_trader.application_flows.provider_provenance.scheduler_health_exports_mixin import ProviderProvenanceSchedulerHealthExportsMixin
from akra_trader.application_flows.provider_provenance.scheduler_health_reconstruction_mixin import ProviderProvenanceSchedulerHealthReconstructionMixin
from akra_trader.application_flows.provider_provenance.scheduler_health_reports_mixin import ProviderProvenanceSchedulerHealthReportsMixin

class ProviderProvenanceSchedulerHealthMixin(
  ProviderProvenanceSchedulerHealthCoreMixin,
  ProviderProvenanceSchedulerHealthSearchEvalMixin,
  ProviderProvenanceSchedulerHealthSearchResultsMixin,
  ProviderProvenanceSchedulerHealthPagesMixin,
  ProviderProvenanceSchedulerHealthExportsMixin,
  ProviderProvenanceSchedulerHealthReconstructionMixin,
  ProviderProvenanceSchedulerHealthReportsMixin,
):
  pass
