from __future__ import annotations

import csv
from copy import deepcopy
from dataclasses import replace
from datetime import UTC
from datetime import datetime
from datetime import timedelta
import hashlib
import io
import json
import math
from numbers import Number
import re
from typing import Any
from typing import Mapping
from uuid import uuid4

from akra_trader.domain.models import *  # noqa: F403


from akra_trader.application_flows.provider_provenance.scheduler_stitched_report_records_mixin import ProviderProvenanceSchedulerStitchedReportRecordsMixin
from akra_trader.application_flows.provider_provenance.scheduler_stitched_report_workspace_mixin import ProviderProvenanceSchedulerStitchedReportWorkspaceMixin
from akra_trader.application_flows.provider_provenance.scheduler_stitched_report_views_mixin import ProviderProvenanceSchedulerStitchedReportViewsMixin
from akra_trader.application_flows.provider_provenance.scheduler_stitched_report_governance_mixin import ProviderProvenanceSchedulerStitchedReportGovernanceMixin
from akra_trader.application_flows.provider_provenance.scheduler_stitched_report_preview_mixin import ProviderProvenanceSchedulerStitchedReportPreviewMixin

class ProviderProvenanceSchedulerStitchedReportMixin(
  ProviderProvenanceSchedulerStitchedReportRecordsMixin,
  ProviderProvenanceSchedulerStitchedReportWorkspaceMixin,
  ProviderProvenanceSchedulerStitchedReportViewsMixin,
  ProviderProvenanceSchedulerStitchedReportGovernanceMixin,
  ProviderProvenanceSchedulerStitchedReportPreviewMixin,
):
  pass
