from __future__ import annotations

from akra_trader.adapters.operator_delivery_grafana_oncall_workflow import OperatorDeliveryGrafanaOncallWorkflowMixin
from akra_trader.adapters.operator_delivery_zenduty_workflow import OperatorDeliveryZendutyWorkflowMixin
from akra_trader.adapters.operator_delivery_splunk_oncall_workflow import OperatorDeliverySplunkOncallWorkflowMixin
from akra_trader.adapters.operator_delivery_jira_service_management_workflow import OperatorDeliveryJiraServiceManagementWorkflowMixin
from akra_trader.adapters.operator_delivery_pagertree_workflow import OperatorDeliveryPagerTreeWorkflowMixin
from akra_trader.adapters.operator_delivery_alertops_workflow import OperatorDeliveryAlertOpsWorkflowMixin
from akra_trader.adapters.operator_delivery_signl4_workflow import OperatorDeliverySignl4WorkflowMixin
from akra_trader.adapters.operator_delivery_ilert_workflow import OperatorDeliveryIlertWorkflowMixin
from akra_trader.adapters.operator_delivery_betterstack_workflow import OperatorDeliveryBetterStackWorkflowMixin


class OperatorDeliveryWorkflowProvidersGroupTwoMixin(
  OperatorDeliveryGrafanaOncallWorkflowMixin,
  OperatorDeliveryZendutyWorkflowMixin,
  OperatorDeliverySplunkOncallWorkflowMixin,
  OperatorDeliveryJiraServiceManagementWorkflowMixin,
  OperatorDeliveryPagerTreeWorkflowMixin,
  OperatorDeliveryAlertOpsWorkflowMixin,
  OperatorDeliverySignl4WorkflowMixin,
  OperatorDeliveryIlertWorkflowMixin,
  OperatorDeliveryBetterStackWorkflowMixin,
):
  pass
