from __future__ import annotations

from akra_trader.adapters.operator_delivery_onpage_workflow import OperatorDeliveryOnpageWorkflowMixin
from akra_trader.adapters.operator_delivery_allquiet_workflow import OperatorDeliveryAllQuietWorkflowMixin
from akra_trader.adapters.operator_delivery_moogsoft_workflow import OperatorDeliveryMoogsoftWorkflowMixin
from akra_trader.adapters.operator_delivery_spikesh_workflow import OperatorDeliverySpikeshWorkflowMixin
from akra_trader.adapters.operator_delivery_dutycalls_workflow import OperatorDeliveryDutyCallsWorkflowMixin
from akra_trader.adapters.operator_delivery_incidenthub_workflow import OperatorDeliveryIncidentHubWorkflowMixin
from akra_trader.adapters.operator_delivery_resolver_workflow import OperatorDeliveryResolverWorkflowMixin
from akra_trader.adapters.operator_delivery_openduty_workflow import OperatorDeliveryOpenDutyWorkflowMixin
from akra_trader.adapters.operator_delivery_cabot_workflow import OperatorDeliveryCabotWorkflowMixin
from akra_trader.adapters.operator_delivery_haloitsm_workflow import OperatorDeliveryHaloItsmWorkflowMixin
from akra_trader.adapters.operator_delivery_incidentmanagerio_workflow import OperatorDeliveryIncidentManagerIoWorkflowMixin


class OperatorDeliveryWorkflowProvidersGroupThreeMixin(
  OperatorDeliveryOnpageWorkflowMixin,
  OperatorDeliveryAllQuietWorkflowMixin,
  OperatorDeliveryMoogsoftWorkflowMixin,
  OperatorDeliverySpikeshWorkflowMixin,
  OperatorDeliveryDutyCallsWorkflowMixin,
  OperatorDeliveryIncidentHubWorkflowMixin,
  OperatorDeliveryResolverWorkflowMixin,
  OperatorDeliveryOpenDutyWorkflowMixin,
  OperatorDeliveryCabotWorkflowMixin,
  OperatorDeliveryHaloItsmWorkflowMixin,
  OperatorDeliveryIncidentManagerIoWorkflowMixin,
):
  pass
