from __future__ import annotations

import json
import logging
from datetime import UTC
from datetime import datetime
from typing import Any
from urllib import error as urllib_error
from urllib import parse as urllib_parse
from urllib import request as urllib_request

from akra_trader.domain.models import OperatorAlertPrimaryFocus
from akra_trader.domain.models import OperatorIncidentDelivery
from akra_trader.domain.models import OperatorIncidentEvent
from akra_trader.domain.models import OperatorIncidentProviderPullSync
from akra_trader.adapters.operator_delivery_provider_pull_schema import OperatorDeliveryProviderPullSchemaMixin
from akra_trader.adapters.operator_delivery_provider_recovery_payload import OperatorDeliveryProviderRecoveryPayloadMixin


LOGGER = logging.getLogger("akra_trader.operator_delivery")


from akra_trader.adapters.operator_delivery_recovery_engine_helpers import OperatorDeliveryRecoveryEngineHelpersMixin
from akra_trader.adapters.operator_delivery_payload_helpers import OperatorDeliveryPayloadHelpersMixin
from akra_trader.adapters.operator_delivery_market_context_helpers import OperatorDeliveryMarketContextHelpersMixin
from akra_trader.adapters.operator_delivery_workflow_request_group_one import OperatorDeliveryWorkflowRequestGroupOneMixin
from akra_trader.adapters.operator_delivery_workflow_request_group_two import OperatorDeliveryWorkflowRequestGroupTwoMixin
from akra_trader.adapters.operator_delivery_workflow_request_group_three import OperatorDeliveryWorkflowRequestGroupThreeMixin
from akra_trader.adapters.operator_delivery_workflow_request_group_four import OperatorDeliveryWorkflowRequestGroupFourMixin
from akra_trader.adapters.operator_delivery_workflow_delivery_group_one import OperatorDeliveryWorkflowDeliveryGroupOneMixin
from akra_trader.adapters.operator_delivery_workflow_delivery_group_two import OperatorDeliveryWorkflowDeliveryGroupTwoMixin
from akra_trader.adapters.operator_delivery_workflow_run_group_one import OperatorDeliveryWorkflowRunGroupOneMixin
from akra_trader.adapters.operator_delivery_workflow_run_group_two import OperatorDeliveryWorkflowRunGroupTwoMixin
from akra_trader.adapters.operator_delivery_response_mapping_helpers import OperatorDeliveryResponseMappingHelpersMixin
from akra_trader.adapters.operator_delivery_priority_mapping_helpers import OperatorDeliveryPriorityMappingHelpersMixin


class OperatorDeliverySharedHelpersMixin(
  OperatorDeliveryProviderRecoveryPayloadMixin,
  OperatorDeliveryProviderPullSchemaMixin,
  OperatorDeliveryRecoveryEngineHelpersMixin,
  OperatorDeliveryPayloadHelpersMixin,
  OperatorDeliveryMarketContextHelpersMixin,
  OperatorDeliveryWorkflowRequestGroupOneMixin,
  OperatorDeliveryWorkflowRequestGroupTwoMixin,
  OperatorDeliveryWorkflowRequestGroupThreeMixin,
  OperatorDeliveryWorkflowRequestGroupFourMixin,
  OperatorDeliveryWorkflowDeliveryGroupOneMixin,
  OperatorDeliveryWorkflowDeliveryGroupTwoMixin,
  OperatorDeliveryWorkflowRunGroupOneMixin,
  OperatorDeliveryWorkflowRunGroupTwoMixin,
  OperatorDeliveryResponseMappingHelpersMixin,
  OperatorDeliveryPriorityMappingHelpersMixin,
):
  pass
