from __future__ import annotations

from akra_trader.adapters.operator_delivery_core_pagerduty import CorePagerDutyWorkflowProviderMixin
from akra_trader.adapters.operator_delivery_core_opsgenie import CoreOpsgenieWorkflowProviderMixin
from akra_trader.adapters.operator_delivery_core_incidentio import CoreIncidentioWorkflowProviderMixin
from akra_trader.adapters.operator_delivery_core_firehydrant import CoreFireHydrantWorkflowProviderMixin
from akra_trader.adapters.operator_delivery_core_rootly import CoreRootlyWorkflowProviderMixin


class CoreWorkflowProviderMixin(
  CorePagerDutyWorkflowProviderMixin,
  CoreOpsgenieWorkflowProviderMixin,
  CoreIncidentioWorkflowProviderMixin,
  CoreFireHydrantWorkflowProviderMixin,
  CoreRootlyWorkflowProviderMixin,
):
  pass
