from __future__ import annotations

from akra_trader.adapters.operator_delivery_oneuptime_workflow import OperatorDeliveryOneUptimeWorkflowMixin
from akra_trader.adapters.operator_delivery_squzy_workflow import OperatorDeliverySquzyWorkflowMixin
from akra_trader.adapters.operator_delivery_crisescontrol_workflow import OperatorDeliveryCrisesControlWorkflowMixin
from akra_trader.adapters.operator_delivery_freshservice_workflow import OperatorDeliveryFreshserviceWorkflowMixin
from akra_trader.adapters.operator_delivery_freshdesk_workflow import OperatorDeliveryFreshdeskWorkflowMixin
from akra_trader.adapters.operator_delivery_happyfox_workflow import OperatorDeliveryHappyfoxWorkflowMixin
from akra_trader.adapters.operator_delivery_zendesk_workflow import OperatorDeliveryZendeskWorkflowMixin
from akra_trader.adapters.operator_delivery_zohodesk_workflow import OperatorDeliveryZohoDeskWorkflowMixin
from akra_trader.adapters.operator_delivery_servicedeskplus_workflow import OperatorDeliveryServiceDeskPlusWorkflowMixin
from akra_trader.adapters.operator_delivery_helpscout_workflow import OperatorDeliveryHelpscoutWorkflowMixin
from akra_trader.adapters.operator_delivery_kayako_workflow import OperatorDeliveryKayakoWorkflowMixin
from akra_trader.adapters.operator_delivery_intercom_workflow import OperatorDeliveryIntercomWorkflowMixin
from akra_trader.adapters.operator_delivery_front_workflow import OperatorDeliveryFrontWorkflowMixin
from akra_trader.adapters.operator_delivery_sysaid_workflow import OperatorDeliverySysaidWorkflowMixin
from akra_trader.adapters.operator_delivery_bmchelix_workflow import OperatorDeliveryBmcHelixWorkflowMixin
from akra_trader.adapters.operator_delivery_solarwindsservicedesk_workflow import OperatorDeliverySolarWindsServiceDeskWorkflowMixin
from akra_trader.adapters.operator_delivery_topdesk_workflow import OperatorDeliveryTopdeskWorkflowMixin
from akra_trader.adapters.operator_delivery_invgateservicedesk_workflow import OperatorDeliveryInvGateServiceDeskWorkflowMixin
from akra_trader.adapters.operator_delivery_opsramp_workflow import OperatorDeliveryOpsRampWorkflowMixin


class OperatorDeliveryWorkflowProvidersGroupFourMixin(
  OperatorDeliveryOneUptimeWorkflowMixin,
  OperatorDeliverySquzyWorkflowMixin,
  OperatorDeliveryCrisesControlWorkflowMixin,
  OperatorDeliveryFreshserviceWorkflowMixin,
  OperatorDeliveryFreshdeskWorkflowMixin,
  OperatorDeliveryHappyfoxWorkflowMixin,
  OperatorDeliveryZendeskWorkflowMixin,
  OperatorDeliveryZohoDeskWorkflowMixin,
  OperatorDeliveryServiceDeskPlusWorkflowMixin,
  OperatorDeliveryHelpscoutWorkflowMixin,
  OperatorDeliveryKayakoWorkflowMixin,
  OperatorDeliveryIntercomWorkflowMixin,
  OperatorDeliveryFrontWorkflowMixin,
  OperatorDeliverySysaidWorkflowMixin,
  OperatorDeliveryBmcHelixWorkflowMixin,
  OperatorDeliverySolarWindsServiceDeskWorkflowMixin,
  OperatorDeliveryTopdeskWorkflowMixin,
  OperatorDeliveryInvGateServiceDeskWorkflowMixin,
  OperatorDeliveryOpsRampWorkflowMixin,
):
  pass
